### PR TITLE
Qml callback warning

### PR DESCRIPTION
**Pull request by suricactus**
Attempts to fix:

> fix QML Connections: Implicitly defined onFoo properties in Connections are deprecated

This was already attempted a few weeks ago https://github.com/opengisch/QField/pull/1079, but it was reverted https://github.com/opengisch/QField/pull/1134 . Hopefully the change will work this time or the needed changes should be applied.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1275-13fe7697e171c680a11adf419d37f8631217b0cc-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1275-13fe7697e171c680a11adf419d37f8631217b0cc-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1275-13fe7697e171c680a11adf419d37f8631217b0cc-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1275-13fe7697e171c680a11adf419d37f8631217b0cc-x86_64.apk)

**Comment by suricactus** [comment]
@nirvn can you try if you experience the same problems as you mentioned in #1079 ? All is working fine for me and the `onLoadProjectEnded` is triggerred.

**Comment by nirvn** [comment]
I can't be the guinea pig this time around, I'm not making against qt 5.12 anymore :)

**Comment by m-kuhn** [comment]
@signedav what's your qt version?

**Comment by signedav** [comment]
It's possible building QField with 5.15 using QGIS built with 5.12.
I don't know why it used to make troubles earlier.

**Comment by suricactus** [comment]
May I have green light for these changes?

**Comment by nirvn** [comment]
The problem then was that it wasn't possible to build qfield against qt 5.12.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1275-de8cc73e0b03261b2f7d5c404414f6c0a2f91709-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1275-de8cc73e0b03261b2f7d5c404414f6c0a2f91709-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1275-de8cc73e0b03261b2f7d5c404414f6c0a2f91709-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1275-de8cc73e0b03261b2f7d5c404414f6c0a2f91709-x86_64.apk)

**Comment by m-kuhn** [comment]
> The problem then was that it wasn't possible to build qfield against qt 5.12.

`s/build/run/`

We can merge as soon as all devs are on more modern Qt versions

**Comment by signedav** [comment]
Okay for me

**Review by signedav — APPROVED** [review]
I haven't checked all parameters passed but I guess you did @suricactus 
Since I've been the last guinea pic with 5.12 but not anymore I think we can merge that.

**Comment by suricactus** [comment]
Hopefully there is nothing missing. I have checked them one by one, Mathhias did too in #1079 . Merging...

**Pull request merged**
