### PR TITLE
Improve login screen on small vertical screen space

### PR DESCRIPTION
**Pull request by nirvn**
Doing a couple of things here: a/ trying to increase vertical height to allow scrolling the panel when the virtual keyboard is open, and b/ moving the about label to sit _below_ the user/password/log in button widgets.

image

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9be80c7bbce2de649c7bf9a0dd270f9abd569f0e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-b2a3ca21c6920e6e0b7fc44092aaaf09e7644c9f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-b2a3ca21c6920e6e0b7fc44092aaaf09e7644c9f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-b2a3ca21c6920e6e0b7fc44092aaaf09e7644c9f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-b2a3ca21c6920e6e0b7fc44092aaaf09e7644c9f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c1fba2f7821d89dc0e04f59bb18226a132eaffa2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-037c732bd2b51a82e8201a866fdf15c3798f7ccb-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-037c732bd2b51a82e8201a866fdf15c3798f7ccb-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-037c732bd2b51a82e8201a866fdf15c3798f7ccb-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-037c732bd2b51a82e8201a866fdf15c3798f7ccb-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for dd3490673eb1fa5d4e4141b7723413422c748185:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-a01386c95600e8873cb8d5d7f44169e4810a1b0d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-a01386c95600e8873cb8d5d7f44169e4810a1b0d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-a01386c95600e8873cb8d5d7f44169e4810a1b0d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-a01386c95600e8873cb8d5d7f44169e4810a1b0d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4943118f8ff4910ef17ed2a5439f5d9baca7c23e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-1ff6d11d690d43decc0fc53d776f081245a7d441-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-1ff6d11d690d43decc0fc53d776f081245a7d441-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-1ff6d11d690d43decc0fc53d776f081245a7d441-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-1ff6d11d690d43decc0fc53d776f081245a7d441-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d79797583e72837689b23d30d9fecaf8db72e638:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-47c4bf0d25d5202e1629f95a28def29ccf155234-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-47c4bf0d25d5202e1629f95a28def29ccf155234-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-47c4bf0d25d5202e1629f95a28def29ccf155234-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2170-47c4bf0d25d5202e1629f95a28def29ccf155234-x86.apk)

**Review by suricactus — APPROVED** [review]

**Comment by mbernasocchi** [comment]
Task linked: [DEV-3303 Password input is not reachable on android keyboard](https://app.clickup.com/t/2192114/DEV-3303)

**Pull request merged**
