### PR TITLE
Bump vcpkg baseline

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5d91b83639d1d636ab8269b27b375c0532320995: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3713-e2bb10dcf3c35b480951fb35a38024e962980919-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3713-e2bb10dcf3c35b480951fb35a38024e962980919-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3713-e2bb10dcf3c35b480951fb35a38024e962980919-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3713-e2bb10dcf3c35b480951fb35a38024e962980919-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3713-e2bb10dcf3c35b480951fb35a38024e962980919-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3713-e2bb10dcf3c35b480951fb35a38024e962980919-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3713-e2bb10dcf3c35b480951fb35a38024e962980919-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3713-e2bb10dcf3c35b480951fb35a38024e962980919-x86-android.apk)
</details>

**Comment by nirvn** [comment]
@m-kuhn , the Qt5 builds are easy to fix. As for Qt6, all appears to compile until QGIS, the error being:

```
FAILED: src/providers/postgres/CMakeFiles/provider_postgres_a.dir/qgspostgresconnpool.cpp.o 
ccache /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DH5_BUILT_AS_STATIC_LIB -DQT_CONCURRENT_LIB -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050800 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/x64-osx-rel/src/providers/postgres/provider_postgres_a_autogen/include -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/x64-osx-rel -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/postgres -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/x64-osx-rel/src/core -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/3d -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/annotations -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/auth -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/browser -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/callouts -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/classification -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/diagram -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/dxf -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/editform -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/effects -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/elevation -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/expression -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/externalstorage -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/fieldformatter -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/geometry -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/geocms -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/geocms/geonode -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/geocoding -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/gps -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/labeling -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/layertree -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/layout -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/locator -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/maprenderer -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/mesh -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/metadata -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/network -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/numericformats -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/pal -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/plot -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/pointcloud -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/pointcloud/expression -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/processing -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/processing/models -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/proj -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/project -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/providers -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/providers/arcgis -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/providers/memory -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/providers/gdal -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/providers/ogr -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/providers/meshmemory -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/raster -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/renderer -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/scalebar -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/settings -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/symbology -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/textrenderer -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/validity -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/vector -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/vectortile -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/external -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/external/nlohmann -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/external/kdbush/include -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/external/nmea -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/external/rtree/include -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/external/meshOptimizer -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/providers/ept -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/providers/copc -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/wms -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/wcs -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/delimitedtext -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/arcgisrest -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/spatialite -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/wfs -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/wfs/oapif -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/virtual -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/auth/basic/core -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/auth/esritoken/core -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/auth/identcert/core -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/auth/pkipaths/core -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/auth/pkipkcs12/core -I/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/auth/oauth2/core -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/postgresql/server -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtCore -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6 -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtGui -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtDBus -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtXml -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtWidgets -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtSvg -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtPrintSupport -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtNetwork -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtSql -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtConcurrent -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/QtCrypto -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/qt6keychain -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtSerialPort -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/lib/pkgconfig/../../include -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/poly2tri -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/share/Qt6/mkspecs/macx-clang -isystem /Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtCore5Compat -isystem /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/external/o2/src -fPIC -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wnon-virtual-dtor -Wno-redundant-move -Wno-misleading-indentation -Wreturn-type-c-linkage -Woverloaded-virtual -Wimplicit-fallthrough -Qunused-arguments -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.7 -fvisibility=hidden -fPIC -ffunction-sections -fdata-sections -std=gnu++17 -MD -MT src/providers/postgres/CMakeFiles/provider_postgres_a.dir/qgspostgresconnpool.cpp.o -MF src/providers/postgres/CMakeFiles/provider_postgres_a.dir/qgspostgresconnpool.cpp.o.d -o src/providers/postgres/CMakeFiles/provider_postgres_a.dir/qgspostgresconnpool.cpp.o -c /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/postgres/qgspostgresconnpool.cpp
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/postgres/qgspostgresconnpool.cpp:16:
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/postgres/qgspostgresconnpool.h:20:
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/postgres/qgspostgresconn.h:31:
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/vector/qgsvectordataprovider.h:30:
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/qgsaggregatecalculator.h:23:
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/qgsdatetimestatisticalsummary.h:21:
/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/qgsinterval.h:353:25: error: functions that differ only in their return type cannot be overloaded
QgsInterval CORE_EXPORT operator-( const QDateTime &datetime1, const QDateTime &datetime2 );
~~~~~~~~~~~             ^
/Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtCore/qdatetime.h:469:38: note: previous definition is here
    friend std::chrono::milliseconds operator-(const QDateTime &lhs, const QDateTime &rhs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/postgres/qgspostgresconnpool.cpp:16:
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/postgres/qgspostgresconnpool.h:20:
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/providers/postgres/qgspostgresconn.h:31:
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/vector/qgsvectordataprovider.h:30:
In file included from /Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/qgsaggregatecalculator.h:23:
/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/qgsdatetimestatisticalsummary.h:158:45: error: use of overloaded operator '-' is ambiguous (with operand types 'const QDateTime' and 'const QDateTime')
    QgsInterval range() const { return mMax - mMin; }
                                       ~~~~ ^ ~~~~
/Users/runner/builddir/vcpkg_installed/x64-osx/include/Qt6/QtCore/qdatetime.h:469:38: note: candidate function
    friend std::chrono::milliseconds operator-(const QDateTime &lhs, const QDateTime &rhs)
                                     ^
/Users/runner/builddir/_deps/vcpkg-src/buildtrees/qgis-qt6/src/nal-3_28_2-ec42ce6e8b.clean/src/core/qgsinterval.h:353:25: note: candidate function
QgsInterval CORE_EXPORT operator-( const QDateTime &datetime1, const QDateTime &datetime2 );
                        ^
2 errors generated.
```

**Comment by m-kuhn** [comment]
@nirvn if you happen to be in front of a keyboard, the patch for that is already in the overlay but not yet applied

**Comment by nirvn** [comment]
@m-kuhn , done.

**Comment by nirvn** [comment]
@m-kuhn , fixed!!

**Comment by nirvn** [comment]
@m-kuhn , tested the Android APKs, all good on that front. I just removed the debug's tmate addition in the Qt6 workflow to clean up the PR.

**Comment by m-kuhn** [comment]
@nirvn merge whenever you want

**Comment by nirvn** [comment]
@m-kuhn , as soon as this PR (https://github.com/opengisch/QField/pull/3828) is merged, I'll rebase and merge this, woupidou!

**Pull request merged**
