### PR TITLE
Pull translations before build

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-553-5394b9d2e3e22e0ccd69ad74ea84c72e24774f54-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-553-5394b9d2e3e22e0ccd69ad74ea84c72e24774f54-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-553-b49b6855481434c5b7f974c48830a9bcff9e6fc9-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-553-b49b6855481434c5b7f974c48830a9bcff9e6fc9-x86.apk)

**Comment by m-kuhn** [comment]
@mbernasocchi @3nids no more need to manually update translation, that's all part of the build now.

**Comment by mbernasocchi** [comment]
@m-kuhn great!

**Pull request merged**
