### PR TITLE
Camera

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-236-87ce5f753d8d896bec12ec5be56fcd90f97bf434-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-236-87ce5f753d8d896bec12ec5be56fcd90f97bf434-x86.apk)

**Comment by m-kuhn** [comment]
@signedav, this is compiled with Qt 5.9.4, do we still have the mirror issue?

**Comment by m-kuhn** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-236-8389ac52ff74998f9adfd020ef5c9719c415f8cc-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-236-8389ac52ff74998f9adfd020ef5c9719c415f8cc-x86.apk)

**Comment by m-kuhn** [comment]
I didn't change anything inside the camera code, so it should be no problem at all to merge the two.

In your branch do

```
git fetch origin
git cherry-pick b9fac77..79cfd99 
```

**Comment by signedav** [comment]
Okay thanks. 
You can work now with this branch #238 - so we are on the same.
If okay for you I will close this PR and delete the branch "camera" (this one).

**Comment by m-kuhn** [comment]
I'll still have to do some tests for auto deploy which I started in here. Give me some time until our server is back up and I'll clean up this branch and create a new one for the deploy code.

**Comment by signedav** [comment]
Aight.

**Comment by m-kuhn** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-236-b60ae3a292e787fa0b56ba9fe9e9225bc756f31a-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-236-b60ae3a292e787fa0b56ba9fe9e9225bc756f31a-x86.apk)

**Comment by olivierlefl** [comment]
Hi,
I tested the apk (for armv7 I think), I could take pictures whitout difficult, the button to take, save or cancel are viewable. Also on the last apk, when I lunched again the app, it always crashed . Now it doesn't crash. To test, I created two features with a field configurated in picture format, so I can take two differentes pictures (two features), however only the last picture is saved on both fields (picture format). Is it normal?  Also, if I want to take again the picture, it doesn't save, even in the Qfield window.

**Comment by signedav** [comment]
Thanks @olivierlefl That's not how it should work. I will take a look on that.

**Comment by signedav** [comment]
I think it shouldn't be a problem anymore with this version #238 @olivierlefl

**Comment by signedav** [comment]
I couldn't reproduce it with this apk neighter. In case it doesn't work with the release on #238 you could probably upload your project or give us more information? Thanks.

**Comment by olivierlefl** [comment]
Thanks ! I didn't see there was a new version released on #238 .
I tried with that new version, but I get the same problem, it saves only the last picture I took on my project, and again if I want to take again the picture to change it, it doesn't save that new picture. Do you think it's because of my settings on my Qgis project ? (like the picture format or other)

**Comment by signedav** [comment]
So you create a feature with a picture (pic 1) and save it. Then abother feature with a picture (picture 2). Then you select again the first feature and you see picture 2 and you cannot change it anymore. Correct?

I dont't think that it should work like this with a specific setting. But if you can give me your project or a dummy project with the same problem or a movie it would be easier to reproduce.

**Comment by olivierlefl** [comment]
Yes that's correct. Maybe easier I send you the project? 
Where can I send it to you?

**Comment by signedav** [comment]
@olivierlefl If it's not private, you can upload it here. Otherwise email me david at opengis.ch - then I will send you a link to our cloud.

**Comment by olivierlefl** [comment]
[qgis_qfield.zip](https://github.com/opengisch/QField/files/1806877/qgis_qfield.zip)
It's not private :) I put the project on Qgis and on Qfield.

**Comment by signedav** [comment]
Thanks.

**Comment by mrtwister3142** [comment]
The problem is that every photo is saved as "DCIM.jpg" with no individual number/timestamp whatsoever. in the filename. Everytime a new photo ist taken, the old one gets overwritten.

**Comment by signedav** [comment]
@mrtwister3142 is right. This happens when the folder DCIM not yet exists in the project dir yet. I will care about that. Thanks.

**Comment by olivierlefl** [comment]
Ah yes sorry I forgot which said mrtwister3142

**Comment by signedav** [comment]
@olivierlefl and @mrtwister3142 this should be solved with the last commit here #238

**Pull request closed without merging**
