### PR TITLE
Avoid feature model's double setFeature() calls when creating a new feature

### PR DESCRIPTION
**Pull request by nirvn**
@marioba , this fixes the problem you had reported to you which we discussed yesterday.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b90fa36123d44d11fc6a404446357c9a9c8d04e7: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3685-6b18b4b08ed2f49da195a7365cf88574558eafcd-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3685-6b18b4b08ed2f49da195a7365cf88574558eafcd-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3685-6b18b4b08ed2f49da195a7365cf88574558eafcd-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3685-6b18b4b08ed2f49da195a7365cf88574558eafcd-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3685-6b18b4b08ed2f49da195a7365cf88574558eafcd-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3685-6b18b4b08ed2f49da195a7365cf88574558eafcd-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3685-6b18b4b08ed2f49da195a7365cf88574558eafcd-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3685-6b18b4b08ed2f49da195a7365cf88574558eafcd-x86-android.apk)
</details>

**Comment by marioba** [comment]
> @marioba , this fixes the problem you had reported to you which we discussed yesterday.

Great, thanks @nirvn. I asked the user who reported this to check if it fixes the issue.

**Comment by nirvn** [comment]
@marioba , perfect.

**Comment by marioba** [comment]
Works perfectly. User very happy.

**Review by marioba — APPROVED** [review]

**Pull request merged**
