### PR TITLE
Fix delta generation on NULL and 0

### PR DESCRIPTION
**Pull request by suricactus**
When a field is nullable and it's value is changed to zero or other way
around, QField deltafilewrapper check the difference using a simple
`QVariant(1) == QVariant(2)`. However, there are special cases such as
`QVariant(0) == QVariant( QJsonValue::Null )` that return TRUE, even
though one of the values has undefined NULL value.

This fix checks explicitly about such cases and fixes the issue.

Also added appropriate test case.

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-2162 Apparenlty some NULL int fields which were set to 0 on the field were not updated on the cloud project](https://app.clickup.com/t/2192114/QF-2162)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c97d484dea3760e578f64b5793a6b89e1403afad: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3280-c0ca16965fdc3d8913a3ade7c6397f79bfbccece-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3280-c0ca16965fdc3d8913a3ade7c6397f79bfbccece-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3280-c0ca16965fdc3d8913a3ade7c6397f79bfbccece-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3280-c0ca16965fdc3d8913a3ade7c6397f79bfbccece-x86-android.apk)
</details>

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Backport?

**Comment by suricactus** [comment]
Definitely backport and release asap.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
