### PR TITLE
Antenna height float fix

### LINKED ISSUE #1027: Qfield crash when entering antenna height correction value
There is a severe crash when you enter a value in the antenna height correction field. Sometimes Qfield has to be removed from device and reinstalled.

### Reproduction Steps:

1. Enable antenna height correction.
2. Enter a value in antenna height correction field. Sometimes it only crashes when a decimal point is entered (eg. 1.66).

### Expected behavior:

Decimals should be no problem.
### Observed behavior:

Crashes unreliably.

**QField version:** 1.5.3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

### PR DESCRIPTION
**Pull request by signedav**
The text should be parsed to assign to the float (real) and not the other way around.

The `mDeltaZ` is protected instead of private.

Fixes #1027

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-f4b7b685440cdf4732375ae10a1c83e1719888f6-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-f4b7b685440cdf4732375ae10a1c83e1719888f6-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-f4b7b685440cdf4732375ae10a1c83e1719888f6-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-f4b7b685440cdf4732375ae10a1c83e1719888f6-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-f8aba20e261808645d905c43ff66fe78108b1f20-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-f8aba20e261808645d905c43ff66fe78108b1f20-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-f8aba20e261808645d905c43ff66fe78108b1f20-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-f8aba20e261808645d905c43ff66fe78108b1f20-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-7fc8c74fce38590b850a4542f5f97a50ff2a1db0-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-7fc8c74fce38590b850a4542f5f97a50ff2a1db0-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-7fc8c74fce38590b850a4542f5f97a50ff2a1db0-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-7fc8c74fce38590b850a4542f5f97a50ff2a1db0-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-864770579f030fc0968151b52b8dc576831ce7e5-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-864770579f030fc0968151b52b8dc576831ce7e5-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-864770579f030fc0968151b52b8dc576831ce7e5-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-864770579f030fc0968151b52b8dc576831ce7e5-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-b17f165a1ab37378e9b79a6c355d16d539574ba5-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-b17f165a1ab37378e9b79a6c355d16d539574ba5-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-b17f165a1ab37378e9b79a6c355d16d539574ba5-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-b17f165a1ab37378e9b79a6c355d16d539574ba5-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-01f943fa8b744c54b12fe53bac652e6f1d9ea7f8-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-01f943fa8b744c54b12fe53bac652e6f1d9ea7f8-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-01f943fa8b744c54b12fe53bac652e6f1d9ea7f8-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1038-01f943fa8b744c54b12fe53bac652e6f1d9ea7f8-x86_64.apk)

**Comment by signedav** [comment]
What do you think @m-kuhn about this?

I have to admit, that I don't understand why the `QgsQuickCoordinateTransformer` Object "turns" NULL when the private member `mDeltaZ` is set to a value with decimals. Anyway, I think the solution does not become worse by having `mDeltaZ` as a protected variable...

**Pull request merged**
