### PR TITLE
Handle importing of zipped projects

### PR DESCRIPTION
**Pull request by nirvn**
This builds on top of #2397 . It adds a mechanism to treat a .zip file as an archived project when the presence of a QGIS project file is detected. When that's the case, QField will decompress the project into the Imported protects directory.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 66c446ab5e9005e7d768e8b0efdb2dce04141b3a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-9f0415f8c11bdbee834c5f05addbcd6376b8fbe3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-9f0415f8c11bdbee834c5f05addbcd6376b8fbe3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-9f0415f8c11bdbee834c5f05addbcd6376b8fbe3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-9f0415f8c11bdbee834c5f05addbcd6376b8fbe3-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a06c2482dc967035cf6960749d8548e0c00a4fbf:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-e2a8b2d503b6d9f837159c0efa1ef14c59e7c1c3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-e2a8b2d503b6d9f837159c0efa1ef14c59e7c1c3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-e2a8b2d503b6d9f837159c0efa1ef14c59e7c1c3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-e2a8b2d503b6d9f837159c0efa1ef14c59e7c1c3-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3e951c9b85a4c7f0ef502676e445d4a1af4926f3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-c470aa1a525d0303a6a15e40314b584a5d9689b7-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-c470aa1a525d0303a6a15e40314b584a5d9689b7-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-c470aa1a525d0303a6a15e40314b584a5d9689b7-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-c470aa1a525d0303a6a15e40314b584a5d9689b7-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0e68dd1159831872a19454cdd4337eb4404aa322:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-610b87ae5ed5d33b3b87d9c00b03c6731a5f3685-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-610b87ae5ed5d33b3b87d9c00b03c6731a5f3685-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-610b87ae5ed5d33b3b87d9c00b03c6731a5f3685-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2403-610b87ae5ed5d33b3b87d9c00b03c6731a5f3685-x86.apk)

**Pull request merged**
