### PR TITLE
Fix the blank screen on resume issue while greatly simplifying manifest & QFieldActivity java class

### PR DESCRIPTION
**Pull request by nirvn**
... the day has finally come ... we are now blank screen free :partying_face: :tada:

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 521406f1cb81844e9889780022bf90dc0b9a4e22:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-f8f53ad916e22bb2f1465f92cc450a51d6a68d9e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-f8f53ad916e22bb2f1465f92cc450a51d6a68d9e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-f8f53ad916e22bb2f1465f92cc450a51d6a68d9e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-f8f53ad916e22bb2f1465f92cc450a51d6a68d9e-x86.apk)

**Comment by nirvn** [comment]
File association still works on this simplified manifest.xml, however I still see a white screen.

**Comment by m-kuhn** [comment]
Are you able to get a logcat?
If you add a log around here https://github.com/opengisch/QField/blob/master/android/src/ch/opengis/qfield/QFieldActivity.java#L67 do you get that for the whitescreen launch?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 79ebed47e63e2caad49d28efc29e0783d4bffca6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-900bc0b7412dd032abd2da380d1fb5bbd444ec79-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-900bc0b7412dd032abd2da380d1fb5bbd444ec79-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-900bc0b7412dd032abd2da380d1fb5bbd444ec79-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-900bc0b7412dd032abd2da380d1fb5bbd444ec79-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 03232153095c619a3cb2534a31149d66a9bbb62c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-c3b13db07e0fa3542d94914e7ba85aa736be5895-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-c3b13db07e0fa3542d94914e7ba85aa736be5895-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-c3b13db07e0fa3542d94914e7ba85aa736be5895-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-c3b13db07e0fa3542d94914e7ba85aa736be5895-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b11ee58b6c0e8546909f53bce807bf15ddf192bb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-440114481cfeb40d4bed396385cbf635deec3033-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-440114481cfeb40d4bed396385cbf635deec3033-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-440114481cfeb40d4bed396385cbf635deec3033-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-440114481cfeb40d4bed396385cbf635deec3033-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1fe21957e8486bdfd05362d3939c50deb99c8ccc:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-86f1b1f76cd7fab5ee1b8544ca1a562efbbccd99-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-86f1b1f76cd7fab5ee1b8544ca1a562efbbccd99-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-86f1b1f76cd7fab5ee1b8544ca1a562efbbccd99-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-86f1b1f76cd7fab5ee1b8544ca1a562efbbccd99-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1e9d966f1bff7dcf9d8326cc1f1609308c141b55:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-eca986cc2bc8f0075d0fb8ed4f074ac959dd6e72-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-eca986cc2bc8f0075d0fb8ed4f074ac959dd6e72-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-eca986cc2bc8f0075d0fb8ed4f074ac959dd6e72-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-eca986cc2bc8f0075d0fb8ed4f074ac959dd6e72-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1b498f7ed65350cdc38c076e7e4a090ca9f5b845:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-b7fb17eb91bcfabddeb6e53510b6e40a0422f94b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-b7fb17eb91bcfabddeb6e53510b6e40a0422f94b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-b7fb17eb91bcfabddeb6e53510b6e40a0422f94b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-b7fb17eb91bcfabddeb6e53510b6e40a0422f94b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 256e4aa12d3802a5de2b4922505831f14b98bdc7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-ac713625f0f9770d2bf63e07da704a737c99bb21-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-ac713625f0f9770d2bf63e07da704a737c99bb21-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-ac713625f0f9770d2bf63e07da704a737c99bb21-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-ac713625f0f9770d2bf63e07da704a737c99bb21-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 03a97a2ab7d6a5622ed5c8a9844453aab28097ec:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-495cedfc4f1c28ec50fe0070fb4a219e1393fd68-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-495cedfc4f1c28ec50fe0070fb4a219e1393fd68-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-495cedfc4f1c28ec50fe0070fb4a219e1393fd68-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-495cedfc4f1c28ec50fe0070fb4a219e1393fd68-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a61521767e27a36fad4a5f8db48333cfe102e62c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-102d79bc3f4201a3c01952c040df049d0f42088f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-102d79bc3f4201a3c01952c040df049d0f42088f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-102d79bc3f4201a3c01952c040df049d0f42088f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-102d79bc3f4201a3c01952c040df049d0f42088f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cfe37abb922e01c765163a16529715b075f6856a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-64a0b6ffb8421dda66ee925bd127de748b48759f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-64a0b6ffb8421dda66ee925bd127de748b48759f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-64a0b6ffb8421dda66ee925bd127de748b48759f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-64a0b6ffb8421dda66ee925bd127de748b48759f-x86.apk)

**Comment by m-kuhn** [comment]
Regular start: https://gist.github.com/m-kuhn/98d4172bb72f2aafa3e9c46d328d2076

**Comment by m-kuhn** [comment]
Possibly related https://bugreports.qt.io/browse/QTBUG-63500

**Comment by m-kuhn** [comment]
onNewIntent is called when you click the home button within the app

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d562a9008802bf0968fa17cfa12b2f269e6f1bb5:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-4c18bee4b984b7801664e4a528af73a739ffa144-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-4c18bee4b984b7801664e4a528af73a739ffa144-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-4c18bee4b984b7801664e4a528af73a739ffa144-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-4c18bee4b984b7801664e4a528af73a739ffa144-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cee57fdb2d8cf0a73284b2aec3a73093bc3e8548:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-8c66b11e9a2315278b04a03e61ee080c5e9938a7-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-8c66b11e9a2315278b04a03e61ee080c5e9938a7-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-8c66b11e9a2315278b04a03e61ee080c5e9938a7-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-8c66b11e9a2315278b04a03e61ee080c5e9938a7-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 840a917dcf335514f7c1cd6505321d408d9cf690:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-8e803c63c9d15a7f1c6bcadcae4ed6cf1b09a296-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-8e803c63c9d15a7f1c6bcadcae4ed6cf1b09a296-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-8e803c63c9d15a7f1c6bcadcae4ed6cf1b09a296-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-8e803c63c9d15a7f1c6bcadcae4ed6cf1b09a296-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for be5c5181fc053af4c28fe51f9351e46feabaf0b3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-10a76218cdd8aa71e83a211d319a276aada2f623-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-10a76218cdd8aa71e83a211d319a276aada2f623-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-10a76218cdd8aa71e83a211d319a276aada2f623-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-10a76218cdd8aa71e83a211d319a276aada2f623-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ec694e0e5cbfa88fa094aa1e871f6bb95863e3f7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-dcc611c33f5f7a51ea31a890ca25c2b7221e5c9d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-dcc611c33f5f7a51ea31a890ca25c2b7221e5c9d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-dcc611c33f5f7a51ea31a890ca25c2b7221e5c9d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-dcc611c33f5f7a51ea31a890ca25c2b7221e5c9d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 636c2ce4cf5d5eeccb89e0183006aaec37d6220a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-065e5ac1a2fb937f6087eb06a317705c9f0a555c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-065e5ac1a2fb937f6087eb06a317705c9f0a555c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-065e5ac1a2fb937f6087eb06a317705c9f0a555c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-065e5ac1a2fb937f6087eb06a317705c9f0a555c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fba999cafcbe532cd0904d176b8fd6da8e24c601:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-64d904acd065326af0e13e260574f7682df6df52-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-64d904acd065326af0e13e260574f7682df6df52-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-64d904acd065326af0e13e260574f7682df6df52-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-64d904acd065326af0e13e260574f7682df6df52-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bc39b31992d9fa872c3766796fd28047fc0e2edf:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-448a06217175605961aac197db5ca9a697aabb30-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-448a06217175605961aac197db5ca9a697aabb30-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-448a06217175605961aac197db5ca9a697aabb30-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-448a06217175605961aac197db5ca9a697aabb30-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7d3c6f71be9e1d8a4fd62dc995a745cb8c66f51d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-3b9a0b9bd025c6ab6f31218de71925e1bbc5a060-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-3b9a0b9bd025c6ab6f31218de71925e1bbc5a060-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-3b9a0b9bd025c6ab6f31218de71925e1bbc5a060-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1484-3b9a0b9bd025c6ab6f31218de71925e1bbc5a060-x86.apk)

**Comment by m-kuhn** [comment]
This deserves :1st_place_medal:

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
