### PR TITLE
Remove cloud project from the recent projects when removed from the cloud projects list

### PR DESCRIPTION
**Pull request by suricactus**
Pretty much the title.

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1479 QField should remove the cloud project from the recent projects, if the project is removed from the cloud projects list](https://app.clickup.com/t/2192114/QF-1479)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5246d145c8bd1b903f16634600507986c63c2698:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-6a4e787e4c468b31bd2dd2cf9f3baced009ab72e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-6a4e787e4c468b31bd2dd2cf9f3baced009ab72e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-6a4e787e4c468b31bd2dd2cf9f3baced009ab72e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-6a4e787e4c468b31bd2dd2cf9f3baced009ab72e-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ef25865095fa8196d6b89b377176d779602d2e5e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-7a54fd14495ff0d0f8b32f181d54c93c7f980c34-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-7a54fd14495ff0d0f8b32f181d54c93c7f980c34-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-7a54fd14495ff0d0f8b32f181d54c93c7f980c34-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-7a54fd14495ff0d0f8b32f181d54c93c7f980c34-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for de0349f204c856086f92c02041d2e284feda8214:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-30504154e962a3580b1ab71cf46ba57f5bebcfb2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-30504154e962a3580b1ab71cf46ba57f5bebcfb2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-30504154e962a3580b1ab71cf46ba57f5bebcfb2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2351-30504154e962a3580b1ab71cf46ba57f5bebcfb2-x86.apk)

**Review by nirvn — APPROVED** [review]

**Pull request merged**
