### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-536ea5403a172e291f5f33290788aa9cfa2cc511-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-536ea5403a172e291f5f33290788aa9cfa2cc511-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-536ea5403a172e291f5f33290788aa9cfa2cc511-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-536ea5403a172e291f5f33290788aa9cfa2cc511-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-536ea5403a172e291f5f33290788aa9cfa2cc511-x86-5.apk)

**Comment by m-kuhn** [comment]
@3nids I think this should be safe to merge. Can you give it a quick look and approve if ok?

**Comment by Emic37** [comment]
@m-kuhn, can you update the french translation too? Some strings was updated.

**Comment by m-kuhn** [comment]
@Emic37 they should normally be updated automatically. When did you add them?

**Comment by Emic37** [comment]
@m-kuhn it's strange. There is ome untranslated strings in the application while there are translated on Transifex. Some of them are translated since 6 months on transifex but not in qfield.
Also, I translated the strings for crowdfunding wizard last week, before you release the new 1.2.0 version, but no change in the application.

**Comment by m-kuhn** [comment]
Do you have an example of these?

**Comment by Emic37** [comment]
Yes of course : 

- all strings of the new wizard
- "measure tool"
- Keep current scale when triggering search results option
- Enable Positioning in GPS menu
- etc.

**Comment by m-kuhn** [comment]
Good to know, I will look into it.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-383ddeb496c2db5779514d1a95cc02684e8982e1-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-383ddeb496c2db5779514d1a95cc02684e8982e1-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-383ddeb496c2db5779514d1a95cc02684e8982e1-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-383ddeb496c2db5779514d1a95cc02684e8982e1-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-e6d459dc30892843610411c471b9893a89216be8-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-e6d459dc30892843610411c471b9893a89216be8-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-e6d459dc30892843610411c471b9893a89216be8-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-e6d459dc30892843610411c471b9893a89216be8-x86_64.apk)

**Comment by Emic37** [comment]
@m-kuhn you probably know it but there is a problem with this pull request. QField crashes during the boot. :/

**Comment by m-kuhn** [comment]
Really? It works for me.
Which apk did you download?
If you delete the app data and restart, does it still crash?


screenshot_20191005-190213_qfield_beta_662

**Comment by Emic37** [comment]
Yes I tried to delete the app data before to post. I just retried and it doesn't work with the last test APK beta 662. 🙁

**Comment by 3nids** [comment]
no crash for me (with the arm64_v8a) but an empty dashboard, empty menu and no demo project to be loaded.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-b09ba175aec9c81c3d047991e4dfd515bf7a82ff-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-b09ba175aec9c81c3d047991e4dfd515bf7a82ff-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-b09ba175aec9c81c3d047991e4dfd515bf7a82ff-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-b09ba175aec9c81c3d047991e4dfd515bf7a82ff-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-f03d4fd03063cee5de3dc9f5fdf72174f5d59469-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-f03d4fd03063cee5de3dc9f5fdf72174f5d59469-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-f03d4fd03063cee5de3dc9f5fdf72174f5d59469-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-f03d4fd03063cee5de3dc9f5fdf72174f5d59469-x86_64.apk)

**Comment by m-kuhn** [comment]
The latest one should be better, anyone up to proof me wrong?

**Comment by Emic37** [comment]
Really good! All works perfectly for me using the latest test APK armv7.

**Comment by m-kuhn** [comment]
Phew. Thanks.
I'd like to do one more test, can you check the upcoming apk for stability also?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-723a4c344ff45676680d3834c047a2780c83d422-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-723a4c344ff45676680d3834c047a2780c83d422-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-723a4c344ff45676680d3834c047a2780c83d422-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-723a4c344ff45676680d3834c047a2780c83d422-x86_64.apk)

**Comment by Emic37** [comment]
@ m-kuhn The last apk crashes again. 🙁

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-2391dbb6b9e14f0b6ba9943b227f1415041f7aff-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-2391dbb6b9e14f0b6ba9943b227f1415041f7aff-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-2391dbb6b9e14f0b6ba9943b227f1415041f7aff-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-662-2391dbb6b9e14f0b6ba9943b227f1415041f7aff-x86_64.apk)

**Comment by 3nids** [comment]
no crash for me with last armv7 build

**Comment by 3nids** [comment]
here is the crash with gdal 3: 

```
10-07 10:32:31.812 27563 27619 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27619 (qtMainLoopThrea), pid 27563 (gis.qfield_beta)
10-07 10:32:31.960 27639 27639 F DEBUG   : pid: 27563, tid: 27619, name: qtMainLoopThrea  >>> ch.opengis.qfield_beta <<<
10-07 10:32:31.963 27639 27639 F DEBUG   :     #01 pc 0017fe8f  /data/app/ch.opengis.qfield_beta-d_y8IsUSXz4W6y_B9vZmew==/lib/arm/libproj.so
10-07 10:32:31.963 27639 27639 F DEBUG   :     #02 pc 0017f93b  /data/app/ch.opengis.qfield_beta-d_y8IsUSXz4W6y_B9vZmew==/lib/arm/libproj.so
10-07 10:32:31.963 27639 27639 F DEBUG   :     #03 pc 0017f795  /data/app/ch.opengis.qfield_beta-d_y8IsUSXz4W6y_B9vZmew==/lib/arm/libproj.so (__gxx_personality_v0+100)
10-07 10:32:31.963 27639 27639 F DEBUG   :     #04 pc 00132c68  /data/app/ch.opengis.qfield_beta-d_y8IsUSXz4W6y_B9vZmew==/lib/arm/libsqlite3.so (__gnu_Unwind_RaiseException+108)
10-07 10:32:31.963 27639 27639 F DEBUG   :     #05 pc 001337ac  /data/app/ch.opengis.qfield_beta-d_y8IsUSXz4W6y_B9vZmew==/lib/arm/libsqlite3.so (___Unwind_RaiseException+20)
```

**Comment by m-kuhn** [comment]
@3nids can you approve?

**Pull request merged**
