### PR TITLE
Flush wal on edit stop

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-747-4b7d8fac34bbe9575c11a4f5fa21b3ffb413d418-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-747-4b7d8fac34bbe9575c11a4f5fa21b3ffb413d418-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-747-4b7d8fac34bbe9575c11a4f5fa21b3ffb413d418-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-747-4b7d8fac34bbe9575c11a4f5fa21b3ffb413d418-x86_64.apk)

**Comment by signedav** [comment]
On the device your APK works....

**Comment by m-kuhn** [comment]
Thanks for the test!
The additional connections shouldn't hurt, there's gonna be one single flush after 500 ms

@saemiw can I ask you to test too? Then we can release a 1.3.4 with this patch included.

**Comment by signedav** [comment]
> The additional connections shouldn't hurt, there's gonna be one single flush after 500 ms
Fair enough. But still it's a little confusing when we listen on two (at least) signals telling the same. Maybe a comment, that the other ones had troubles to remember in future..?

**Comment by m-kuhn** [comment]
I take your continued request as a volunteering for additional testing :stuck_out_tongue_winking_eye:

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-747-122d49c3ee926767e67f4c1cca8a49486c4e90f8-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-747-122d49c3ee926767e67f4c1cca8a49486c4e90f8-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-747-122d49c3ee926767e67f4c1cca8a49486c4e90f8-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-747-122d49c3ee926767e67f4c1cca8a49486c4e90f8-x86_64.apk)

**Comment by signedav** [comment]
Tested again and it works on the device.

Mergymerge?

**Pull request merged**
