### PR TITLE
Fix date widget not liking date-as-string value

### PR DESCRIPTION
**Pull request by nirvn**
@m-kuhn , as discussed.

### CODE REVIEW

**Comment by m-kuhn** [comment]
QtCreator shows me a warning on line 103

https://github.com/opengisch/QField/pull/1747/files#diff-ee3ba3cc616154fffee41eed4fb28dd60eab9aa87de23d6ebbb50bf3abfbd233R103

"date" is declared more than once. In cpp it would be in a different scope, does JS behave differently here?

**Comment by nirvn** [comment]
I honestly don't know how JS deals with variable scoping. I'm surprised. But then again it's JS. Maybe just rename var to something like var temporaryDate or something.

**Comment by suricactus** [comment]
In js the `var` variables are scoped on function level. This differes from what one would expect and it is fixed with `const` and `let` keywords.

```
(() => {
  var date1 = 123;
  let date2 = 123;

  if (1) {
     var date1 = 456;
     let date2 = 456;
     console.log(date1, date2);
  }

  console.log(date1, date2);
})()
```
gives:
```
456 456
456 123
```

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 69c7d26b0e03ce8b7f07a2630272a93e6c66762d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-663858ea72e26cf71cbcdfd95151f6e372ba65d7-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-663858ea72e26cf71cbcdfd95151f6e372ba65d7-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-663858ea72e26cf71cbcdfd95151f6e372ba65d7-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-663858ea72e26cf71cbcdfd95151f6e372ba65d7-x86.apk)

**Comment by m-kuhn** [comment]
Thanks @suricactus 

Your advice: use `let` instead of `var`?

**Comment by suricactus** [comment]
If your js engine supports them - YES! Unfortunately QML is not one of them.

**Comment by m-kuhn** [comment]
https://bugreports.qt.io/browse/QTBUG-47735 says fixed since Qt 5.12, is that possible?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9ccb64bca73c05d8f9f2efa770e96b3eb6e70fd3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-d81be7a2d63da5acef187e255faf76ce6a0b34fb-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-d81be7a2d63da5acef187e255faf76ce6a0b34fb-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-d81be7a2d63da5acef187e255faf76ce6a0b34fb-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-d81be7a2d63da5acef187e255faf76ce6a0b34fb-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c091b28e64b13d4e1341cd3167691090cc5af6c7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-0cfc7ab3dc15c46c3245e7d9400e5313fd1d7c65-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-0cfc7ab3dc15c46c3245e7d9400e5313fd1d7c65-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-0cfc7ab3dc15c46c3245e7d9400e5313fd1d7c65-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1747-0cfc7ab3dc15c46c3245e7d9400e5313fd1d7c65-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
