### PR TITLE
Hide outdated fairy comments

### PR DESCRIPTION
**Pull request by suricactus**
Reduce the noise

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for abd464b8d27ad0a050941b09743c6986d4d812dd:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-9c4d731271bf95622612eecfa0ce168d45658272-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-9c4d731271bf95622612eecfa0ce168d45658272-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-9c4d731271bf95622612eecfa0ce168d45658272-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-9c4d731271bf95622612eecfa0ce168d45658272-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for abd464b8d27ad0a050941b09743c6986d4d812dd:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-4aca6ec9f77ff74094b31084691d7a757107ee2e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-4aca6ec9f77ff74094b31084691d7a757107ee2e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-4aca6ec9f77ff74094b31084691d7a757107ee2e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-4aca6ec9f77ff74094b31084691d7a757107ee2e-x86.apk)

**Comment by signedav** [comment]
What does it mean? Only one fairy comment per PR?

**Comment by suricactus** [comment]
Nope, you have all the comments, but all but the last one are folded. Everything is else is the same.
This way the PR comments clutter is reduced and it is easier to find the latest APKs for testing.

**Comment by signedav** [comment]
Ah okay. Thanks. If they are only folded and not discarded it's good for me. Let's make a quick test :-)

**Comment by signedav** [comment]
Ah sorry, you already made a test like I see now.

**Review by signedav — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for abd464b8d27ad0a050941b09743c6986d4d812dd:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-dbd6ef14155d9e9970bfebafc8ba8c29b6ed90d9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-dbd6ef14155d9e9970bfebafc8ba8c29b6ed90d9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-dbd6ef14155d9e9970bfebafc8ba8c29b6ed90d9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1468-dbd6ef14155d9e9970bfebafc8ba8c29b6ed90d9-x86.apk)

**Pull request merged**
