### PR TITLE
Guard QField from crashing when handling an intent with missing mime type

### PR DESCRIPTION
**Pull request by nirvn**
As seen on sentry.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0d8fd1473a7993414122acc9f046b11bb4d54444:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-c74460e300bb6152b384b7b74052a29ad68549c8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-c74460e300bb6152b384b7b74052a29ad68549c8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-c74460e300bb6152b384b7b74052a29ad68549c8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-c74460e300bb6152b384b7b74052a29ad68549c8-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bbe398e57547790938b18083e5cf9b3bc3fe326b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-f1482a1e4a6462353684389bdcf1ba92477885f1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-f1482a1e4a6462353684389bdcf1ba92477885f1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-f1482a1e4a6462353684389bdcf1ba92477885f1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-f1482a1e4a6462353684389bdcf1ba92477885f1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a8c8734696107a5b6263ec3de1d4960b2022b7c6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-13e1b359e16e9004610653b0dab72ee6f92b909d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-13e1b359e16e9004610653b0dab72ee6f92b909d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-13e1b359e16e9004610653b0dab72ee6f92b909d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2423-13e1b359e16e9004610653b0dab72ee6f92b909d-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Very good. Let's see if there is more to come

**Pull request merged**
