### PR TITLE
reset digitizing rubbberband when escaping form

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-309-14eccd1f5d1e9dda6150ffc2f1b1fc5116798434-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-309-14eccd1f5d1e9dda6150ffc2f1b1fc5116798434-x86.apk)

**Comment by 3nids** [comment]
ok to merge?

**Comment by m-kuhn** [comment]
No idea yet.
It would be good to have some thoughts of yours to justify this change.

**Comment by 3nids** [comment]
it fixes a bad behavior when escaping the add feature form.
The rubberband remains but you cannot continue digitizing.

Or do you want that ESC does not cancel the operation and still be able to digitize (similarly to the capture in the drawer PR #294 )

**Comment by m-kuhn** [comment]
No, I think it's fine to kill the geometry in this case.

**Pull request merged**
