### PR TITLE
FEATURE disable geometry add/edit/delete

### LINKED ISSUE #1065: Lock features and geometry
It would be nice to be able to lock the geometries of a layer.

Use case:

A field worker should visit a number of known assets. For each visited asset, he should be able to adjust some attributes ("validated", "needs replacement", "repaired", "out of order", you name it).

The field worker should not be able to:

 - add new features
 - delete existing features
 - adjust the geometries

This behavior needs to be configurable on a per-layer basis in the project.

### PR DESCRIPTION
**Pull request by suricactus**
A new PR of the same feature to lock the geometries https://github.com/opengisch/QField/pull/1063 to get demo APKs

Add a new layer option to "lock geometries". This new option should ideally live on a new vector layer properties panel. QField should respect this new configuration option and not allow adding, splitting, modifying etc. geometries.

Peek 2020-06-15 11-32

https://github.com/opengisch/qfieldsync/pull/157 functionality:
Peek 2020-06-17 12-48

Closes #1065

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-e26c2be208dc55704dea06cc7d17f80fb11ccf0c-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-e26c2be208dc55704dea06cc7d17f80fb11ccf0c-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-e26c2be208dc55704dea06cc7d17f80fb11ccf0c-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-e26c2be208dc55704dea06cc7d17f80fb11ccf0c-x86_64.apk)

**Comment by nirvn** [comment]
My 2 cents regarding the lock pad: as mentioned by others, it's likely not the appropriate icon to attach to a partial geometry-only lock. 

I'm not against those indicator icons in the legend per say, I like those in QGIS and it's nice to see its little brother QField adopt the concept. I'd however make sure they don't take over users' attention, a light semi-transparent gray would be a better color choice for those icons (unless, like tracking, it's about something that's "active" vs. a passive state).

So should we have a lock icon for truly read-only layers? Maybe. For geometry-lock, maybe there's a better UI. Maybe the (+) button could became semi-transparent gray (disabled-like state), with a toaster message if users try to click on it? The navigation bar's 'edit geometry' could also feature a similar disabled state.

**Comment by m-kuhn** [comment]
Thanks for the constructive feedback.

I agree on the "taking attention" statement, a light gray would help. I'm not convinced by the semi-transparent (+) icon. While it helps to bring across the message (you cannot edit geometries), for those cases where a field worker will never ever work with geometries, it's taking screen space and adds messages for no reason.

I would propose to continue:

 - Remove the lockpad *or* make it light gray and also for fully locked layers
 - Anyway: add a note on the layer properties dialog, indicating (in a phrase) what this means for the user (something like "this layer is configured with "locked geometries", this means you are not able to edit any geometries or add or delete any features.")

**Comment by suricactus** [comment]
This is an updated version of the gif based on the @m-kuhn suggestions:
Peek 2020-06-22 16-29

**Comment by m-kuhn** [comment]
Cool, can you add the padlock next to the explanation text? I think that would make for a super visual context.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-2be5ac51be4d9b08c970ea1d48298e4d4144b1de-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-2be5ac51be4d9b08c970ea1d48298e4d4144b1de-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-2be5ac51be4d9b08c970ea1d48298e4d4144b1de-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-2be5ac51be4d9b08c970ea1d48298e4d4144b1de-x86_64.apk)

**Comment by suricactus** [comment]
Padlock added:
image

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-e2a5a5ce0da3a931513fe3bbb4bc340636ea8d6d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-e2a5a5ce0da3a931513fe3bbb4bc340636ea8d6d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-e2a5a5ce0da3a931513fe3bbb4bc340636ea8d6d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1070-e2a5a5ce0da3a931513fe3bbb4bc340636ea8d6d-x86_64.apk)

**Comment by signedav** [comment]
Should this be backported to release-1_6 @m-kuhn ? If so, then it makes sense to backport #1071 as well, no?

**Pull request merged**
