### PR TITLE
Attribute form as a drawer

### PR DESCRIPTION
**Pull request by m-kuhn**
peek 2018-07-05 16-33

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-294-b4d766653f4c1a0a2ea176ad4ad26b28349c67c5-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-294-b4d766653f4c1a0a2ea176ad4ad26b28349c67c5-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-294-17c1d83c410dbd39c9edc11a09fde7877ceb8503-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-294-17c1d83c410dbd39c9edc11a09fde7877ceb8503-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-294-5f4684ecde6d074cb6e8affd6dc3f83c9cb439e7-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-294-5f4684ecde6d074cb6e8affd6dc3f83c9cb439e7-x86.apk)

**Comment by m-kuhn** [comment]
Hey @mejiafabiandj how are you doing?
I just wondered if we ever finalized this pull request. Didn't we have some code that brings the toast to the front somewhere on your computer? Would be nice to merge and create a new release :)

**Comment by 3nids** [comment]
I cannot reproduce the toast issue (message is displayed on top of feature form)

**Comment by m-kuhn** [comment]
Ping @mejiafabiandj 
do you have something left for this pull request to be committed?

**Comment by mejiafabiandj** [comment]
@m-kuhn sorry, i forgot to make a pull request. done in https://github.com/opengisch/QField/pull/315.

**Pull request merged**
