### PR TITLE
[range widget] Don't display 0 when value is null in slider mode

### PR DESCRIPTION
**Pull request by nirvn**
Small follow up to initial range widget implementation.

### CODE REVIEW

**Comment by 3nids** [comment]
should this follow an allow null config?
shall we take care of adding a set to null button?

**Comment by nirvn** [comment]
I'm following QGIS' slider mode, which has no null representation AFAIK.

**Comment by 3nids** [comment]
and if it's null, the value isn't changed until you touch the slider?

**Comment by nirvn** [comment]
@3nids , yep, see:
Screenshot from 2020-02-12 15-20-39

(In fact, as seen here, the slider has a 0 label, which we should fix on the QGIS side of things)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-825-372a8cfc12093b7eb4d0f6ec7cffa803912df9c8-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-825-372a8cfc12093b7eb4d0f6ec7cffa803912df9c8-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-825-372a8cfc12093b7eb4d0f6ec7cffa803912df9c8-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-825-372a8cfc12093b7eb4d0f6ec7cffa803912df9c8-x86_64.apk)

**Comment by nirvn** [comment]
Also, for the record, when you switch the range widget to slider, the [x] allow null checkbox grays out too.

**Pull request merged**
