### PR TITLE
Qt version 5.14.2

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix stylus on ~windows~ linux anc macos

### CODE REVIEW

**Comment by nirvn** [comment]
Also good to have it harmonized with our main android package.

**Review by nirvn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Actually the first comment is off. Windows already uses 5.14.2, this is for linux and mac.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ccf51beb8648b508305050f0bcb3f771e7cef324:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2326-edfe1b0998d3df03a6f074632ed8a18fcae7fd39-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2326-edfe1b0998d3df03a6f074632ed8a18fcae7fd39-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2326-edfe1b0998d3df03a6f074632ed8a18fcae7fd39-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2326-edfe1b0998d3df03a6f074632ed8a18fcae7fd39-x86.apk)

**Comment by m-kuhn** [comment]
To push new versions of these packages (qca, qtkeychain, qgis, ...) we'll need to change the port revisions. We cannot simply force push a newer version as I tried here.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for eb6f98981161676fbd224bbd0909178f63bb25f3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2326-f2d42fd131966d1ddc022796d4c2674bbab58590-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2326-f2d42fd131966d1ddc022796d4c2674bbab58590-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2326-f2d42fd131966d1ddc022796d4c2674bbab58590-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2326-f2d42fd131966d1ddc022796d4c2674bbab58590-x86.apk)

**Pull request merged**
