### PR TITLE
Fix location marker glitch

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2e8fdff6003374f174c0e164646ffa369cd4eda9: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3792-2b4a3819bfe128f4830516f61b2b1d9cf7b6a5fc-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3792-2b4a3819bfe128f4830516f61b2b1d9cf7b6a5fc-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3792-2b4a3819bfe128f4830516f61b2b1d9cf7b6a5fc-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3792-2b4a3819bfe128f4830516f61b2b1d9cf7b6a5fc-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3792-2b4a3819bfe128f4830516f61b2b1d9cf7b6a5fc-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3792-2b4a3819bfe128f4830516f61b2b1d9cf7b6a5fc-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3792-2b4a3819bfe128f4830516f61b2b1d9cf7b6a5fc-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3792-2b4a3819bfe128f4830516f61b2b1d9cf7b6a5fc-x86-android.apk)
</details>

**Comment by m-kuhn** [comment]
Does this fix something?

**Comment by nirvn** [comment]
@mbernasocchi reported not being afflicted by the glitch running this build.

**Comment by nirvn** [comment]
@m-kuhn , just saw your question after posting the above message. It fixes the glitch that Marco is seeing on his phone whereas the location marker glitches out and shows corrupted image fragments.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
