### PR TITLE
[Backport release-1_4] Improve location information text placement and size

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-867-18376ecdf3ae8e54c2f16b02b2fc340e206990c2-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-867-18376ecdf3ae8e54c2f16b02b2fc340e206990c2-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-867-18376ecdf3ae8e54c2f16b02b2fc340e206990c2-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-867-18376ecdf3ae8e54c2f16b02b2fc340e206990c2-x86_64.apk)

**Comment by mbernasocchi** [comment]
@m-kuhn shouldn't this get merged?

**Comment by m-kuhn** [comment]
@mbernasocchi I don't know, I wasn't involved.
We're lining up a 1.5 release anyway. I think it's better to focus on that one and forget about this one.

**Comment by mbernasocchi** [comment]
@nirvn can you either merge or close this?
cheers
MArco

**Comment by nirvn** [comment]
Merged, there was no additional work required so it'd just be a waste not to hit that button :wink:

**Pull request merged**
