### PR TITLE
New SDK

### LINKED ISSUE #1178: Rendering speed of raster images considerably slower with Qfield 1.6.1
Since I updated from QField 1.5.3 to 1.6.1 i observed that the rendering speed of my orthofotos is significantly slower than it was before.
I have an orthofoto with a spatial resolution of 20cm. At 1:500 scale with QField 1.5.3 it took approx. 4-5secs to load when i moved the canvas. This time has almost doubled with Qfield 1.6.1

### PR DESCRIPTION
**Pull request by m-kuhn**
Fixes #1178 

Needs an OSGeo4A release before merging

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-7429e04268363b21f85ffc0335e3e6de1c489633-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-7429e04268363b21f85ffc0335e3e6de1c489633-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-7429e04268363b21f85ffc0335e3e6de1c489633-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-7429e04268363b21f85ffc0335e3e6de1c489633-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-ce64f70b9287a7893e72a6913d9b2046a25ff7ee-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-ce64f70b9287a7893e72a6913d9b2046a25ff7ee-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-ce64f70b9287a7893e72a6913d9b2046a25ff7ee-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-ce64f70b9287a7893e72a6913d9b2046a25ff7ee-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-d6f6cc97da1711fac1d6c12d17bedcde00ac1dbd-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-d6f6cc97da1711fac1d6c12d17bedcde00ac1dbd-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-d6f6cc97da1711fac1d6c12d17bedcde00ac1dbd-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1211-d6f6cc97da1711fac1d6c12d17bedcde00ac1dbd-x86_64.apk)

**Comment by m-kuhn** [comment]
Solves all our problems. Almost.

**Pull request merged**
