### PR TITLE
set-env is disabled

### PR DESCRIPTION
**Pull request by m-kuhn**
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1423-a8292eec2f91b2dc6f42510a4465c6e85435b97f-arm64_v8a.apk)

Other architectures: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1423-a8292eec2f91b2dc6f42510a4465c6e85435b97f-armv7.apk), [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1423-a8292eec2f91b2dc6f42510a4465c6e85435b97f-x86_64.apk), [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1423-a8292eec2f91b2dc6f42510a4465c6e85435b97f-x86.apk)

**Comment by suricactus** [comment]
Okay, much smarter way to do it than my attempt. Thanks!

**Comment by m-kuhn** [comment]
```
s/smarter/easier/
```

I wouldn't mind having these variables set per job instead of globally

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1423-02c6b16fbf5e82fee374bcb20bec3b1be5643ab9-arm64_v8a.apk)

Other architectures: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1423-02c6b16fbf5e82fee374bcb20bec3b1be5643ab9-armv7.apk), [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1423-02c6b16fbf5e82fee374bcb20bec3b1be5643ab9-x86_64.apk), [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1423-02c6b16fbf5e82fee374bcb20bec3b1be5643ab9-x86.apk)

**Pull request merged**
