### PR TITLE
🚧 Replace ACTION_VIEW with ACTION_EDIT

### PR DESCRIPTION
**Pull request by m-kuhn**
Make external resources editable.
Test only

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-976-177ac1069f443267a3a7509ed367f7c474cf5365-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-976-177ac1069f443267a3a7509ed367f7c474cf5365-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-976-177ac1069f443267a3a7509ed367f7c474cf5365-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-976-177ac1069f443267a3a7509ed367f7c474cf5365-x86_64.apk)

**Comment by m-kuhn** [comment]
Feedback:

 - This *works* with the Collabora office suite
 - This *does not work* with the MS office suite

The later is likely related to https://github.com/cryptomator/cryptomator-android/issues/150#issuecomment-514401775

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-976-4a82a3ec2b4c464debe43c7b6e8584424f347b58-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-976-4a82a3ec2b4c464debe43c7b6e8584424f347b58-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-976-4a82a3ec2b4c464debe43c7b6e8584424f347b58-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-976-4a82a3ec2b4c464debe43c7b6e8584424f347b58-x86_64.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d6d67755831e2dac87770779e8d95d22ad199f52:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-976-af97f28c4143f7f2336f421a19eaf80e97f9d9c1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-976-af97f28c4143f7f2336f421a19eaf80e97f9d9c1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-976-af97f28c4143f7f2336f421a19eaf80e97f9d9c1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-976-af97f28c4143f7f2336f421a19eaf80e97f9d9c1-x86.apk)

**Comment by nirvn** [comment]
Superseded by https://github.com/opengisch/QField/pull/2316

**Pull request closed without merging**
