### PR TITLE
Test Version Build

### PR DESCRIPTION
**Pull request by signedav**
I'm only testing a little.

It's about  to have another app built for testing. Then the brave testers do not need to uninstall the original app and can use it for comparison etc.

### CODE REVIEW

**Comment by 3nids** [comment]
See #416 I had the same idea in mind, had a quick try but failed

**Comment by signedav** [comment]
Yeah, has been a quick shot into the air from me.
Should we continue on your branch with that @3nids ?

**Comment by signedav** [comment]
Closing this - still can reopen when we continue on that...

**Comment by signedav** [comment]
Oops... Sorry haven't seen @m-kuhn that you apparently did something here as well. Feel free to reopen.

**Pull request closed without merging**
