### PR TITLE
Sentry opt-out implementation

### PR DESCRIPTION
**Pull request by nirvn**
This PR implements a UI to opt out of sentry anonymized crash reports.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e3004df9fdb66d1b967024c3b5c5a6169ae71ef9:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-17849de3d3e1e40d8ee38371b88580a5aee0b393-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-17849de3d3e1e40d8ee38371b88580a5aee0b393-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-17849de3d3e1e40d8ee38371b88580a5aee0b393-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-17849de3d3e1e40d8ee38371b88580a5aee0b393-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3cbf1dd2103eb4485395ea7af0468027b119cb9d:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-4bcd219ddb7b052453c499b9c85ddb3d9f7fc589-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-4bcd219ddb7b052453c499b9c85ddb3d9f7fc589-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-4bcd219ddb7b052453c499b9c85ddb3d9f7fc589-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-4bcd219ddb7b052453c499b9c85ddb3d9f7fc589-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b3514c92c6ae240e9a90742341653c3feb53a4bd:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-892e0aa43387674424d8a6654a0f668d9550b760-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-892e0aa43387674424d8a6654a0f668d9550b760-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-892e0aa43387674424d8a6654a0f668d9550b760-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-892e0aa43387674424d8a6654a0f668d9550b760-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 40f77487b2ffce7052625413be30a91b6aa17070:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-ff6c27824b001b22a1e0ae04fae6d72f3b685d5a-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-ff6c27824b001b22a1e0ae04fae6d72f3b685d5a-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-ff6c27824b001b22a1e0ae04fae6d72f3b685d5a-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-ff6c27824b001b22a1e0ae04fae6d72f3b685d5a-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fa3689bc98c881c202cff0dfa1c3326c6b597db9:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-9dc6d0dffe8bf8d781db05a8ec8072d85354b97d-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-9dc6d0dffe8bf8d781db05a8ec8072d85354b97d-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-9dc6d0dffe8bf8d781db05a8ec8072d85354b97d-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-9dc6d0dffe8bf8d781db05a8ec8072d85354b97d-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 92dde06b593a7d27c8b3c28d9bca546b84ab7036:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-48a2ee79154fc8fc2a5cc742702402694f59d507-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-48a2ee79154fc8fc2a5cc742702402694f59d507-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-48a2ee79154fc8fc2a5cc742702402694f59d507-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-48a2ee79154fc8fc2a5cc742702402694f59d507-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 92dde06b593a7d27c8b3c28d9bca546b84ab7036:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-f4221ac9fcf440a8101a701f8f49a14055e09adf-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-f4221ac9fcf440a8101a701f8f49a14055e09adf-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-f4221ac9fcf440a8101a701f8f49a14055e09adf-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-f4221ac9fcf440a8101a701f8f49a14055e09adf-x86-android.apk)

**Comment by nirvn** [comment]
@marioba , that's ready for review.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 99a988136c89e514c5d108a3818fdbf901a71042:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-ec591880b16b55cc456c4c56f67ce1ea575ad634-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-ec591880b16b55cc456c4c56f67ce1ea575ad634-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-ec591880b16b55cc456c4c56f67ce1ea575ad634-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-ec591880b16b55cc456c4c56f67ce1ea575ad634-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e64d9175309d9ebd9b7514228e8b333d4450ffad:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-68c5dc01fb3eea569855b4fc6d00add223388907-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-68c5dc01fb3eea569855b4fc6d00add223388907-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-68c5dc01fb3eea569855b4fc6d00add223388907-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2620-68c5dc01fb3eea569855b4fc6d00add223388907-x86-android.apk)

**Review by marioba — APPROVED** [review]
LGTM

**Comment by qfield-fairy** [comment]
The backport to `release-2_0` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 3580d2363... Manually initiate sentry on the java side
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
[backport-2620-to-release-2_0 3e425edb5] Disable auto initialization of sentry
 Author: Mathieu Pellerin <nirvn.asia@gmail.com>
 Date: Sun Mar 20 12:39:50 2022 +0700
 1 file changed, 1 insertion(+)
Auto-merging src/core/CMakeLists.txt
Auto-merging src/core/platforms/platformutilities.cpp
CONFLICT (content): Merge conflict in src/core/platforms/platformutilities.cpp
Auto-merging src/core/platforms/platformutilities.h
CONFLICT (content): Merge conflict in src/core/platforms/platformutilities.h

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release-2_0 release-2_0
# Navigate to the new working tree
cd .worktrees/backport-release-2_0
# Create a new branch
git switch --create backport-2620-to-release-2_0
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 8500b80b65b67352abc1a51d4694444fdb503847,3580d23632b487a65c2f90ffb8311baf2e1e9db1,4eed5cb7c5fd5e7776798cdb170376ce5fa28bae,2105133fb1fa6af826813fce3cb04f7de96901c0,e3004df9fdb66d1b967024c3b5c5a6169ae71ef9,3cbf1dd2103eb4485395ea7af0468027b119cb9d,b3514c92c6ae240e9a90742341653c3feb53a4bd,92dde06b593a7d27c8b3c28d9bca546b84ab7036,99a988136c89e514c5d108a3818fdbf901a71042,e64d9175309d9ebd9b7514228e8b333d4450ffad
# Push it to GitHub
git push --set-upstream origin backport-2620-to-release-2_0
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release-2_0
```
Then, create a pull request where the `base` branch is `release-2_0` and the `compare`/`head` branch is `backport-2620-to-release-2_0`.

**Pull request merged**
