### PR TITLE
Direct users straight to QField's page in the all files access activity

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 77f21a591c4a5eb2245eb0afa7c42aee7ffd25c2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2344-5bc6554944e40fc6f7d88b240a766af2eef51e3c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2344-5bc6554944e40fc6f7d88b240a766af2eef51e3c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2344-5bc6554944e40fc6f7d88b240a766af2eef51e3c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2344-5bc6554944e40fc6f7d88b240a766af2eef51e3c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 973e4b45c559a800a6ce8111396be02004fa72b5:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2344-7edf285f341a4130753ad0311bf0959380e10f2a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2344-7edf285f341a4130753ad0311bf0959380e10f2a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2344-7edf285f341a4130753ad0311bf0959380e10f2a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2344-7edf285f341a4130753ad0311bf0959380e10f2a-x86.apk)

**Comment by nirvn** [comment]
Alright, this PR is ready to merge. It improves the UX of granting all files permissions a bit by avoiding the apps list selection step.

**Review by m-kuhn — APPROVED** [review]
:sparkles:

**Pull request merged**
