### PR TITLE
Fix translation

### LINKED ISSUE #752: Some words cannot translate to Japanese language
I translated QField to Japanese language by transfix. I checked my Japanese translation with version 1.3.4. Translation is mostly very fine, however, I just found 4 places which cannot translate at the following two cases.

* When I changed mode to digitize mode or browse mode or measure mode.
* When I visible / invisible  selected layer ("Show on map canvas" cannot be translated). 

Although they are not very big issue, but this might be related to other languages.

### Screenshots and GIFs
Please see following screenshots attached.

Screenshot_20191223-205132
Screenshot_20191223-205136
Screenshot_20191223-205142
Screenshot_20191223-205223

**QField version:** 1.3.4

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: [No]

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #752

### CODE REVIEW

**Comment by m-kuhn** [comment]
@JinIgarashi thank you for reporting.

I hope that this fixes the issues of the untranslatable strings. If you could check that the generated apks (they arrive in 20 minutes) work properly, let's merge and hope that they will appear on transifex.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-753-95dfdf483ab35a8eb2b34c3baf03423342095735-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-753-95dfdf483ab35a8eb2b34c3baf03423342095735-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-753-95dfdf483ab35a8eb2b34c3baf03423342095735-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-753-95dfdf483ab35a8eb2b34c3baf03423342095735-x86_64.apk)

**Comment by JinIgarashi** [comment]
@m-kuhn Thank you for fixing the issue quickly. I already translated 3 new strings to Japanese on transifex.
However, I could not find a remaining string "Show on map canvas" which appears in dialog when I change visibility of layer. I think you may need to fix same for this untranslated string.

**Comment by m-kuhn** [comment]
I tried to fix that one too, but I am still not sure what happens.
It actually is in the translation file (.ts) uploaded to transifex, but it does not appear in the web interface. I'll have to do some more tests for that one.

**Comment by ElvisDahnert** [comment]
It is not working in release 1.4.0.
New strings are missing on the transifex.

**Comment by m-kuhn** [comment]
Which strings specifically?

**Comment by ElvisDahnert** [comment]
In this PR you removed the string "You are now in% 1 mode" and added three others: "You are now in browse mode", "You are now in scan mode" and "You are now in measure mode".
Modifications were applied, new strings went to Transifex, but recently returned to what it was before.

**Pull request merged**
