### PR TITLE
Solid transparency reloaded

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for dcc07f6fc3b7437d8b01ede8adfb0d7609794562:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-508f4e6423b4cbd5c49c64959aa6dba2706d172b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-508f4e6423b4cbd5c49c64959aa6dba2706d172b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-508f4e6423b4cbd5c49c64959aa6dba2706d172b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-508f4e6423b4cbd5c49c64959aa6dba2706d172b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4ba33a632b461a85fce1da945703038eab4fcda6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-f656f31f250ffabd4befac1c5ddb7510991eb491-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-f656f31f250ffabd4befac1c5ddb7510991eb491-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-f656f31f250ffabd4befac1c5ddb7510991eb491-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-f656f31f250ffabd4befac1c5ddb7510991eb491-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 49cefb501b624fdc4646a85713e9734f7756abb9:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-407b8a3d6c07f54ef301bcc821fbac1e171106d5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-407b8a3d6c07f54ef301bcc821fbac1e171106d5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-407b8a3d6c07f54ef301bcc821fbac1e171106d5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-407b8a3d6c07f54ef301bcc821fbac1e171106d5-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3b6b3eaf367e0f1be3884a1d5f67d831e14bafb1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d5ebffe4c11fad4f7ec553118cc72a69578ec5cd-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d5ebffe4c11fad4f7ec553118cc72a69578ec5cd-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d5ebffe4c11fad4f7ec553118cc72a69578ec5cd-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d5ebffe4c11fad4f7ec553118cc72a69578ec5cd-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 24999822e65a99045be7847fc522ae65247108b1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d58b1748f0832f667b3e61761b15afb9124da779-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d58b1748f0832f667b3e61761b15afb9124da779-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d58b1748f0832f667b3e61761b15afb9124da779-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d58b1748f0832f667b3e61761b15afb9124da779-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fbeeef4d97982912fb4e471e228f2da5710410ba:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d397df3494c1b698a445fc828e787dfe8d00fd4c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d397df3494c1b698a445fc828e787dfe8d00fd4c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d397df3494c1b698a445fc828e787dfe8d00fd4c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-d397df3494c1b698a445fc828e787dfe8d00fd4c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5bab1de0f14f9a97a44c7c93282c5d076545f456:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-40831ff150f94829f0738bd66cd34fb5a52f0954-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-40831ff150f94829f0738bd66cd34fb5a52f0954-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-40831ff150f94829f0738bd66cd34fb5a52f0954-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-40831ff150f94829f0738bd66cd34fb5a52f0954-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 99d51a0a9e1dee6aadad3d352700fb3559a8816a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-06cbc7b14bf5c479bb66d0196ea0c024bcd70777-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-06cbc7b14bf5c479bb66d0196ea0c024bcd70777-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-06cbc7b14bf5c479bb66d0196ea0c024bcd70777-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-06cbc7b14bf5c479bb66d0196ea0c024bcd70777-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 00bea69ba6a850601ab4fe21d8351bd6b4579642:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-222cec23230dbc4d42f5dc5ee70d04702f01fa96-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-222cec23230dbc4d42f5dc5ee70d04702f01fa96-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-222cec23230dbc4d42f5dc5ee70d04702f01fa96-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-222cec23230dbc4d42f5dc5ee70d04702f01fa96-x86.apk)

**Comment by nirvn** [comment]
@m-kuhn , what's the status of this PR, working?

**Comment by m-kuhn** [comment]
@lucienicolier can you test the latest builds? https://github.com/opengisch/QField/actions/runs/767782635

**Comment by m-kuhn** [comment]
Seems we need to fix packaging qtcharts to revert https://github.com/opengisch/QField/pull/1844/commits/99d51a0a9e1dee6aadad3d352700fb3559a8816a

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1393daaac55242f886e5aad5dc0364538a6427d3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-79fbf2bfa3d326363d67f771343c932e9c4d6323-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-79fbf2bfa3d326363d67f771343c932e9c4d6323-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-79fbf2bfa3d326363d67f771343c932e9c4d6323-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-79fbf2bfa3d326363d67f771343c932e9c4d6323-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d1f556cdbabae6612b73a86786671ae9f3a0dc81:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-12b06a286966ef97c079be26117438518c187105-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-12b06a286966ef97c079be26117438518c187105-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-12b06a286966ef97c079be26117438518c187105-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-12b06a286966ef97c079be26117438518c187105-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d0512f4a13bf79ed0155d81507a3a3c81f58ef8a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-4055bcae0c7183e6809e7db8d2a5a2605b772e86-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-4055bcae0c7183e6809e7db8d2a5a2605b772e86-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-4055bcae0c7183e6809e7db8d2a5a2605b772e86-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-4055bcae0c7183e6809e7db8d2a5a2605b772e86-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5499a634b9915fdaaae7b6e4f9507da11b76d378:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-b8e216d35e4feed23b5b198a462d22d786038ca5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-b8e216d35e4feed23b5b198a462d22d786038ca5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-b8e216d35e4feed23b5b198a462d22d786038ca5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-b8e216d35e4feed23b5b198a462d22d786038ca5-x86.apk)

**Review by nirvn — APPROVED** [review]
:heart: :heart: :heart:

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d6e893008b61b0a7c7d723df96c396eb3f1ef497:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-48407c1d67426e5de98ad02fc6f1e4140bb91d63-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-48407c1d67426e5de98ad02fc6f1e4140bb91d63-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-48407c1d67426e5de98ad02fc6f1e4140bb91d63-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1844-48407c1d67426e5de98ad02fc6f1e4140bb91d63-x86.apk)

**Pull request merged**
