### PR TITLE
message what's happening on change of the gps icons (#880)

### PR DESCRIPTION
**Pull request by signedav**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-881-5702a2159dc5fcc711647b070ee942d04c5608ea-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-881-5702a2159dc5fcc711647b070ee942d04c5608ea-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-881-5702a2159dc5fcc711647b070ee942d04c5608ea-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-881-5702a2159dc5fcc711647b070ee942d04c5608ea-x86_64.apk)

**Comment by mbernasocchi** [comment]
@signedav here I have the old behaviour of the gps point appearing at 0,0

**Comment by signedav** [comment]
We have to merge #879 first @3nids

Thats a follow up...

**Comment by signedav** [comment]
Do we need that still?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-881-885bf0d2e714cbae32f90ce675d276cded30101d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-881-885bf0d2e714cbae32f90ce675d276cded30101d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-881-885bf0d2e714cbae32f90ce675d276cded30101d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-881-885bf0d2e714cbae32f90ce675d276cded30101d-x86_64.apk)

**Comment by signedav** [comment]
Since it works I merge...

**Pull request merged**
