### PR TITLE
Fix 0 representation in TextEdit widget

### LINKED ISSUE #139: Value '0' is handled as 'NULL'
Value '0' is handled as 'NULL'

### Reproduction Steps:

1. Create a numeric Field (default value 'NULL' or no default value)
2. insert value '0'
3. Qfield saves value as 'NULL'

### Expected behavior:

It is expected that qfield saves the enterd value '0' in to the field.

### Observed behavior:

Instead of '0' Qfield leaves the field blank (NULL)

**QField version:** 0.10

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: ?
* Problem can be reliably reproduced, doesn't happen randomly: Yes (on postgis and geopackage datasources)
* Problem happens with all files and projects, not only some files or projects: Yes (on postgis and geopackage datasources)

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #139

### CODE REVIEW

**Comment by m-kuhn** [comment]
@soester can you give this a try? It's heavily untested, but looks like a sensible approach ;)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-269-a9d5bae911176165fa92d95725615ada154931c2-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-269-a9d5bae911176165fa92d95725615ada154931c2-x86.apk)

**Comment by soester** [comment]
when digitizing a new feature it is still the same (no representation of 0).
when editing an already existing feature and entering 0 it is displayed as expected. getting closer 👍

**Comment by m-kuhn** [comment]
Any chance you can send me a demo project somehow?

**Comment by soester** [comment]
sent per mail

**Comment by giedrioks26** [comment]
> when digitizing a new feature it is still the same (no representation of 0).
when editing an already existing feature and entering 0 it is displayed as expected.

it is the same for me

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-269-a5ea59a011b089126d57776753e936945e08ac3f-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-269-a5ea59a011b089126d57776753e936945e08ac3f-x86.apk)

**Comment by giedrioks26** [comment]
Now it is good

**Comment by soester** [comment]
Wasn't able to check before.
Now (0.10.13)
If 0 is entered in to a numeric field it is stored as 0 in the data :)

just one thing:
Opening an existing record/feature in Qfield: All numeric fields with no data (NULL) are displayed as 0. It is not possible to distinguish fields with value 0 and fields where there is no data (NULL).

**Comment by giedrioks26** [comment]
I do not understand what you are talking about. I just tried it again on various devices (sony, lenovo, samsung, balckview). Everything works great. Are you sure that this version is 0.10.13?

**Comment by saemiw** [comment]
Took me a while to find out whats different. But I can only reproduce the problem when using the qfieldsync plugin. I assume you didn't test with qfieldsync @giedrioks26? When I copy'n' paste the same project (without setting it offline) it works. I used QField 0.10.13, qfieldsync 1.1.3 and QGIS 2.18.18. Attached the project I tested with:
[0 vs NULL.zip](https://github.com/opengisch/QField/files/1959703/0.vs.NULL.zip)


Do the developpers understand whats going wrong and (hopefully) can you fix it (hopefully easily...)? Can you quickly lose some words about possible solutions or workarounds (QGIS3?..., fix it quickly?). I need to find a solution soon for my project and it would be helpful to plan accordingly.

**Comment by m-kuhn** [comment]
Thanks for the demodata.
I *guess* it's related to the spatialite provider and its null handling. Not completely sure what's going on there though because inside QGIS the provider seems to work. We'll have a look at it and are also looking forward to implementing offline editing as geopackage.

**Pull request merged**
