### PR TITLE
Debug output for SRS path

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-251-044f5852b566f8e37fe58232d892593d2a5aefd8-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-251-044f5852b566f8e37fe58232d892593d2a5aefd8-x86.apk)

**Comment by m-kuhn** [comment]
@saemiw can you test this apk and let me know the first line in the message log (On this path it searches the srs.db).

**Comment by saemiw** [comment]
I uninstalled QField and then installed the test apk from above. I tested with 2 projects and get the following two messages (depending on which project I open) in the message log:

screenshot_2018-03-26-10-37-45

screenshot_2018-03-26-10-40-30

**Comment by mbernasocchi** [comment]
@saemiw could you share the projects?

**Comment by mbernasocchi** [comment]
@saemiw on what android version?

**Comment by mbernasocchi** [comment]
on my Galaxy 7 with android 7.0 I get:
image

**Comment by mbernasocchi** [comment]
or ino: /data/user was added in Jelly Bean as part of multi-user support. Each user on the device gets a directory in there named after their user ID, and that directory contains each app's data directory for that user. /data/user/0 is a symlink to /data/data.

**Comment by saemiw** [comment]
I have Android-Version 5.1.1 I'll send the two projcts through wetransfer to info@opengis.ch (in a few seconds)

**Comment by fahrwegdienste** [comment]
We have the same issue with our Galaxy Tab 2 Tablets and Android 7:
```
CRS Could not open CRS database / data / user / 0 / ch. opengis. qfield / files / share / resources / srs.db 
Error (14): unable to open database file

`````

**Pull request closed without merging**
