### PR TITLE
More codecs

### PR DESCRIPTION
**Pull request by m-kuhn**
Many new raster file formats supported, most notably COG

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f512dbe01aa494dc109a001908758c2db654aecf:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1439-6d0ee5e42d2f62809c7058b7d857e86e00dd3ac7-arm64_v8a.apk)

Other architectures: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1439-6d0ee5e42d2f62809c7058b7d857e86e00dd3ac7-armv7.apk), [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1439-6d0ee5e42d2f62809c7058b7d857e86e00dd3ac7-x86_64.apk), [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1439-6d0ee5e42d2f62809c7058b7d857e86e00dd3ac7-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 390e1bb9b69e7dbb1c2ac9fdc40400f92e7b1e51:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1439-3d67673d2b2d54acdc9087f0e09dd8b7348223b0-arm64_v8a.apk)

Other architectures: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1439-3d67673d2b2d54acdc9087f0e09dd8b7348223b0-armv7.apk), [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1439-3d67673d2b2d54acdc9087f0e09dd8b7348223b0-x86_64.apk), [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1439-3d67673d2b2d54acdc9087f0e09dd8b7348223b0-x86.apk)

**Comment by m-kuhn** [comment]
test comment

**Comment by m-kuhn** [comment]
test

**Pull request closed without merging**
