### PR TITLE
Fix the backport fairy

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
@suricactus what do you think?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3dd71e8fe8036ae3dfa0eff6ae75b6fd1e2aa62a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1639-a624c57a2e76efea835f6ca282dac85c16f418e2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1639-a624c57a2e76efea835f6ca282dac85c16f418e2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1639-a624c57a2e76efea835f6ca282dac85c16f418e2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1639-a624c57a2e76efea835f6ca282dac85c16f418e2-x86.apk)

**Review by suricactus — COMMENTED** [review]
I will not have an explanation why this would fix it, but it is what I would try too. Let's see.

**Comment by m-kuhn** [comment]
It does. Not sure why https://github.com/opengisch/QField/pull/1637

**Review by suricactus — APPROVED** [review]

**Pull request merged**
