### PR TITLE
Proper auto scale of QField buttons

### PR DESCRIPTION
**Pull request by nirvn**
Woupidou, back to proper button size on hidpi auto up-scaled mode.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-fe3bf33839a85a956d44a7b7c930829067da63dc-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-fe3bf33839a85a956d44a7b7c930829067da63dc-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-fe3bf33839a85a956d44a7b7c930829067da63dc-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-fe3bf33839a85a956d44a7b7c930829067da63dc-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-54b94ada7d443fefd4bc906cb9e5d16956f330c5-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-54b94ada7d443fefd4bc906cb9e5d16956f330c5-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-54b94ada7d443fefd4bc906cb9e5d16956f330c5-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-54b94ada7d443fefd4bc906cb9e5d16956f330c5-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-7e30a3754dfdcd4245ee1c7441188955a6451fc0-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-7e30a3754dfdcd4245ee1c7441188955a6451fc0-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-7e30a3754dfdcd4245ee1c7441188955a6451fc0-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-997-7e30a3754dfdcd4245ee1c7441188955a6451fc0-x86_64.apk)

**Comment by m-kuhn** [comment]
ToolButton -> Button
Button -> QfButton

Correct?

**Comment by nirvn** [comment]
@m-kuhn , yep. What follows after that is - hopefully - Button -> QfToolButton by moving Button.qml into the Themes directory.

**Comment by nirvn** [comment]
(But that's for a different PR)

**Pull request merged**
