### PR TITLE
Save/Cancel option

### PR DESCRIPTION
**Pull request by signedav**
Regarding the discussion here #268

Sorry for the GIF frenzy ;-)

### Add-Session
Save-Button is removed. It saves on pressing "back"-key. It cancels on X. 
Message "Changes saved" / "Changes discarded" appears.
add-save-cancel

Before the Save-Button was greyed out if constraints where not valid yet. I did it with orange color and message "Constraints not valid"

add-save-constraint

***Open question: Should it be saved or canceled on tipping on canvas? Currently it saves.***

### Edit-Session
Save-Button is removed. It saves on pressing "back"-key. It cancels on X.
Message "Changes saved" / "Changes discarded" appears.
edit-save-cancel

I did the constraint handling here with orange color and message "Constraints not valid" as well.
edit-save-constraints

***Open question: Should it be saved or canceled on tipping on canvas? Currently it cancels.***

### Settings
Settings are always saved. No canceling here. Additionally I changed the checkboxes to switch-buttons.
settings

### Other Fixes in this implementation:
- Reset of values on cancel in form on edit-session (before the have been only reseted in the model)
- Care about constraints in edit-session (before you were able to save even with invalid conastraints)
- Hide of sidebar (FeatureList) when no Feature is selected (before there was an empty sidebar)

### CODE REVIEW

**Comment by signedav** [comment]
@3nids @m-kuhn Probably it's good, if you test it on the device to feel the handling.

Please give a feedback on the two open questions. It should be the same on both (edditing and adding) - but I want your opinion before I change the one or the other.

Thanks.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-320-0721f67aa271178617e54bc0af3d324e48a87e1b-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-320-0721f67aa271178617e54bc0af3d324e48a87e1b-x86.apk)

**Comment by m-kuhn** [comment]
I like the background colors for the constraints :+1: 

I'm not yet convinced by the cross icon for saving changes. I find myself looking for the "save" button, which shouldn't be if it's natural and intuitive. I have just had a look at the android stock contacts app, there's a button with the label (text) "save", the calendar I use (acal) has a cross (dismiss) and a checkmark (save) to accept new agenda entries. They also allow aborting an edit operation.

Did you look at other apps as examples?

**Comment by VxTedxV** [comment]
according to me :
- cross should not save
- back button should not save (as it's used as cancel button in many apps)
- tap on the map to exit should save entries 
- a "save" icon or text should valid entries

**Comment by signedav** [comment]
Just for information: The X cross is for cancel, not for saving.

**Comment by m-kuhn** [comment]
Not sure if we are talking about the same thing. I was talking about the feature form where I cannot see any other button which would save then?

**Comment by signedav** [comment]
The Back-Key on the device is to save: 
backkey

**Comment by m-kuhn** [comment]
That was not obvious to me at least :/

**Comment by signedav** [comment]
Ok, thanks. I like it like this pretty much, but I wasn't sure if everyone does. That's why I started the discussion in #268

For me it's intuitive on editing a feature that it's saved on back key. On adding a feature I thought it is as well because we add the feature (after digitizing) and then kind of edit it's attributes. I think it makes sense, that the behavior is the same on editing and adding features.

On other apps the back key is used diverse. It depends on the workflow. 
Eg. Some Google Map functionality (setting labels) save on back-key. Acalendar for example has the hook (like m-kuhn said). Evernote has a hook and saves on back...

**Comment by VxTedxV** [comment]
I guess it's just a matter of getting used to it. I'm personally not against any choice in the end ;)
Just be sure not to make a choice and go back... for the user to have time to get the habit !

**Comment by m-kuhn** [comment]
Modern devicec don't have physical buttons any more and from what I can see, the trend is to go to software buttons everywhere. Especially if we consider iOS apps in the future as well, where there does not even a software button exist (and none is emulated like on all the android devices without a hardware button).

Note: I am not against saving with the back key, but I think we need a button on the form as well. I did not check, but I guess even the mentioned google maps functionality does have one?

**Comment by signedav** [comment]
VxTedxV is right, that if we do it, it has to be definitive and we don't change it back on the next release. That's why it's important that this solution is okay for everyone.

@m-kuhn Google has a back arrow icon that does the same like back key. Actually on Evernote it's weird: On adding it's saved with back arrow and on edit it's not. That's not what I expected.

So should I make an update - working the same like now but including a checkmark or floppy icon?

What is the opinion of my questions with the tip on the canvas?

**Comment by 3nids** [comment]
yep, makes sense to add the button then

**Comment by signedav** [comment]
- Reinserted save buttons
- Save on tip on the canvas (like with back-key) and avoid saving with invalid constraint

savecancel_points

savecancel_poly

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-320-d68ffb02c50d8daa3bf273297ac1cc47edeb0025-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-320-d68ffb02c50d8daa3bf273297ac1cc47edeb0025-x86.apk)

**Comment by signedav** [comment]
I made some design changes for the icons:

1. Changed + button for digitizing and saving points from green to yellow. Because this button combines digitizing (in polygon the green plus) and saving (in polygon the yellow floppy). So it has to be coherent to both. We decided to make a yellow plus.
selection_028

2. Changed for adding the cancel-key (X) to a trashcan, while it's still the X on editing. This because you vanish there everything, while on editing you just cancel your changes.
selection_029

3. Replaced the floppy on adding and editing with a checkmark, because it looks more modern and most apps uses checkmarks to accept changes.
selection_030
Hereby follows the question, if we should replace the yellow floppy on digitizing as well? What do you think @VxTedxV and @3nids? Are you happy with these changes (and the ones before)?

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-320-5d058e11555de9d8b7edf92bf41902706cd778c7-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-320-5d058e11555de9d8b7edf92bf41902706cd778c7-x86.apk)

**Comment by 3nids** [comment]
sorry I meant for editing.
But looking at it again, I think it's fine as is!
good job!

**Pull request merged**
