### PR TITLE
Add cppcheck

### PR DESCRIPTION
**Pull request by m-kuhn**
:broom: :sparkles:

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-2a229b673ed7d098637d3d4ba5327ac7f20c75b8-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-2a229b673ed7d098637d3d4ba5327ac7f20c75b8-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-2a229b673ed7d098637d3d4ba5327ac7f20c75b8-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-2a229b673ed7d098637d3d4ba5327ac7f20c75b8-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-ffd19370cc79dcf212c87201e6e29fb822635028-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-ffd19370cc79dcf212c87201e6e29fb822635028-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-ffd19370cc79dcf212c87201e6e29fb822635028-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-ffd19370cc79dcf212c87201e6e29fb822635028-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-37b9dbc2cf27af0ca91f3d752244aa0b0893bfe0-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-37b9dbc2cf27af0ca91f3d752244aa0b0893bfe0-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-37b9dbc2cf27af0ca91f3d752244aa0b0893bfe0-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-37b9dbc2cf27af0ca91f3d752244aa0b0893bfe0-x86_64.apk)

**Comment by m-kuhn** [comment]
@3nids what do you think about https://github.com/opengisch/QField/pull/1050/commits/595f415b6c7e72cdc7c954aa0bf1626a816c8965 ?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-e0fc9bd883d9cbd4d02bf572f558830b405481f7-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-e0fc9bd883d9cbd4d02bf572f558830b405481f7-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-e0fc9bd883d9cbd4d02bf572f558830b405481f7-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-e0fc9bd883d9cbd4d02bf572f558830b405481f7-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-9d20b56adfb4e4c1574b242223cf574064af18d4-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-9d20b56adfb4e4c1574b242223cf574064af18d4-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-9d20b56adfb4e4c1574b242223cf574064af18d4-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-9d20b56adfb4e4c1574b242223cf574064af18d4-x86_64.apk)

**Comment by 3nids** [comment]
> @3nids what do you think about 595f415 ?

I think the whole thing is to actually copy the QgsGeometry to avoid a crash.

So maybe, the right approach is to have a clone method?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-26b1c69953245a792b35fec6860ba30a0a5c453f-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-26b1c69953245a792b35fec6860ba30a0a5c453f-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-26b1c69953245a792b35fec6860ba30a0a5c453f-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-26b1c69953245a792b35fec6860ba30a0a5c453f-x86_64.apk)

**Comment by m-kuhn** [comment]
I don't understand why the QgsGeometry should be copied to avoid a crash. In this case I'd love to see the crash.

Otherwise yes, it should be `clone()`.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-c64495abec74979e5132d333e70dcacface65090-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-c64495abec74979e5132d333e70dcacface65090-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-c64495abec74979e5132d333e70dcacface65090-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-c64495abec74979e5132d333e70dcacface65090-x86_64.apk)

**Comment by 3nids** [comment]
> I don't understand why the QgsGeometry should be copied to avoid a crash. In this case I'd love to see the crash.

I don't recall exactly but it was with the search bar.
More generally, I've seen quite a few crash occurring when you don't copy QgsFeature or QgsGeometry.  I am quite sure I had one here.

Should the wrapper use const references in the constructor?

Feel free to remove it but let's play with the search bar before releasing ;)

**Comment by m-kuhn** [comment]
> I don't recall exactly but it was with the search bar.
> More generally, I've seen quite a few crash occurring when you don't copy QgsFeature or
> QgsGeometry. I am quite sure I had one here.

Thanks for the pointer!

> Should the wrapper use const references in the constructor?

Where exactly?

> Feel free to remove it but let's play with the search bar before releasing ;)

Ok, let's do that ! It's only on master, so has still some time to cool down (no intention to backport all of this)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-6c1dfbf2b22570e169e81f9e473cd577721039f1-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-6c1dfbf2b22570e169e81f9e473cd577721039f1-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-6c1dfbf2b22570e169e81f9e473cd577721039f1-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1050-6c1dfbf2b22570e169e81f9e473cd577721039f1-x86_64.apk)

**Pull request merged**
