### PR TITLE
Qt cache

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4626574c17ddf04cc77bc081b2934034b0d927de:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-562e66b1bdef9a5c25f7b49733db120ba01764e1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-562e66b1bdef9a5c25f7b49733db120ba01764e1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-562e66b1bdef9a5c25f7b49733db120ba01764e1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-562e66b1bdef9a5c25f7b49733db120ba01764e1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 392a8e8ca751b1bd7db7d1c71f53996184042ff2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-2dd3f0e00b56191f40c1725e150035813f6f2aa4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-2dd3f0e00b56191f40c1725e150035813f6f2aa4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-2dd3f0e00b56191f40c1725e150035813f6f2aa4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-2dd3f0e00b56191f40c1725e150035813f6f2aa4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 15c22a9ae6cea39049572c835866cb3a294df3b5:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-f56e0ae41a9fae1562ad4a7e8f3c8a073bfd4fa5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-f56e0ae41a9fae1562ad4a7e8f3c8a073bfd4fa5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-f56e0ae41a9fae1562ad4a7e8f3c8a073bfd4fa5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-f56e0ae41a9fae1562ad4a7e8f3c8a073bfd4fa5-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 975819551cd41e300df319bfbb144eb0de01d9cb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-df3d4ec63663ab84dbf9a4537e350ce67cab48c4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-df3d4ec63663ab84dbf9a4537e350ce67cab48c4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-df3d4ec63663ab84dbf9a4537e350ce67cab48c4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-df3d4ec63663ab84dbf9a4537e350ce67cab48c4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6d2ab92b8006da9eba6f8d298edb92b67a9fb10f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-b9bf482d02f66a4b1c1be5ecda3515d12e8ddf0b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-b9bf482d02f66a4b1c1be5ecda3515d12e8ddf0b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-b9bf482d02f66a4b1c1be5ecda3515d12e8ddf0b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2450-b9bf482d02f66a4b1c1be5ecda3515d12e8ddf0b-x86.apk)

**Comment by m-kuhn** [comment]
Closed in favor of #2487

**Pull request closed without merging**
