### PR TITLE
Refresh logo on website, harmonize features area to match QFieldCloud website

### PR DESCRIPTION
**Pull request by nirvn**
Logo refresh campaign, part 3:
image

@mbernasocchi , while updating the logo, I've taken the liberty to adjust the features section to more or less match the style on the  qfield.cloud website.

### CODE REVIEW

**Review by mbernasocchi — APPROVED** [review]
the only micro changes that could be done is tho rename the pointx.svg to point_sync.svg and so on. Also, I think we could remove the _v3 in the css file and just call it qfield.css.

but up to you

**Comment by nirvn** [comment]
@mbernasocchi , the _v3 suffix for the css file is to avoid browsers misrendering the page due to an old cached file. A good trick to remember.

I'll rename the files from point{1,2,3} to point_{deploy,formats,sync} now.

**Comment by nirvn** [comment]
@mbernasocchi , done.

**Comment by mbernasocchi** [comment]
> @mbernasocchi , the _v3 suffix for the css file is to avoid browsers misrendering the page due to an old cached file. A good trick to remember.
fair enough :) I usually add a query param with the date :)

**Comment by nirvn** [comment]
@mbernasocchi , let's go with your query param then :) PR updated.

**Pull request merged**
