### PR TITLE
fix package path on Android

### PR DESCRIPTION
**Pull request by 3nids**
this should fix:  default demo projects on home screens not working 
see https://github.com/opengisch/QField/pull/1450#issuecomment-739251204

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 34fe7fd7c1e02f96ec250a7025de19b9b78098ed:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1452-45df2ab08818c092f2d8289b64a8e1b5527ca5dc-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1452-45df2ab08818c092f2d8289b64a8e1b5527ca5dc-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1452-45df2ab08818c092f2d8289b64a8e1b5527ca5dc-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1452-45df2ab08818c092f2d8289b64a8e1b5527ca5dc-x86.apk)

**Comment by suricactus** [comment]
Still broken for me :( https://github.com/opengisch/QField/issues/1458

**Comment by suricactus** [comment]
```
  const QList<RecentProject> demoProjects
  {
    RecentProject( LocalProject, QStringLiteral( "Simple Bee Farming Demo" ), QStringLiteral( "/resources/demo_projects/simple_bee_farming.qgs" ), true ),
    RecentProject( LocalProject, QStringLiteral( "Advanced Bee Farming Demo" ), QStringLiteral( "/resources/demo_projects/advanced_bee_farming.qgs" ), true ),
    RecentProject( LocalProject, QStringLiteral( "Live QField Users Survey Demo" ), QStringLiteral( "/resources/demo_projects/live_qfield_users_survey.qgs" ), true )
  };
```
adding the "resources" as path prefix fixed it for me.

**Comment by 3nids** [comment]
oh, right.
OK, this is something left to be done: it is not possible to have a `resources` folder on iOS as it conflicts with a system one.

2 solutions:
1. we treat the platforms differently
2. we rename the folder to something like `qfield_resources`

I'd vote for the second approach.

**Comment by suricactus** [comment]
Both work for me. 2 sounds like no code, so better we go for it.

**Comment by m-kuhn** [comment]
can we use `/share/qfield` instead of `/resources`?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 24846f6239a46ce1c2c3cc20d0cd70839e11b86e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1452-033c4c7f019e3ac9639ac1b3bc83b3b3350d1690-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1452-033c4c7f019e3ac9639ac1b3bc83b3b3350d1690-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1452-033c4c7f019e3ac9639ac1b3bc83b3b3350d1690-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1452-033c4c7f019e3ac9639ac1b3bc83b3b3350d1690-x86.apk)

**Comment by m-kuhn** [comment]
Superseded by #1482

**Pull request closed without merging**
