### PR TITLE
Fix curved geometry highlight

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0a1f3278102c726de0ce189f2f001240873a8a2b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-0070084d1e76d270cd8a9198f1b5e9903405686b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-0070084d1e76d270cd8a9198f1b5e9903405686b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-0070084d1e76d270cd8a9198f1b5e9903405686b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-0070084d1e76d270cd8a9198f1b5e9903405686b-x86.apk)

**Review by suricactus — APPROVED** [review]

**Review by nirvn — APPROVED** [review]
Test most welcome!

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 99f3b2459b8fd1e59dbee3644eb0d817771c67cb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-a81b8a694bd4cdc3c396b08b25321760cf7ecf98-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-a81b8a694bd4cdc3c396b08b25321760cf7ecf98-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-a81b8a694bd4cdc3c396b08b25321760cf7ecf98-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-a81b8a694bd4cdc3c396b08b25321760cf7ecf98-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8e44bdc7c5fa639f6758df9bcc807df2a5f7a275:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-d1e399932ab0c70ae706924a2a4fe3719d66ad94-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-d1e399932ab0c70ae706924a2a4fe3719d66ad94-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-d1e399932ab0c70ae706924a2a4fe3719d66ad94-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-d1e399932ab0c70ae706924a2a4fe3719d66ad94-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a9c3fef549d68b709317c19499f2b38131285b69:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-5be66f4a45fcc7632ce11cf42a830773220d27ae-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-5be66f4a45fcc7632ce11cf42a830773220d27ae-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-5be66f4a45fcc7632ce11cf42a830773220d27ae-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2424-5be66f4a45fcc7632ce11cf42a830773220d27ae-x86.apk)

**Pull request merged**
