### PR TITLE
Add step increase/decrease button to the attribute editor number widget

### PR DESCRIPTION
**Pull request by nirvn**
A screencast worth a thousand words:

https://user-images.githubusercontent.com/1728657/126148140-61146b61-f6ae-4eb2-af22-965d743f1b39.mp4

This PR adds a pair of buttons to the attribute editor's number widget to increase/decrease numerical value by a given step (that is defined in projects' editor settings).

The buttons support tap/press and hold interaction, whereas the increase/decrease will be triggered at an interval that starts relatively large and gets faster over time (mimicking what we do in the digitizing toolbar's remove vertex button).

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1fcd71c56a277f1dde9ed379f69794bbfb1d3614:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2046-a4972c9378f8a9a967c7183840499ca1923e367b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2046-a4972c9378f8a9a967c7183840499ca1923e367b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2046-a4972c9378f8a9a967c7183840499ca1923e367b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2046-a4972c9378f8a9a967c7183840499ca1923e367b-x86.apk)

**Review by suricactus — APPROVED** [review]
:tada: Wohoo!

**Comment by suricactus** [comment]
Fix https://github.com/opengisch/QField/issues/1399

**Comment by johnnycosmos** [comment]
The problem with this functionality is, when working on a mobile phone it is nearly impossible not to press those buttons when scrolling. My projects have plenty of numeric attribute fields and this results in rogue data being entered into some of them without knowing about it.

My question is, whether it would be possible to add an option in the settings for enabling and disabling this function?

**Pull request merged**
