### PR TITLE
fix translation issue take 2

### PR DESCRIPTION
**Pull request by 3nids**
see https://doc.qt.io/qt-5/qtquick-internationalization.html#7-use-qt-tr-noop-for-translatable-data-text-strings

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1092-1a9961c9dee81279795943484f3630b8771d321e-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1092-1a9961c9dee81279795943484f3630b8771d321e-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1092-1a9961c9dee81279795943484f3630b8771d321e-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1092-1a9961c9dee81279795943484f3630b8771d321e-x86_64.apk)

**Comment by m-kuhn** [comment]
Screenshot_20200702-131416_QField_Beta_1092

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1092-9edf5f29b901038e6b9b09564d65f5f6337da69e-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1092-9edf5f29b901038e6b9b09564d65f5f6337da69e-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1092-9edf5f29b901038e6b9b09564d65f5f6337da69e-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1092-9edf5f29b901038e6b9b09564d65f5f6337da69e-x86_64.apk)

**Comment by m-kuhn** [comment]
What do we gain from the extra code complexity?

**Comment by 3nids** [comment]
> What do we gain from the extra code complexity? 

I recall now: with the other approach, I could not run QField, because it was complaining that you could not run qsTr in the model (as it's scripting).
I guess it goes through here because you now compile the QML.

So, do as you think is best, it might not be a big deal to resurrect this one if we face the issue again.

**Comment by 3nids** [comment]
see https://stackoverflow.com/questions/7659442/listelement-fields-as-properties

**Comment by m-kuhn** [comment]
Bug report there says affected version 4.7, resolved in 5.0.
PR #1091 works. Is there an issue I am missing?

**Comment by m-kuhn** [comment]
I think we should go for the "simpler" approach and react if we see problems.

**Comment by 3nids** [comment]
I guess not. As said, we can still revert to this one later

**Pull request closed without merging**
