### PR TITLE
Use C locale to validate doubles

### PR DESCRIPTION
**Pull request by m-kuhn**
Attempt to fix https://github.com/opengisch/QField/issues/1667

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1a53392fe09b6a11d331aa6c76c745312786fd3f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1672-0b36f0c7e47d18b4d90c1d1c6cee435402c62679-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1672-0b36f0c7e47d18b4d90c1d1c6cee435402c62679-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1672-0b36f0c7e47d18b4d90c1d1c6cee435402c62679-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1672-0b36f0c7e47d18b4d90c1d1c6cee435402c62679-x86.apk)

**Comment by MRossez** [comment]
Thank you, with this modification, the "." can be used in the French region for the separation of floating numbers. However, "," can be used but does not change the height of the antenna.

**Comment by m-kuhn** [comment]
I think @signedav once invested a considerable amount of time to support ","

**Comment by signedav** [comment]
I don't remember everything. I think I could accept the comma by using `RegExpValidator` instead of `DoubleValidator` her c836a030e863d28118090ca2411c45c3c47f69c6 but since I couldn't use the max and min value for the range widgets anymore, I came back to the same sollution like you did here in this PR @m-kuhn see #1047 But maybe here a  `RegExpValidator` would be appropriated... 

Anyway I give you an aprovement.

**Review by signedav — APPROVED** [review]

**Comment by m-kuhn** [comment]
Thanks for testing @MRossez and for the feedback @signedav 
Backport?

**Pull request merged**
