### PR TITLE
Add framework to produce QField+ builds

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4d5830bb24a289f2ea1da396bc8e04e8a6e4c6af:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-9fdea48263582000a0547ca75f5e44551c96ead9-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-9fdea48263582000a0547ca75f5e44551c96ead9-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-9fdea48263582000a0547ca75f5e44551c96ead9-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-9fdea48263582000a0547ca75f5e44551c96ead9-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-9fdea48263582000a0547ca75f5e44551c96ead9-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7e21a503bff098cc3c0fc34e882ae041c12171be:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-565bfab976b538e959811117c686cbbc83d3adfd-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-565bfab976b538e959811117c686cbbc83d3adfd-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-565bfab976b538e959811117c686cbbc83d3adfd-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-565bfab976b538e959811117c686cbbc83d3adfd-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-565bfab976b538e959811117c686cbbc83d3adfd-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 10a1c9a4dc246fe7a3dda7ca44d24c0a2b6fd050:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-287ab17cedaf978a52e185409e50e9253b2f8044-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-287ab17cedaf978a52e185409e50e9253b2f8044-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-287ab17cedaf978a52e185409e50e9253b2f8044-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-287ab17cedaf978a52e185409e50e9253b2f8044-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-287ab17cedaf978a52e185409e50e9253b2f8044-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 80841f6d3eb07adfb8f4ba7d36c4c5bc3e714833:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-15085c0f052023f5ac77e33a30d9c4aa778011ca-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-15085c0f052023f5ac77e33a30d9c4aa778011ca-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-15085c0f052023f5ac77e33a30d9c4aa778011ca-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-15085c0f052023f5ac77e33a30d9c4aa778011ca-x86-android.apk)

**Comment by suricactus** [comment]
+

**Comment by nirvn** [comment]
@m-kuhn , I've disabled the QField+ builds, but I'd like to merge the framework that's coded here. It removes the android-neon builds (needless) and disables the .aab uploads until a day we might need it.

We can continue discussion on this QField+ thing and add the relevant matrix whenever we got a plan :)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 662ec33f38a5a6e328507f324b86adfe8176f74b:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-d603f52343bd2aa796297bdc03b24497ccdaeaf0-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-d603f52343bd2aa796297bdc03b24497ccdaeaf0-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-d603f52343bd2aa796297bdc03b24497ccdaeaf0-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2883-d603f52343bd2aa796297bdc03b24497ccdaeaf0-x86-android.apk)

**Pull request merged**
