### PR TITLE
Indent

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
style police please

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 46981c9d90a519e550082b82e931b4ee3b9fbae3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1881-344e546e3d1fbecf400a73846600b0ab8cf52b5a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1881-344e546e3d1fbecf400a73846600b0ab8cf52b5a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1881-344e546e3d1fbecf400a73846600b0ab8cf52b5a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1881-344e546e3d1fbecf400a73846600b0ab8cf52b5a-x86.apk)

**Comment by m-kuhn** [comment]
style police please

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 46981c9d90a519e550082b82e931b4ee3b9fbae3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1881-369c650fb15538225a3960ccaf5938282936dcf0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1881-369c650fb15538225a3960ccaf5938282936dcf0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1881-369c650fb15538225a3960ccaf5938282936dcf0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1881-369c650fb15538225a3960ccaf5938282936dcf0-x86.apk)

**Comment by m-kuhn** [comment]
style police please

**Comment by m-kuhn** [comment]
style police please

**Comment by m-kuhn** [comment]
style police please

**Pull request closed without merging**
