### PR TITLE
modernize CMake

### PR DESCRIPTION
**Pull request by 3nids**
using the same script I used for QGIS in https://github.com/qgis/QGIS/pull/40004

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7d61075f1232a6769a6a0f4372cb7cf59708d480:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1772-cdf9837dc592d0e53bb35eab60988246f4456c46-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1772-cdf9837dc592d0e53bb35eab60988246f4456c46-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1772-cdf9837dc592d0e53bb35eab60988246f4456c46-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1772-cdf9837dc592d0e53bb35eab60988246f4456c46-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a7c7157ce71d822d93db75d6011f2d9a73501b95:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1772-f448b117793e77b8016b93a264d58200a78dbfe5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1772-f448b117793e77b8016b93a264d58200a78dbfe5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1772-f448b117793e77b8016b93a264d58200a78dbfe5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1772-f448b117793e77b8016b93a264d58200a78dbfe5-x86.apk)

**Comment by m-kuhn** [comment]
Should we wait for #1768 ?

**Comment by 3nids** [comment]
> Should we wait for #1768 ? 

it doesn't have have any CMakeLists changes which would require a rebase. Seems very safe to me.

**Comment by m-kuhn** [comment]
Even if they are not rebased, we'll have to run the script again?
Other PR should be merged soon.

**Comment by 3nids** [comment]
> we'll have to run the script again?

no, this will not require any other run.
But I am not in a hurry, we can definitely wait!

**Review by m-kuhn — APPROVED** [review]
Looks good to me, thanks 👍

**Pull request merged**
