### PR TITLE
NMEA followup

### PR DESCRIPTION
**Pull request by nirvn**
@signedav , as discussed with you yesterday.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7790e8b10717608059a321cb57885b131eba1d03:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-88ee6024f254ba17449cd33389df9ea8e99441bf-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-88ee6024f254ba17449cd33389df9ea8e99441bf-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-88ee6024f254ba17449cd33389df9ea8e99441bf-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-88ee6024f254ba17449cd33389df9ea8e99441bf-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e32d067d9540b973806aa4b8258300876fa090da:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-a95579c2998607dccc412f515cbfe91d7d2f036c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-a95579c2998607dccc412f515cbfe91d7d2f036c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-a95579c2998607dccc412f515cbfe91d7d2f036c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-a95579c2998607dccc412f515cbfe91d7d2f036c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 879763887053ca7341c55fe6d2406c05ff17f519:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-10fd3a1652108c56e66e6f9d4d25c0f254bbe1f3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-10fd3a1652108c56e66e6f9d4d25c0f254bbe1f3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-10fd3a1652108c56e66e6f9d4d25c0f254bbe1f3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-10fd3a1652108c56e66e6f9d4d25c0f254bbe1f3-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 100d67578e23e793c769be962c644158fb61a6d0:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-c424eaab35dcb80f7442eafbcde1d4dbbea0cebc-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-c424eaab35dcb80f7442eafbcde1d4dbbea0cebc-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-c424eaab35dcb80f7442eafbcde1d4dbbea0cebc-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1547-c424eaab35dcb80f7442eafbcde1d4dbbea0cebc-x86.apk)

**Pull request merged**
