### PR TITLE
Add Theme

### PR DESCRIPTION
**Pull request by m-kuhn**
One thing to rule them all

### CODE REVIEW

**Comment by nirvn** [comment]
Good move.

**Comment by m-kuhn** [comment]
There are many font sizes used:

12, 14, 16, 20, 25 (pointSize) and 16*dp for pixelSize.

Can we clean that up?

```
defaultFontSize: 14 # Everything that was 12, 14 or 16
titleFontSize: 20 # Everything above 16
```

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-c480628001e430eeedb73bdac0e328c76ba4503a-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-c480628001e430eeedb73bdac0e328c76ba4503a-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-c480628001e430eeedb73bdac0e328c76ba4503a-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-c480628001e430eeedb73bdac0e328c76ba4503a-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-c480628001e430eeedb73bdac0e328c76ba4503a-x86-5.apk)

**Comment by nirvn** [comment]
When working on harmonizing headers, I felt 14 was too small, but 20 was definitely too big. 

default 14
secondaryTitle 16
mainTitle 20

?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-846bd95a6dd1657e80588425d64771e07c4b944e-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-846bd95a6dd1657e80588425d64771e07c4b944e-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-846bd95a6dd1657e80588425d64771e07c4b944e-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-846bd95a6dd1657e80588425d64771e07c4b944e-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-846bd95a6dd1657e80588425d64771e07c4b944e-x86-5.apk)

**Comment by m-kuhn** [comment]
Sometimes we have a bold default font.

What's better having this in place

```
font.pointSize: Theme.defaultFontSize
font.bold: true
```

or as a preset

```
font: Theme.defaultFontStrong
```

**Comment by nirvn** [comment]
I think served as a font preset would be better indeed.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-0c3a4476083910845aa3d73e65f12254dead6f1f-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-0c3a4476083910845aa3d73e65f12254dead6f1f-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-0c3a4476083910845aa3d73e65f12254dead6f1f-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-0c3a4476083910845aa3d73e65f12254dead6f1f-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-661-0c3a4476083910845aa3d73e65f12254dead6f1f-x86-5.apk)

**Comment by m-kuhn** [comment]
@3nids @nirvn @signedav 
if someone can give me a positive review I can merge this

**Comment by nirvn** [comment]
Done.

**Pull request merged**
