### PR TITLE
Fix storing new variables

### LINKED ISSUE #856: New Global variables cannot be saved
[Short description of problem here]
Existing global variables from previous versions of Qfield continue to work, but when new global variables are added, they can be viewed in Settings for the rest of the session, but disappear when Qfield is closed. Also, expressions that rely on them and that worked correctly in earlier versions of Qfield no longer work.

### Reproduction Steps:

1. [First Step]
Navigate to Settings>Global Variables
2. [Second Step]
Naviagate to the new record
3. [Other Steps...]
Add a new variable name and value "Operator_name","RatLen"
Click Tick
[AshwayGap.zip](https://github.com/opengisch/QField/files/4250199/AshwayGap.zip)

### Expected behavior:
New global variable is added permenantly and remains available after closing and reopening Qfield
New global variable is available to expressions allowing functionality that mirrors QGIS

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]
New global variables remain ONLY for the current session dying when Qfield is closed
New global variables are not available for expressions to use.

### Screenshots and GIFs

Screenshots and GIFs which follow reproduction steps to demonstrate the problem

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]
1.4.4 - Olavtoppen (code:010404992)
1.3.4 - Ben Nevis (10304995)
Issue has been seen in the Above versions of Qfield

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] Yes
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #856

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-862-eadc49888ec77688537ed312758e3031ddc2b190-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-862-eadc49888ec77688537ed312758e3031ddc2b190-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-862-eadc49888ec77688537ed312758e3031ddc2b190-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-862-eadc49888ec77688537ed312758e3031ddc2b190-x86_64.apk)

**Comment by m-kuhn** [comment]
@nirvn can you give me a review on this?
For reference, it has been successfully tested (see #856)

**Comment by nirvn** [comment]
Done.

**Comment by m-kuhn** [comment]
Thanks !

**Pull request merged**
