### PR TITLE
Fix location marker direction/bearing rotation

### LINKED ISSUE #782: GPS direction is not working
Upon installing new version 1.4.0 from apk available here, I tested the GPS direction functionality on a Pixel 2 running Android 10 and a Samsung Galaxy Tab Active2 running Android 9. In both cases, the cone graphic indicating the direction always faces straight up (in most cases presumed North). Rotating the device produces no change in the heading.  Walking around a square city block produces no change in heading. I confirmed that the implementation in Google Maps is functioning correctly and did compass calibrations on each device.  In addition, I tested the dev apk version associated with PR #757 just in case this functionality somehow didn't make it into the 1.4.0 release.  GPS direction also did not function as intended in that version. 

### Reproduction Steps:

1. Install Version 1.4.0 from apk over existing 1.3.4 version or install independent version from dev apk
2. Open any project and activate GPS positioning services
3. Once a fix has been obtained, change orientation of device by rotating or walking differing headings for at least a city block

### Expected behavior:

Direction indicator graphic should point towards my GPS heading

### Observed behavior:

Direction indicator always points straight up

**QField version:** 1.4.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

### PR DESCRIPTION
**Pull request by nirvn**
Proof of life:
image

Fix #782

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-0807509596db248964b35abcd5192fc48f74a82c-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-0807509596db248964b35abcd5192fc48f74a82c-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-0807509596db248964b35abcd5192fc48f74a82c-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-0807509596db248964b35abcd5192fc48f74a82c-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-b0bd6af1311c7c99b207f638fb777edc49260b46-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-b0bd6af1311c7c99b207f638fb777edc49260b46-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-b0bd6af1311c7c99b207f638fb777edc49260b46-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-b0bd6af1311c7c99b207f638fb777edc49260b46-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-de9e584e65aa55f36060b96c31ba1067afd37dfc-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-de9e584e65aa55f36060b96c31ba1067afd37dfc-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-de9e584e65aa55f36060b96c31ba1067afd37dfc-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-de9e584e65aa55f36060b96c31ba1067afd37dfc-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-7aeff54665f975349fc04e59eed8faa705603462-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-7aeff54665f975349fc04e59eed8faa705603462-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-7aeff54665f975349fc04e59eed8faa705603462-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-7aeff54665f975349fc04e59eed8faa705603462-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-aef9044bdaaef38c73a22928a3e8c2e749cb69df-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-aef9044bdaaef38c73a22928a3e8c2e749cb69df-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-aef9044bdaaef38c73a22928a3e8c2e749cb69df-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-aef9044bdaaef38c73a22928a3e8c2e749cb69df-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-2e64eb9ee7ecc584f8763d89c5c903a5f1cff09b-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-2e64eb9ee7ecc584f8763d89c5c903a5f1cff09b-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-2e64eb9ee7ecc584f8763d89c5c903a5f1cff09b-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-2e64eb9ee7ecc584f8763d89c5c903a5f1cff09b-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-914f9701fe2e694e0b2231444dd2faf77f4e05c9-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-914f9701fe2e694e0b2231444dd2faf77f4e05c9-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-914f9701fe2e694e0b2231444dd2faf77f4e05c9-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-914f9701fe2e694e0b2231444dd2faf77f4e05c9-x86_64.apk)

**Comment by m-kuhn** [comment]
Thanks @nirvn !

@ivankautter can you test this apk?
I think that's the main issue for a release of 1.4.1 and going live (out of beta)

**Comment by ivankautter** [comment]
Not sure what would constitute a complete tests here, but I downloaded the apk above onto Pixel 2 running Android 10. Did a quick walk around the block and the heading corresponded to my direction of movement.  I don't whether the spec was for gps heading which I believe is based on movement or device orientation/azimuth which has more to do with position sensors, but it appeared that rotating the device independent of movement did not cause a heading change.

**Comment by nirvn** [comment]
That's the expected behavior of the code as PositionSource's position.ditection is a representation of movement direction, not compass per say.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-de01db4cdfe5e7cadf546d940c01ab5382397cc2-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-de01db4cdfe5e7cadf546d940c01ab5382397cc2-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-de01db4cdfe5e7cadf546d940c01ab5382397cc2-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-de01db4cdfe5e7cadf546d940c01ab5382397cc2-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-8b9dfef7498e86b7e62f7ed38e64dc313982c02c-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-8b9dfef7498e86b7e62f7ed38e64dc313982c02c-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-8b9dfef7498e86b7e62f7ed38e64dc313982c02c-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-786-8b9dfef7498e86b7e62f7ed38e64dc313982c02c-x86_64.apk)

**Comment by nirvn** [comment]
Direction image updated:
Screenshot_20200129-114023_QField Beta 786

IMHO , ready to merge.

**Pull request merged**
