### PR TITLE
Bump Qt Version to 5.12

### LINKED ISSUE #289: Text entry only in capital letters
Since at least QField 0.10.12 (also 0.10.13) but not 0.10.9 QField has a problem when entering text. It always turns on the capital function and all text is entered in capital letters. The button to write in small letters can be pushed and one letter be entered correctly. But he following letter will be entered as capital again. This behaviour seems device or android version specific. We can only reproduce it on Samsung Galaxy Tab Active 2 (model number SM-T395, android version 7.1.1) but not on with model number Galaxy Tab Active (SM-T365, android version 5.1.1)

Can anyone reproduce this with other devices/Android versions? Do the developers see a possiblity to solve this?

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #289

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-403-48e9722421297fc2992e366c596127a8dd184365-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-403-48e9722421297fc2992e366c596127a8dd184365-x86.apk)

**Comment by 3nids** [comment]
12-06 08:00:08.156   882   900 I mmid    : select timeout: wait for receiving msg
12-06 08:00:08.184 20709 20709 W System  : ClassLoader referenced unknown path: 
12-06 08:00:08.214 20709 20714 I zygote  : Do partial code cache collection, code=22KB, data=23KB
12-06 08:00:08.215 20709 20714 I zygote  : After code cache collection, code=22KB, data=23KB
12-06 08:00:08.215 20709 20714 I zygote  : Increasing code cache capacity to 128KB
12-06 08:00:08.462 20709 20709 W qtMainLoopThrea: type=1400 audit(0.0:16646): avc: denied { read } for name="stat" dev="proc" ino=4026532075 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
12-06 08:00:08.506 20709 20910 E AndroidRuntime: FATAL EXCEPTION: qtMainLoopThread
12-06 08:00:08.506 20709 20910 E AndroidRuntime: Process: ch.opengis.qfield, PID: 20709
12-06 08:00:08.506 20709 20910 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found
12-06 08:00:08.506 20709 20910 E AndroidRuntime: 	at java.lang.Runtime.load0(Runtime.java:928)
12-06 08:00:08.506 20709 20910 E AndroidRuntime: 	at java.lang.System.load(System.java:1621)
12-06 08:00:08.506 20709 20910 E AndroidRuntime: 	at org.qtproject.qt5.android.QtNative$2.run(QtNative.java:179)
12-06 08:00:08.506 20709 20910 E AndroidRuntime: 	at org.qtproject.qt5.android.QtThread$2.run(QtThread.java:87)
12-06 08:00:08.506 20709 20910 E AndroidRuntime: 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
12-06 08:00:08.506 20709 20910 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
12-06 08:00:08.516  1375  7599 W ActivityManager:   Force finishing activity ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity
12-06 08:00:08.520  1375  7599 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
12-06 08:00:08.556  1375  1445 I ActivityManager: Showing crash dialog for package ch.opengis.qfield u0
12-06 08:00:08.657  1375  4408 I OpenGLRenderer: Initialized EGL, version 1.4
12-06 08:00:08.657  1375  4408 D OpenGLRenderer: Swap behavior 2
12-06 08:00:09.038  1375  1444 W ActivityManager: Activity pause timeout for ActivityRecord{429f97b u0 ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity t1040 f}
12-06 08:00:09.042  1375  1444 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{4eb08aa com.google.android.packageinstaller} is now in focus and seems to be in full-screen mode
12-06 08:00:09.042  1375  1444 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.google.android.packageinstaller/com.android.packageinstaller.DeleteStagedFileOnResult/27
12-06 08:00:09.044   857   884 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-06 08:00:09.091  1375  1401 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
12-06 08:00:09.105  1375 13235 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{4d74b50 com.android.launcher3} is now in focus and seems to be in full-screen mode
12-06 08:00:09.105  1375 13235 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.android.launcher3/com.android.searchlauncher.SearchLauncher/27

is this enough?

**Comment by m-kuhn** [comment]
yes, but doesn't ring a bell yet :(

**Comment by 3nids** [comment]
here is more if needed https://pastebin.com/6xJUDSPe

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-403-48e9722421297fc2992e366c596127a8dd184365-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-403-48e9722421297fc2992e366c596127a8dd184365-x86.apk)

**Comment by m-kuhn** [comment]
@PeterPetrik since updating to Qt 5.12 and disabling QtSerialPort we have crashes on startup because of missing libc++_shared.so
Did you experience something similar?

**Comment by PeterPetrik** [comment]
Havent upgrade to 5.12 yet... sorry

**Comment by 3nids** [comment]
image

**Comment by m-kuhn** [comment]
@3nids that's a warning only I think it should work anyway

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-403-d45267864f06a846561b66bfff5ea0e4c28864c3-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-403-d45267864f06a846561b66bfff5ea0e4c28864c3-x86.apk)

**Comment by m-kuhn** [comment]
Superseded by #478

**Pull request closed without merging**
