### PR TITLE
Add support for importing datasets/archived projects via ACTION_SEND

### PR DESCRIPTION
**Pull request by nirvn**
Unlocks importing of data from Google Hangout / Google Meet et al.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 93bf581222689bb6ab7069d3fa6261a5c1fc8421:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-ef12e2b8767bdfac85470c9f4a874c736fef20c8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-ef12e2b8767bdfac85470c9f4a874c736fef20c8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-ef12e2b8767bdfac85470c9f4a874c736fef20c8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-ef12e2b8767bdfac85470c9f4a874c736fef20c8-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 59a1c1cce4051b1930af39a193f6fef5512d6a8b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-db71584e87fc48e35f9444d5057d7e553d800e2b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-db71584e87fc48e35f9444d5057d7e553d800e2b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-db71584e87fc48e35f9444d5057d7e553d800e2b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-db71584e87fc48e35f9444d5057d7e553d800e2b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4a7a6726f670e51a045f54667e3151136a0cdd42:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-8322902a5afe05f0224e1fd1e5d3e46d90b7ee8b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-8322902a5afe05f0224e1fd1e5d3e46d90b7ee8b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-8322902a5afe05f0224e1fd1e5d3e46d90b7ee8b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2414-8322902a5afe05f0224e1fd1e5d3e46d90b7ee8b-x86.apk)

**Comment by nirvn** [comment]
@suricactus , shall we merge? :smile:

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
