### PR TITLE
hidpi fixes on map themes combo

### PR DESCRIPTION
**Pull request by signedav**
I did the same like it's done already on the widgets `ValueMap` and `RelationReference`:

Could still use some beautification. Eg:
- [ ] that it's not empty on intialization
- [ ] position of selected text has no margin in front
- [ ] I don't like the title. Shouldn't we make a symbol in front of the combo instead. eg. an eye?

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-520-7f8c879fe7b7ce8ec528c467e10a8820cd0a672d-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-520-7f8c879fe7b7ce8ec528c467e10a8820cd0a672d-x86.apk)

**Comment by signedav** [comment]
@mbernasocchi please test it, when it's built.

**Comment by mbernasocchi** [comment]
almost perfect :)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-520-7143e128d7f09917057b5df718f507c04377fa3d-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-520-7143e128d7f09917057b5df718f507c04377fa3d-x86.apk)

**Comment by mbernasocchi** [comment]
looks great. thanks

**Comment by m-kuhn** [comment]
+1 for the eye symbol (or just nothing at all)

**Comment by signedav** [comment]
Thought about nothing (as title) as well...

**Comment by mbernasocchi** [comment]
@signedav I think an eye left of the combobox is the best

**Comment by signedav** [comment]
After thinking again I prefer no title and no symbol. Because there are alot of icons already. And with a single tip on the xombo the user would understand what it's about. Don't you agree @mbernasocchi ?

**Comment by mbernasocchi** [comment]
not sure, a visual cue would be good. Fully agree on getting rid of the test though.
can you put a screenshot without title

**Comment by signedav** [comment]
image

**Comment by signedav** [comment]
I just think another icon there leads the part there a little overloaded and the user would anyway get it what the combo box is about...

**Comment by mbernasocchi** [comment]
ok. lets live i like that

**Pull request merged**
