### PR TITLE
Allow for users to manually push images/PDF files to the cloud from the project folder panel

### PR DESCRIPTION
**Pull request by nirvn**
This PR adds a mechanism - through the project folder panel - which allows users to push images and PDFs contained within a cloud project folder (or one of its subfolders) to the QFieldCloud server. 

The action is available through a raster image's 3-dot menu within the project folder panel:
image

It is enabled _only for raster files_ to prevent the world from colliding if we were to push back geopackages to the cloud, messing up with delta handling et al.

Practically speaking, this allows: a/ users to recover images that never made it into the server automatically (it shouldn't happen, but as Jurassic Park told us, life finds a way), and b/ users to send back printed layouts and atlases back onto the server.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for db116a090a2209d0ffac79cd5c76f6e98e36de1a: [**arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5542-199ce3fb3b4a64d41d4a1c8a7da0f676154a4120-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5542-199ce3fb3b4a64d41d4a1c8a7da0f676154a4120-android-arm-neon.apk)
- [x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5542-199ce3fb3b4a64d41d4a1c8a7da0f676154a4120-android-x64.apk)
- [x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5542-199ce3fb3b4a64d41d4a1c8a7da0f676154a4120-android-x86.apk)
- [**all access arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5542-199ce3fb3b4a64d41d4a1c8a7da0f676154a4120-android-arm64.apk)
- [all access arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5542-199ce3fb3b4a64d41d4a1c8a7da0f676154a4120-android-arm-neon.apk)
- [all access x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5542-199ce3fb3b4a64d41d4a1c8a7da0f676154a4120-android-x64.apk)
- [all access x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5542-199ce3fb3b4a64d41d4a1c8a7da0f676154a4120-android-x86.apk)
</details>

**Comment by m-kuhn** [comment]
@meyerlor
As author of https://ideas.qfield.org/qfieldcloud-feature-requests/p/better-pdf-handling-make-sync-deletion-possible I think you will like this

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
The backport to `release-3_3` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply db116a090... Allow for users to manually push images/PDF files to the cloud from the project folder panel
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/core/utils/qfieldcloudutils.h
Auto-merging src/qml/QFieldLocalDataPickerScreen.qml
CONFLICT (content): Merge conflict in src/qml/QFieldLocalDataPickerScreen.qml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release-3_3 release-3_3
# Navigate to the new working tree
cd .worktrees/backport-release-3_3
# Create a new branch
git switch --create backport-5542-to-release-3_3
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick db116a090a2209d0ffac79cd5c76f6e98e36de1a,e7a09c9e5449b50b3618e76c96741338415d11d2
# Push it to GitHub
git push --set-upstream origin backport-5542-to-release-3_3
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release-3_3
```
Then, create a pull request where the `base` branch is `release-3_3` and the `compare`/`head` branch is `backport-5542-to-release-3_3`.

**Comment by meyerlor** [comment]
@m-kuhn wow, great stuff! Thanks for your awesome work again!

**Pull request merged**
