### PR TITLE
Load libexiv2 lib to fix crash on android platform

### PR DESCRIPTION
**Pull request by signedav**
test for #833

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-834-927c7135800402b66efed1bf183f59d7505aafbf-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-834-927c7135800402b66efed1bf183f59d7505aafbf-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-834-927c7135800402b66efed1bf183f59d7505aafbf-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-834-927c7135800402b66efed1bf183f59d7505aafbf-x86_64.apk)

**Comment by signedav** [comment]
Oh, it works. 🙂

🤔 So this leaded to a crash, but the JNI part doesn't. Still the JNI causes a crash on my local build as well. Strange. 

If you confirm this @nirvn then let's merge this and close the other one...

**Comment by nirvn** [comment]
This APK works for me on my two devices, no crash.

**Comment by 3nids** [comment]
woohoo, thanks.
The fact that we now rely both on cmake and pro files makes this a bit cumbersome.

**Pull request merged**
