### PR TITLE
Shake me

### PR DESCRIPTION
**Pull request by m-kuhn**
:wave: to digitize

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-787-0e2a2f80788c18bd2d09de4ea257a67cafe2c7eb-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-787-0e2a2f80788c18bd2d09de4ea257a67cafe2c7eb-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-787-0e2a2f80788c18bd2d09de4ea257a67cafe2c7eb-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-787-0e2a2f80788c18bd2d09de4ea257a67cafe2c7eb-x86_64.apk)

**Comment by nirvn** [comment]
Noyce. I think this deserves a toggle in the settings panel.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-787-6aa5d1f0c56f4d576aad47448fee0373bd7bf750-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-787-6aa5d1f0c56f4d576aad47448fee0373bd7bf750-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-787-6aa5d1f0c56f4d576aad47448fee0373bd7bf750-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-787-6aa5d1f0c56f4d576aad47448fee0373bd7bf750-x86_64.apk)

**Comment by 3nids** [comment]
Interesting, but is seems to go against the idea of removing the toggling. Or is the plan either shake or always in digitizing mode?

**Comment by nirvn** [comment]
@3nids , for what it's worth, I'd be a -1 to remove the browse/edit mode toggle. When I first used QField, I had noted that very specific UI/UX as a very nice one.

**Comment by signedav** [comment]
Nice thingy. But I agree that it needs a configuration, since maybe the user is working on a shaky place (walking with the device hanging down or the motorcycle guys)...

Regarding the remove of the digitizing / browse mode:

The point is, that it's not really consistent. 
- In digitizing only we are able to add features
- In digitize and browse we are able to edit attributes on pressing the edit button on the top bar of the form
- In digitizing only we are able to edit geometries on pressing the edit button on the top bar of the form

So the question raises why being able to edit attributes over the form but not geometries. Removing the edit attributes button on browse would be a limitation in UX. And adding the edit geometries button would make the digitizing mode only to add features. So why not remove it at all? We are talking just about the toggle. The form will still have the two buttons on top to activate editing.

**Comment by nirvn** [comment]
@signedav , IMHO, keeping in a browse vs. edit state has one big benefit: being able to create the best possible UI/UX for these individual modes.

For example, if one would merge the browse and edit mode, we'd end up with a (+) add feature button overlay on the canvas, editing up visual space for absolutely no reason when you want to use QField in a view-only session. It also helps streamlining the experience for novice users.

IMHO, I'd stick to this UI/UX division, and build on top of that really nice foundation, like this PR does :smile:

**Comment by signedav** [comment]
Thanks @nirvn 

> For example, if one would merge the browse and edit mode, we'd end up with a (+) add feature button overlay on the canvas, editing up visual space for absolutely no reason when you want to use QField in a view-only session. It also helps streamlining the experience for novice users.

I agree on that. But that's the only thing at the moment and this will be compensated with the point that there would be one option less for the (new) user needs to think about (two different modes). But you're right that there could come more in future (e.g. the tracing option).

So I'm not sure. What do @m-kuhn @mbernasocchi @3nids think about it?

IMO the main problem is the inconsistent behavior at forms I mentioned above. I see three possibilities:
- Keep the mode switch but remove the attribute edit option in the form, when it's in browse mode (I don't like it since it's a restriction)
- Keep the mode switch but add the geometry edit option in the form, when it's in browse mode (I prefer, but then the only difference between the modes is the +)
- Remove the mode switch and having always the + there when the layer is selected and editable

**Comment by 3nids** [comment]
@signedav you summarised very well the situation, I am still slightly in favor of removing the switch.

One thing to recall is that the + is only visible when you have set the active layer.

 A small variant would be to tell the users to properly configure the project by making layers editable or not, the + would then be shown only for the editable ones.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cba161e4aa04d305d2f8720f3ae90af3bd5b8bd1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-98a458b600ec2a0e915988209f25e7a36c988baa-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-98a458b600ec2a0e915988209f25e7a36c988baa-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-98a458b600ec2a0e915988209f25e7a36c988baa-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-98a458b600ec2a0e915988209f25e7a36c988baa-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 017b38e9e164e52acdf65fcaf0fae5bce37e79d5:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-eb257b36769d56f264d5b2956c1c3555dcf531ba-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-eb257b36769d56f264d5b2956c1c3555dcf531ba-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-eb257b36769d56f264d5b2956c1c3555dcf531ba-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-eb257b36769d56f264d5b2956c1c3555dcf531ba-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8c9052bcdde5dd303f16c980b42fa514e0a893d2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-2946e1765c9e3d1b9cc4087a1cb39d0311323c9d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-2946e1765c9e3d1b9cc4087a1cb39d0311323c9d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-2946e1765c9e3d1b9cc4087a1cb39d0311323c9d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-787-2946e1765c9e3d1b9cc4087a1cb39d0311323c9d-x86.apk)

**Comment by m-kuhn** [comment]
Looks like we get some "whip" and "twistright" notifications, but these are too easily triggered. I don't think we something usable here.

**Comment by nirvn** [comment]
Agreed. Unless we can trigger after several shake events.

It'd likely be a much better UX win to have the mode persist across sessions.

**Comment by m-kuhn** [comment]
> It'd likely be a much better UX win to have the mode persist across sessions.

That for sure !

**Pull request closed without merging**
