### PR TITLE
Add firebase

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cb089672e7a4ff6a730d4dbb849947af29eae1fc:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-6b7ab6343cf52149fc2fb24a0a9292b0ec8e3407-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-6b7ab6343cf52149fc2fb24a0a9292b0ec8e3407-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-6b7ab6343cf52149fc2fb24a0a9292b0ec8e3407-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-6b7ab6343cf52149fc2fb24a0a9292b0ec8e3407-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 909dfa82cb2c820a8f5e291d2a2fdb23f342ff8c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-b9fe5179ae0402512c8fdd59136fcacfe4cd4512-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-b9fe5179ae0402512c8fdd59136fcacfe4cd4512-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-b9fe5179ae0402512c8fdd59136fcacfe4cd4512-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-b9fe5179ae0402512c8fdd59136fcacfe4cd4512-x86.apk)

**Comment by nirvn** [comment]
@m-kuhn , this appears to be the answer to the latest failures:

https://stackoverflow.com/questions/57868282/cannot-resolve-symbol-activitycompat-and-content

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 40c4b6d3eedcd1bc0b3bb3a0261e985e820ecda9:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-f93aa88bcdd700fb46ae01190cb29aa1f0f53456-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-f93aa88bcdd700fb46ae01190cb29aa1f0f53456-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-f93aa88bcdd700fb46ae01190cb29aa1f0f53456-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-f93aa88bcdd700fb46ae01190cb29aa1f0f53456-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5082898229df57c439f7a7e9099136edfa889a17:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-c6820253f642033205ffd5f0070f6d0ba38537bc-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-c6820253f642033205ffd5f0070f6d0ba38537bc-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-c6820253f642033205ffd5f0070f6d0ba38537bc-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-c6820253f642033205ffd5f0070f6d0ba38537bc-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9f0cbf6ab5ec7544b17b092e55bbe76884b28b5a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-15f5c0ce168192de5d47ea7f3d87d68ba220dad3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-15f5c0ce168192de5d47ea7f3d87d68ba220dad3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-15f5c0ce168192de5d47ea7f3d87d68ba220dad3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-15f5c0ce168192de5d47ea7f3d87d68ba220dad3-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3c932a6e50bf06d35bbf9e0fd3796e3f43ecf931:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-718132a64834b177788bb28cc565a71abce2671b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-718132a64834b177788bb28cc565a71abce2671b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-718132a64834b177788bb28cc565a71abce2671b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-718132a64834b177788bb28cc565a71abce2671b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cfd1e729575620991d2f8819c59978832c365c2e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-599b0701eddc18c401c90927c7333e02a00ef851-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-599b0701eddc18c401c90927c7333e02a00ef851-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-599b0701eddc18c401c90927c7333e02a00ef851-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-599b0701eddc18c401c90927c7333e02a00ef851-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3f9be62f15067e6f44d9d29f117f5ea33d42bd04:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-20087f7a9b1efab43c8b236a24d2b49606960a23-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-20087f7a9b1efab43c8b236a24d2b49606960a23-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-20087f7a9b1efab43c8b236a24d2b49606960a23-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-20087f7a9b1efab43c8b236a24d2b49606960a23-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 23969c6b76abd7cae16f321f9f3447aba830d003:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-2603f6d622292e5448be88dedb13304ab13d1c87-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-2603f6d622292e5448be88dedb13304ab13d1c87-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-2603f6d622292e5448be88dedb13304ab13d1c87-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-2603f6d622292e5448be88dedb13304ab13d1c87-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b4ddcfcd0f4e12493d66bd6948d3d27cdea19563:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-64fbba637165cfb78531291fb2a80fb0b793f6c1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-64fbba637165cfb78531291fb2a80fb0b793f6c1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-64fbba637165cfb78531291fb2a80fb0b793f6c1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-64fbba637165cfb78531291fb2a80fb0b793f6c1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2f40a51c259981012957cfefd5399cc62da5dd70:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-7d44d74555debd0b9eeac6c1183b422c5c8b21b4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-7d44d74555debd0b9eeac6c1183b422c5c8b21b4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-7d44d74555debd0b9eeac6c1183b422c5c8b21b4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-7d44d74555debd0b9eeac6c1183b422c5c8b21b4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 72d6f9d3d0e39ace0de7d34271cdd9494a9a61c6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-0f3e0e833714ed27ec96db4e860955a7f60909f3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-0f3e0e833714ed27ec96db4e860955a7f60909f3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-0f3e0e833714ed27ec96db4e860955a7f60909f3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-0f3e0e833714ed27ec96db4e860955a7f60909f3-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c050d126b0f820541c85be8f0cd43029c11220c6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-7402ab15e2675dedb40dd06a81fafe716031a4a7-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-7402ab15e2675dedb40dd06a81fafe716031a4a7-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-7402ab15e2675dedb40dd06a81fafe716031a4a7-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1682-7402ab15e2675dedb40dd06a81fafe716031a4a7-x86.apk)

**Comment by m-kuhn** [comment]
Crashlytics debug

```
adb logcat -s FirebaseCrashlytics TransportRuntime.SQLiteEventStore TransportRuntime.JobInfoScheduler TransportRuntime.CctTransportBackend TransportRuntime.DefaultScheduler
````

**Pull request closed without merging**
