### PR TITLE
fix size of checkboxes on hidpi devices

### PR DESCRIPTION
**Pull request by signedav**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-714-5f75bd55292e57af29080a754bdd8c3e393f98ee-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-714-5f75bd55292e57af29080a754bdd8c3e393f98ee-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-714-5f75bd55292e57af29080a754bdd8c3e393f98ee-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-714-5f75bd55292e57af29080a754bdd8c3e393f98ee-x86_64.apk)

**Comment by signedav** [comment]
Before

Screenshot_20191114-081445_QField

After

Screenshot_20191114-105341_QField Beta 714

**Comment by signedav** [comment]
Thanks @m-kuhn Merge?

**Comment by m-kuhn** [comment]
Yes :+1:

**Comment by 3nids** [comment]
So we already have value relation with multiple choice?

**Comment by m-kuhn** [comment]
yes

**Comment by m-kuhn** [comment]
https://github.com/opengisch/QField/releases/tag/v1.2.0

**Comment by rjwillson** [comment]
yah it is great as I just got it working this week. The increased size of the checkboxes is a nice improvement as I did worry about workers with stubby fingers

**Pull request merged**
