### PR TITLE
Free ourselves from the insanity-inducing taphandler to handle main taps/clicks

### PR DESCRIPTION
**Pull request by nirvn**
Title says it all.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8cd1e3a074a71398df32df739a38cf27ee755bb0: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4297-6b1f976b0c4386aebaf08e77aba69b708a5e1826-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4297-6b1f976b0c4386aebaf08e77aba69b708a5e1826-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4297-6b1f976b0c4386aebaf08e77aba69b708a5e1826-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4297-6b1f976b0c4386aebaf08e77aba69b708a5e1826-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4297-6b1f976b0c4386aebaf08e77aba69b708a5e1826-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4297-6b1f976b0c4386aebaf08e77aba69b708a5e1826-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4297-6b1f976b0c4386aebaf08e77aba69b708a5e1826-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4297-6b1f976b0c4386aebaf08e77aba69b708a5e1826-x86-android.apk)
</details>

**Comment by nirvn** [comment]
@m-kuhn , pitch zoom/rotate fixed.

**Comment by m-kuhn** [comment]
Confirmed. But there is still a weird freeze when pinching for more than 1s

**Comment by nirvn** [comment]
@m-kuhn , fixed.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
