### PR TITLE
Update to Qt 5.11.1

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-295-74f07b5b95e9a316b2781aaa8d2c7a6d8814378f-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-295-74f07b5b95e9a316b2781aaa8d2c7a6d8814378f-x86.apk)

**Comment by m-kuhn** [comment]
@signedav can you have a look at this?
It basically just needs some generic tests if things work as before. QGIS and Qt is updated to newer versions.

**Comment by m-kuhn** [comment]
@3nids I managed to compile the new QGIS, let's see if your quick integrations work with this.

**Comment by 3nids** [comment]
can we merge this?
or do you want prior testing with the quick changes?

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-295-cc4ac198ff588baf72b7ae2911b4b65b260899b2-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-295-cc4ac198ff588baf72b7ae2911b4b65b260899b2-x86.apk)

**Comment by 3nids** [comment]
ok!

**Comment by signedav** [comment]
```

**Comment by 3nids** [comment]
@m-kuhn just thinking, have you disable opencl?

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-295-695dfd098509985db5717fa2c52b6dabbfa261d3-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-295-695dfd098509985db5717fa2c52b6dabbfa261d3-x86.apk)

**Comment by signedav** [comment]
No crash anymore. Still kind of deadlock on vevey-project.

**Comment by signedav** [comment]
And I receive a lot of "Can't open database: unable to open database" Errors...
Didn't checked yet why. Tell me if you need the logcat...

**Comment by m-kuhn** [comment]
Logcat is mostly useful for crashes on startup (identify missing libs etc)
If this runs stable as before, I'd say merge and have a look at the wfs issue separately.

**Pull request merged**
