### PR TITLE
Avoid double std::unique_ptr::reset, long shot to fix sentry-reported crash

### PR DESCRIPTION
**Pull request by nirvn**
E.g.
- https://sentry.io/organizations/opengisch/issues/3339596703/?project=6119013
- https://sentry.io/organizations/opengisch/issues/3525218534/?project=6119013

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1bae24053afab2c8488b8b80b58284728a51c5df: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3257-e5cd890e52450071f988114c5d3bbe200579bd62-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3257-e5cd890e52450071f988114c5d3bbe200579bd62-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3257-e5cd890e52450071f988114c5d3bbe200579bd62-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3257-e5cd890e52450071f988114c5d3bbe200579bd62-x86-android.apk)
</details>

**Comment by m-kuhn** [comment]
Hmm, a double reset should be safe to do.
https://stackoverflow.com/a/57502995

**Comment by m-kuhn** [comment]
Hmm, a double reset should be safe to do.
https://stackoverflow.com/a/57502995

**Comment by nirvn** [comment]
@m-kuhn , that's what I thought too. I did stipulate it was a long shot :wink:

**Review by m-kuhn — APPROVED** [review]
It's not a bad change anyway, so let's go

**Pull request merged**
