### PR TITLE
Attribute form optimization, handling of  field present in multiple tabs

### PR DESCRIPTION
**Pull request by nirvn**
@lindacamathias , et voila. It should be _muuuch_ faster!

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5632ddabf094d3a9b910cc5312d93fae3cad85e8: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4387-c0f6a738361b3e06cfaa90431d32de19b95607be-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4387-c0f6a738361b3e06cfaa90431d32de19b95607be-arm-neon-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4387-c0f6a738361b3e06cfaa90431d32de19b95607be-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4387-c0f6a738361b3e06cfaa90431d32de19b95607be-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4387-c0f6a738361b3e06cfaa90431d32de19b95607be-arm64-android.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4387-c0f6a738361b3e06cfaa90431d32de19b95607be-arm-neon-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4387-c0f6a738361b3e06cfaa90431d32de19b95607be-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4387-c0f6a738361b3e06cfaa90431d32de19b95607be-x86-android.apk)
</details>

**Comment by lindacamathias** [comment]
i tested with simple test project and briefly with a clients project and it worked like its's supposed to :-)

**Review by lindacamathias — APPROVED** [review]
adjustment tested and it works good

**Comment by nirvn** [comment]
@lindacamathias , did you notice any speed improvements?

**Comment by lindacamathias** [comment]
> @lindacamathias , did you notice any speed improvements?
 what i experienced is that when a value is insertetd in one field it's immediately apearing in all the same fields (same field source) located somewhere else in the attribute form. this was definetely not the case before your improvements (it did not actualize at all some times)

**Comment by nirvn** [comment]
@lindacamathias , great.

@m-kuhn , @suricactus , I'd love for one or two pair of eyes to look at this.

**Review by suricactus — APPROVED** [review]
Code looks good, I shortly followed the logic but didn't go into much detail.

Is there something specific I should look at?

**Comment by nirvn** [comment]
@suricactus , if you were able to discern the logic, that's mostly what I was worried about. I didn't want to create an obscure black box. Thanks.

**Pull request merged**
