### PR TITLE
add stings for the store so they appear in transifex

### PR DESCRIPTION
**Pull request by mbernasocchi**
@m-kuhn is there some thing else to do to get the store strings to appear in Transifex?

### CODE REVIEW

**Comment by m-kuhn** [comment]
I guess there is more to do, currently only .ts files (.qml and .cpp) are sent to transifex.

Once translated, how are strings synchronized back to the store?

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-424-e521708e06c79e5f9a9a15d2e52a0d49361a554e-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-424-e521708e06c79e5f9a9a15d2e52a0d49361a554e-x86.apk)

**Comment by mbernasocchi** [comment]
> I guess there is more to do, currently only .ts files (.qml and .cpp) are sent to transifex.
ok, can I put them somewhere else then? it does not matter where, as long as the translators get to see the text

> Once translated, how are strings synchronized back to the store?
Manually, but at least we have a translation done by somebody.

**Comment by m-kuhn** [comment]
Manually uploaded
https://www.transifex.com/opengisch/qfield-for-qgis/storexml/

**Comment by mbernasocchi** [comment]
thx

**Pull request closed without merging**
