### PR TITLE
Value map performance

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-4ca7035cf3fb56801ed90a2c9886089baf5ef266-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-4ca7035cf3fb56801ed90a2c9886089baf5ef266-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-c280da129233f5249155526e4e6acd9770086a54-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-c280da129233f5249155526e4e6acd9770086a54-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-93798e2797d525d14e0ddaa5ee813f4820f42bbe-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-93798e2797d525d14e0ddaa5ee813f4820f42bbe-x86.apk)

**Comment by m-kuhn** [comment]
@saemiw this now works much faster for me with value maps, can you confirm?

**Comment by saemiw** [comment]
We tested with a project that has +/- 99 fields of which 39 have value maps. With QField 1.0.0.-rc3 it takes 21 seconds to load the form. With the above test-apk it takes 13 seconds. This is of course a great (!) improvement (and should absolutely be incorporated into the next release)  - however 13 seconds are still an aweful long time to wait. Most users will probably think QField crashed.

Some toughts on this: 99 fields are alot. We hence grouped the fields in different tabs. I guess if Qfield only loaded the necessary value maps for the tab currently shown in the form it could be faster. I don't know if a "tab-wise" loading of valuemaps is implementable/a good idea. Maybe you see other options as well. 

We worked around this issue by separating the table into multiple tables (which works fine for us, but is not solving the software "issue"). ;D In conclusion: If you don't see other promising/simple options don't worry too much (it's not a killer at the moment).

**Comment by m-kuhn** [comment]
Thanks a lot for the feedback, @saemiw 
Can you send us the dataset, so we can check where it's spending the remaining 13 seconds?
Thanks in advance

**Comment by saemiw** [comment]
> Can you send us the dataset, so we can check where it's spending the remaining 13 seconds?
-> check your mail ;D

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-597a9452fb8424c548f8ea6f7851160a93408831-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-597a9452fb8424c548f8ea6f7851160a93408831-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-61499c682ae22e0dbe4a3415d7ecf0ae2553613a-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-487-61499c682ae22e0dbe4a3415d7ecf0ae2553613a-x86.apk)

**Pull request merged**
