### PR TITLE
Performance boost when downloading packages

### PR DESCRIPTION
**Pull request by suricactus**
Use `md5` checksum instead of `sha256` checksum to gain extra performance
when downloading packaged files in QField. The `sha256` causes N+1 requests
to the S3 storage, therefore makes the QFieldCloud response on the 
`packages/<projec-id>/latest` endpoint super slow.

This change will cause an extra initial download of the project file for
all users when they sync, since we renamed `lastProjectFileSha256` to
`lastProjectFileMd5`. IMO it is acceptable, otherwise we have to handle
extra code that I would prefer not to maintain.

See https://github.com/opengisch/qfieldcloud/pull/885

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-3835 Use md5 checksum instead of sha256 checksum to gain extra performance when downloading packaged files in QField](https://app.clickup.com/t/2192114/QF-3835)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bf07b57c7abf781c0630cdd09d3c7d4d4e998c87: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5040-1a23fe16d9db0140d0a1190ccef1e40dd2736e0c-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5040-1a23fe16d9db0140d0a1190ccef1e40dd2736e0c-android-arm-neon.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5040-1a23fe16d9db0140d0a1190ccef1e40dd2736e0c-android-x64.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5040-1a23fe16d9db0140d0a1190ccef1e40dd2736e0c-android-x86.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5040-1a23fe16d9db0140d0a1190ccef1e40dd2736e0c-android-arm64.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5040-1a23fe16d9db0140d0a1190ccef1e40dd2736e0c-android-arm-neon.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5040-1a23fe16d9db0140d0a1190ccef1e40dd2736e0c-android-x64.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5040-1a23fe16d9db0140d0a1190ccef1e40dd2736e0c-android-x86.apk)
</details>

**Review by nirvn — APPROVED** [review]
Cool trick.

**Comment by nirvn** [comment]
@suricactus , can we merge this today so we can have it in the dev channel for a couple of days prior to QField 3.2.0 release? Thanks

**Comment by boardend** [comment]
Looks good from my side :+1: 

Did the following tests:
- Linux 
  - Syncing of a project with more than 2000 attachments
    - QField can now get the large file list which failed before
      - see https://github.com/opengisch/qfieldcloud/pull/885
    - But failed to actually sync on my machine because of:
```
"Downloading project `cfafd6f6-1a33-4533-97af-16e316769fd6` finished with an error: Project `sha-test`, file `files/dummy_5BE4F7F7-613D-4F0C-8823-B0D8A1B7FA61.jpg`: File system error. Failed to open file for writing on temporary `/tmp/QField.Wklgqi`. System message: Too many open files"`
```
- Android
  - Syncing of a project with more than 2000 attachments
    - Works as expected

**Comment by suricactus** [comment]
Ready to merge and as soon as we have the 0.25.0 QFC live.

**Comment by suricactus** [comment]
Ready to merge and as soon as we have the 0.25.0 QFC live.

**Comment by m-kuhn** [comment]
@suricactus @nirvn what is the expected timeline for this?

**Comment by nirvn** [comment]
I'd love to see this in for 3.2, very much fits with what's already in the changelog :)

**Pull request merged**
