### PR TITLE
Less obtrusive buttons

### PR DESCRIPTION
**Pull request by m-kuhn**
A small test to get rid of the almost black buttons.
Let me know what you think

unobtrusive buttons

### CODE REVIEW

**Comment by nirvn** [comment]
+1

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 25b75116573b3473f09e0974612c76c6da7eddf4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-a0946d369ee1a0708c124e5c7e1477cd3e0f40e8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-a0946d369ee1a0708c124e5c7e1477cd3e0f40e8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-a0946d369ee1a0708c124e5c7e1477cd3e0f40e8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-a0946d369ee1a0708c124e5c7e1477cd3e0f40e8-x86.apk)

**Comment by signedav** [comment]
+1

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 522b351313bc45cf236c1962df88bb5132e22f23:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-ed98a872a258e6b0dc21036a6f1e14a9ba219466-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-ed98a872a258e6b0dc21036a6f1e14a9ba219466-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-ed98a872a258e6b0dc21036a6f1e14a9ba219466-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-ed98a872a258e6b0dc21036a6f1e14a9ba219466-x86.apk)

**Comment by m-kuhn** [comment]
The `<` was replaced with a :arrow_left: which is more commonly used

image

**Comment by m-kuhn** [comment]
Auto merge activated. Waiting for someone brave enough to approve.

**Comment by nirvn** [comment]
@m-kuhn , I'd actually keep the '<' button when that panel you took a screenshot of is showing a specific feature from the features list. Otherwise the '>' next to it looks really odd.

**Comment by m-kuhn** [comment]
You are right, that is weird, reverted and only left it for the dashboard

**Review by nirvn — APPROVED** [review]

**Comment by nirvn** [comment]
Note: we'll need to adjust the visual for the [ delete ] button, which had a red background. Maybe keep it as is, or change the outline image itself to become red.

**Comment by nirvn** [comment]
Or wait, I think I moved that button into the 3-dot menu. Ignore me :wink:

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6bcf6c5d16a73b3134ceafb856955a88eaddc082:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-d9dd2808ca817d5ee5bd4eef6522c6648aecf78c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-d9dd2808ca817d5ee5bd4eef6522c6648aecf78c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-d9dd2808ca817d5ee5bd4eef6522c6648aecf78c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2033-d9dd2808ca817d5ee5bd4eef6522c6648aecf78c-x86.apk)

**Comment by signedav** [comment]
Really like it.

Is it planned only to be for part of the forms? I would prefere to have it for "add feature" and "embedded" forms as well.

**Comment by signedav** [comment]
And two small things.

1. There is an overlay when feature selection is active:
Screenshot_20210708-182601_QField Beta 2033

2. The disabled checkmark does not look that disabled anymore. Could be brighter maybe.
Screenshot_20210708-182417_QField Beta 2033

**Comment by m-kuhn** [comment]
Good findings.

> And two small things.
> 
> 1. There is an overlay when feature selection is active:
>    Screenshot_20210708-182601_QField Beta 2033

Hmmm... that probably was there before, overlaid with a solid black color.

> 2. The disabled checkmark does not look that disabled anymore. Could be brighter maybe.
>    Screenshot_20210708-182417_QField Beta 2033

or semi transparent?

**Comment by nirvn** [comment]
+1 to semi transparent on the disabled checkmark.

**Comment by m-kuhn** [comment]
image
30% opacity

**Comment by m-kuhn** [comment]
I cannot get the problem with the two overlaying icons to show up, what's the steps to reproduce that?

**Comment by nirvn** [comment]
@m-kuhn , I'm not in front of the computer now but I assume it's when the multi selection mode is toggled on?

**Comment by signedav** [comment]
Exactly. Having the feature list and then toggle selection on.

**Comment by m-kuhn** [comment]
image

**Comment by nirvn** [comment]
I feel it'd be better with an X here

**Comment by m-kuhn** [comment]
Can you long press a conversation in your favorite messaging app to select one (a couple of)?

**Comment by nirvn** [comment]
@m-kuhn , my favorite app being signal, is shows an 'X' which IMHO beats WhatsApp :)

**Comment by m-kuhn** [comment]
And telegram has an X too. X it is.

**Comment by signedav** [comment]
Prefering x as well.

And btw. could we stay better than all the others and keep the beautyful `<` instead of this clumbsy arrow? 🤪

**Comment by m-kuhn** [comment]
> And btw. could we stay better than all the others and keep the beautyful `<` instead of this clumbsy arrow?

If someone has time to read this blog post, I have to pack my bags now
http://mobiledesignguy.com/2018/07/20/chevrons-android-google-material-uxdesign/

**Comment by signedav** [comment]
I will read it later. From a quick look it says that it's not acceptable to use chevrons. And it does it in a very emotive way :slightly_smiling_face: :
> If you disagree then STOP reading, put the blog down, walk away and change careers. Seriously… Ok, if you are still here then you are a great designer, passionate, willing to continue to get better. AWESOME!

Even when I agree because of the circumstances that it's just best UX not to use them, I like them. `<` :heart:

**Comment by signedav** [comment]
But interesting anyway: Should we make specific designs for other platforms? Like iOS?

**Comment by signedav** [comment]
Btw. I see a lot of chevrons on my phone. Like e.g. in the gallery (Samsung), SMS and the settings. I agree to avoid it, if it's bad UX, but the statement, that it's uncommon for a Android user to see chevrons, like the blog post sais, is just wrong.

**Pull request merged**
