### PR TITLE
QField does not "require" bluetooth

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 51b721ad932e609a3c1496c43b27afb5b788998e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1504-c654455e87405452441bfe313a27a501fcfaed02-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1504-c654455e87405452441bfe313a27a501fcfaed02-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1504-c654455e87405452441bfe313a27a501fcfaed02-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1504-c654455e87405452441bfe313a27a501fcfaed02-x86.apk)

**Comment by m-kuhn** [comment]
@nirvn (aka mister "I have a couple of gps devices"), does this pr work for you?
If yes, shall we merge so people with a device without bluetooth builtin can use it again?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 370e75dca5fddca6d755cc1b97846abb0edba659:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1504-a82d6d89a54fe315ae0d5cebdf1d9dd263eb0454-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1504-a82d6d89a54fe315ae0d5cebdf1d9dd263eb0454-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1504-a82d6d89a54fe315ae0d5cebdf1d9dd263eb0454-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1504-a82d6d89a54fe315ae0d5cebdf1d9dd263eb0454-x86.apk)

**Review by nirvn — APPROVED** [review]
Testing, all good. Let bluetooth-less people be happy again!

**Pull request merged**
