### PR TITLE
Fit the feature name in the navigation bar

### PR DESCRIPTION
**Pull request by suricactus**
Peek 2020-12-07 05-31

This should be applied for the feature list and the new relation editor in future PRs.

### CODE REVIEW

**Comment by nirvn** [comment]
What happens when it reaches three lines, we get the ellipsis?

**Comment by suricactus** [comment]
Yes, the ellipsis.

**Comment by suricactus** [comment]
Anyway it should be ridiculously long name or extremely long screen.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for aa03e1bdbf64fb8911299b75fa30ed84a3ef11e7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1457-f20baa445a10922c196b5ea977a93ec7858e2379-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1457-f20baa445a10922c196b5ea977a93ec7858e2379-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1457-f20baa445a10922c196b5ea977a93ec7858e2379-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1457-f20baa445a10922c196b5ea977a93ec7858e2379-x86.apk)

**Comment by xBcai** [comment]
工程列表里长按名称，之前可以删除，现在删除不了了，希望修复
IMG_20201207_124422

**Comment by suricactus** [comment]
@xBcai please write in English, if needed use google/baidu translate. Thank you.

From your screenshot I guess you want to refer to the following issue https://github.com/opengisch/QField/issues/1458 .
This is a issue that was not introduced by this PR, but exists on master.

**Comment by xBcai** [comment]
> @xBcai please write in English, if needed use google/baidu translate. Thank you.
> 
> From your screenshot I guess you want to refer to the following issue #1458 .
> This is a issue that was not introduced by this PR, but exists on master.

ok,thank you

**Review by nirvn — APPROVED** [review]
It tickles me that we're losing all of our margin when it reflows to two lines, but it's nevertheless better than the current situation, so merge at will.

**Pull request merged**
