### PR TITLE
Further legend improvements

### LINKED ISSUE #115: Legend indentation and size
A picture says more than 1000 words

image

### LINKED ISSUE #1110: lisibility of legend structure lost
Groups and sub-groups not well rendered in legend :

path4522

I know we loose collapsible nodes but is it possible to keep legend structure in some other way like indents ?

**QField version:** 1.6.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

### PR DESCRIPTION
**Pull request by nirvn**
Screenshot:
image

Improvements include:
- while we serve the layer tree as a flattened list, its hierarchy is now preserved by adding a growing left padding (fixes #1110 );
- as discussed with @mbernasocchi  on hive, to further ease readability of the legend, layer type icons are now shown when needed;
- when toggling visibility of an item, insure all of its children are flagged as having had their visibility changed to insure that the legend widget's visibility state of items are sync'ed (fixes unreported issue)
- legend images are now properly returned for layer items with special characters (fixes #115 )
- visual improvement to the map theme combobox area

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1136-12b94e9c67e84e5671edfae4f7a71f9b82f79107-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1136-12b94e9c67e84e5671edfae4f7a71f9b82f79107-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1136-12b94e9c67e84e5671edfae4f7a71f9b82f79107-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1136-12b94e9c67e84e5671edfae4f7a71f9b82f79107-x86_64.apk)

**Comment by VxTedxV** [comment]
Works very well. Thanks ! 👍

**Comment by nirvn** [comment]
@VxTedxV , can you attach a screenshot of a complex legend of yours displayed using this PR build?

**Comment by VxTedxV** [comment]
> @VxTedxV , can you attach a screenshot of a complex legend of yours displayed using this PR build?

To compare with previous screenshot here : https://github.com/opengisch/QField/issues/1110#issue-650934450 , it's now like in QGIS 👍 :

**Pull request merged**
