### PR TITLE
Fix constraint description height

### LINKED ISSUE #908: Constraint Description Layout
There are some layout issues on the constraint description.

On e.g. drop down boxes of the value map widget, they are not visible.
On entering a value in a text widget there is not enough space.

See:
WhatsApp Image 2020-03-25 at 19 26 03

### PR DESCRIPTION
**Pull request by signedav**
Fix constraint description height
Fix position of remember box on constraint description 

fixes #908

Looks like this:
WhatsApp Image 2020-03-26 at 09 53 56

### CODE REVIEW

**Comment by signedav** [comment]
Btw. the constraint description is quite present. What about using smaller font there?
WhatsApp Image 2020-03-26 at 09 58 15

Or is this not that nice for the UX @nirvn ?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-910-7d5498bae75df14dc8b54c40aea77cafcb1cdf89-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-910-7d5498bae75df14dc8b54c40aea77cafcb1cdf89-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-910-7d5498bae75df14dc8b54c40aea77cafcb1cdf89-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-910-7d5498bae75df14dc8b54c40aea77cafcb1cdf89-x86_64.apk)

**Comment by nirvn** [comment]
I think the small font looks great.

**Comment by signedav** [comment]
Thanks @nirvn 
I made it now dependent on the field label size.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-910-e61a491ddd13731b17f6320b9367129e167926b9-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-910-e61a491ddd13731b17f6320b9367129e167926b9-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-910-e61a491ddd13731b17f6320b9367129e167926b9-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-910-e61a491ddd13731b17f6320b9367129e167926b9-x86_64.apk)

**Pull request merged**
