### PR TITLE
Vertex editor polishing and improvements

### PR DESCRIPTION
**Pull request by nirvn**
This PR gets rid of a bunch of warnings when using the geometry editor tool, and insures the vertex model highlight is only shown when the vertex  editor is activated.

The vertex model highlight also got a bit of a facelift to improve the looks (also more closely matches that of QGIS).

Before:
Screenshot from 2023-11-01 17-11-15

PR:
image

Note the far more muted segment mid-point markers in the screenshot above. That's deliberate. When already cycling through vertices and hitting the add vertex button, QField now does a much better job at hinting at the user that they are expected to select a mid-point prior to moving:
image

Last but certainly *not* least, the add vertex button is now much more clever in the way it adds a new vertex when not yet cycling through the vertex model. In the past, the vertex addition selection might have felt "random". Now, it will automatically select the segment mid-point _nearest to the coordinate cursor_.

It is also possible to select a vertex (or segment mid-point) by tapping on the device screen. This offers a fast alternative to cycling via tool buttons.

Screencast:

[Screencast from 2023-11-01 18-28-29.webm](https://github.com/opengisch/QField/assets/1728657/8673d047-386c-4867-bf8f-bd06803e9d38)

_Sponsored by [National Land Survey of Finland](https://www.maanmittauslaitos.fi/en) with the help of [GISPO](https://www.gispo.fi/en/)._

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ceb50ef0ab6632fbd1e8040d660937085c1919e2: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4724-2ffe73a22dae492837f203c5f860e1afb1a90c85-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4724-2ffe73a22dae492837f203c5f860e1afb1a90c85-arm-neon-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4724-2ffe73a22dae492837f203c5f860e1afb1a90c85-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4724-2ffe73a22dae492837f203c5f860e1afb1a90c85-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4724-2ffe73a22dae492837f203c5f860e1afb1a90c85-arm64-android.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4724-2ffe73a22dae492837f203c5f860e1afb1a90c85-arm-neon-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4724-2ffe73a22dae492837f203c5f860e1afb1a90c85-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4724-2ffe73a22dae492837f203c5f860e1afb1a90c85-x86-android.apk)
</details>

**Comment by JuhoErvasti** [comment]
Hi, I had the opportunity to test these changes and here are some things I noticed:

- I had the same issue with vertex markers persisting after clicking Cancel as noted [here](https://github.com/opengisch/QField/pull/4730#issuecomment-1808998926), although I could reproduce the same issue in an earlier version ([v.3.0.6](https://github.com/opengisch/QField/commit/d36352e844554cea7aa48ab913768ee226cd7b95)) so it's probably not related to this specific PR
- When editing a point layer since there is no add vertex button selecting the closest vertex to the coordinate cursor does not work and you have to click the point that you want to move again. 
- Overall I think this is a significant improvement to the vertex editor. Editing feels much easier and more intuitive with these changes. I wasn't able to find any bugs either.

**Comment by nirvn** [comment]
@JuhoErvasti , thanks for the feedback. The persisting vertex markers issue has been fixed. I've taken note of the point issue, although if you could share a screencast it'd probably help me better understand what you expect here.

**Comment by JuhoErvasti** [comment]
@nirvn Hi, apologies for taking so long to get back on this. So currently to move a point you have to

1. Select the point you want to edit
2. Turn on editing
3. Select the point (or vertex) again

As demonstrated in this screencast:

https://github.com/opengisch/QField/assets/118284595/13e65047-94cc-417c-9b6a-987957062001

My thought was that since a (single) point only has one vertex, when you activate the vertex editor it could either automatically select the single vertex to be edited or you'd have a button which selects it, similar to cycling through the points with lines and polygons. So step 3 could be skipped or made faster. I think it would be a bit more user-friendly this way, not sure if there'd be unintended consequences though.

**Pull request closed without merging**
