### PR TITLE
NMEA follow up: improve elevation situation

### PR DESCRIPTION
**Pull request by nirvn**
This PR is additional follow up work on NMEA support in QField based on valuable feedbacks from beta testers.

Work has been done to improve elevation value from bluetooth devices. In this PR, the default elevation is now ellipsoidal. A new toggle has been added in the positioning settings panel to switch to orthometric elevation provided by external bluetooth devices:
Screenshot from 2021-01-27 15-52-56

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fcf0aa363f5c65e89f81ecbd993a5798d6a80fad:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-e787a2d5eddcd743dbb82f1f29c90014559471d4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-e787a2d5eddcd743dbb82f1f29c90014559471d4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-e787a2d5eddcd743dbb82f1f29c90014559471d4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-e787a2d5eddcd743dbb82f1f29c90014559471d4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6a80354b3fac25c730cfb273e32ed5fa40a2205f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-13e5943663e5ddce88547d4215136ea4b73bb4d6-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-13e5943663e5ddce88547d4215136ea4b73bb4d6-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-13e5943663e5ddce88547d4215136ea4b73bb4d6-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-13e5943663e5ddce88547d4215136ea4b73bb4d6-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b8d35983a0d28db1074bb32067990c1ce0789e7b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-87e721dc4903b2d95b12311a91402a4bd32e12a3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-87e721dc4903b2d95b12311a91402a4bd32e12a3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-87e721dc4903b2d95b12311a91402a4bd32e12a3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-87e721dc4903b2d95b12311a91402a4bd32e12a3-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5f81d5b96d6c06c09ab2d118c0da110e00e686be:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-246cf8814de118164fc011d2295bd7ceaa3606a2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-246cf8814de118164fc011d2295bd7ceaa3606a2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-246cf8814de118164fc011d2295bd7ceaa3606a2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-246cf8814de118164fc011d2295bd7ceaa3606a2-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 74af84039b4742eaf95d57bbf33f1cdd55de3cb5:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-02f3b7e2e6e96219930599fbe167d0720c1357d8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-02f3b7e2e6e96219930599fbe167d0720c1357d8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-02f3b7e2e6e96219930599fbe167d0720c1357d8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-02f3b7e2e6e96219930599fbe167d0720c1357d8-x86.apk)

**Comment by schoeller** [comment]
@nirvn 
Thanks for your work. I am using Reach RS2 with integrated NTRIP correction streaming to Qfield via bluetooth. When testing the beta from https://github.com/opengisch/QField/pull/1625#issuecomment-768164232 I cannot see any stream values incoming. Please find my visual user experience on the same hardware compared between 1.8.1 and beta.
Kind regards
Sebastian

1#position configuration
Screenshot_20210127-194536_QField Beta 1625

2#1.8.1 stream view
Screenshot_20210127-194711_QField

3#beta stream view
Screenshot_20210127-194616_QField Beta 1625

**Comment by nirvn** [comment]
@schoeller , have you tried hitting the connect button?

**Comment by nirvn** [comment]
I'm coming to realize that one change here would have killed the auto connect on startup. I'll check that theory and fix it. In the meantime, if you can try hitting the connect button (as well as switching to internal device and back to reach), that'd be great.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 359dc06dc4673f521137c91d9c8019a43a783118:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-445e6d794e916e5a667066a022273fb4eae1af3d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-445e6d794e916e5a667066a022273fb4eae1af3d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-445e6d794e916e5a667066a022273fb4eae1af3d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-445e6d794e916e5a667066a022273fb4eae1af3d-x86.apk)

**Comment by nirvn** [comment]
@schoeller , can you try the latest APKs to see if the device connection issue is fixed?

**Comment by schoeller** [comment]
> 
> 
> @schoeller , can you try the latest APKs to see if the device connection issue is fixed?

@nirvn 
Thanks for the response. Installed https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-445e6d794e916e5a667066a022273fb4eae1af3d-armv7.apk and switched devices from _internally_ to _reach_ back an forth. After Pressung Connect the message "connecting..." + "successfully connected" is not showing. In 1.8.1 it is working on the same device.

**Comment by nirvn** [comment]
@schoeller , OK, hmm, wondering if it has to do with us reverting back to Qt 5.14.2 -- can you test the following APK: https://github.com/opengisch/QField/commit/b3cb747e8bb63541b6d2d8210bb438d410353e14#commitcomment-46421621 and tell me if the device properly connects. Thanks.

**Comment by schoeller** [comment]
> 
> 
> @schoeller , OK, hmm, wondering if it has to do with us reverting back to Qt 5.14.2 -- can you test the following APK: [b3cb747#commitcomment-46421621](https://github.com/opengisch/QField/commit/b3cb747e8bb63541b6d2d8210bb438d410353e14#commitcomment-46421621) and tell me if the device properly connects. Thanks.

@nirvn 
Thanks for the response. I deinstalled the previous version, installed https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-master-b3cb747e8bb63541b6d2d8210bb438d410353e14-armv7.apk. 1#Scanninng delivers message _Scanning done..._ but 2#Switching from _internal_ device to _reach_ and pressing connect does not deliver.

**Comment by nirvn** [comment]
@schoeller , this is rather worrying development, it means the issue isn't in this PR but with master (and possibly the 1.8.X branch). 

Are you in a position to give us a logcat? I'd love to see a logcat of you launching QField, opening the settings, switching to reach, clicking on connect.

**Comment by nirvn** [comment]
For the record, I was doing some testing with a reach device yesterday and the connection was fine.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 115bfefe0a591ece51aa0070ddd431a08675cff9:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-8a4728d6cbb85ece5ccc001e1ced5a8e260ae5b7-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-8a4728d6cbb85ece5ccc001e1ced5a8e260ae5b7-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-8a4728d6cbb85ece5ccc001e1ced5a8e260ae5b7-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-8a4728d6cbb85ece5ccc001e1ced5a8e260ae5b7-x86.apk)

**Comment by Benwaa74** [comment]
@nirvn, @schoeller I found the same when testing the previous apk (qfield-dev-1625-445e6d794e916e5a667066a022273fb4eae1af3d-arm64_v8a.apk) - could not connect to the reach device. Still connects no problem with 1.8.1. Just downloading the latest apk you just posted (https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-8a4728d6cbb85ece5ccc001e1ced5a8e260ae5b7-arm64_v8a.apk)...

**Comment by nirvn** [comment]
@Benwaa74 , can you give this APK a try: https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-master-b3cb747e8bb63541b6d2d8210bb438d410353e14-armv7.apk ?

**Comment by Benwaa74** [comment]
@nirvn, I'll give it a go. The previous one did not connect either. Will let you know shortly

**Comment by Benwaa74** [comment]
@nirvn , No luck unfortunately. Still will not connect to the reach antenna. It shows in the list after tapping the Scan button, but the 'Connect to reach' button has no effect. Have tried changing to Internal device and back again to the reach (multiple times) but still no good.

**Comment by nirvn** [comment]
@Benwaa74 , are you able to provide a logcat that'd cover launching QField, going in the settings and hitting the connect button?

**Comment by Benwaa74** [comment]
@nirvn Sorry, I have no idea how to create or find a logcat. Is this something that can be found on the device somewhere? I'm using a Samsung Galaxy Tab A if that helps

**Comment by schoeller** [comment]
> @schoeller , this is rather worrying development, it means the issue isn't in this PR but with master (and possibly the 1.8.X branch).
> 
> Are you in a position to give us a logcat? I'd love to see a logcat of you launching QField, opening the settings, switching to reach, clicking on connect.

@nlrvn
I tried using https://github.com/tananaev/rootless-logcat which I found on F-Droid. Using it according to best knowledge please find the [logcat.txt](https://github.com/opengisch/QField/files/5886288/logcat.txt). I hope to be useful and not misleading in any way. If to test otherwise or further please instruct.

**Comment by nirvn** [comment]
@schoeller , what is the Android version of your device? Also, did you see a permission request popup when launching QField? It'd have requested for file and network /location access permission

**Comment by schoeller** [comment]
> @schoeller , what is the Android version of your device? Also, did you see a permission request popup when launching QField? It'd have requested for file and network /location access permission

@nlrvn:
It is Android 9, kernel 3.18.91 with SE and Knox 3.3 on Samsung Galaxy Tab Active 2 SM-T395. When installing I am using arm7, since arm8 is failing. When opening after install I am prompted for access to _pictures, media, files_ and _position_ which I agree to. I then open the _Simple bee.._ dataset and scan for position etc.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 125fcc0403f4c187a3fc0600e3cb62f02e3c08fb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-81a02eeae12d8ecc4feddbf08355c2db63dfdea4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-81a02eeae12d8ecc4feddbf08355c2db63dfdea4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-81a02eeae12d8ecc4feddbf08355c2db63dfdea4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-81a02eeae12d8ecc4feddbf08355c2db63dfdea4-x86.apk)

**Comment by nirvn** [comment]
@schoeller , thanks for the information (and the time you're taking to test this out). Could you try installing the latest APKs above ( from this comment https://github.com/opengisch/QField/pull/1625#issuecomment-768953086 )  and see if it helps?

**Comment by schoeller** [comment]
@nirvn , did so. Unfortunately no change in behaviour. No message _Connecting..._ + _Successfully connected_ received compared to 1.8.1

**Comment by nirvn** [comment]
@schoeller , would you mind making a screencasting of what you see? Record QField launch, going into settings, etc.

**Comment by nirvn** [comment]
@schoeller , this is the APK that reverted Qt to 5.14.2 (https://github.com/opengisch/QField/commit/db8bbc2494df4da57504319f53f9790cc1afbacb) -- could you test if that APK also fails?

If it fails, this is the immediate revision before reverting to 5.14.2 (https://github.com/opengisch/QField/commit/bbd6c4054a5a165d40a3664b19e3c9c71057ba1d#commitcomment-45791318), again, if you can test that one and report whether bluetooth connection works, it'd be great.

**Comment by schoeller** [comment]
> @schoeller , would you mind making a screencasting of what you see? Record QField launch, going into settings, etc.

Sorry for the quality. First time use. https://user-images.githubusercontent.com/106036/106132818-b66aab80-6164-11eb-8d26-0deb125216ec.mp4

**Comment by Benwaa74** [comment]
@nirvn , the video @schoeller made is exactly what I experience too.

**Comment by schoeller** [comment]
> 
> 
> @schoeller , this is the APK that reverted Qt to 5.14.2 ([db8bbc2#commitcomment-45792024](https://github.com/opengisch/QField/commit/db8bbc2494df4da57504319f53f9790cc1afbacb#commitcomment-45792024)) -- could you test if that APK also fails?
> 
> If it fails, this is the immediate revision before reverting to 5.14.2 ([bbd6c40#commitcomment-45791318](https://github.com/opengisch/QField/commit/bbd6c4054a5a165d40a3664b19e3c9c71057ba1d#commitcomment-45791318)), again, if you can test that one and report whether bluetooth connection works, it'd be great.

@nirvn 
I sincerely hope I am not misleading anyone:
db8bbc2: arm8 install fails, arm7 installs, scan works, but does not connect to bluetooth
bbd6c40: arm8 install fails, arm7 installs, scan works, but does not connect to bluetooth

**Comment by nirvn** [comment]
@schoeller , one more, can you try the APK here:

https://github.com/opengisch/QField/commit/2a89192019cc9bc28877fd3de511f978ae6089a3#commitcomment-45790859

**Comment by schoeller** [comment]
@nirvn , please find my result as follows:
2a89192: arm8 install fails, arm7 installs, scan works, but does not connect to bluetooth

**Comment by Benwaa74** [comment]
@nirvn , arm8 installs. Have not tried arm7.  Same result as @schoeller , scan works but will not connect to antenna.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 81e9998e2b02d70e42ec81548788cebb75ef5747:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-b5c709be7513389b04142627b15d75e6a2f0202a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-b5c709be7513389b04142627b15d75e6a2f0202a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-b5c709be7513389b04142627b15d75e6a2f0202a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-b5c709be7513389b04142627b15d75e6a2f0202a-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 598bffbdf2d06690095a4ac7ff5073a06f72cac7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-e7c780dcad418db37daea7bf0fe04d9677389346-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-e7c780dcad418db37daea7bf0fe04d9677389346-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-e7c780dcad418db37daea7bf0fe04d9677389346-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-e7c780dcad418db37daea7bf0fe04d9677389346-x86.apk)

**Comment by nirvn** [comment]
@schoeller , one thing I noticed in your screencast, your location is turned off (i.e. when you launch the app, the location button at the bottom right side of the screen is disabled). Can you try to first activate this location button (by clicking on it) and see what happens?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e60b6713f89551ad913673c45c596c5278bbb3d1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-92806b2e5b0dc44978bf81e93ca40182a90df4bf-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-92806b2e5b0dc44978bf81e93ca40182a90df4bf-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-92806b2e5b0dc44978bf81e93ca40182a90df4bf-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-92806b2e5b0dc44978bf81e93ca40182a90df4bf-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d7ea2c3bbae65a2d20c5e41416d3589eab7ef9b6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-ccf10f29c450d2ce82719811b9d70924cbf542fb-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-ccf10f29c450d2ce82719811b9d70924cbf542fb-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-ccf10f29c450d2ce82719811b9d70924cbf542fb-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-ccf10f29c450d2ce82719811b9d70924cbf542fb-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1ed814c96676bffac8316a21989139513fce4051:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-f294b0d0dc261c56e7cf874db7b39962acda9825-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-f294b0d0dc261c56e7cf874db7b39962acda9825-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-f294b0d0dc261c56e7cf874db7b39962acda9825-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-f294b0d0dc261c56e7cf874db7b39962acda9825-x86.apk)

**Comment by schoeller** [comment]
> 
> 
> @schoeller , one thing I noticed in your screencast, your location is turned off (i.e. when you launch the app, the location button at the bottom right side of the screen is disabled). Can you try to first activate this location button (by clicking on it) and see what happens?

@nirvn: I kindly ask you to pardon my ignorance and to excuse the time waster. I returned to https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-445e6d794e916e5a667066a022273fb4eae1af3d-armv7.apk and enabled location within Qfield before/after configuring the bluetooth stream. Reporting of ellipsoidal position is now working as below **(_=perfect_).** In comparison the measurement with manufacturers software (ReachView3) reads an ellipsoidal height of 159,27.
_Screenshot_20210128-164612_QField Beta 1625

I am located at _lat = 50.17622849 lon = 8.73083562_. Using an ellipsoidal _height 159.272_ and the official online GEOID correction (http://gibs.bkg.bund.de/geoid/gscomp.php?p=g) I receive a correction of _z = 47.890_ to an _orthometric height = 111.38_. This matches with the official manhole cadastre which states 111,39.

After confirming correct ellipsoidal height, I would like to further test vertical correction. I have taken the freely available EGM2008, converted to GeoTIFF and stored on the device.

`gdal_translate -ot Float32 -scale 0 65000 -108 87 egm2008-1.pgm egm2008-1.tif`

When taking the same lat, lon coordinates and cross-checking (https://geographiclib.sourceforge.io/cgi-bin/GeoidEval?input=50.17622849+8.73083562&option=Submit) I receive a _vertical correction = 48.0838_, so I expect a value of 111,19 when enabling vertical correction. I suspect to require the following configuration

a#Disable _Use orthometric altitude from device_
b#Enable _Skip altitude correction from coordinate transformation_
c#Enable the vertical grid shift to _egm2008-1.tif_

Please advise whether above configuration is correct to achieve the desired behaviour. 

Best

Sebastian

**Comment by nirvn** [comment]
@schoeller , thanks for confirming things are working and the elevation value is now in sync with what is expected. Your steps on getting orthometric height via grid is sound.

Since this PR is already super noisy, I'd like to merge it and handle any additional tweaks (if needed) separately.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5552b35247be5147c134283e4868902a3b912d06:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-faecdee10a732b7d6f6b1ba42084500095fbbb68-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-faecdee10a732b7d6f6b1ba42084500095fbbb68-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-faecdee10a732b7d6f6b1ba42084500095fbbb68-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-faecdee10a732b7d6f6b1ba42084500095fbbb68-x86.apk)

**Comment by schoeller** [comment]
> Since this PR is already super noisy, I'd like to merge it and handle any additional tweaks (if needed) separately.

@nirvn 👍 
For the record: I tested vertical grid functionality using a GTIFF. It does not work, but is listed in available formats. When using GTX format it does work. I recommend to limit the listing to supported grid types. Please advise whether I should file this as an issue.

**Review by m-kuhn — APPROVED** [review]

**Comment by Benwaa74** [comment]
@nirvn The latest build (https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1625-faecdee10a732b7d6f6b1ba42084500095fbbb68-arm64_v8a.apk) works fine. Connects to reach antenna no problems.
Well done and thank you!

**Pull request merged**
