### PR TITLE
Re-focus on feature list form item after dialog is closed

### LINKED ISSUE #1173: Unable to close attribute form
QField v1.6.0 ~1.6.1

In the attribute form, after long-pressing and deleting the feature to be deleted, the attribute form cannot be closed by tapping the device back button or the map.

### PR DESCRIPTION
**Pull request by nirvn**
This should fix #1173 .

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1175-5ca4d742ff87dcf3b18daa5bc585f9e43d5ed0f2-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1175-5ca4d742ff87dcf3b18daa5bc585f9e43d5ed0f2-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1175-5ca4d742ff87dcf3b18daa5bc585f9e43d5ed0f2-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1175-5ca4d742ff87dcf3b18daa5bc585f9e43d5ed0f2-x86_64.apk)

**Comment by m-kuhn** [comment]
backport?

**Comment by m-kuhn** [comment]
@nirvn does this need backporting?

**Comment by nirvn** [comment]
I don't think so no, as far as I remember, neither multi feature delete nor merge were backported to the 1.6 branch.

**Pull request merged**
