### PR TITLE
Fix the changelog listening to QNetworkAccessManager

### PR DESCRIPTION
**Pull request by suricactus**
I know you were going to do it anyway, I just wanted to save you from some additional work @signedav .

EDIT: @nirvn saved the changelog

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 29bfc92b3e0362cc8d3a1c6c78dd90022f074987:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-e4410edc745060c54f7b0dce5121c8f8ee8a5fb1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-e4410edc745060c54f7b0dce5121c8f8ee8a5fb1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-e4410edc745060c54f7b0dce5121c8f8ee8a5fb1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-e4410edc745060c54f7b0dce5121c8f8ee8a5fb1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8c712e0d4a77c0fe4c13605a2ef94848e612698a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-71f33f2557396e43144cd4f5a94d536a4f3654b3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-71f33f2557396e43144cd4f5a94d536a4f3654b3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-71f33f2557396e43144cd4f5a94d536a4f3654b3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-71f33f2557396e43144cd4f5a94d536a4f3654b3-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c64362bdb49aa110d7cd48aa6a3252f27333ee1b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-748a005b81ca122aaf9cf7f74b063e15e2fd8a22-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-748a005b81ca122aaf9cf7f74b063e15e2fd8a22-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-748a005b81ca122aaf9cf7f74b063e15e2fd8a22-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1998-748a005b81ca122aaf9cf7f74b063e15e2fd8a22-x86.apk)

**Review by nirvn — APPROVED** [review]

**Comment by nirvn** [comment]
giphy

**Review by m-kuhn — APPROVED** [review]

**Comment by signedav** [comment]
Would never dare to touch your changelog 😇

**Comment by m-kuhn** [comment]
> Would never dare to touch **your** changelog 😇

Smooth ownership pass over 😄

**Pull request merged**
