### PR TITLE
Fix favorite folders name

### LINKED ISSUE #2352: Same name
https://user-images.githubusercontent.com/66826351/145485337-c6c16755-d7ed-497a-8ff7-7615e2e5446b.mp4

### PR DESCRIPTION
**Pull request by nirvn**
Fixes #2352 .

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 71c22e478a3fc1f2a8f585c32aa933a4eadb8736:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-1c0448f49419b1ce687fa09474152359206d811e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-1c0448f49419b1ce687fa09474152359206d811e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-1c0448f49419b1ce687fa09474152359206d811e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-1c0448f49419b1ce687fa09474152359206d811e-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0763164b93782fe85b45d1c7297f78b89f0e3682:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-c2f9dca7c4a9e2298ed7a4e1f6582dfb4ef9fd17-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-c2f9dca7c4a9e2298ed7a4e1f6582dfb4ef9fd17-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-c2f9dca7c4a9e2298ed7a4e1f6582dfb4ef9fd17-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-c2f9dca7c4a9e2298ed7a4e1f6582dfb4ef9fd17-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8f14c8ce9507cb6b3b5413433ec2f7971e50b42c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-68936aecf26af4fc8826119e74159879873af132-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-68936aecf26af4fc8826119e74159879873af132-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-68936aecf26af4fc8826119e74159879873af132-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-68936aecf26af4fc8826119e74159879873af132-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 16ac574b283fe2dc89794c08a1e8ebf85e8e5d0b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-bd5e066757f7935c9da74ac0f7d38234523dae8c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-bd5e066757f7935c9da74ac0f7d38234523dae8c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-bd5e066757f7935c9da74ac0f7d38234523dae8c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-bd5e066757f7935c9da74ac0f7d38234523dae8c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1db3d48e4f9c77317789108518af18cf7c713323:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-36c710cdf99021db961e1b99e4ec89800927c7e4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-36c710cdf99021db961e1b99e4ec89800927c7e4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-36c710cdf99021db961e1b99e4ec89800927c7e4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-36c710cdf99021db961e1b99e4ec89800927c7e4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 336eb90a8b9f3445a8e674d567f8a3c06f8729fc:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-56a9eddabf73f2ee307c46a83d67f6666df40262-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-56a9eddabf73f2ee307c46a83d67f6666df40262-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-56a9eddabf73f2ee307c46a83d67f6666df40262-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-56a9eddabf73f2ee307c46a83d67f6666df40262-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c1ab93fa1bb2aef81d0b1cb9ea6252da63118028:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-e7bfa840ca9486a97c05554dc26aafc88873f777-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-e7bfa840ca9486a97c05554dc26aafc88873f777-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-e7bfa840ca9486a97c05554dc26aafc88873f777-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-e7bfa840ca9486a97c05554dc26aafc88873f777-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c162c44bae5b456ea24c618aed14153abf98b160:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-1f12a898a7aa3d4fe34fe4002cf487604160f096-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-1f12a898a7aa3d4fe34fe4002cf487604160f096-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-1f12a898a7aa3d4fe34fe4002cf487604160f096-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-1f12a898a7aa3d4fe34fe4002cf487604160f096-x86.apk)

**Comment by nirvn** [comment]
@qfield-fairy style please

**Comment by nirvn** [comment]
😿

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b75040a9bb66eb52964ca0ada327354da2b1788a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-0292b5453e77a2185d2882193bf2e8945f377ae3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-0292b5453e77a2185d2882193bf2e8945f377ae3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-0292b5453e77a2185d2882193bf2e8945f377ae3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-0292b5453e77a2185d2882193bf2e8945f377ae3-x86.apk)

**Comment by m-kuhn** [comment]
@qfield-fairy style please

**Comment by m-kuhn** [comment]
@qfield-fairy style please

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4c1aab20bde6d5d5e57e29d85aecbf3447884907:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-f96fc74baf5b96e7c64921faeeca47447f47577e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-f96fc74baf5b96e7c64921faeeca47447f47577e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-f96fc74baf5b96e7c64921faeeca47447f47577e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-f96fc74baf5b96e7c64921faeeca47447f47577e-x86.apk)

**Comment by m-kuhn** [comment]
@qfield-fairy style please

**Comment by nirvn** [comment]
@m-kuhn , sorry, I think our wires crossed :)

**Comment by m-kuhn** [comment]
Nothing left to fix for fairy?

**Comment by nirvn** [comment]
@qfield-fairy style please

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for de11e796c97f99ec05d83676fe34c732471e21ad:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-297e7cc98574299c7230e50c6d86bcf5fa51d748-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-297e7cc98574299c7230e50c6d86bcf5fa51d748-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-297e7cc98574299c7230e50c6d86bcf5fa51d748-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-297e7cc98574299c7230e50c6d86bcf5fa51d748-x86.apk)

**Comment by nirvn** [comment]
@m-kuhn , ready to approve, auto merge enabled.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4664ce3e461397214aea121393ba6606ad806b07:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-45d7a4bb3d3edd68541f6bebca28c58ca339ce23-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-45d7a4bb3d3edd68541f6bebca28c58ca339ce23-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-45d7a4bb3d3edd68541f6bebca28c58ca339ce23-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-45d7a4bb3d3edd68541f6bebca28c58ca339ce23-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e62e5cc19e1650addf8a22f79900c5fe81b88444:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-b900b723cfeb08e83684ac58008b4169b11b62d1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-b900b723cfeb08e83684ac58008b4169b11b62d1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-b900b723cfeb08e83684ac58008b4169b11b62d1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2353-b900b723cfeb08e83684ac58008b4169b11b62d1-x86.apk)

**Pull request merged**
