### PR TITLE
Tweak inputStreamToFile implementation to guard from signal messenger crasher

### PR DESCRIPTION
**Pull request by nirvn**
PR fixes a crash when opening datasets and archived project from a signal messenger conversation.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 468bba004940af6778a1a470929e71726a626d1f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-95416adbab4f79b35f3cb9a406a1d6eece3164b4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-95416adbab4f79b35f3cb9a406a1d6eece3164b4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-95416adbab4f79b35f3cb9a406a1d6eece3164b4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-95416adbab4f79b35f3cb9a406a1d6eece3164b4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d8ba12dcd5168bc91a053a8abbf4fdf31ee46a88:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-02f55b7189a86a5c614f3c2ed43614f917278580-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-02f55b7189a86a5c614f3c2ed43614f917278580-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-02f55b7189a86a5c614f3c2ed43614f917278580-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-02f55b7189a86a5c614f3c2ed43614f917278580-x86.apk)

**Review by m-kuhn — APPROVED** [review]
Confirmed

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 64a1e69450a0506ad2c6b4350f4b0d1c94044697:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-3fffd24e48c972addc267567ccba878ff1adade6-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-3fffd24e48c972addc267567ccba878ff1adade6-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-3fffd24e48c972addc267567ccba878ff1adade6-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-3fffd24e48c972addc267567ccba878ff1adade6-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e4dd72f0d3e1f2972a89deaedac8105d8021dbe8:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-b499fefa055dabde8f6293e989ed73b5268f6426-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-b499fefa055dabde8f6293e989ed73b5268f6426-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-b499fefa055dabde8f6293e989ed73b5268f6426-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2473-b499fefa055dabde8f6293e989ed73b5268f6426-x86.apk)

**Pull request merged**
