### PR TITLE
Make sure the "Locked Geometry" setting is respected when adding/deleting/duplicating/moving features

### PR DESCRIPTION
**Pull request by suricactus**
Also consistency with hiding menu items if they are disabled.

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1932 QField configuration of `is_geometry_locked` is no longer respected on adding, deleting, moving and duplicating features](https://app.clickup.com/t/2192114/QF-1932)

**Comment by nirvn** [comment]
@suricactus , code looks good. I dislike these if (<new line> though:
image

**Comment by suricactus** [comment]
I cannot read the conditions if they are on one line since it gets quite long. Thanks why I prefer having them like this. Also, this formatting didn't came from a thin air, pretty much all code formatters do the same. The only question is where to put the operators - start or end line. My personal preference is to put the start line, as it reduces the follow-up diffs in the code if a new condition is added. However, prettier guys prefer it at the end, so I am open to change that.

**Comment by nirvn** [comment]
@suricactus , yeah, I don't have problem breaking long conditional statements into more than one line, but I really don't like a if ( without at least one conditions after it. 

E.g., I'm -1 on:
```
if (
    a == b
    || c == d
   )
```

But +1 :heart: on:
```
if ( a == b
     || c == d )
```

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 67fe93e37d41e250996cee62d2ae020824692a9e:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-x86-android.apk)

**Comment by suricactus** [comment]
Sorry, I am -2 on mixing the brackets and the condition on the same line, at least not in JS-like language. 

Play a bit with https://prettier.io/playground/ .

The logic is the same as arrays, hashes, code blocks.

You never write (I hope):
```
function foo(name) { const greeting = 'Hello';
  return `${greeting} ${name}`;
}
```
or
```
function foo(parameterWithLongName1,
  parameterWithLongName2,
  parameterWithLongName3,
  parameterWithLongName4
) {
  
}
```

So the rule is consistent: if you cannot fit your any kind of bracket contents on a single line, you add a new line after the opening bracket.

**Review by nirvn — APPROVED** [review]
Approving as I think we need to agree to disagree brother ;) let's discuss this internally, we'd have to reformat a bunch of code either way.

**Comment by gabgarcies** [comment]
> tada Ta-daaa, freshly created APKs are available for [67fe93e](https://github.com/opengisch/QField/commit/67fe93e37d41e250996cee62d2ae020824692a9e):
> 
> * [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-arm64-android.apk)
> 
> Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2828-356f6b368c91d07bed1f4388d38dc4eb5cfd5f2f-x86-android.apk)

Hi,

Does it mean the problem is solved with this apk version?

**Comment by suricactus** [comment]
Yes, it is most likely your problem no longer exists. Please test and share your feedback here https://github.com/opengisch/QField/issues/2829 . If you still experience problems, please put exact steps to reproduce.

**Pull request merged**
