### PR TITLE
Fix APK links on commits

### PR DESCRIPTION
**Pull request by suricactus**
fix https://github.com/opengisch/QField/issues/1454

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5ddc999dce87487b48ce550ad7957fd59900b8c8:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1455-7fbedb027907943039edfbe7c6b8c84f86e468d9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1455-7fbedb027907943039edfbe7c6b8c84f86e468d9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1455-7fbedb027907943039edfbe7c6b8c84f86e468d9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1455-7fbedb027907943039edfbe7c6b8c84f86e468d9-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 053e701f83cae62e0a42494b81e3849583f2f6b2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1-94f4a04e931728b847e380af63bcf467be62650d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1-94f4a04e931728b847e380af63bcf467be62650d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1-94f4a04e931728b847e380af63bcf467be62650d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1-94f4a04e931728b847e380af63bcf467be62650d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 78d3b548319f6c57f3afa68fb13904bfe9e37889:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1-bfabbf5123857b6df2db7754c5406e8f9cd64fa2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1-bfabbf5123857b6df2db7754c5406e8f9cd64fa2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1-bfabbf5123857b6df2db7754c5406e8f9cd64fa2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1-bfabbf5123857b6df2db7754c5406e8f9cd64fa2-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 275bf5d1db7bb83f5bc6356f4c196a5238a2f3e6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1455-87fc9af9b74219d6bdf1d3837d8b0b39e7952760-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1455-87fc9af9b74219d6bdf1d3837d8b0b39e7952760-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1455-87fc9af9b74219d6bdf1d3837d8b0b39e7952760-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1455-87fc9af9b74219d6bdf1d3837d8b0b39e7952760-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
