### PR TITLE
Prefer lowercase characters when entering username on layer login

### PR DESCRIPTION
**Pull request by suricactus**

### CODE REVIEW

**Review by signedav — APPROVED** [review]
Code looks good. Let's wait for the fairy to make a quick test on mobile

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 27fdc4b74965aa527ef3c82b13ba07b44e19644c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1609-a8dd9fce35b0e3e2ef7b47666a078876627b99ca-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1609-a8dd9fce35b0e3e2ef7b47666a078876627b99ca-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1609-a8dd9fce35b0e3e2ef7b47666a078876627b99ca-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1609-a8dd9fce35b0e3e2ef7b47666a078876627b99ca-x86.apk)

**Comment by signedav** [comment]
It seems not to make it. Still opens the keyboard with uppercase letter. But no big deal.

**Comment by suricactus** [comment]
I do confirm it does not make a diffrence on Android 10. I think we should keep it though, in case it is supported on some devices?

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Nützts nüt so schads nüt, they say

**Pull request merged**
