### PR TITLE
add cadastra font to the app + support  loading fonts in the project folder

### PR DESCRIPTION
**Pull request by 3nids**
Screenshot 2020-03-12 at 16 25 38

### CODE REVIEW

**Comment by nirvn** [comment]
Funny, I have been brainstorming about adding embedded font support to QGIS projects in QGIS core itself.

My thinking: we embed fonts as QByteArrays, safe and load to / from the project XML, and use QFontDatabase::addApplicationFontFromData( QByteArray ) to register those.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-877-11f041e622b1314e60c28fb5050c8181b1c26afe-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-877-11f041e622b1314e60c28fb5050c8181b1c26afe-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-877-11f041e622b1314e60c28fb5050c8181b1c26afe-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-877-11f041e622b1314e60c28fb5050c8181b1c26afe-x86_64.apk)

**Comment by nirvn** [comment]
Benefits: we get embedded font support to the mothership, and users use QGIS' project properties (it'd fit in nicely in the styles tab) to embed fonts.

**Comment by mbernasocchi** [comment]
> we embed fonts as QByteArrays, safe and load to / from the project XML

@nirvn fonts can some times be pretty large, wouldnt this slow down a lot the initial parsing of the project?

**Comment by nirvn** [comment]
@mbernasocchi , I don't think so no. 

The only limitation is that ATM, Qt only supports loading TTF fonts that way. Which IMHO is an acceptable bottleneck.

**Comment by 3nids** [comment]
@nirvn we were discussing it today.
The nice approach we had in mind was that the fonts would be embedded in the zip (or in `.font` folder for qgs).
In the project properties, you can add your own fonts that would be saved like this.
Having the fonts in the XML is an alternative, but the idea of having resources on the side sounds nicer to use and more flexible for other usecases than fonts.

This is a minimal version for supporting additional fonts in QField, but I'd be willing to do this in QGIS in we get funding for this.

**Comment by nirvn** [comment]
An alternative approach: we allow users to refer to font files that should be loaded alongside the project when opening it, storing paths as relative. UI/UX resides in the project properties of QGIS.

That way, we can have nice n clean folder hierarchy, share fonts across projects files from different folders, etc.

**Comment by nirvn** [comment]
@3nids , just read your reply after posting. Glad you guys are considering adding this to QGIS :+1:

**Comment by 3nids** [comment]
@nirvn btw, Qt (now?) supports both TTF and OTF: https://doc.qt.io/qt-5/qfontdatabase.html#addApplicationFont

**Comment by 3nids** [comment]
test project: [Archive.zip](https://github.com/opengisch/QField/files/4325660/Archive.zip)

**Comment by 3nids** [comment]
test project v2 [Archive.zip](https://github.com/opengisch/QField/files/4325681/Archive.zip)

**Pull request merged**
