### PR TITLE
Triplets

### PR DESCRIPTION
**Pull request by m-kuhn**
This makes builds faster by building libs only once, (not twice).
Adds stack protection for better stack traces on android.
Builds against shared c++ lib on android

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2d2ca33fc13aff209d6f5cd389d56c3c3811c3a9:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-e8a140d3fe18b79dc2161bd68c1d0192a6f1f325-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-e8a140d3fe18b79dc2161bd68c1d0192a6f1f325-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-e8a140d3fe18b79dc2161bd68c1d0192a6f1f325-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-e8a140d3fe18b79dc2161bd68c1d0192a6f1f325-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c564c664da7c3c8370ff436578f41cac7da224db:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9b6d981589cb8d9583cc8c2d5307b5c6a7c127e2-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9b6d981589cb8d9583cc8c2d5307b5c6a7c127e2-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9b6d981589cb8d9583cc8c2d5307b5c6a7c127e2-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9b6d981589cb8d9583cc8c2d5307b5c6a7c127e2-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cd47b413705d5130ab334cdcd8ba0c7366eab097:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-753813a573d9b2de688343fc078d65de9c5e5995-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-753813a573d9b2de688343fc078d65de9c5e5995-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-753813a573d9b2de688343fc078d65de9c5e5995-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-753813a573d9b2de688343fc078d65de9c5e5995-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 955fbc2d347b76d05da911a367f6154d5a4e22e3:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-53a8fa1392db5541d984569fd752e1ab50faa655-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-53a8fa1392db5541d984569fd752e1ab50faa655-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-53a8fa1392db5541d984569fd752e1ab50faa655-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-53a8fa1392db5541d984569fd752e1ab50faa655-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c4bbc723c9673bd6da8f440837826b319bd94587:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8d607485391901629a55d9d152ba73fcf867033b-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8d607485391901629a55d9d152ba73fcf867033b-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8d607485391901629a55d9d152ba73fcf867033b-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8d607485391901629a55d9d152ba73fcf867033b-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 955fbc2d347b76d05da911a367f6154d5a4e22e3:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8967a4059cddef7218bea075ccf5cc74d36a5def-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8967a4059cddef7218bea075ccf5cc74d36a5def-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8967a4059cddef7218bea075ccf5cc74d36a5def-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8967a4059cddef7218bea075ccf5cc74d36a5def-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 955fbc2d347b76d05da911a367f6154d5a4e22e3:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8967a4059cddef7218bea075ccf5cc74d36a5def-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8967a4059cddef7218bea075ccf5cc74d36a5def-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8967a4059cddef7218bea075ccf5cc74d36a5def-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-8967a4059cddef7218bea075ccf5cc74d36a5def-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b8a4c6805c09e3d8133293a932bc08e396a0b8f5:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-081dc4fba71b04650916c5bc8e1a46f8b058bd66-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-081dc4fba71b04650916c5bc8e1a46f8b058bd66-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-081dc4fba71b04650916c5bc8e1a46f8b058bd66-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-081dc4fba71b04650916c5bc8e1a46f8b058bd66-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 69bf71d035da434972464cdb2e865b4ca25b6745:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-e2784e26de4e55ad6e2aeeff96c3cc4b35b4d1e8-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-e2784e26de4e55ad6e2aeeff96c3cc4b35b4d1e8-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-e2784e26de4e55ad6e2aeeff96c3cc4b35b4d1e8-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-e2784e26de4e55ad6e2aeeff96c3cc4b35b4d1e8-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1be4f3508fbabbf38319e458e65176cfd23484b2:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9d0bb69742bf031de11ac1ab62e3cad29073fb9d-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9d0bb69742bf031de11ac1ab62e3cad29073fb9d-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9d0bb69742bf031de11ac1ab62e3cad29073fb9d-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9d0bb69742bf031de11ac1ab62e3cad29073fb9d-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 39a1753b1cc29219b4c0916ac9f5ae2134202a82:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-6681e98b5db1492f8dc7285d9c84efd55a95d72c-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-6681e98b5db1492f8dc7285d9c84efd55a95d72c-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-6681e98b5db1492f8dc7285d9c84efd55a95d72c-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-6681e98b5db1492f8dc7285d9c84efd55a95d72c-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 39ede48234d1890e40b4f4f117e0f2915c7b0b39:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-cf8fa835f4e128e15d66e29e5d12e3f4fa90b680-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-cf8fa835f4e128e15d66e29e5d12e3f4fa90b680-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-cf8fa835f4e128e15d66e29e5d12e3f4fa90b680-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-cf8fa835f4e128e15d66e29e5d12e3f4fa90b680-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 39a1753b1cc29219b4c0916ac9f5ae2134202a82:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-26d8b818ca7f338adff99fc98fa74b943ae551ea-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-26d8b818ca7f338adff99fc98fa74b943ae551ea-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-26d8b818ca7f338adff99fc98fa74b943ae551ea-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-26d8b818ca7f338adff99fc98fa74b943ae551ea-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e8223cfca450539249e44f6f71efe5c45d4b2e5e:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-71329fd28d4cc2e2f41858d4762785d453ee2045-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-71329fd28d4cc2e2f41858d4762785d453ee2045-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-71329fd28d4cc2e2f41858d4762785d453ee2045-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-71329fd28d4cc2e2f41858d4762785d453ee2045-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7f877768adf6e7bc21c9b01551ed05ef8006ad14:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-2a96b0e4ed6b0fe929568595589e5d2e8583fcc8-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-2a96b0e4ed6b0fe929568595589e5d2e8583fcc8-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-2a96b0e4ed6b0fe929568595589e5d2e8583fcc8-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-2a96b0e4ed6b0fe929568595589e5d2e8583fcc8-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7f877768adf6e7bc21c9b01551ed05ef8006ad14:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9cbaa274f390b6850faf4524abd52bbf34b062b4-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9cbaa274f390b6850faf4524abd52bbf34b062b4-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9cbaa274f390b6850faf4524abd52bbf34b062b4-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-9cbaa274f390b6850faf4524abd52bbf34b062b4-x86-android.apk)

**Comment by m-kuhn** [comment]
This is almost ready. Missing bit is harmonizing all android triplets with the arm one.
Could someone with a keyboard ⌨️ take care?

@nirvn @suricactus

**Comment by nirvn** [comment]
Can do

**Comment by nirvn** [comment]
@m-kuhn , done.

**Comment by m-kuhn** [comment]
So much karma and zen in these triplets now. 🙏

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 942e0341ed5c6c71f060c44e4964b0b2ff8afd99:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-34536fc9afd7f3e17bc892f635f4caa78645c206-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-34536fc9afd7f3e17bc892f635f4caa78645c206-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-34536fc9afd7f3e17bc892f635f4caa78645c206-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2667-34536fc9afd7f3e17bc892f635f4caa78645c206-x86-android.apk)

**Comment by m-kuhn** [comment]
Working fine on arm64.
Squashandmerge?

**Review by nirvn — APPROVED** [review]
Also tested on my armv8 device, no crash.

**Comment by nirvn** [comment]
Go ahead, merge at will :)

**Pull request merged**
