### PR TITLE
Allow hiding legend nodes

### PR DESCRIPTION
**Pull request by m-kuhn**
configuration is to be done InvisibleLayersAndGroups Qgis Plug-in

Supersedes #578

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-725-6ebbe91397d3b0c074853cb20d37aa9b881b95cb-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-725-6ebbe91397d3b0c074853cb20d37aa9b881b95cb-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-725-6ebbe91397d3b0c074853cb20d37aa9b881b95cb-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-725-6ebbe91397d3b0c074853cb20d37aa9b881b95cb-x86_64.apk)

**Comment by m-kuhn** [comment]
@gacarrillor / @jhonalex06 can you verify if this works as expected?

**Comment by jhonalex06** [comment]
Hi @m-kuhn 

@gacarrillor and I verified the branch and this worked perfectly.

Thanks.

**Comment by m-kuhn** [comment]
@jhonalex06 thanks for testing. Is it possible for you to add documentation for the configuration to the qfield docs? A minimal example with a link to the plugin should be sufficient.
Or should we do it?

@signedav can I get your approval on this PR?

**Comment by jhonalex06** [comment]
Yes, @m-kuhn this week I will add documentation for the configuration of hiding legend nodes.

Regards.

**Comment by m-kuhn** [comment]
@jhonalex06 what is the status on your end? 1.3.2 is planned for next week and the question is to ship this functionality with 1.3.2 or wait for 1.4.0 (Jan 2020)

**Comment by jhonalex06** [comment]
> @jhonalex06 what is the status on your end? 1.3.2 is planned for next week and the question is to ship this functionality with 1.3.2 or wait for 1.4.0 (Jan 2020)

We create a pull request for the documentation, https://github.com/opengisch/QField-docs/pull/41

I think is possible to add the functionality for next week in version 1.3.2.

Thanks

**Pull request merged**
