### PR TITLE
Bump SDK to 20190505

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-573-eef1595f504a82ca9a580fa620f0dcd7d1b6c30c-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-573-eef1595f504a82ca9a580fa620f0dcd7d1b6c30c-x86.apk)

**Comment by soester** [comment]
Hi @m-kuhn 

thanks for providing the test apk!

@snapping_results as default value doesn't work so far.
tested on my sample project 
[sample_project.zip](https://github.com/opengisch/QField/files/3152894/sample_project.zip)

It doesn't work for lines and points!
Actually i did never test it on pevious qfield versions ->> will do that

btw: couldnt install the test apk on samsung galaxy tab active wifi running Android 5.1.1 (Parsing-Fehler), but worked on Android 8.1.0

**Comment by m-kuhn** [comment]
Thanks for the feedback @soester 
It is well possible that this part of the snapping was desktop specific and it needs to be implemented again for QField. We will have a look (https://github.com/opengisch/QField/issues/575).

Apart from the snapping, is this package working fine?

**Comment by soester** [comment]
@m-kuhn 
> Apart from the snapping, is this package working fine?
i just tested the @snapping_results feature, can't tell about stability or such things. sorry.

tested @snapping_results also on 1.0.3: there is also no result... so #575 is probably necessary

**Comment by m-kuhn** [comment]
Obsolete (newer SDK integrated already)

**Pull request closed without merging**
