### PR TITLE
feat: update softwareVersion v2.0.0 in publiccode.yml

### PR DESCRIPTION
**Pull request by qfield-fairy**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ff85706cd8fb83441c3dda016fe02f1bb4ffc9f9:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-13eb4b41f62990860e78f53081fae82501a80196-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-13eb4b41f62990860e78f53081fae82501a80196-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-13eb4b41f62990860e78f53081fae82501a80196-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-13eb4b41f62990860e78f53081fae82501a80196-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 472d8ab4d3394ae1b1fa8b4bd65f82a2b39f0e30:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-6ebb37d8a8a1caf7959378dddfa281767fa2aa01-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-6ebb37d8a8a1caf7959378dddfa281767fa2aa01-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-6ebb37d8a8a1caf7959378dddfa281767fa2aa01-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-6ebb37d8a8a1caf7959378dddfa281767fa2aa01-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6bb2a72eeed590c7abc31865e6c24d8e6a31c507:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-7fc00d2e45063fd687743323499d065eff76118e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-7fc00d2e45063fd687743323499d065eff76118e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-7fc00d2e45063fd687743323499d065eff76118e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-7fc00d2e45063fd687743323499d065eff76118e-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 76c45b788f586bf6cb51d3b903b0aabfc4cac486:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-fae966252c502f0eb2f31ee31a4d6348b9b59d25-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-fae966252c502f0eb2f31ee31a4d6348b9b59d25-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-fae966252c502f0eb2f31ee31a4d6348b9b59d25-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1975-fae966252c502f0eb2f31ee31a4d6348b9b59d25-x86.apk)

**Comment by m-kuhn** [comment]
@astagi I think something went wrong here, the action opened a pull request from a different branch with plenty of changes against master.
Probably either the workflow must only ever be run against master or in the checkout command master as branch explicitly specified.
Or we might just drop the latest version from it and hope for the crawler to look at the releases itself ;-)

**Pull request closed without merging**
