### PR TITLE
Astyle check

### PR DESCRIPTION
**Pull request by m-kuhn**
`clang-format-13` was also run once with `IndentAccessModifiers` before `astyle` was ran again and is now enforced.
clang-format helped to bring the current codebase into a more consistent shape but it's not yet widely available so we can't enforce it for now.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 775dbd1fc266950cd1b2f27701d04a9af12666fb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-c6cff20637e15ebf959ef110af24838bb696db54-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-c6cff20637e15ebf959ef110af24838bb696db54-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-c6cff20637e15ebf959ef110af24838bb696db54-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-c6cff20637e15ebf959ef110af24838bb696db54-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4341cb98d43655180f7e66dc896bf19de4135e14:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-4cb7c6b082a23dd528167232a50aa65401cb1603-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-4cb7c6b082a23dd528167232a50aa65401cb1603-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-4cb7c6b082a23dd528167232a50aa65401cb1603-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-4cb7c6b082a23dd528167232a50aa65401cb1603-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b6700714bb460fe9d3fcce3cd0d9de0a4453267f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-1308db4ef356c56b992e8fad7910dd79f51daeb5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-1308db4ef356c56b992e8fad7910dd79f51daeb5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-1308db4ef356c56b992e8fad7910dd79f51daeb5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-1308db4ef356c56b992e8fad7910dd79f51daeb5-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d473ca3d4efdf142d851da27c0df7da4ad6dcfb4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-31f9741d83ae370b7c32ad837a6ba613a41e0c05-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-31f9741d83ae370b7c32ad837a6ba613a41e0c05-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-31f9741d83ae370b7c32ad837a6ba613a41e0c05-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-31f9741d83ae370b7c32ad837a6ba613a41e0c05-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c151741a85d751ca660f79a5feee20cbec6b4fdf:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-78f3d70be7955358e00affb801d3f57c8ee9c5c1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-78f3d70be7955358e00affb801d3f57c8ee9c5c1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-78f3d70be7955358e00affb801d3f57c8ee9c5c1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-78f3d70be7955358e00affb801d3f57c8ee9c5c1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1eb1db7262275c9dce5025aa32d417f9ea8ddaba:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-581d73172257c60256a780b18c99fe40d07600bf-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-581d73172257c60256a780b18c99fe40d07600bf-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-581d73172257c60256a780b18c99fe40d07600bf-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-581d73172257c60256a780b18c99fe40d07600bf-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 48143bfb9c023850dc56e15043d898a3a4c2c0bb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-979f6bc2019e9d9e66ae209379a9fca03d395b9d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-979f6bc2019e9d9e66ae209379a9fca03d395b9d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-979f6bc2019e9d9e66ae209379a9fca03d395b9d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-979f6bc2019e9d9e66ae209379a9fca03d395b9d-x86.apk)

**Comment by m-kuhn** [comment]
style police please

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d929ad1c4893ebe35eced5277b6321b6451f2cb2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-491e4a2829fcdf2f3b352ce51b58546c8ddf63da-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-491e4a2829fcdf2f3b352ce51b58546c8ddf63da-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-491e4a2829fcdf2f3b352ce51b58546c8ddf63da-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-491e4a2829fcdf2f3b352ce51b58546c8ddf63da-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d6367a7b6bd0c3ae476eeaa73c64a51ecb381645:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8691e31f941934c136f17bf3276af6eb8dfee6fa-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8691e31f941934c136f17bf3276af6eb8dfee6fa-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8691e31f941934c136f17bf3276af6eb8dfee6fa-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8691e31f941934c136f17bf3276af6eb8dfee6fa-x86.apk)

**Comment by m-kuhn** [comment]
style police please

**Comment by m-kuhn** [comment]
style police please

**Comment by m-kuhn** [comment]
style police please

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 73c9ca25a6dc6bdd63ecea68f8470eaa8dde6267:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8449155856af5a71f043d1087312c42eac761830-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8449155856af5a71f043d1087312c42eac761830-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8449155856af5a71f043d1087312c42eac761830-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8449155856af5a71f043d1087312c42eac761830-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 421be52f6bb3f999239fac9f3f84c023746fb18c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-669a7a4db8f90c0cbb1790e22f3c37bbb3d3550c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-669a7a4db8f90c0cbb1790e22f3c37bbb3d3550c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-669a7a4db8f90c0cbb1790e22f3c37bbb3d3550c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-669a7a4db8f90c0cbb1790e22f3c37bbb3d3550c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 13322cf75a4e7189d5ebe403cbab82dfa27b8edf:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-cc01b09a352db3b3fef51251cdef00ecbe86ed3c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-cc01b09a352db3b3fef51251cdef00ecbe86ed3c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-cc01b09a352db3b3fef51251cdef00ecbe86ed3c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-cc01b09a352db3b3fef51251cdef00ecbe86ed3c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 75c6e34357fe80e196b97c4e40d6c3a92d3a4a19:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8426707f7968fd5d608e6d251008ea73d401aff2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8426707f7968fd5d608e6d251008ea73d401aff2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8426707f7968fd5d608e6d251008ea73d401aff2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-8426707f7968fd5d608e6d251008ea73d401aff2-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 507865438504118e0559c3e123b8f61576a41a20:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-ced086b6950a4329d58a562b6c0d4f52735611cc-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-ced086b6950a4329d58a562b6c0d4f52735611cc-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-ced086b6950a4329d58a562b6c0d4f52735611cc-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-ced086b6950a4329d58a562b6c0d4f52735611cc-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2e30ca6018b5dbd66c1e06cfab441fe935fb7470:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-0e5b20977ad7dd249bdbb2e9e39d53b787695117-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-0e5b20977ad7dd249bdbb2e9e39d53b787695117-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-0e5b20977ad7dd249bdbb2e9e39d53b787695117-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-0e5b20977ad7dd249bdbb2e9e39d53b787695117-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 37dc06756840bc77f5538fa3dc5c94b432668549:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-7df0e703706db40959c50852ec644bd95192bf69-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-7df0e703706db40959c50852ec644bd95192bf69-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-7df0e703706db40959c50852ec644bd95192bf69-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1878-7df0e703706db40959c50852ec644bd95192bf69-x86.apk)

**Pull request merged**
