### PR TITLE
DateTime widget's today button plus calendar visual improvements

### PR DESCRIPTION
**Pull request by nirvn**
This PR supersedes #532 and adds a "today" button into the main DateTime widget:
Screenshot from 2019-12-30 12-09-56

The button is always visible, as my testing showed it was the best UX approach. To make sure people aren't confused by clicking on it when the date is already set to today, there's a toaster message popping up.

The PR also tries to "de-uglify" the widget on Android by adding a basic custom style.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-813d8721b4def4233a70fa9a5206793ded731680-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-813d8721b4def4233a70fa9a5206793ded731680-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-813d8721b4def4233a70fa9a5206793ded731680-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-813d8721b4def4233a70fa9a5206793ded731680-x86_64.apk)

**Comment by 3nids** [comment]
Nice addition!
I am not a huge fan of the icon as I find it a bit misleading but I have no great proposition.
Maybe: 
image ?

Also, the text would need some padding with its box, but not sure if you can keep alignment with other texts.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-185c068ad787cc15417bd248875147736c827b7f-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-185c068ad787cc15417bd248875147736c827b7f-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-185c068ad787cc15417bd248875147736c827b7f-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-185c068ad787cc15417bd248875147736c827b7f-x86_64.apk)

**Comment by nirvn** [comment]
@3nids , I'm not in love with the picture either, but my two attempts at coming up with something better failed. The proposed alternative looks too much of a "valid" state. IMHO, while not ideal, I think the toaster message helps clarify any confusion.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-f1ca0f8e9fab6482e8c7cdc7ca7f4a13a43a7b9e-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-f1ca0f8e9fab6482e8c7cdc7ca7f4a13a43a7b9e-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-f1ca0f8e9fab6482e8c7cdc7ca7f4a13a43a7b9e-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-f1ca0f8e9fab6482e8c7cdc7ca7f4a13a43a7b9e-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-1d182ed8b8a6fa68188775057b332bce7eb5b80d-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-1d182ed8b8a6fa68188775057b332bce7eb5b80d-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-1d182ed8b8a6fa68188775057b332bce7eb5b80d-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-1d182ed8b8a6fa68188775057b332bce7eb5b80d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-2a7f8cc20e8d84e81ec5ab84cd46cc220303fdfd-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-2a7f8cc20e8d84e81ec5ab84cd46cc220303fdfd-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-2a7f8cc20e8d84e81ec5ab84cd46cc220303fdfd-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-764-2a7f8cc20e8d84e81ec5ab84cd46cc220303fdfd-x86_64.apk)

**Comment by nirvn** [comment]
Finally:
image

Clear button vertically aligns properly, so does text. Ouf, QML, you're as beautiful as you're ugly :wink:

**Pull request merged**
