### PR TITLE
2.0 beta 13 branch

### PR DESCRIPTION
**Pull request by nirvn**
This is a test PR to get APKs for what will become beta 13 (as discussed, includes changes applied post beta 12 minus temporal, navigation, and compass stuff)

@mbernasocchi , I would like to force push this onto release-2_0 but the branch is protected ATM and I can't turn that off with my current repository access rights. Could you do so?

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for adcbb3f23bf644e7d1441dda1739150d4b8e3d39:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-37b8105509fefe6fee492b9c2dc2d91045fe4d41-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-37b8105509fefe6fee492b9c2dc2d91045fe4d41-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-37b8105509fefe6fee492b9c2dc2d91045fe4d41-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-37b8105509fefe6fee492b9c2dc2d91045fe4d41-x86-android.apk)

**Comment by nirvn** [comment]
A new hyperlink for users to directly go to the account registration page has been added to the QFieldCloud login panel:
image

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 132b2343c6ba7199a2ca6a568de4420048fc6a45:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-ce477ae296737823e5f1ec81560fd3860c4cd819-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-ce477ae296737823e5f1ec81560fd3860c4cd819-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-ce477ae296737823e5f1ec81560fd3860c4cd819-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-ce477ae296737823e5f1ec81560fd3860c4cd819-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 132b2343c6ba7199a2ca6a568de4420048fc6a45:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-84570562d61a47148aa6ccabaf88e09d24e430bf-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-84570562d61a47148aa6ccabaf88e09d24e430bf-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-84570562d61a47148aa6ccabaf88e09d24e430bf-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2559-84570562d61a47148aa6ccabaf88e09d24e430bf-x86-android.apk)

**Pull request closed without merging**
