### PR TITLE
Add stack protector strong

### PR DESCRIPTION
**Pull request by nirvn**
Extracting lessons learned from the ongoing asan adventure.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7ac1713927da883ca2e4463d3782cce79d338616:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2725-09e72ed5f0fea461ae57981c5455a33001e3444e-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2725-09e72ed5f0fea461ae57981c5455a33001e3444e-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2725-09e72ed5f0fea461ae57981c5455a33001e3444e-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2725-09e72ed5f0fea461ae57981c5455a33001e3444e-x86-android.apk)

**Comment by nirvn** [comment]
@m-kuhn , tested the arm64 APK, all good.

**Comment by marioba** [comment]
@m-kuhn, tested the arm APK, not good.

**Comment by m-kuhn** [comment]
https://lwn.net/Articles/584225/

**Comment by m-kuhn** [comment]
I think we should kill the env var, it's superseded by the new var

**Comment by nirvn** [comment]
@m-kuhn , in the asan PR, removing the env variable (with asan) led to build failure, which makes me feel the old env variable are somehow still needed/useful. Thoughts?

**Comment by m-kuhn** [comment]
That would hint to ports not respecting these variables. And would rather be something to fix in these ports instead.

**Comment by nirvn** [comment]
In the asan PR, QField's linking was failing with a bunch of missing function references. But again that might just be asan specific & need us to fix that somewhere else. I can remove the env tomorrow morning.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ab83014c635405ca8445750d9da09f5913f64e2b:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2725-9c8e50f43fe79310d73eae7cc9ac9457e23071d8-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2725-9c8e50f43fe79310d73eae7cc9ac9457e23071d8-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2725-9c8e50f43fe79310d73eae7cc9ac9457e23071d8-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2725-9c8e50f43fe79310d73eae7cc9ac9457e23071d8-x86-android.apk)

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
