### PR TITLE
Merry holiday and happy rippling

### PR DESCRIPTION
**Pull request by nirvn**
Peek 2020-12-25 15-22

### CODE REVIEW

**Review by m-kuhn — COMMENTED** [review]
:christmas_tree: merry christmas

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 57a3f22d838c35eb104a634fcee043d82e35ef86:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1526-9b60a6ca0083f2a079abcbaccadecf367647782b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1526-9b60a6ca0083f2a079abcbaccadecf367647782b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1526-9b60a6ca0083f2a079abcbaccadecf367647782b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1526-9b60a6ca0083f2a079abcbaccadecf367647782b-x86.apk)

**Comment by xBcai** [comment]
Happy holidays, wish QField better and better! ! !

**Comment by nirvn** [comment]
@m-kuhn , can you approve this one?

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
