### PR TITLE
bump ios sdk

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 14ed820a6e2074c8172b8bf3bd4020ca804abd1b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-a739a76c4ea54813796c9643e8c81d2f2b4291f6-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-a739a76c4ea54813796c9643e8c81d2f2b4291f6-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-a739a76c4ea54813796c9643e8c81d2f2b4291f6-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-a739a76c4ea54813796c9643e8c81d2f2b4291f6-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 314208c9c64a16ef7923bf20c28a1a4bc3575d6d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-d10bcf0701f4914a6a487e7d0e5a7689b0abda6e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-d10bcf0701f4914a6a487e7d0e5a7689b0abda6e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-d10bcf0701f4914a6a487e7d0e5a7689b0abda6e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-d10bcf0701f4914a6a487e7d0e5a7689b0abda6e-x86.apk)

**Comment by m-kuhn** [comment]
https://github.com/opengisch/QField/runs/2720605557?check_suite_focus=true#step:10:208

```
/Users/runner/work/QField/QField/OSGeo4I/arm64/QGIS.app/Contents/Frameworks/qgis_core.framework/Headers/qgsauthmanager.h:38:10: fatal error: 'QtCrypto' file not found
#include <QtCrypto>
         ^~~~~~~~~~
** BUILD FAILED **
1 error generated.
```

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0b10f85e42bbd332c5fb221a477333b3ba6ee772:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-0ea2179bfd81a7d0db8364097e27dfc60ca73b17-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-0ea2179bfd81a7d0db8364097e27dfc60ca73b17-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-0ea2179bfd81a7d0db8364097e27dfc60ca73b17-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-0ea2179bfd81a7d0db8364097e27dfc60ca73b17-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 310da005fb48f0dd160c8ff0ee58d493d306d852:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-0097cc0a07d1ccd4c4c5e279c834ef908aee54bb-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-0097cc0a07d1ccd4c4c5e279c834ef908aee54bb-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-0097cc0a07d1ccd4c4c5e279c834ef908aee54bb-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1952-0097cc0a07d1ccd4c4c5e279c834ef908aee54bb-x86.apk)

**Pull request merged**
