### PR TITLE
Add logging facility

### PR DESCRIPTION
**Pull request by m-kuhn**
This needs a proper gui option (or as a short term measure to be disabled on release)

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d6a1d4507b10ca42f380dc7e3e152138d85e78da:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-50962e3e5e29943070efc7962698cf71b647d62c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-50962e3e5e29943070efc7962698cf71b647d62c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-50962e3e5e29943070efc7962698cf71b647d62c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-50962e3e5e29943070efc7962698cf71b647d62c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1964467ec427f5aebaf23bdf3b2f561a839235fc:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-5d906531eaf64bb090a958d1f18bf5a9f79fc07e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-5d906531eaf64bb090a958d1f18bf5a9f79fc07e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-5d906531eaf64bb090a958d1f18bf5a9f79fc07e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-5d906531eaf64bb090a958d1f18bf5a9f79fc07e-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 281790601d2f9e2ababb7bd403e7fa6688bbc366:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-85cec9108e4478d24a80b60add57412f86d0f59c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-85cec9108e4478d24a80b60add57412f86d0f59c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-85cec9108e4478d24a80b60add57412f86d0f59c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-85cec9108e4478d24a80b60add57412f86d0f59c-x86.apk)

**Review by nirvn — APPROVED** [review]
The latest APKs working fine here. Approving on that basis.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f140cae77a0e370ad47e7053f8d0f50ff17a6270:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-526b6972377b6207365949d2643ff78b74d9970c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-526b6972377b6207365949d2643ff78b74d9970c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-526b6972377b6207365949d2643ff78b74d9970c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-526b6972377b6207365949d2643ff78b74d9970c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0a92ffb5a9efc7b94d04cdc85b99f3ddfa752072:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-f2116da6a8237dbeb43b4dd2ffc425ccb5533ee6-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-f2116da6a8237dbeb43b4dd2ffc425ccb5533ee6-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-f2116da6a8237dbeb43b4dd2ffc425ccb5533ee6-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-f2116da6a8237dbeb43b4dd2ffc425ccb5533ee6-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a56834ec5304cbf902c030f7a9dbdf4511f2d074:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-3b27720470d9b4aedcc2f352c773edbcc539368c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-3b27720470d9b4aedcc2f352c773edbcc539368c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-3b27720470d9b4aedcc2f352c773edbcc539368c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-3b27720470d9b4aedcc2f352c773edbcc539368c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e845f68f0a5ebfe71215ed06c3774ee53b2a6fe1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-47abf4e2629a59aba550605a2939c911168cd88b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-47abf4e2629a59aba550605a2939c911168cd88b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-47abf4e2629a59aba550605a2939c911168cd88b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-47abf4e2629a59aba550605a2939c911168cd88b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 03d55e02c304fb43ed32ccd074a4a30e3ace677c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-af4f9b18e77d664cf6fefb7294c663c557126921-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-af4f9b18e77d664cf6fefb7294c663c557126921-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-af4f9b18e77d664cf6fefb7294c663c557126921-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-af4f9b18e77d664cf6fefb7294c663c557126921-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 68c0cec07caaf59ef6820e7d5671101d20977288:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-a809c7838e3b6f6d0cc00dfb496b632917363894-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-a809c7838e3b6f6d0cc00dfb496b632917363894-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-a809c7838e3b6f6d0cc00dfb496b632917363894-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-a809c7838e3b6f6d0cc00dfb496b632917363894-x86.apk)

**Comment by m-kuhn** [comment]
Yes we want (a better location for) this button.

image

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a723267cc96354867e032b8d58c398db133fc7a4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-a5a79d5afd739739980bd3f6b51b1e657b1a6a22-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-a5a79d5afd739739980bd3f6b51b1e657b1a6a22-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-a5a79d5afd739739980bd3f6b51b1e657b1a6a22-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-a5a79d5afd739739980bd3f6b51b1e657b1a6a22-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6f48abf0f9898bcac32da100bce4891036b54c71:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-4809506596022d979ba8d7d45665d2947a0e48cd-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-4809506596022d979ba8d7d45665d2947a0e48cd-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-4809506596022d979ba8d7d45665d2947a0e48cd-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-4809506596022d979ba8d7d45665d2947a0e48cd-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 158b5369fc51bb5349aa1d14654e62e180270ee1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-2e0a3ead6a61b9cf5c6adc01ff3bfaf58c142dcc-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-2e0a3ead6a61b9cf5c6adc01ff3bfaf58c142dcc-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-2e0a3ead6a61b9cf5c6adc01ff3bfaf58c142dcc-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-2e0a3ead6a61b9cf5c6adc01ff3bfaf58c142dcc-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 91238d26a7b907c26cc42ea2ad4dbf82a3903ed4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-473219585e349db23235b55e6de3d16fcf384555-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-473219585e349db23235b55e6de3d16fcf384555-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-473219585e349db23235b55e6de3d16fcf384555-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-473219585e349db23235b55e6de3d16fcf384555-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f81a360cc2a2d67bd5fd0b38fdf574a4920ada7e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-e8a60db78c063957264804f5eecf6e15b6533586-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-e8a60db78c063957264804f5eecf6e15b6533586-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-e8a60db78c063957264804f5eecf6e15b6533586-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-e8a60db78c063957264804f5eecf6e15b6533586-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d9a749906fe28e1fd4b611bc1191d6efaf5a404b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-2968e79bc5b30515610d0285f2b7cc97cb5801d0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-2968e79bc5b30515610d0285f2b7cc97cb5801d0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-2968e79bc5b30515610d0285f2b7cc97cb5801d0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-2968e79bc5b30515610d0285f2b7cc97cb5801d0-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2df7bcf758abaaad75186a55320732df3a444c3d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-b700a86556decd065d3a1c5c83679f84513851c7-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-b700a86556decd065d3a1c5c83679f84513851c7-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-b700a86556decd065d3a1c5c83679f84513851c7-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-b700a86556decd065d3a1c5c83679f84513851c7-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d0485ae8143cbdfbdf130d51b8d2f67fde6c3514:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-48ad2490d18a5c015fbd3ac937dc68776dd76ed3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-48ad2490d18a5c015fbd3ac937dc68776dd76ed3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-48ad2490d18a5c015fbd3ac937dc68776dd76ed3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-48ad2490d18a5c015fbd3ac937dc68776dd76ed3-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5ee7308c9a28dde2471607f52718565f2c0b2561:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-bd373353258825308b1ae5c841f6bebcf077eee5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-bd373353258825308b1ae5c841f6bebcf077eee5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-bd373353258825308b1ae5c841f6bebcf077eee5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2366-bd373353258825308b1ae5c841f6bebcf077eee5-x86.apk)

**Pull request merged**
