### PR TITLE
Implement handling of soft vs. hard constraints

### PR DESCRIPTION
**Pull request by nirvn**
This PR implements a refined handling of constraints by acknowledging soft vs hard expression constraints. 

Hard constrains are dealt as constrains were in QField until now (i.e., a feature can't be added/edited if hard constrains aren't met). The UI has been slightly updated here, with labels (and the header bar background color) colored using Theme.errorColor:
Screenshot from 2020-02-09 11-55-04

Unmet soft constrains will result in a warning label shown (in orange), however won't block features from being added/edited:
Screenshot from 2020-02-09 11-56-05

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-c79704ab3eccd3eb8b6b99caa32279ba8ebf6d03-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-c79704ab3eccd3eb8b6b99caa32279ba8ebf6d03-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-c79704ab3eccd3eb8b6b99caa32279ba8ebf6d03-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-c79704ab3eccd3eb8b6b99caa32279ba8ebf6d03-x86_64.apk)

**Comment by m-kuhn** [comment]
Lovely.

- I'd suggest to also highlight failing soft constraints in the header.
- It would be really cool to indicate the tab on which the checks failed as well, but I think that's a bit more complicated.

**Comment by nirvn** [comment]
@m-kuhn , I thought about changing the header color for unmet soft constraints, but I settled on not doing it, because I think we should avoid doing so generally speaking (do you remember the days the header was served in blue, orange, green, etc.? :wink: ), and only do it for a very narrow set of scenarios.

That decision can be overwritten by a democratic majority :smile:

**Comment by m-kuhn** [comment]
> I'd suggest to also highlight failing soft constraints in the header.

> [...] but I settled on not doing it [...]
> That decision can be overwritten by a democratic majority smile

Call for vote @opengisch/devs

**Comment by m-kuhn** [comment]
For what it's worth @nirvn I think it's even more important for failing soft constraints to communicate them. The missing possibility to accept a form with failing hard constraints is a very prominent indicator that something is wrong whereas soft constraints have to be discovered by scrolling through the form.

**Comment by nirvn** [comment]
I don't think we have to call for a vote, I think you're vote weights two units, mine one, I'm overruled :wink: 

More seriously, I hadn't thought about the point you've just made. I'll do it then. So orange header?

**Comment by nirvn** [comment]
There:
Screenshot from 2020-02-09 15-43-27

**Comment by nirvn** [comment]
@m-kuhn , BTW, to the point you were raising above on importance of highlighting soft constraints since those aren't blocking feature saving, a soft constraints unmet will show the constrains description in the feature form in or out of edit mode, so viewers can be aware of unmet constraints.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-6e4d402882d41fbc1e2043746d8fb7c8d0101f62-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-6e4d402882d41fbc1e2043746d8fb7c8d0101f62-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-6e4d402882d41fbc1e2043746d8fb7c8d0101f62-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-6e4d402882d41fbc1e2043746d8fb7c8d0101f62-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-d464603464bea9ae8a0cf8fc1807aad03439d9fe-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-d464603464bea9ae8a0cf8fc1807aad03439d9fe-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-d464603464bea9ae8a0cf8fc1807aad03439d9fe-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-d464603464bea9ae8a0cf8fc1807aad03439d9fe-x86_64.apk)

**Comment by 3nids** [comment]
I'm not 100% convinced by the tri-state header color.
The difference between the 3 is not very obvious to me (although I am colorblind).
What about adding a icon, similarly to success/warning/critical we have in the message bar in QGIS?

**Comment by nirvn** [comment]
@3nids , what about removing the [ ✓ ] button from the nav bar for unmet hard constraints? We'd then have the following states:
- unmet hard constraints: no apply button, red bg
- unmet soft constraints: apply button present, orange bg
- all contraints met: green bg

Also, we could prepend a qsTr( "Error" ) and qsTr( "Warning" ) string when printing the constraints description below the field title.

**Comment by nirvn** [comment]
Alright, on the basis of the feedback @3nids provided, I've made some tweaks to try and increase effectiveness of our visual queues with regards to unmet hard and/or soft constrains.

When a hard constraint isn't met, in addition to changing the navigation bar color to red, QField now fades away the save/apply button to further hint at the impossibility of doing so. In addition, we now prepend 'Error' to the unmet constraint description:
Screenshot from 2020-02-12 13-15-25

For soft constraints, the save/apply button remains fully opaque, and a 'Warning' string precedes the constraint description:
Screenshot from 2020-02-12 13-15-15

@3nids , I'm hoping this satisfies you. Introducing icons in the navigation bar would be a bit cumbersome (in terms of alignment) and IMHO I'd rather keep the navigation bar clean and lean.

**Comment by signedav** [comment]
I like this behavior. 
I don't like the "reded" out checkmark. I understand that you didn't wanted to remove it at all, to show the user that it could be possible... 
Is a grey out possible with this? The checkmark grey instead of white, or is it not clear enough then?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-4feead9c7fa79e243be0b0ac844c5f82fd871722-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-4feead9c7fa79e243be0b0ac844c5f82fd871722-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-4feead9c7fa79e243be0b0ac844c5f82fd871722-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-4feead9c7fa79e243be0b0ac844c5f82fd871722-x86_64.apk)

**Comment by nirvn** [comment]
@signedav , I'm merely reducing the opacity of the dark gray button (with its white check) to 0.33, hence the sense of it being "reded" out. 

We could add a black variant of the check image (used here), and use that when the button is disabled due to hard constraints. But I'm not sure it's worth adding that black variant x 5 PNGs for that.

**Comment by 3nids** [comment]
thanks!

sorry to insist, but what about adding icons?
Or instead of changing the header line color, adding another panel under it which would be only shown when constraints are unmet (red/orange with proper icon and saying constraints unmet)?

If that's not considerer, I'm with Dave here to remove the reded look by adding a grey version of the icon.

**Comment by nirvn** [comment]
OK, could we settle for this look:
image

?

**Comment by signedav** [comment]
I like the updated look :+1:

**Comment by nirvn** [comment]
:tada:

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-4915f74cadc8ac388c64615710956f70ff21cd7c-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-4915f74cadc8ac388c64615710956f70ff21cd7c-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-4915f74cadc8ac388c64615710956f70ff21cd7c-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-810-4915f74cadc8ac388c64615710956f70ff21cd7c-x86_64.apk)

**Pull request merged**
