### PR TITLE
[backport release 1.7] Fix topological editing

### PR DESCRIPTION
**Pull request by suricactus**
Broken since the new legend

### CODE REVIEW

**Comment by nirvn** [comment]
Not linked to legend, linked to isValid morphed from a function to a property :)

**Comment by suricactus** [comment]
Which happened arround that time, sorry for the fake news :)

**Review by m-kuhn — APPROVED** [review]

**Comment by nirvn** [comment]
It was an entirely reasonable assumption 😄

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1333-4279aa27436f8af3fb84e23134157604a4b714c9-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1333-4279aa27436f8af3fb84e23134157604a4b714c9-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1333-4279aa27436f8af3fb84e23134157604a4b714c9-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1333-4279aa27436f8af3fb84e23134157604a4b714c9-x86_64.apk)

**Pull request merged**
