### PR TITLE
Fix for double validators

### PR DESCRIPTION
**Pull request by signedav**
Apparently on the swiss-french locale configured, still the dot is displayed to enter as separator. But the `DoubleValidator` does not accept it. I had no success in setting the `DoubleValidator`s `locale: Qt.locale("C")` to set the validators locale setting to the C locale.

Additionally I tried to set this in main.cpp, but it has no influence. The `decimalPoint` is still a comma after:
```
setlocale(LC_NUMERIC, "C");
QLocale::setDefault( QLocale::system() );
```

Fixes https://github.com/opengisch/qfieldsync/issues/153

I'm mainly not happy with this workaround because it does not validate anymore minimum and maximum value in the range widget. That's why it's still WIP. Maybe anyone has an idea.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-4bfbca4308b759f82bb969892b33c9d2ace6e23d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-4bfbca4308b759f82bb969892b33c9d2ace6e23d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-4bfbca4308b759f82bb969892b33c9d2ace6e23d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-4bfbca4308b759f82bb969892b33c9d2ace6e23d-x86_64.apk)

**Comment by m-kuhn** [comment]
@signedav did something change with respect to the new Qt version?
If not, I'd like to give a look to this.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-99075556eff2c4ce87178fd9cde2410dfe97bc62-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-99075556eff2c4ce87178fd9cde2410dfe97bc62-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-99075556eff2c4ce87178fd9cde2410dfe97bc62-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-99075556eff2c4ce87178fd9cde2410dfe97bc62-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-ffbf26fb0707982e36034d16b573125ba949f368-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-ffbf26fb0707982e36034d16b573125ba949f368-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-ffbf26fb0707982e36034d16b573125ba949f368-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-ffbf26fb0707982e36034d16b573125ba949f368-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-db6542f0bfb07bfba2958fc689e13d16727f1ec4-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-db6542f0bfb07bfba2958fc689e13d16727f1ec4-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-db6542f0bfb07bfba2958fc689e13d16727f1ec4-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-db6542f0bfb07bfba2958fc689e13d16727f1ec4-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-d01c537117c85bfdf1022bec026089ac5e892d5a-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-d01c537117c85bfdf1022bec026089ac5e892d5a-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-d01c537117c85bfdf1022bec026089ac5e892d5a-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-d01c537117c85bfdf1022bec026089ac5e892d5a-x86_64.apk)

**Comment by signedav** [comment]
Good idea @m-kuhn Apparently it works with `locale: 'C'` on QtQuick 2.14

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-b800c221baac3f23dfe3729013211b2d3b701fd4-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-b800c221baac3f23dfe3729013211b2d3b701fd4-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-b800c221baac3f23dfe3729013211b2d3b701fd4-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1047-b800c221baac3f23dfe3729013211b2d3b701fd4-x86_64.apk)

**Pull request merged**
