### PR TITLE
Add today button

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-532-4748be3b4d9595b8eb4c375099d0a7f14e3ba1b1-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-532-4748be3b4d9595b8eb4c375099d0a7f14e3ba1b1-x86.apk)

**Comment by mbernasocchi** [comment]
Looks good to me, tested and works

**Comment by wonder-sk** [comment]
FYI there were some follow up commits in https://github.com/qgis/QGIS/pull/9572

**Comment by mbernasocchi** [comment]
@m-kuhn does this have to go in 1.0?

**Comment by m-kuhn** [comment]
Thanks for the hint @wonder-sk I noticed but wasn't sure if I prefer the icon or the text, it's only styling, right?

@mbernasocchi I don't think so, that can wait for after.

**Comment by wonder-sk** [comment]
@m-kuhn it's not just styling - initially the "today" button was in the calendar popup, now it is embedded in the edit widget

**Comment by m-kuhn** [comment]
Oh, thanks, I'll have a look again.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-532-d0ba1861a6bee70918ccc8ace29491375ba6abb7-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-532-d0ba1861a6bee70918ccc8ace29491375ba6abb7-x86.apk)

**Comment by mbernasocchi** [comment]
hi @m-kuhn is this still relevant?

**Comment by m-kuhn** [comment]
Yes, would be a nice improvement.

**Comment by mbernasocchi** [comment]
@m-kuhn maybe something for @nirvn?

**Comment by m-kuhn** [comment]
Yep :+1:

**Comment by nirvn** [comment]
Where do you guys think the today button should be located? In the calendar popup widget or its parent line edit widget? If it's the latter, should it only show up when there's no date entered yet?

**Comment by mbernasocchi** [comment]
open to suggestions, but from guts, I'd say in the parent line edit only if no date is there

**Comment by mbernasocchi** [comment]
superseeded by  #764

**Pull request closed without merging**
