### PR TITLE
Use S3

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 500f3bdd9051c78d806d90f57788d024bef56834:
  - [**arm64_v8a**](https://qfieldapks.sos-CH-DK-2.exo.io/ci-builds/qfield-dev-1451-bd88d28aa41b95dfeeab5ecfeab2321cad663a9f-arm64_v8a.apk)

Other architectures: [armv7](https://qfieldapks.sos-CH-DK-2.exo.io/ci-builds/qfield-dev-1451-bd88d28aa41b95dfeeab5ecfeab2321cad663a9f-armv7.apk), [x86_64](https://qfieldapks.sos-CH-DK-2.exo.io/ci-builds/qfield-dev-1451-bd88d28aa41b95dfeeab5ecfeab2321cad663a9f-x86_64.apk), [x86](https://qfieldapks.sos-CH-DK-2.exo.io/ci-builds/qfield-dev-1451-bd88d28aa41b95dfeeab5ecfeab2321cad663a9f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 631f58bcdbc68a73549d7bfc3a71476e15fe4edb:
  - [**arm64_v8a**](https://qfieldapks.sos-CH-DK-2.exo.io/ci-builds/qfield-dev-1451-92fa89f2182577f0b7d496974164025376b58804-arm64_v8a.apk)

Other architectures: [armv7](https://qfieldapks.sos-CH-DK-2.exo.io/ci-builds/qfield-dev-1451-92fa89f2182577f0b7d496974164025376b58804-armv7.apk), [x86_64](https://qfieldapks.sos-CH-DK-2.exo.io/ci-builds/qfield-dev-1451-92fa89f2182577f0b7d496974164025376b58804-x86_64.apk), [x86](https://qfieldapks.sos-CH-DK-2.exo.io/ci-builds/qfield-dev-1451-92fa89f2182577f0b7d496974164025376b58804-x86.apk)

**Comment by mbernasocchi** [comment]
https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1451-92fa89f2182577f0b7d496974164025376b58804-arm64_v8a.apk is th eworking link structure

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6feaba969afca1b4525b4f98511ad77b2253efd1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1451-1dcf166f8085e8709a883a833173443c34eac9a4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1451-1dcf166f8085e8709a883a833173443c34eac9a4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1451-1dcf166f8085e8709a883a833173443c34eac9a4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1451-1dcf166f8085e8709a883a833173443c34eac9a4-x86.apk)

**Comment by mbernasocchi** [comment]
on ubuntu with chrome and firefox I get an apk with _both_ URL structure (https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/ and https://qfieldapks.sos-ch-dk-2.exo.io/ci-builds/). on android mobile with firefox I also get an apk.

on android with chrome I get an .apk.zip :(
image

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d3aa9d8d491552cf572f883b972531d852f53acf:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1451-b104d69d0a7c4488589d27602bf32ec6ef7aec99-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1451-b104d69d0a7c4488589d27602bf32ec6ef7aec99-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1451-b104d69d0a7c4488589d27602bf32ec6ef7aec99-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1451-b104d69d0a7c4488589d27602bf32ec6ef7aec99-x86.apk)

**Comment by mbernasocchi** [comment]
:tada: :tada: :tada: works now!

**Review by mbernasocchi — APPROVED** [review]

**Review by mbernasocchi — APPROVED** [review]

**Pull request merged**
