### PR TITLE
Skip comment when CI not running from opengisch repository

### PR DESCRIPTION
**Pull request by nirvn**
Less red.

### CODE REVIEW

**Comment by m-kuhn** [comment]
We might want to do [what QGIS does for this](https://github.com/qgis/QGIS/blob/master/.github/workflows/build_artifact_comment.yml), it's not yet as flexible and portable as I'd like it to be, with a bit of luck I get around to implementing something better.

**Comment by nirvn** [comment]
@m-kuhn , probably still worth turning red into green for the immediate future, then eventually replace. 

The PR also includes two additional fixes to shut down daily action failures (cron jobs) on 3rd party repositories. IMHO pretty important as it otherwise means anybody forking QField ATM gets notification spammed :)

**Comment by m-kuhn** [comment]
> @m-kuhn , probably still worth turning red into green for the immediate future, then eventually replace.

:+1: 

> The PR also includes additional fixes to shut down daily action failures (cron jobs) on 3rd party repositories. IMHO pretty important as it otherwise means anybody forking QField ATM gets notification spammed :)

I was under the impression, that 3rd party repos need to opt in to enable workflows on forks, but if you say so

**Review by m-kuhn — APPROVED** [review]

**Comment by nirvn** [comment]
@m-kuhn , maybe it's because of my user status within the main repo? In any case, I didn't enable anything and I got a bunch of daily notifications after pulling my fork.

**Pull request merged**
