### PR TITLE
Add GPX as supported vector dataset, JP2 and WEBP as supported raster datasets

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 15b4ce41e6118b171d201f00b88233f54d8b8cbb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1666-36077ff065b4eb6e1dc9712e0268f46be6d66fb4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1666-36077ff065b4eb6e1dc9712e0268f46be6d66fb4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1666-36077ff065b4eb6e1dc9712e0268f46be6d66fb4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1666-36077ff065b4eb6e1dc9712e0268f46be6d66fb4-x86.apk)

**Comment by xBcai** [comment]
Is support for KML format taken into consideration?

**Comment by nirvn** [comment]
@xBcai , already part of the initial implementation. Supported.

**Review by m-kuhn — APPROVED** [review]
🖼️

**Pull request merged**
