### PR TITLE
Add a zoom in/out button on the main screen

### LINKED ISSUE #96: Needed "+" and "-" buttons or doubule touch zooming function.
When the outside temperature is below zero, I use the touch pencil. But with the touch pencil impossible zooming. Needed "+" and "-" buttons or doubule touch zooming function.
"Doubule touch" now works, but in very small increments. Now every time you touch the screen, switches on the identification window, and the object is marked.

buttons Example pic: https://s24.postimg.org/5hkf4eoxx/plius_minus.png

### LINKED ISSUE #1509: Allow single finger zoom
It would be great if qfield supported the Google maps style single finger zoom gesture, where a double tap and hold causes up/down movements to zoom in or out of the map.

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

Screenshots and GIFs which follow reproduction steps to demonstrate the problem

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

### PR DESCRIPTION
**Pull request by nirvn**
Empowers your thumbs and your styluses:
Peek 2020-12-24 16-48

Fixes #1509 , which also was a long-standing item in my personal wish list.
Fixes #96

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f0928eb0099fd91c3a583b0cdae6b45806899aed:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-230b9cf0d067d43e96fff23037b8232f525c6b5c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-230b9cf0d067d43e96fff23037b8232f525c6b5c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-230b9cf0d067d43e96fff23037b8232f525c6b5c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-230b9cf0d067d43e96fff23037b8232f525c6b5c-x86.apk)

**Comment by nirvn** [comment]
The add/remove vertex and zoom in/out buttons have the same sign , planning on changing the vertex ones.

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2c67d8282b59cc4f87ca7f0a31eb0734bd507382:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-7c2700287e4248a3a487b932bbecf49bddc2456e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-7c2700287e4248a3a487b932bbecf49bddc2456e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-7c2700287e4248a3a487b932bbecf49bddc2456e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-7c2700287e4248a3a487b932bbecf49bddc2456e-x86.apk)

**Comment by nirvn** [comment]
The magnifying glass + / - icons didn't work as they were clashing with the search magnifying glass above them.

This is the alternative dedicated add / remove vertex icons:
image

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2165ebaefd229f8857d735b6c47b29a9ebac2ca1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-e5053aafc6b193ca7a15dff2cf6a3c8c95d3a36e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-e5053aafc6b193ca7a15dff2cf6a3c8c95d3a36e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-e5053aafc6b193ca7a15dff2cf6a3c8c95d3a36e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-e5053aafc6b193ca7a15dff2cf6a3c8c95d3a36e-x86.apk)

**Comment by signedav** [comment]
It's really handy like that. Nice improvement!

But they take visually a lot of space. I don't have a good idea how to improve it. Maybe by making the buttons trasparent with black +/- in a black circle. But not sure...

**Comment by nyalldawson** [comment]
This doesn't actually fix #1509, which relates to the single finger double tap-and-hold zoom gesture (which allows you to zoom smoothly from anywhere on the screen)

**Comment by m-kuhn** [comment]
> This doesn't actually fix #1509, which relates to the single finger double tap-and-hold zoom gesture (which allows you to zoom smoothly from anywhere on the screen)

Wow, I wasn't even aware of this concept.

**Comment by nyalldawson** [comment]
@m-kuhn try it in Google maps -- it's one of those naturally intuitive gestures that you'll quickly become dependent on!

**Comment by m-kuhn** [comment]
Guess what I did before using the term : Wow!

**Comment by m-kuhn** [comment]
> It's really handy like that. Nice improvement!
> 
> But they take visually a lot of space. I don't have a good idea how to improve it. Maybe by making the buttons trasparent with black +/- and black border. But not sure...

We discussed making it optional. Is that required.

We could also use the g maps concept of hiding ui elements when tapping an empty space on the screen.

**Comment by nirvn** [comment]
One possibility: we slightly scale down the zoom in / out button:
image

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3661d06746721802e92b95dfcfb73bc82c0f4ac2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-d21f953d1103b436a695bcbb2ad8e71095b20525-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-d21f953d1103b436a695bcbb2ad8e71095b20525-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-d21f953d1103b436a695bcbb2ad8e71095b20525-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-d21f953d1103b436a695bcbb2ad8e71095b20525-x86.apk)

**Comment by m-kuhn** [comment]
I think I can get used to the small buttons

I would add a bit more spacing between them. And also to the screen edge.
Zooming in is double the speed than zooming out. I'd reduce the zoom in factor.

**Comment by signedav** [comment]
I like the small buttons 👍

Just a thought (doesn't need to be considered in this PR): the buttons could be visually connected (since it's one function and not two) like having a long oval button with + in the upper half and - in the lower one.

Regarding the question if we need a setting option to show/hide them: I think such a setting would make sence as soon we have other options to zoom with one finger (like e.g. the one Nyall mentioned from Google Maps). For now I think we don't need a setting option.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 06c4c229ebec69510fb768976d00156b36dd0c2a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-4215425182d3bb33b81e301322b1348f7b0bba87-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-4215425182d3bb33b81e301322b1348f7b0bba87-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-4215425182d3bb33b81e301322b1348f7b0bba87-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1519-4215425182d3bb33b81e301322b1348f7b0bba87-x86.apk)

**Comment by nirvn** [comment]
Comments addressed, merging now so we can test this more wildly. 

@signedav , OK, we can revisit option if/when we implement that nice gesture Nyall made us aware of :)

**Pull request merged**
