### PR TITLE
A round of windows fixes

### PR DESCRIPTION
**Pull request by nirvn**
This fixes install path for proj data on windows (and I assume OSX). No regression on the Android front.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c218f0e028cf2742df41f1313f6308b32dfa4554: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3192-aec7824d1c6dfc389a803301815850ca22fd1184-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3192-aec7824d1c6dfc389a803301815850ca22fd1184-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3192-aec7824d1c6dfc389a803301815850ca22fd1184-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3192-aec7824d1c6dfc389a803301815850ca22fd1184-x86-android.apk)
</details>

**Comment by nirvn** [comment]
With this commit, QField on Windows can find the proj.db, and reprojection works flawlessly:
image

**Comment by nirvn** [comment]
@m-kuhn , when testing QField on windows, I noticed that upon first launch after installing QField, the systemSharedDataLocation() returned C:\ (only once). That's bad (in part because it's needed to properly initiate the qgis profile database creation, etc.)

Googling a bit about QCoreApplication::applicationDirPath(), it seems that's not as reliable as QCoreApplication::applicationFilePath(), hence the commit here. That should give us reliable paths.

**Review by m-kuhn — APPROVED** [review]

**Comment by nirvn** [comment]
@m-kuhn , first launch issue fixed, brilliant.

**Pull request merged**
