### PR TITLE
Show that the QFieldCloud project has no connection if currently logged in with another user

### PR DESCRIPTION
**Pull request by suricactus**
image

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1775 Show that the QFieldCloud project has no connection if currently logged in with another user](https://app.clickup.com/t/2192114/QF-1775)

**Comment by nirvn** [comment]
@suricactus , is the delta file tracking still working even though the user isn't the right one?

**Comment by suricactus** [comment]
It does, just tested.

**Comment by nirvn** [comment]
@suricactus , good design :) I was wondering whether we had to put the project in read only mode or not.

**Review by nirvn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 04cd9d22f25e0d80987a64d4c3c1577118319340:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2536-8223bdbab8480cec0fb40f93d6d150adb7347e1c-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2536-8223bdbab8480cec0fb40f93d6d150adb7347e1c-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2536-8223bdbab8480cec0fb40f93d6d150adb7347e1c-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2536-8223bdbab8480cec0fb40f93d6d150adb7347e1c-x86-android.apk)

**Comment by suricactus** [comment]
@nirvn I also do not have an answer whether it is a good or bad that we track project changes... For sure it is easier to be like it is now and we will see how time goes.

If we can upload project from QField to QFieldCloud...

**Pull request merged**
