### PR TITLE
Add macos builds and tests

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Screenshot 2021-10-06 at 21 40 45

Providers still missing

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0beca5219c8299550ddcb35e18b37af750a20c61:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-69b99f3a140ed69f43d3caffefe13bd6c8481e2a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-69b99f3a140ed69f43d3caffefe13bd6c8481e2a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-69b99f3a140ed69f43d3caffefe13bd6c8481e2a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-69b99f3a140ed69f43d3caffefe13bd6c8481e2a-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4b33e789e1475c501c9f70b71fb0c3d4027b2363:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-1810bffeab3739616ce194cf78d9bea954c525ec-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-1810bffeab3739616ce194cf78d9bea954c525ec-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-1810bffeab3739616ce194cf78d9bea954c525ec-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-1810bffeab3739616ce194cf78d9bea954c525ec-x86.apk)

**Comment by m-kuhn** [comment]
Bundling is removed for the moment, that needs more work.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 231bc9f025a646cdb8de0e5801cdfb36b76ca42e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-49b7a2102c0195ceb70a86a5947906c52f77cb5f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-49b7a2102c0195ceb70a86a5947906c52f77cb5f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-49b7a2102c0195ceb70a86a5947906c52f77cb5f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2205-49b7a2102c0195ceb70a86a5947906c52f77cb5f-x86.apk)

**Pull request merged**
