### PR TITLE
Simplify qtkeychain usage

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
Nice

**Comment by m-kuhn** [comment]
Close and reopen when #5020 has been merged, just as a random try. Not sure what's wrong here.

**Comment by nirvn** [comment]
@m-kuhn , pretty sure I know what's wrong. I'll take a shot at it now.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 49539fa2d9f8dd3453cd8f950a3c1b1b3ac089e6: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5025-ea3a78bc8d35b98af05aadf35f31a651613704d4-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5025-ea3a78bc8d35b98af05aadf35f31a651613704d4-android-arm-neon.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5025-ea3a78bc8d35b98af05aadf35f31a651613704d4-android-x64.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5025-ea3a78bc8d35b98af05aadf35f31a651613704d4-android-x86.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5025-ea3a78bc8d35b98af05aadf35f31a651613704d4-android-arm64.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5025-ea3a78bc8d35b98af05aadf35f31a651613704d4-android-arm-neon.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5025-ea3a78bc8d35b98af05aadf35f31a651613704d4-android-x64.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5025-ea3a78bc8d35b98af05aadf35f31a651613704d4-android-x86.apk)
</details>

**Pull request merged**
