### PR TITLE
Use documents location to share printing PDF

### PR DESCRIPTION
**Pull request by signedav**
Maybe it has been to easy that it can be true.
Let's see what the fairy brings to us...

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-28418f3387a7ec288f2f43cd2556194f76f9c97d-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-28418f3387a7ec288f2f43cd2556194f76f9c97d-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-28418f3387a7ec288f2f43cd2556194f76f9c97d-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-28418f3387a7ec288f2f43cd2556194f76f9c97d-x86-5.apk))

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-d8173f8ebb178424fed170d54f3682c1403dcc3a-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-d8173f8ebb178424fed170d54f3682c1403dcc3a-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-d8173f8ebb178424fed170d54f3682c1403dcc3a-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-d8173f8ebb178424fed170d54f3682c1403dcc3a-x86-5.apk))

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-d8c9ff9e7591ef5f31db13ec0478d55ebddc81b3-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-d8c9ff9e7591ef5f31db13ec0478d55ebddc81b3-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-d8c9ff9e7591ef5f31db13ec0478d55ebddc81b3-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-615-d8c9ff9e7591ef5f31db13ec0478d55ebddc81b3-x86-5.apk))

**Comment by signedav** [comment]
Opened Pull Request with the information in the doc: https://github.com/opengisch/QField-docs/pull/35
Opened issue for future improvement https://github.com/opengisch/QField/issues/617

**Pull request merged**
