### PR TITLE
Positioning {TCP,UDP} receiver

### PR DESCRIPTION
**Pull request by nirvn**
This PR adds a brand new TCP and UDP receiver to our growing number of supported positioning sources:

image

Both receivers have been tested against a local python-driver TCP and UDP servers streaming NMEA logs. I have not had the good fortune of testing it against an external GNSS device though.

It is _super_ exciting for many, many reasons, including the fact that this unlocks high-precision GNSS devices support for iOS (which never did and never will support Bluetooth connections).

Merry Christmas!

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cbbf7f2314369b843559ed66d9487820d2fd3215: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3770-0f017eb18b2869cbf1031ab2da2ec7ede19cacae-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3770-0f017eb18b2869cbf1031ab2da2ec7ede19cacae-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3770-0f017eb18b2869cbf1031ab2da2ec7ede19cacae-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3770-0f017eb18b2869cbf1031ab2da2ec7ede19cacae-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3770-0f017eb18b2869cbf1031ab2da2ec7ede19cacae-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3770-0f017eb18b2869cbf1031ab2da2ec7ede19cacae-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3770-0f017eb18b2869cbf1031ab2da2ec7ede19cacae-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3770-0f017eb18b2869cbf1031ab2da2ec7ede19cacae-x86-android.apk)
</details>

**Comment by nirvn** [comment]
I've taken the time to improve the UI/UX for Bluetooth device addition by avoiding showing an empty combobox list. 

The user is first asked to scan for nearby device:
Screenshot from 2022-12-26 11-22-30

When the combobox has at least one item, it will show up for users to pick the device:
Screenshot from 2022-12-26 11-21-49

**Comment by m-kuhn** [comment]
> It is super exciting for many, many reasons, including the fact that this unlocks high-precision GNSS devices support for iOS (which never did and never will support Bluetooth connections).

🎉🎉🎉

**Comment by nirvn** [comment]
@m-kuhn , I'd like to merge this today if at all possible.

**Review by m-kuhn — APPROVED** [review]

**Comment by pyrog** [comment]
Does it close #3484 ?

**Pull request merged**
