### PR TITLE
Calendar comeback, build a brand new QtQuick 2 calendar item

### PR DESCRIPTION
**Pull request by nirvn**
Title says it all.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-ef5800a67006adda75ab365e24d57dbf72812fa8-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-ef5800a67006adda75ab365e24d57dbf72812fa8-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-ef5800a67006adda75ab365e24d57dbf72812fa8-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-ef5800a67006adda75ab365e24d57dbf72812fa8-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-77fa8123f12fdae9bdbbcbb51f995ee600ec2c9d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-77fa8123f12fdae9bdbbcbb51f995ee600ec2c9d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-77fa8123f12fdae9bdbbcbb51f995ee600ec2c9d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-77fa8123f12fdae9bdbbcbb51f995ee600ec2c9d-x86_64.apk)

**Comment by nirvn** [comment]
Did someone say DateTime? :smile: 
Screenshot from 2020-05-16 14-58-51

That should please a fair amount of QField users, having time support embedded into the calendar widget gets rid of the need for QField users to add a separate time field.

The screenshot also shows the brand new year navigation buttons (the double arrow buttons at the far left and right of the calendar popup).

This is ready to be reviewed and merged.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-5511d0d235663a8f33ca5f4b2ac24ea0ad301c73-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-5511d0d235663a8f33ca5f4b2ac24ea0ad301c73-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-5511d0d235663a8f33ca5f4b2ac24ea0ad301c73-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1021-5511d0d235663a8f33ca5f4b2ac24ea0ad301c73-x86_64.apk)

**Pull request merged**
