### PR TITLE
Alternative dual touch/mouse fix

### PR DESCRIPTION
**Pull request by nirvn**
I think this might work better. @m-kuhn , can you try with your touch screen and mouse?

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-aebc3f2e5ca5e3119a4724b49bfaa3edd7b884a2-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-aebc3f2e5ca5e3119a4724b49bfaa3edd7b884a2-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-aebc3f2e5ca5e3119a4724b49bfaa3edd7b884a2-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-aebc3f2e5ca5e3119a4724b49bfaa3edd7b884a2-x86_64.apk)

**Comment by m-kuhn** [comment]
Works :tada:

**Comment by 3nids** [comment]
This fixes the issues with the zoom but with finger:
* it breaks digitizing with the finger: clicking on the point adds a point once over 10 tries
* when you pan, the cursor follows the finger before going back to the center

with the pen:
* while digitizing the validate button is shown while it should not (validate is on long press)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-64dd2a91dfa84715406438e5ad7782edd8adccd5-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-64dd2a91dfa84715406438e5ad7782edd8adccd5-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-64dd2a91dfa84715406438e5ad7782edd8adccd5-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-64dd2a91dfa84715406438e5ad7782edd8adccd5-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-e32bde75f2a69d24065d609ddb1e8c9004fe5e29-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-e32bde75f2a69d24065d609ddb1e8c9004fe5e29-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-e32bde75f2a69d24065d609ddb1e8c9004fe5e29-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-e32bde75f2a69d24065d609ddb1e8c9004fe5e29-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-153c0d8556a8b2f11b98cad2b6b7868f00665e88-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-153c0d8556a8b2f11b98cad2b6b7868f00665e88-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-153c0d8556a8b2f11b98cad2b6b7868f00665e88-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-153c0d8556a8b2f11b98cad2b6b7868f00665e88-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-61fc3f0ab965dfa7fcc6309222d242b69df3dee6-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-61fc3f0ab965dfa7fcc6309222d242b69df3dee6-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-61fc3f0ab965dfa7fcc6309222d242b69df3dee6-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-61fc3f0ab965dfa7fcc6309222d242b69df3dee6-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-ee0c439b1bb89cdf0d112880db026788529a994a-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-ee0c439b1bb89cdf0d112880db026788529a994a-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-ee0c439b1bb89cdf0d112880db026788529a994a-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-ee0c439b1bb89cdf0d112880db026788529a994a-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-13091cdae4c4535e55a5bde8832c8f4277df434d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-13091cdae4c4535e55a5bde8832c8f4277df434d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-13091cdae4c4535e55a5bde8832c8f4277df434d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-13091cdae4c4535e55a5bde8832c8f4277df434d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-db7394b92f9a25f98bb5f410b9a05bb5b1a54072-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-db7394b92f9a25f98bb5f410b9a05bb5b1a54072-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-db7394b92f9a25f98bb5f410b9a05bb5b1a54072-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-db7394b92f9a25f98bb5f410b9a05bb5b1a54072-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-1395894a13cf9d5b404317d534d19a7fda2c58e8-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-1395894a13cf9d5b404317d534d19a7fda2c58e8-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-1395894a13cf9d5b404317d534d19a7fda2c58e8-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-1395894a13cf9d5b404317d534d19a7fda2c58e8-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-8e9dd40765f6d9a6895cd43b1dd8cf8163bcff45-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-8e9dd40765f6d9a6895cd43b1dd8cf8163bcff45-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-8e9dd40765f6d9a6895cd43b1dd8cf8163bcff45-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-8e9dd40765f6d9a6895cd43b1dd8cf8163bcff45-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-3f4d88de15790a479f7a857f148c5169a96b8cee-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-3f4d88de15790a479f7a857f148c5169a96b8cee-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-3f4d88de15790a479f7a857f148c5169a96b8cee-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-3f4d88de15790a479f7a857f148c5169a96b8cee-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-dd8fe8c5869173dc30f27a77623bf78d10460d9f-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-dd8fe8c5869173dc30f27a77623bf78d10460d9f-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-dd8fe8c5869173dc30f27a77623bf78d10460d9f-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-dd8fe8c5869173dc30f27a77623bf78d10460d9f-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-7f41a34c9db4be479e260f04a859754fa1dfccf1-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-7f41a34c9db4be479e260f04a859754fa1dfccf1-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-7f41a34c9db4be479e260f04a859754fa1dfccf1-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-7f41a34c9db4be479e260f04a859754fa1dfccf1-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-8b5a5ac065ab80d5a5024cbb236a48e1177fd2ef-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-8b5a5ac065ab80d5a5024cbb236a48e1177fd2ef-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-8b5a5ac065ab80d5a5024cbb236a48e1177fd2ef-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1103-8b5a5ac065ab80d5a5024cbb236a48e1177fd2ef-x86_64.apk)

**Pull request closed without merging**
