### PR TITLE
Rate us / user feedback do-over

### PR DESCRIPTION
**Pull request by nirvn**
This PR re-do the "rate us if you like us" UI/UX. First, how it looks.

Positive experience:
Peek 2021-04-22 18-33

Negative experience:
Peek 2021-04-22 18-33-bad

The benefits of this re-do include:
- The feedback form is in pure QML, which makes it easier to maintain and reduce burden of maintaining such a function for platforms QField runs on.
- Instead of a popup dialog, which tents to appear at the worse possible time for users, the new QML feedback form is non-intrusive and adds itself in the welcome screen; users are free to engage with it or ignore it and click on projects below it immediately without the need to close any obstructing element
- if a user is unhappy with the experience so far, he/she is provided with a much better follow up button, one that will land on a support / contact page with links to the github issue report page, as well as contact details

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9d8e15d66bfd275a2ed92e6f1fe68e8d1b6b1f9b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-d3aa87df0668f9e9aca22e1cfb51003c453709b4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-d3aa87df0668f9e9aca22e1cfb51003c453709b4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-d3aa87df0668f9e9aca22e1cfb51003c453709b4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-d3aa87df0668f9e9aca22e1cfb51003c453709b4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 74afe1c1b13c291a4afc1b36ace451c8d6bde0f8:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-c78ba7a7fad623103545863859af39a88d791107-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-c78ba7a7fad623103545863859af39a88d791107-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-c78ba7a7fad623103545863859af39a88d791107-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-c78ba7a7fad623103545863859af39a88d791107-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5ab8e9bcfdfe2cb733a9d580c421d71184499f8c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-213dd057c4e907bf27978bc9bcd52afb6d6b3afa-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-213dd057c4e907bf27978bc9bcd52afb6d6b3afa-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-213dd057c4e907bf27978bc9bcd52afb6d6b3afa-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1863-213dd057c4e907bf27978bc9bcd52afb6d6b3afa-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
have to test the backport bot

**Pull request merged**
