### PR TITLE
Ubuntu 18.04 image has been retired, causing failures

### PR DESCRIPTION
**Pull request by nirvn**
See https://github.com/opengisch/QField/actions/runs/4232664525 for example of failure.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f423c30daaa34f25b4a348cc04e6252bbb1a3248: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3940-d0a352a10c4c95ee2257d421e4a8f719b105dc51-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3940-d0a352a10c4c95ee2257d421e4a8f719b105dc51-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3940-d0a352a10c4c95ee2257d421e4a8f719b105dc51-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3940-d0a352a10c4c95ee2257d421e4a8f719b105dc51-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3940-d0a352a10c4c95ee2257d421e4a8f719b105dc51-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3940-d0a352a10c4c95ee2257d421e4a8f719b105dc51-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3940-d0a352a10c4c95ee2257d421e4a8f719b105dc51-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3940-d0a352a10c4c95ee2257d421e4a8f719b105dc51-x86-android.apk)
</details>

**Comment by m-kuhn** [comment]
Can we have https://github.com/pocc/pre-commit-hooks instead?

**Comment by nirvn** [comment]
@m-kuhn , to replace the remaining cppcheck 1.9?

**Comment by m-kuhn** [comment]
Probably...
Less special things.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
