### PR TITLE
Use clang format instead of astyle

### PR DESCRIPTION
**Pull request by m-kuhn**
With clang 13 available we finally have all we need

Will also format java files

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
Nice.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for aa7ba472b49681a1b331da692fe0ce54f0687201:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-af39fc13971efae757963615cf89493055543b1d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-af39fc13971efae757963615cf89493055543b1d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-af39fc13971efae757963615cf89493055543b1d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-af39fc13971efae757963615cf89493055543b1d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e3eb72a1806078b940a387c56fa13dac4657f409:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-9687005754e984da2cc203ef077d7b07b23e50d1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-9687005754e984da2cc203ef077d7b07b23e50d1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-9687005754e984da2cc203ef077d7b07b23e50d1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-9687005754e984da2cc203ef077d7b07b23e50d1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for be0959f0d33b09ef8d9dd7ecff76112032643130:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-9391d4295cc719312cfee09ba3b3d4dc0023b72e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-9391d4295cc719312cfee09ba3b3d4dc0023b72e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-9391d4295cc719312cfee09ba3b3d4dc0023b72e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-9391d4295cc719312cfee09ba3b3d4dc0023b72e-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5af4945fd92e2c63c04c3ba522a5026181e19eb6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-f7ccf930e65cfb967975406986141eeaa681dc49-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-f7ccf930e65cfb967975406986141eeaa681dc49-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-f7ccf930e65cfb967975406986141eeaa681dc49-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-f7ccf930e65cfb967975406986141eeaa681dc49-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2620a6a9083e7e8ed09b9b9e3134f15946be085c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-8a87714b6a2faa282fe2f7679d85433ab061b28d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-8a87714b6a2faa282fe2f7679d85433ab061b28d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-8a87714b6a2faa282fe2f7679d85433ab061b28d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-8a87714b6a2faa282fe2f7679d85433ab061b28d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 58b25e6ce451edacf81c72cc37fa7bab98373928:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-d1d1ea37af884ba2a65d24cae21471e517de8a91-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-d1d1ea37af884ba2a65d24cae21471e517de8a91-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-d1d1ea37af884ba2a65d24cae21471e517de8a91-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-d1d1ea37af884ba2a65d24cae21471e517de8a91-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cfec75ff2fe6fdb35255597575304f9f96f6ab57:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-937881b6063160527165bdeddc8d5cf292f6276d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-937881b6063160527165bdeddc8d5cf292f6276d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-937881b6063160527165bdeddc8d5cf292f6276d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2319-937881b6063160527165bdeddc8d5cf292f6276d-x86.apk)

**Pull request merged**
