### PR TITLE
use default button on welcome screen

### PR DESCRIPTION
**Pull request by signedav**
I believe the background of the button before got invisible

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-501-647413a494d06339dab9b77c7548346520fba5ae-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-501-647413a494d06339dab9b77c7548346520fba5ae-x86.apk)

**Comment by marioba** [comment]
With this apk I don't see the welcome screen but directly the main screen...

**Comment by signedav** [comment]
And with reinstalling the official build you see it again @marioba ?

**Comment by marioba** [comment]
Yes, with the RC3 from the play store I see the welcome screen and the button

**Comment by signedav** [comment]
Imported path. Tough I cannot imagine that this helps.

It's weird, I cannot reproduce it. I always see the button.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-501-981896f599c9acdc412938b4dffe794060c2ef42-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-501-981896f599c9acdc412938b4dffe794060c2ef42-x86.apk)

**Comment by mbernasocchi** [comment]
@signedav the welcome screen is skipped with the https://github.com/opengisch/QField/pull/501#issuecomment-469750611

**Comment by signedav** [comment]
Hm... weird. Not on my devices with Android 8...

**Comment by marioba** [comment]
It's maybe a theme related issue. In different Android versions the default theme is different and maybe this is the cause if the issue...

**Comment by mbernasocchi** [comment]
superseded by #503

**Pull request closed without merging**
