### PR TITLE
Fix QField crashing on arm(v7) devices

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4957e176cfab7e90bee4e30689e243e3e55821e4:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-9523efccdc156bab5fe83efdea026c053f4b79f3-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-9523efccdc156bab5fe83efdea026c053f4b79f3-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-9523efccdc156bab5fe83efdea026c053f4b79f3-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-9523efccdc156bab5fe83efdea026c053f4b79f3-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6c20ea3e370f8b5df278950b73dd0e0dd9672586:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-ea7d8f226a61df22757d800cc0f85479fc823d39-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-ea7d8f226a61df22757d800cc0f85479fc823d39-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-ea7d8f226a61df22757d800cc0f85479fc823d39-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-ea7d8f226a61df22757d800cc0f85479fc823d39-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c9e71e99f735da20eee9b406f9a0e386320cf45a:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-28ad32ff319cc423640c394b1deaedab8db92e98-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-28ad32ff319cc423640c394b1deaedab8db92e98-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-28ad32ff319cc423640c394b1deaedab8db92e98-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-28ad32ff319cc423640c394b1deaedab8db92e98-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 582972adbc65ee54cfadfadf3f411edffd644a1a:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-c698e3fdcd7cbf322a01c5bcd4f093c601efd0f0-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-c698e3fdcd7cbf322a01c5bcd4f093c601efd0f0-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-c698e3fdcd7cbf322a01c5bcd4f093c601efd0f0-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-c698e3fdcd7cbf322a01c5bcd4f093c601efd0f0-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 068ac80e54aa663919fd53d887105677c2fe595a:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-bb269af3364a1739465dc60a9e2fde632c2cbbf9-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-bb269af3364a1739465dc60a9e2fde632c2cbbf9-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-bb269af3364a1739465dc60a9e2fde632c2cbbf9-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-bb269af3364a1739465dc60a9e2fde632c2cbbf9-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 79abaa67d0c11e714aad579ccec0baecc76c67ca:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-042314113df76c4f2fb9e37756cea28e7302ce55-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-042314113df76c4f2fb9e37756cea28e7302ce55-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-042314113df76c4f2fb9e37756cea28e7302ce55-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-042314113df76c4f2fb9e37756cea28e7302ce55-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c6ffbbd322070f7229a4a1fef939c3cdf8ff5888:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-d0141e86e3094d1428fa98c5d27ecc51cbe90907-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-d0141e86e3094d1428fa98c5d27ecc51cbe90907-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-d0141e86e3094d1428fa98c5d27ecc51cbe90907-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-d0141e86e3094d1428fa98c5d27ecc51cbe90907-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bffd7c33aef1ddcf6ac8923350a6dee2aab1baa3:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-00af7e97e58b88982c768c37806f7fa8622e7a00-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-00af7e97e58b88982c768c37806f7fa8622e7a00-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-00af7e97e58b88982c768c37806f7fa8622e7a00-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-00af7e97e58b88982c768c37806f7fa8622e7a00-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c56162c3861e60bc707354d4796fa6112235a991:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-77b47813b0fc08700e591ccb538f8d9f847fa4f7-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-77b47813b0fc08700e591ccb538f8d9f847fa4f7-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-77b47813b0fc08700e591ccb538f8d9f847fa4f7-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-77b47813b0fc08700e591ccb538f8d9f847fa4f7-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-77b47813b0fc08700e591ccb538f8d9f847fa4f7-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2ff2b61121525a4d3b8cb4e496a33a5ae26bbcc6:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-f8bc57c45894fa3d4f687aeb9b9ff3767b825116-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-f8bc57c45894fa3d4f687aeb9b9ff3767b825116-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-f8bc57c45894fa3d4f687aeb9b9ff3767b825116-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-f8bc57c45894fa3d4f687aeb9b9ff3767b825116-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2773-f8bc57c45894fa3d4f687aeb9b9ff3767b825116-x86-android.apk)

**Review by marioba — APPROVED** [review]

**Comment by m-kuhn** [comment]
Note to seld, re unwind etc.
r23 seems to improve things
https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Unwinding

**Pull request merged**
