### PR TITLE
Add workaround for synthesized touch events

### PR DESCRIPTION
**Pull request by m-kuhn**
I don't like timers for workarounds.
But since there has been so much time lost already in finding clean solutions, why not for once do it.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@3nids @nirvn interested in comments and test results

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1107-5a162d9e5a2748200919f7ea2be89dd0fbe2d00d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1107-5a162d9e5a2748200919f7ea2be89dd0fbe2d00d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1107-5a162d9e5a2748200919f7ea2be89dd0fbe2d00d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1107-5a162d9e5a2748200919f7ea2be89dd0fbe2d00d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1107-d6932efee0f1af13c03c3d94c6d6f8040423b070-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1107-d6932efee0f1af13c03c3d94c6d6f8040423b070-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1107-d6932efee0f1af13c03c3d94c6d6f8040423b070-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1107-d6932efee0f1af13c03c3d94c6d6f8040423b070-x86_64.apk)

**Comment by nirvn** [comment]
@m-kuhn , my extra attempts this morning failed. This timer hack works, I'd say go for it.

It has to be something not working as expected on the QML side of things. Anyhow, glad you find a workaround.

**Comment by m-kuhn** [comment]
Some notes:

- The `hovered` property is a bit flaky. Even when constantly touching the display it is sometimes temporarily off for an instant. This might be in the nature of it.
- The flags for synthesized events (stylus, mouse, touch screen) did not have any effect here. The documentation for `*Handler` is super scarce on information regarding this.
- In short, we currently have the means to test if a touch event happened (semi-stable state, now stabilized through a timer), we do not have any means to test if a stylus or mouse event is really coming from this source (... and not from a touch interaction).

**Comment by m-kuhn** [comment]
Upstream issue https://bugreports.qt.io/browse/QTBUG-85427

**Comment by nirvn** [comment]
Closing other PRs, I think we've dissected this enough to positively conclude it's a Qt issue and timer is the only way around it ATM.

**Pull request merged**
