### PR TITLE
Fix resources

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
tested?

**Comment by nirvn** [comment]
Not tested, just preemptively hopeful, and looking at failures I was too quick?

**Comment by m-kuhn** [comment]
I'm confident but not 100% sure

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 209ab2960ceee7d5416743b81d9756e17d16026a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2338-de26a688354ff4fc711e93d9ebaf1fda8da69ace-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2338-de26a688354ff4fc711e93d9ebaf1fda8da69ace-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2338-de26a688354ff4fc711e93d9ebaf1fda8da69ace-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2338-de26a688354ff4fc711e93d9ebaf1fda8da69ace-x86.apk)

**Pull request merged**
