### PR TITLE
Display {jpg,png,tif,webp,pdf} thumbnails in the project/dataset picker activity

### PR DESCRIPTION
**Pull request by nirvn**
Screencast:

https://user-images.githubusercontent.com/1728657/166442966-8a7ac369-bc23-40f8-9b5d-bd8893617b70.mp4

Can be quite useful when trying to find back a dataset that was imported a while back, or even look for specific image attachment(s) within a project folder.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d130ac3447ba07820b52b193de709f839c3e1e15:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c3c4edd47c8001456fb8c17a6ccce1983b472295-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c3c4edd47c8001456fb8c17a6ccce1983b472295-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c3c4edd47c8001456fb8c17a6ccce1983b472295-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c3c4edd47c8001456fb8c17a6ccce1983b472295-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c3c4edd47c8001456fb8c17a6ccce1983b472295-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2c60f3055849953e96d6cb63966529c1d2f3788e:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-96c8c4308ca54ff7c55b2870c40899f5776a9fd1-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-96c8c4308ca54ff7c55b2870c40899f5776a9fd1-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-96c8c4308ca54ff7c55b2870c40899f5776a9fd1-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-96c8c4308ca54ff7c55b2870c40899f5776a9fd1-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-96c8c4308ca54ff7c55b2870c40899f5776a9fd1-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a7bab30352dbdefbce7f89ec8dd328778e5c847c:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-9ff684f533ffe8bb891acbae496ca562604966dc-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-9ff684f533ffe8bb891acbae496ca562604966dc-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-9ff684f533ffe8bb891acbae496ca562604966dc-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-9ff684f533ffe8bb891acbae496ca562604966dc-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-9ff684f533ffe8bb891acbae496ca562604966dc-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1ca9ee063ec8ea5c7e9e66907b476bb7a8ee4059:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-b556634f63799c2df13e69f01373820a4dc77c0c-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-b556634f63799c2df13e69f01373820a4dc77c0c-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-b556634f63799c2df13e69f01373820a4dc77c0c-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-b556634f63799c2df13e69f01373820a4dc77c0c-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-b556634f63799c2df13e69f01373820a4dc77c0c-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 211874fb6a665cd555b135e6a05c7fa4bfc3e7d4:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c10576545ba6bbfa2427dd28767c057396b5dea9-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c10576545ba6bbfa2427dd28767c057396b5dea9-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c10576545ba6bbfa2427dd28767c057396b5dea9-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c10576545ba6bbfa2427dd28767c057396b5dea9-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2852-c10576545ba6bbfa2427dd28767c057396b5dea9-x86-android.apk)

**Review by m-kuhn — APPROVED** [review]
Very nice

**Pull request merged**
