### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c0054a9a28e9ebc56461c5a715d57fc471ec7442:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-5525e8eb14f2038ea750b53f3907f5cfde0d0ac8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-5525e8eb14f2038ea750b53f3907f5cfde0d0ac8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-5525e8eb14f2038ea750b53f3907f5cfde0d0ac8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-5525e8eb14f2038ea750b53f3907f5cfde0d0ac8-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for de486846aff9bcabfad58299dd1c9029c1869189:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-08351cb245c5781fb964d3f826e9b0828f491a0f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-08351cb245c5781fb964d3f826e9b0828f491a0f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-08351cb245c5781fb964d3f826e9b0828f491a0f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-08351cb245c5781fb964d3f826e9b0828f491a0f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c4e08bc81bcd500a4b9d6e890b7169a539118fa7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-3052ec438c63c80191587f7de3b09a8ff5de9a04-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-3052ec438c63c80191587f7de3b09a8ff5de9a04-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-3052ec438c63c80191587f7de3b09a8ff5de9a04-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-3052ec438c63c80191587f7de3b09a8ff5de9a04-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e2ef70b2151a5d3b25f2ef5a68c26d36a8c3ba0f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-eb7f272b36b160958229afc8d670b80c6b5280e9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-eb7f272b36b160958229afc8d670b80c6b5280e9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-eb7f272b36b160958229afc8d670b80c6b5280e9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-eb7f272b36b160958229afc8d670b80c6b5280e9-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bb63db70629cddbbb22cc09735fbcc3d7d430665:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-25a94bc7a284cad77a10b9e6c5a509e596aa70bd-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-25a94bc7a284cad77a10b9e6c5a509e596aa70bd-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-25a94bc7a284cad77a10b9e6c5a509e596aa70bd-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-25a94bc7a284cad77a10b9e6c5a509e596aa70bd-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8c059bfdd1fd99cee37e67634046447d617eae22:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-b47ee8e6774ecf8fe1f6cb78715b0d0d80604c84-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-b47ee8e6774ecf8fe1f6cb78715b0d0d80604c84-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-b47ee8e6774ecf8fe1f6cb78715b0d0d80604c84-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-b47ee8e6774ecf8fe1f6cb78715b0d0d80604c84-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 349d20ef4eca539c710897df103dd2dbe15ada28:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-3020efa53357ef5580b51348a72f2607369581f4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-3020efa53357ef5580b51348a72f2607369581f4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-3020efa53357ef5580b51348a72f2607369581f4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-3020efa53357ef5580b51348a72f2607369581f4-x86.apk)

**Comment by m-kuhn** [comment]
@3nids any opinion on better configuration?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9c585794fa3af06f3da9ef2478db627a383534b9:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-c6979ca8b41be5e06e299a5f218e15a155a408d8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-c6979ca8b41be5e06e299a5f218e15a155a408d8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-c6979ca8b41be5e06e299a5f218e15a155a408d8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-c6979ca8b41be5e06e299a5f218e15a155a408d8-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7e2ca8b10cf1fa5867167a5f1c07a7b1759872bb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-7838d7fe57991f02d6698e3788102ce042dc028a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-7838d7fe57991f02d6698e3788102ce042dc028a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-7838d7fe57991f02d6698e3788102ce042dc028a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-7838d7fe57991f02d6698e3788102ce042dc028a-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ef9500b6b3c450654fa980320a71d3f9ea6d0f33:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-e84d567176ab27b9644f81b05d1f0fb832d22fce-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-e84d567176ab27b9644f81b05d1f0fb832d22fce-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-e84d567176ab27b9644f81b05d1f0fb832d22fce-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1873-e84d567176ab27b9644f81b05d1f0fb832d22fce-x86.apk)

**Comment by m-kuhn** [comment]
Might be worth waiting for https://github.com/llvm/llvm-project/commit/2a42c759ae7bb09dd448d188138f310d014fcab6

I don't have it available in clang-format 12, even though `IndentAccessModifiers` is documented ...

**Comment by m-kuhn** [comment]
IndentAccessModifiers requires clang-format-13 which is not yet available

**Comment by 3nids** [comment]
what would be your strategy so people could run it on their machine? everyone will need version 13?

**Comment by m-kuhn** [comment]
Approaches:

1. everyone will need version 13
2. fallback to the [style police](https://github.com/opengisch/QField/pull/1881#issuecomment-830874249) and handle this on github
1. run the style command in docker

I think we should wait at least until version 13 is released and available on bleeding edge distros. Then we can switch to this in combination with 2.

**Comment by 3nids** [comment]
I was mainly wondering about when/how we will be able to do the same on QGIS side.

**Comment by m-kuhn** [comment]
I would expect first distros with clang 13 end of this year. Until the majority of devs pick it up a good bit more.

**Pull request closed without merging**
