### PR TITLE
Relation editor rework to allow for map panning/zooming to child feature

### PR DESCRIPTION
**Pull request by nirvn**
This PR implements panning/zooming to child feature UX within relation-related editor widget.

**Relation editor widget**

Showtime:

[Screencast from 2023-06-23 14-56-06.webm](https://github.com/opengisch/QField/assets/1728657/fcfd60ea-3bc1-4665-af3b-b5b0bd0dd166)

_Notice the super flashy opacity animation, which does a much better job at highlighting a feature than a static show/wait/hide_

UI wise, changes include the addition of a button to open a child feature's form so we can take over the tap on child feature display text to pan/zoom the map canvas. It happens to actually be a nice move as it harmonizes the UI/UX with that of the search bar.

**Relation reference widget**

Showtime:

[Screencast from 2023-06-24 15-12-59.webm](https://github.com/opengisch/QField/assets/1728657/b41c37fa-af66-4d37-bb71-0bf5b3615b0c)

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 24544c03ec22872313f61549c60f58bf669fb78e: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4391-e77627e8adde0ca8a62eacdce201fe20770139b5-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4391-e77627e8adde0ca8a62eacdce201fe20770139b5-arm-neon-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4391-e77627e8adde0ca8a62eacdce201fe20770139b5-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4391-e77627e8adde0ca8a62eacdce201fe20770139b5-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4391-e77627e8adde0ca8a62eacdce201fe20770139b5-arm64-android.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4391-e77627e8adde0ca8a62eacdce201fe20770139b5-arm-neon-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4391-e77627e8adde0ca8a62eacdce201fe20770139b5-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4391-e77627e8adde0ca8a62eacdce201fe20770139b5-x86-android.apk)
</details>

**Comment by nirvn** [comment]
FYI, this is ready for review.

**Review by suricactus — APPROVED** [review]
The screen recordings look amazing. 
Had a careful look at the code, didn't see anything that raises any flag to me.
Unfortunately the `.apk` attached didn't manage to install on my phone though.

**Comment by nirvn** [comment]
@suricactus , thanks brother, super keen to merge these PRs ASAP to test things out.

**Pull request merged**
