### PR TITLE
Hide webview items as much as possible, z-index unfriendly on Android

### LINKED ISSUE #1287: Unexpected appearance of HTML Widgets
### Reproduction Steps:

1. Open attribute form apiary (screenshot 1) > widget appears (unexpected)
2. Go to tap "Issues" (screenshot 2) > widget disappears (expected)
3. Go to tab "Help" (screenshot 3) > widget appears (expected)
4. Go to tap "General" (screenshot 4) > widget disappears (expected)
5. Open another apiary point (screenshot 5) > widget appears (unexpected)
6. Open new project (screenshot 6) > widget still appears (unexpected)

| screenshot 1 | screenshot 2 | screenshot 3 | screenshot 4 | screenshot 5 | screenshot 6 | 
|----------|----------|----------|----------|----------|----------|
| Screenshot_20200911-065523_QField Beta 1277 | Screenshot_20200911-065542_QField Beta 1277 | Screenshot_20200911-065533_QField Beta 1277 | Screenshot_20200911-065555_QField Beta 1277 | Screenshot_20200911-065603_QField Beta 1277 | Screenshot_20200911-065611_QField Beta 1277 |

**QField version:** 
Screenshots of a later PR version
Tested as well on 1.7.0 (10700992) 
(as on master, I guess)

**Project to reproduce**
Here the project I tested with:
[htmltrouble.zip](https://github.com/opengisch/QField/files/5206003/htmltrouble.zip)
(don't blame me for the bad HTML code - I botched it quickly for the demo :-) )

### PR DESCRIPTION
**Pull request by nirvn**
Partially fix #1287

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1294-4e94ac280563cb9bd0494efac36b06cb0e8b2620-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1294-4e94ac280563cb9bd0494efac36b06cb0e8b2620-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1294-4e94ac280563cb9bd0494efac36b06cb0e8b2620-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1294-4e94ac280563cb9bd0494efac36b06cb0e8b2620-x86_64.apk)

**Comment by nirvn** [comment]
@signedav , this should fix the feature form issues you spotted. It does _not_ fix the welcome screen (and other page overlays) issues, I still need to address this, in a separate PR.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1294-c6375ef7e075bc84d926a507c938f34322492e8b-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1294-c6375ef7e075bc84d926a507c938f34322492e8b-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1294-c6375ef7e075bc84d926a507c938f34322492e8b-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1294-c6375ef7e075bc84d926a507c938f34322492e8b-x86_64.apk)

**Comment by signedav** [comment]
I don't highly like the approach but I think you would have done it nicer, if there would be a possibility. Maybe you can add a little description to the PR text or the commit why we need to solve it like this and cannot just "unload" the WebView...

Regarding the second case with the open screen I wonder if the feature form needs to be open anyway when the legend drawer is opened. I guess when it's closed the html widget will disappear as well, no?

**Comment by nirvn** [comment]
@signedav , you read my mind, for the welcome (and settings, etc) screen, we'll just make sure the feature form closes.

**Review by signedav — APPROVED** [review]

**Comment by signedav** [comment]
As far as I understand it we cannot hide the `WebView` item in another way than by setting it's visibility by comparing the tab where the item is with the tab currently displayed. So good for me to merge that and I'm looking forward to the featureform-close when pressing the menu button...

**Pull request merged**
