### PR TITLE
Hide console for release builds on win

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1323 QField on Windows should not show the command prompt on regular releases](https://app.clickup.com/t/2192114/QF-1323)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a73bb8f186e738fa67cb554a54b21c3a62da65c7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2327-f8e3511df6cfcdd13b1ab73c99dbd67a459af65f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2327-f8e3511df6cfcdd13b1ab73c99dbd67a459af65f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2327-f8e3511df6cfcdd13b1ab73c99dbd67a459af65f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2327-f8e3511df6cfcdd13b1ab73c99dbd67a459af65f-x86.apk)

**Review by nirvn — APPROVED** [review]
Good polishing.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 98be72dccb634f12c16fd6b5626e4c9e6f33129f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2327-44677aa5fa2c8fa08d72b13ae1e04d2198120832-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2327-44677aa5fa2c8fa08d72b13ae1e04d2198120832-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2327-44677aa5fa2c8fa08d72b13ae1e04d2198120832-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2327-44677aa5fa2c8fa08d72b13ae1e04d2198120832-x86.apk)

**Pull request merged**
