### PR TITLE
Fix external resource widget on add new

### PR DESCRIPTION
**Pull request by signedav**
I've overseen that on the last implementation...

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-868-9223d45cf066ab63af357ca547fb15f00591d5c3-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-868-9223d45cf066ab63af357ca547fb15f00591d5c3-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-868-9223d45cf066ab63af357ca547fb15f00591d5c3-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-868-9223d45cf066ab63af357ca547fb15f00591d5c3-x86_64.apk)

**Comment by signedav** [comment]
@m-kuhn we need that fix for the open documents function (pdf, docx)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-868-46c704ad1857fbfd5158d2daa38c930f84597d14-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-868-46c704ad1857fbfd5158d2daa38c930f84597d14-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-868-46c704ad1857fbfd5158d2daa38c930f84597d14-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-868-46c704ad1857fbfd5158d2daa38c930f84597d14-x86_64.apk)

**Comment by signedav** [comment]
Customers happy

**Comment by signedav** [comment]
Do you approve @m-kuhn?

**Pull request merged**
