### PR TITLE
Target SDK 30

### LINKED ISSUE #3647: Cannot discover bluetooth devices on 2.5
### Describe the issue

When scanning for bluetooth devices, an error appears

> Scanning failed: Classic discovery cannot be started

90e2560a-9830-4c57-8cce-d758146be846

affected device:
galaxy s21 ultra android 12

works fine on 2.4.5

contact @mbernasocchi for more details

### PR DESCRIPTION
**Pull request by nirvn**
Fixes #3647

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b5f309d7ee38996b6e6fbc50dbab31d00d27a085: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3648-aeb56e12e61e762506fd60a69ed905da1b4b19bc-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3648-aeb56e12e61e762506fd60a69ed905da1b4b19bc-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3648-aeb56e12e61e762506fd60a69ed905da1b4b19bc-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3648-aeb56e12e61e762506fd60a69ed905da1b4b19bc-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3648-aeb56e12e61e762506fd60a69ed905da1b4b19bc-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3648-aeb56e12e61e762506fd60a69ed905da1b4b19bc-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3648-aeb56e12e61e762506fd60a69ed905da1b4b19bc-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3648-aeb56e12e61e762506fd60a69ed905da1b4b19bc-x86-android.apk)
</details>

**Review by m-kuhn — APPROVED** [review]

**Review by m-kuhn — CHANGES_REQUESTED** [review]
This also needs changes in the dockerfile (or .sh?) for local build

**Comment by nirvn** [comment]
@m-kuhn , probably yes. Away from laptop until tomorrow though. Can only push big buttons on my smartphone now ;)

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Merging as hotfix local build issues should follow up, thanks 🤘

**Pull request merged**
