### PR TITLE
Fix broken child feature digitizing with stylus (fixes #2079)

### LINKED ISSUE #2079: Geometry digitizing when adding child features to relationships is aborted by stylus usage
I really appreciate the ability in QField to draw new geometries by hand or stylus, by setting nodes or freehand, depending on the situation.

Also very important to me is the ability of QField to digitize new geometries when adding new child features to relationships.

Unfortunately, these two functions do not work in combination.

As soon as QField switches to digitize mode when adding a child feature, it is no longer possible to use the stylus productively. If you try to use the stylus, the digitizing process stops without an error message and no child feature is added.

### Reproduction Steps:

1. Try to add a child object to a geometry layer by clicking the plus button of the corresponding relationship widget.
2. Try to set a node with the stylus or draw freehand.

### Expected behavior:

The same behavior as when a feature is added directly to a geometry layer rather than through a relationship widget. After digitizing the geometry, you should first end up in the attribute form of the child feature and then return to the attribute form of the parent feature (Just like it works when you don't use the stylus to digitize a child feature).

### Observed behavior:

Trying to draw freehand with the stylus moves the map section, trying to set nodes with the stylus cancels the addition of a child feature. The interesting thing about the latter is that the first time you tap with the stylus, you may get a message if soft constraints were not respected. It seems that already at this moment the adding process is aborted. If all restrictions were kept, no message appears at all. Only from the second tap on, the actual digitizing process starts. Now you can set nodes with the stylus and thus create a point, a line or a polygon. However, the drawn object is apparently not saved anywhere. After the digitizing process is finished, the user is returned to the normal map view and not - as would be expected - to the attribute form of the parent feature.

### Screenshots and GIFs

https://user-images.githubusercontent.com/80956612/129181090-9bb1167a-df3e-4c0f-80c8-05ba7ca1badf.mp4

**QField version:** 1.9.6 (d5dd01)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: As far as I can tell, yes.

### PR DESCRIPTION
**Pull request by nirvn**
@lp-dj , this should fix digitizing of child feature geometries in QField using the stylus. Thanks for the reporting.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bdcf878ba949d469db74b824d629381d441a3edc:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2093-a66e6b0762bb47e0279c1ba0879ee2e74ae6d888-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2093-a66e6b0762bb47e0279c1ba0879ee2e74ae6d888-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2093-a66e6b0762bb47e0279c1ba0879ee2e74ae6d888-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2093-a66e6b0762bb47e0279c1ba0879ee2e74ae6d888-x86.apk)

**Comment by lp-dj** [comment]
@nirvn Hey, sounds great!

With such fast reactions to report bugs can even be fun ;)

Thank you very much!

"Unfortunately" I'm just in the long weekend and have left my work equipment in the office. For my personal smartphone I miss the stylus ;)

Looking forward to trying it out right at the beginning of next week. I'll be in touch!

**Review by 3nids — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bdcf878ba949d469db74b824d629381d441a3edc:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2093-f04fd09f63505bbdda5d65506ea0f6b137dc14e6-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2093-f04fd09f63505bbdda5d65506ea0f6b137dc14e6-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2093-f04fd09f63505bbdda5d65506ea0f6b137dc14e6-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2093-f04fd09f63505bbdda5d65506ea0f6b137dc14e6-x86.apk)

**Comment by lp-dj** [comment]
Ok, now you were faster than me ;) But I was happy to see that the bugfix has arrived in the current QField Dev version via the PlayStore.

This means that the digitizing process is no longer interrupted when using the stylus, great!

But I'm experiencing serious performance drops when using the stylus compared to using it by hand. In addition, I can't use the stylus for freehand drawing, and topological editing doesn't seem to be active or activatable while digitizing child objects, since the corresponding button is not displayed.

But I guess for this I should better create a new issue or are you already aware of this?

**Comment by nirvn** [comment]
@lp-dj , creating new issues for each bug with some detailed steps + test project would be great. And you're good at it too :)

**Comment by lp-dj** [comment]
Ok, I'll see when I can find the time. In the meantime, I'm first back out in the field and observe the behavior further ;)

(On occasion I would be interested in your assessment, whether you would advise against the use of the dev version in productive use because it is still too "experimental" or whether you already have a certain confidence in it. Don't know your guidelines yet, from which test status something gets into the master-dev branch.)

**Pull request merged**
