### PR TITLE
fix branching on release from master

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Do you want me to approve or review? If the later, can you add a minimal sentence to describe the rationale?

**Comment by 3nids** [comment]
review is always good.
`GIT_BRANCH` was wrong since we are on a detached head on Travis.

While checking on the docs, I realise this approach is wrong: 

> Note that for tags, git does not store the branch from which a commit was tagged.

So...we would need more git tricks to get the branch from the the tag.

I guess we'll leave it for now and branch manually.
What do you think?

**Comment by m-kuhn** [comment]
Or

```
GIT_MASTER=$(git rev-list -n1 master)

if [[ ${TRAVIS_COMMIT} = ${GIT_MASTER} ]]
```

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-901-cd0dfc8488309a5b3d9901498fa9ecae309943e2-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-901-cd0dfc8488309a5b3d9901498fa9ecae309943e2-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-901-cd0dfc8488309a5b3d9901498fa9ecae309943e2-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-901-cd0dfc8488309a5b3d9901498fa9ecae309943e2-x86_64.apk)

**Comment by 3nids** [comment]
> `GIT_MASTER=$(git rev-list -n1 master)`

is it working on Travis?

**Comment by m-kuhn** [comment]
why not?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-901-f2a919892618f25918f738372c7b3ce50ab0f4ac-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-901-f2a919892618f25918f738372c7b3ce50ab0f4ac-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-901-f2a919892618f25918f738372c7b3ce50ab0f4ac-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-901-f2a919892618f25918f738372c7b3ce50ab0f4ac-x86_64.apk)

**Pull request merged**
