### PR TITLE
QField ❤️ 🔋 and now dims screen brightness when idling

### PR DESCRIPTION
**Pull request by nirvn**
QField now dims screen brightness when idling. It's a default behavior which can be turned off via a setting toggle:
image

This should make field users _very_ happy as it can result in much, much longer battery life when keeping QField on to do tracing et cie.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 96f9bf98f73a3972972c5472b025f706c6deeb96:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-366125bbff49d46453fcb983c47a2c0ae67095bf-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-366125bbff49d46453fcb983c47a2c0ae67095bf-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-366125bbff49d46453fcb983c47a2c0ae67095bf-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-366125bbff49d46453fcb983c47a2c0ae67095bf-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8322caa2fbd51f24cace85eea787eeba17da657c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-40dd76a7e3b60e0faec11a02d5469601b362f8d5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-40dd76a7e3b60e0faec11a02d5469601b362f8d5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-40dd76a7e3b60e0faec11a02d5469601b362f8d5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-40dd76a7e3b60e0faec11a02d5469601b362f8d5-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6f55551537f2510e25381ec9eac4de1958faeb03:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-af74c119762d5db68dfa4e0e6bf90a9d362aed37-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-af74c119762d5db68dfa4e0e6bf90a9d362aed37-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-af74c119762d5db68dfa4e0e6bf90a9d362aed37-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-af74c119762d5db68dfa4e0e6bf90a9d362aed37-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1d4545154aa0f6d9dcfe1e20f709ac10af9df70d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-c28bf91842b2a481c1dc2230be0fd14893f5f02e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-c28bf91842b2a481c1dc2230be0fd14893f5f02e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-c28bf91842b2a481c1dc2230be0fd14893f5f02e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-c28bf91842b2a481c1dc2230be0fd14893f5f02e-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f196e9b5fc71e007fefee8d93f8c04bdd372f2e0:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-a17c8ebb4affc155ff1ca72b913df1929c9a9fa9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-a17c8ebb4affc155ff1ca72b913df1929c9a9fa9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-a17c8ebb4affc155ff1ca72b913df1929c9a9fa9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-a17c8ebb4affc155ff1ca72b913df1929c9a9fa9-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b0957aebca19b93dd57f27d7f4d0521e140b6a52:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-204438b24e0fcb6c6b71578b1c2fb8bcde8eb1d8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-204438b24e0fcb6c6b71578b1c2fb8bcde8eb1d8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-204438b24e0fcb6c6b71578b1c2fb8bcde8eb1d8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-204438b24e0fcb6c6b71578b1c2fb8bcde8eb1d8-x86.apk)

**Comment by nirvn** [comment]
One open question: I've set the dim time out to 20 seconds, which I think might be a bit too high. I think 10-15 seconds might me more appropriate. If anybody has a strong opinion on this, speak out :)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 308af90503d0d7b3030fc91b09669db8ec4ea979:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-19acf4e41e78fbac54a6fb550b6b73ef2bd071dd-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-19acf4e41e78fbac54a6fb550b6b73ef2bd071dd-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-19acf4e41e78fbac54a6fb550b6b73ef2bd071dd-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-19acf4e41e78fbac54a6fb550b6b73ef2bd071dd-x86.apk)

**Comment by m-kuhn** [comment]
Cool, works nicely!
One thing. I accidentally touched a button when undimming, could we intercept the first touch and only use it to undim?

**Comment by nirvn** [comment]
@m-kuhn , very good idea. Consider it done

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7963b76e1fe7c5af6cf22e986d9a8aa005a28802:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-47b23bb5c0591c4166ad26eb18ace55f583dfc46-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-47b23bb5c0591c4166ad26eb18ace55f583dfc46-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-47b23bb5c0591c4166ad26eb18ace55f583dfc46-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-47b23bb5c0591c4166ad26eb18ace55f583dfc46-x86.apk)

**Comment by m-kuhn** [comment]
Works on the canvas but still opens projects on the welcome screen or cloud projects.

**Comment by nirvn** [comment]
@m-kuhn , should work now (QML's hell that is device event handling). 

I've added a capabilities property to platform utilities so we can show the dim brightness setting only on supported platforms (Android now). I've also killed the bool supportsNativeCamera() invokable function in favor of this capabilities property.

**Comment by m-kuhn** [comment]
Starts to look really professional

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3595dfd9b58d0a7279d18cdf5cce9f8bcfb6c34a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-1b43390df47e4c1e9d5537c154cda1c150126c97-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-1b43390df47e4c1e9d5537c154cda1c150126c97-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-1b43390df47e4c1e9d5537c154cda1c150126c97-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-1b43390df47e4c1e9d5537c154cda1c150126c97-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 948ca7ccc096e5d0b2c869ae24ae563763588993:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-423f8964c1f2969517dd3ab011df3526589ba5e5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-423f8964c1f2969517dd3ab011df3526589ba5e5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-423f8964c1f2969517dd3ab011df3526589ba5e5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2016-423f8964c1f2969517dd3ab011df3526589ba5e5-x86.apk)

**Comment by nirvn** [comment]
@m-kuhn , welcome screen interactions when undimming aren't triggered now.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
