### PR TITLE
add missing enum value QgsAttributeEditorElement::AeTypeAction

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for be7ace3add1c8c48509179d563c3c158fd05a847:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-c8ca0f7be8eb4475b4f238e0d3c7120c11d67e00-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-c8ca0f7be8eb4475b4f238e0d3c7120c11d67e00-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-c8ca0f7be8eb4475b4f238e0d3c7120c11d67e00-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-c8ca0f7be8eb4475b4f238e0d3c7120c11d67e00-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for be7ace3add1c8c48509179d563c3c158fd05a847:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-096460ff863e7fce895b047f861d6d278ada7c0f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-096460ff863e7fce895b047f861d6d278ada7c0f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-096460ff863e7fce895b047f861d6d278ada7c0f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-096460ff863e7fce895b047f861d6d278ada7c0f-x86.apk)

**Review by nirvn — APPROVED** [review]

**Comment by 3nids** [comment]
@m-kuhn any idea why the vcpkg tests are skipped (but required)?

https://github.com/opengisch/QField/blob/master/.github/workflows/vcpkg.yml#L8
I don't find any reason why it's skipped

**Comment by m-kuhn** [comment]
I don't know why it says skipped, it should have said "failed", maybe because of the "tmate" step.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2733fea213a87c4a9542e9091fd4bce53b9a76ff:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-4ce48c7d31d2a9a83f7a9d8a154f839a715185ef-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-4ce48c7d31d2a9a83f7a9d8a154f839a715185ef-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-4ce48c7d31d2a9a83f7a9d8a154f839a715185ef-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-4ce48c7d31d2a9a83f7a9d8a154f839a715185ef-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0dcbfb61cd86d3898a780ba64f757e15fc2a0ee3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-acd9887cd93716379bc329ba00e5e391e1cedb2f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-acd9887cd93716379bc329ba00e5e391e1cedb2f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-acd9887cd93716379bc329ba00e5e391e1cedb2f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-acd9887cd93716379bc329ba00e5e391e1cedb2f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 30273e45b923bcae5dfdd368130a347dfa525216:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-be6a169010afbd31d0c8ccd831fc693850535618-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-be6a169010afbd31d0c8ccd831fc693850535618-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-be6a169010afbd31d0c8ccd831fc693850535618-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-be6a169010afbd31d0c8ccd831fc693850535618-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 30f5b7f98d894ab1c0417bc227430013db0f7f39:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-81226aac7cb013412e14ee31efc6ab9821e29e96-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-81226aac7cb013412e14ee31efc6ab9821e29e96-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-81226aac7cb013412e14ee31efc6ab9821e29e96-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-81226aac7cb013412e14ee31efc6ab9821e29e96-x86.apk)

**Comment by m-kuhn** [comment]
```
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,53): error C2653: 'QgsUnitTypes': is not a class or namespace name (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\qgssnappingconfig.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,67): error C2065: 'LayoutUnit': undeclared identifier (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\qgssnappingconfig.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,52): error C2923: 'QgsSettingsEntryEnumFlag': 'LayoutUnit' is not a valid template type argument for parameter 'T' (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\qgssnappingconfig.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,87): error C2990: 'QgsSettingsEntryEnumFlag': non-class template has already been declared as a class template (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\qgssnappingconfig.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,87): error C2946: explicit instantiation; 'QgsSettingsEntryEnumFlag' is not a template-class specialization (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\qgssnappingconfig.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,53): error C2653: 'QgsUnitTypes': is not a class or namespace name (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,67): error C2065: 'LayoutUnit': undeclared identifier (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,52): error C2923: 'QgsSettingsEntryEnumFlag': 'LayoutUnit' is not a valid template type argument for parameter 'T' (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,87): error C2990: 'QgsSettingsEntryEnumFlag': non-class template has already been declared as a class template (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
         C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.h(35,87): error C2946: explicit instantiation; 'QgsSettingsEntryEnumFlag' is not a template-class specialization (compiling source file C:\src\buildtrees\qgis\src\170e8aa77d-5ae686c512.clean\src\core\settings\qgssettingsregistrycore.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]

```

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6d41017865be408986ac8ea652122c0d630f4631:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-e72a3d465b6f7479c403aa9a1b342748f08d6e7a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-e72a3d465b6f7479c403aa9a1b342748f08d6e7a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-e72a3d465b6f7479c403aa9a1b342748f08d6e7a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-e72a3d465b6f7479c403aa9a1b342748f08d6e7a-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 90ae1a0146f3db4941a1c2fec28890417edf5238:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-7b0f62f18878c5abbd62e87bbae890f9f597314c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-7b0f62f18878c5abbd62e87bbae890f9f597314c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-7b0f62f18878c5abbd62e87bbae890f9f597314c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-7b0f62f18878c5abbd62e87bbae890f9f597314c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0bee7b1e7b2fe0d964b9710c1c432cc91da6c5f7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-3c536355bc5903e93de220bd4bcb7fcbe927acb8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-3c536355bc5903e93de220bd4bcb7fcbe927acb8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-3c536355bc5903e93de220bd4bcb7fcbe927acb8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-3c536355bc5903e93de220bd4bcb7fcbe927acb8-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 85189878a4db7bedc213f2684e11ae3f6048f982:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-2c2a41025faa49306d10fcc06c3a7d72f3058846-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-2c2a41025faa49306d10fcc06c3a7d72f3058846-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-2c2a41025faa49306d10fcc06c3a7d72f3058846-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2160-2c2a41025faa49306d10fcc06c3a7d72f3058846-x86.apk)

**Comment by m-kuhn** [comment]
Thanks for the support @nirvn

**Pull request merged**
