### PR TITLE
Fix using cloud information variables in all feature forms (@cloud_username etc)

### PR DESCRIPTION
**Pull request by suricactus**

### CODE REVIEW

**Review by nirvn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9dc73f352c8c195e71bee35a78041767c2689043:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1916-562c02bd7968f658c8a8e7af08b13c27e14b630d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1916-562c02bd7968f658c8a8e7af08b13c27e14b630d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1916-562c02bd7968f658c8a8e7af08b13c27e14b630d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1916-562c02bd7968f658c8a8e7af08b13c27e14b630d-x86.apk)

**Comment by signedav** [comment]
Am I right, that the issue was that the cloudInformation only has been set on featureformmodel when digitizing a new feature?

**Comment by suricactus** [comment]
Seems so. I was surprised we have feature form at so many places.

**Comment by signedav** [comment]
Yes. Sorry, for missing that.

**Comment by signedav** [comment]
And thanks.

**Pull request merged**
