### PR TITLE
Rate popup

### PR DESCRIPTION
**Pull request by marioba**
Add "Rate this app" dialog that appears after at least 30 days and 10 openings of the app.

To test this pull request you can overwrite the following parameters:
- `LauchCount`: long, number of launches of the app
- `FirstLauch`: long, unix time in seconds of the first launch of the app
- `DontShowAgain`: boolean, if true, the popup is never displayed

to pass the parameters to the app launch it using `adb shell`like this:
``` sh
adb shell am start -n ch.opengis.qfield/.QFieldActivity --el LaunchCount 10 --el FirstLaunch 1546300800 --ez DontShowAgain false
```

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-cb098bfb5050e0e5b4ff369dc4d3fd4c8a965923-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-cb098bfb5050e0e5b4ff369dc4d3fd4c8a965923-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-12097bdb086fefad168f3dfb93970695567447fe-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-12097bdb086fefad168f3dfb93970695567447fe-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-e38516e944cc8b38db152f386040550f9a053aac-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-e38516e944cc8b38db152f386040550f9a053aac-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-bd4d65a2d6b5eedfcc5a0e8bdf36918f809c10c0-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-bd4d65a2d6b5eedfcc5a0e8bdf36918f809c10c0-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-9f141364786cf8964d1cba23bd386d338198ddaa-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-510-9f141364786cf8964d1cba23bd386d338198ddaa-x86.apk)

**Comment by mbernasocchi** [comment]
@marioba I'm happy with it now, for me you can merge

**Pull request merged**
