### PR TITLE
Dynamic windows builds

### PR DESCRIPTION
**Pull request by m-kuhn**
References https://github.com/opengisch/QField/issues/4854

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 861c17d717d2de074a71597dab4584695f91dbe3: [**arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5187-761d6e0b29c0935435dfd410c3078f621ee06662-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5187-761d6e0b29c0935435dfd410c3078f621ee06662-android-arm-neon.apk)
- [x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5187-761d6e0b29c0935435dfd410c3078f621ee06662-android-x64.apk)
- [x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5187-761d6e0b29c0935435dfd410c3078f621ee06662-android-x86.apk)
- [**all access arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5187-761d6e0b29c0935435dfd410c3078f621ee06662-android-arm64.apk)
- [all access arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5187-761d6e0b29c0935435dfd410c3078f621ee06662-android-arm-neon.apk)
- [all access x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5187-761d6e0b29c0935435dfd410c3078f621ee06662-android-x64.apk)
- [all access x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5187-761d6e0b29c0935435dfd410c3078f621ee06662-android-x86.apk)
</details>

**Comment by nirvn** [comment]
Error:

`(Link target) ->  C:\builddir\vcpkg_installed\x64-windows\bin\libprotobuf-lite.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x2F8 [C:\src\qgis\x64-windows-rel\src\core\qgis_core.vcxproj]`

**Comment by m-kuhn** [comment]
https://github.com/qgis/QGIS/pull/56876

**Comment by nirvn** [comment]
@m-kuhn , OK, let me create a patch for that

**Comment by nirvn** [comment]
Second set of errors:

```
       "C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj" (default target) (21) ->
       (ClCompile target) -> 
         C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1121,11): error C2664: 'HANDLE FindFirstFileW(LPCWSTR,LPWIN32_FIND_DATAW)': cannot convert argument 1 from 'const _Elem *' to 'LPCWSTR' [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
       C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1121,11): error C2664:         with [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
       C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1121,11): error C2664:         [ [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
       C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1121,11): error C2664:             _Elem=char [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
       C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1121,11): error C2664:         ] [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
         C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1128,25): error C2665: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string': no overloaded function could convert all the argument types [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
         C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1163,17): error C2664: 'HMODULE LoadLibraryW(LPCWSTR)': cannot convert argument 1 from 'const _Elem *' to 'LPCWSTR' [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
       C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1163,17): error C2664:         with [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
       C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1163,17): error C2664:         [ [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
       C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1163,17): error C2664:             _Elem=char [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
       C:\src\qgis\src\nal-3_36_0-5a49fd0279.clean\external\mdal\mdal_utils.cpp(1163,17): error C2664:         ] [C:\src\qgis\x64-windows-rel\src\providers\mdal\provider_mdal.vcxproj]
```

**Comment by m-kuhn** [comment]
https://github.com/qgis/QGIS/pull/56980/files#diff-6de779b4c1af47f866ba627d72aa119a58a26709037e36f5b94f54d7b2d64f71R1165 ?

**Comment by nirvn** [comment]
@m-kuhn , windows built successfully; let's find a windows user out there :)

**Comment by nirvn** [comment]
@m-kuhn , sent a test build to the client.

**Comment by nirvn** [comment]
We took a different path to Rome ;)

**Pull request closed without merging**
