### PR TITLE
Add a bunch of qInfo()

### PR DESCRIPTION
**Pull request by nirvn**
Debugging like we're tool-less.

### CODE REVIEW

**Review by suricactus — APPROVED** [review]
I did the same for the cloud related parts already, nice!

**Comment by nirvn** [comment]
(we shouldn't merge this BTW, ATM just aimed at getting a windows installer)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c05962417ac89097a596a0d455c337f05115b10e: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3191-4b9e643e8ed698277b2caebc9b74c9af80ba477a-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3191-4b9e643e8ed698277b2caebc9b74c9af80ba477a-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3191-4b9e643e8ed698277b2caebc9b74c9af80ba477a-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3191-4b9e643e8ed698277b2caebc9b74c9af80ba477a-x86-android.apk)
</details>

**Comment by m-kuhn** [comment]
> I did the same for the cloud related parts already, nice!

Consistency is key 😅

> (we shouldn't merge this BTW, ATM just aimed at getting a windows installer)

Make it a draft

**Comment by m-kuhn** [comment]
@nirvn close?

**Comment by nirvn** [comment]
@m-kuhn , I was keeping it open in case it still crashes on your machine. If not, let's close.

**Comment by m-kuhn** [comment]
No more need for this

**Pull request closed without merging**
