### PR TITLE
Update vcpkg to catch Qt 6.7.2

### PR DESCRIPTION
**Pull request by nirvn**
Fails locally but I'd like to see how it goes on CI.

### CODE REVIEW

**Comment by nirvn** [comment]
@m-kuhn , one green!

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 752191bb9d9e9623899f9a37a2917a82131508d7: [**arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5405-ef04bee038ff818e5db7302d198eda1e624d6f1d-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5405-ef04bee038ff818e5db7302d198eda1e624d6f1d-android-arm-neon.apk)
- [x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5405-ef04bee038ff818e5db7302d198eda1e624d6f1d-android-x64.apk)
- [x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5405-ef04bee038ff818e5db7302d198eda1e624d6f1d-android-x86.apk)
- [**all access arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5405-ef04bee038ff818e5db7302d198eda1e624d6f1d-android-arm64.apk)
- [all access arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5405-ef04bee038ff818e5db7302d198eda1e624d6f1d-android-arm-neon.apk)
- [all access x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5405-ef04bee038ff818e5db7302d198eda1e624d6f1d-android-x64.apk)
- [all access x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5405-ef04bee038ff818e5db7302d198eda1e624d6f1d-android-x86.apk)
</details>

**Comment by m-kuhn** [comment]
Assumption: if ffmpeg is built static, openh264 needs also to be static

**Comment by nirvn** [comment]
Tested locally, lovely stuff!

**Pull request merged**
