### PR TITLE
Redo resource files

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 042163c3fccbf2418367e858a9c85b103b74fddd:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-b5b4e937f9641cfdc5b2b6efc38539620b2dc8a1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-b5b4e937f9641cfdc5b2b6efc38539620b2dc8a1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-b5b4e937f9641cfdc5b2b6efc38539620b2dc8a1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-b5b4e937f9641cfdc5b2b6efc38539620b2dc8a1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c3d479be89773bbf40ad7c2c9e7919ca2acdf922:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-8a254295f9d9f866e0d3b420060f4321615a7ec3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-8a254295f9d9f866e0d3b420060f4321615a7ec3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-8a254295f9d9f866e0d3b420060f4321615a7ec3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-8a254295f9d9f866e0d3b420060f4321615a7ec3-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 939dcfc50e191eb83ad3379f55a6b4da8803c160:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-7a1f85e201c8fc57f1db5f77508eb6d0e2b6168d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-7a1f85e201c8fc57f1db5f77508eb6d0e2b6168d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-7a1f85e201c8fc57f1db5f77508eb6d0e2b6168d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-7a1f85e201c8fc57f1db5f77508eb6d0e2b6168d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fbd491addc75aa6eaf760f54b6994e0e80a430b8:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-90e048bd4d92482cdb0f97c1312b4c1ec6924272-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-90e048bd4d92482cdb0f97c1312b4c1ec6924272-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-90e048bd4d92482cdb0f97c1312b4c1ec6924272-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-90e048bd4d92482cdb0f97c1312b4c1ec6924272-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for df762b38cfc944018cac7facd4e29456686b1e02:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-2093f02d10fc4f45f072398ceb882702d183fd9f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-2093f02d10fc4f45f072398ceb882702d183fd9f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-2093f02d10fc4f45f072398ceb882702d183fd9f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-2093f02d10fc4f45f072398ceb882702d183fd9f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 61205ac70b6cb0e486422482af5cce1d0384a491:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-7863924533dceb313850ec44ad147a69469a3f83-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-7863924533dceb313850ec44ad147a69469a3f83-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-7863924533dceb313850ec44ad147a69469a3f83-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-7863924533dceb313850ec44ad147a69469a3f83-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 639178388dd7c8328888a131cab3c8455679a93a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-4c50b01640fbaed3b50e50d267474195be2e7faf-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-4c50b01640fbaed3b50e50d267474195be2e7faf-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-4c50b01640fbaed3b50e50d267474195be2e7faf-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-4c50b01640fbaed3b50e50d267474195be2e7faf-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a0732057b325d2e3cb9fa73ae38b5f809a4a0f88:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-b65dc1cabba925ea3f8e3cd0067b1a412321a88b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-b65dc1cabba925ea3f8e3cd0067b1a412321a88b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-b65dc1cabba925ea3f8e3cd0067b1a412321a88b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-b65dc1cabba925ea3f8e3cd0067b1a412321a88b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2a6dc9e9ca065f4ea91e524b6a93a9ccd91cd39d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-ab5b3f11d1c3c5a7373b7da056340f1ef24b1913-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-ab5b3f11d1c3c5a7373b7da056340f1ef24b1913-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-ab5b3f11d1c3c5a7373b7da056340f1ef24b1913-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-ab5b3f11d1c3c5a7373b7da056340f1ef24b1913-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 609b27a41247b3f69b66e4ecd6301cf81b85e8a0:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-57bd6ec016f03301dd712ae9cb9853b5dd5ec738-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-57bd6ec016f03301dd712ae9cb9853b5dd5ec738-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-57bd6ec016f03301dd712ae9cb9853b5dd5ec738-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-57bd6ec016f03301dd712ae9cb9853b5dd5ec738-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6551301ed6715c3383ee1e66bc3f6372863f15ad:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-09252f8aa5872cf3c0541a63e16dac2e7e058391-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-09252f8aa5872cf3c0541a63e16dac2e7e058391-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-09252f8aa5872cf3c0541a63e16dac2e7e058391-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-09252f8aa5872cf3c0541a63e16dac2e7e058391-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f4d6a75207d84dda554b83cf61faed273c05baa3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-c72cad812668011d3796f399a2526e9281b83e5b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-c72cad812668011d3796f399a2526e9281b83e5b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-c72cad812668011d3796f399a2526e9281b83e5b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1481-c72cad812668011d3796f399a2526e9281b83e5b-x86.apk)

**Comment by m-kuhn** [comment]
Superseded by #1482

**Pull request closed without merging**
