### PR TITLE
Added layer CRS authid and layer name to the delta

### PR DESCRIPTION
**Pull request by suricactus**

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1441 store the CRS of the geometry in the old/new of the delta](https://app.clickup.com/t/2192114/QF-1441)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 09f36571882f009eeb634c896f7087344cef0c92:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0557c7a0c4980ae2e75061400d6ef5de88e2988a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0557c7a0c4980ae2e75061400d6ef5de88e2988a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0557c7a0c4980ae2e75061400d6ef5de88e2988a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0557c7a0c4980ae2e75061400d6ef5de88e2988a-x86.apk)

**Comment by nirvn** [comment]
@suricactus , authid will (at least) fail for user defined CRSes. Options:
- store the WKT string instead
- store a WGS84 or pseudo mercator equivalent of geometries
- ignore and go ahead with authid()

Thoughts?

**Comment by suricactus** [comment]
Good note. I think WKT variant is the best, then we will handle the rest on the server side, e.g. trying to guess the srid. @marioba opinion?

**Comment by nirvn** [comment]
I agree re WKT string. The only downside is that it'll add some weight to the delta. But that's negligible really.

**Comment by suricactus** [comment]
The best from both worlds, otherwise it will overcrowd the network and the db.

**Review by nirvn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 39788d8515a7a10d02b37925106a7fc90deef78b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-5f1ad43adb22e228453e3956b2fb45848980e62b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-5f1ad43adb22e228453e3956b2fb45848980e62b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-5f1ad43adb22e228453e3956b2fb45848980e62b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-5f1ad43adb22e228453e3956b2fb45848980e62b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2c3c537467b2f060937ee41401cc31419d543551:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0fa0b44552443bd938db1f7f13e20704fdf40551-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0fa0b44552443bd938db1f7f13e20704fdf40551-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0fa0b44552443bd938db1f7f13e20704fdf40551-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0fa0b44552443bd938db1f7f13e20704fdf40551-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 11c59c498e1aca434a5550b88b06c0931b5cfe3d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-6f0538e620736a0e6f20dce28817641327f0668c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-6f0538e620736a0e6f20dce28817641327f0668c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-6f0538e620736a0e6f20dce28817641327f0668c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-6f0538e620736a0e6f20dce28817641327f0668c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 11c59c498e1aca434a5550b88b06c0931b5cfe3d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0a333d2d7417db54fc1e6da1a98a8c52721291e0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0a333d2d7417db54fc1e6da1a98a8c52721291e0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0a333d2d7417db54fc1e6da1a98a8c52721291e0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2317-0a333d2d7417db54fc1e6da1a98a8c52721291e0-x86.apk)

**Pull request merged**
