### PR TITLE
some fixes to CMake build

### PR DESCRIPTION
**Pull request by 3nids**
and a hack for macos

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1037-b121fae3a1000ec7795656e0f80d7b4f518de299-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1037-b121fae3a1000ec7795656e0f80d7b4f518de299-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1037-b121fae3a1000ec7795656e0f80d7b4f518de299-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1037-b121fae3a1000ec7795656e0f80d7b4f518de299-x86_64.apk)

**Comment by m-kuhn** [comment]
I wonder if it's really the right thing to put this into the code or if it's a local issue (?)

Alternatively:

`cmake -DCMAKE_CXX_FLAGS="-isystem /usr/local/opt/qt/include"`

**Comment by 3nids** [comment]
hack has been removed

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1037-0eff47b105f6ef45ba0fbd165d8810b5ed141154-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1037-0eff47b105f6ef45ba0fbd165d8810b5ed141154-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1037-0eff47b105f6ef45ba0fbd165d8810b5ed141154-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1037-0eff47b105f6ef45ba0fbd165d8810b5ed141154-x86_64.apk)

**Pull request merged**
