### PR TITLE
Bump vcpkg baseline

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Broken tiff dependencies (missing `-lm` in .pc) was likely the source of the first build failure too.

If problems persist, intermediate commits (c41eae7..29f06e4) can be removed to isolate the changes in the overlay from this pull request.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a323d711936c33de1a7cac546a7724b032f42673:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-e3ab58248f678099c26a5d83289c58ff567b456c-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-e3ab58248f678099c26a5d83289c58ff567b456c-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-e3ab58248f678099c26a5d83289c58ff567b456c-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-e3ab58248f678099c26a5d83289c58ff567b456c-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9e79e0295e081519bf05c82d2a4c3b657c8c9c29:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-88db407fdf1e402d59a75ef81219bce3172e9acb-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-88db407fdf1e402d59a75ef81219bce3172e9acb-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-88db407fdf1e402d59a75ef81219bce3172e9acb-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-88db407fdf1e402d59a75ef81219bce3172e9acb-x86-android.apk)

**Comment by nirvn** [comment]
FYI I tested an android build and it worked fine.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 42ece939ecfc1b29fc751786aa1689a08888cbca:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-973db013304b651e1aacc6549c12e9ea8be4c3ac-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-973db013304b651e1aacc6549c12e9ea8be4c3ac-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-973db013304b651e1aacc6549c12e9ea8be4c3ac-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-973db013304b651e1aacc6549c12e9ea8be4c3ac-x86-android.apk)

**Comment by m-kuhn** [comment]
Windows error seems to come from openssl3, let's stick to 1.1.1 for now

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d3b5bb412bebe9a262505f019fb14c804c49573b:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-0fe9bf9529a695df3df68dd5a91dd283bff13aaa-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-0fe9bf9529a695df3df68dd5a91dd283bff13aaa-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-0fe9bf9529a695df3df68dd5a91dd283bff13aaa-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-0fe9bf9529a695df3df68dd5a91dd283bff13aaa-x86-android.apk)

**Comment by nirvn** [comment]
Tried the APKs, working like a charm.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d55afd193fc2b2853f7f9688de7df46b8c31cc4d:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-fb93d1c2337dae3c5c4584c87aabb929fd652a8b-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-fb93d1c2337dae3c5c4584c87aabb929fd652a8b-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-fb93d1c2337dae3c5c4584c87aabb929fd652a8b-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-fb93d1c2337dae3c5c4584c87aabb929fd652a8b-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bc66cf73ac172055200ed840c35144830a40ca2d:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-3571096d7c7a6fa3cc8560013607566c34a7ff22-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-3571096d7c7a6fa3cc8560013607566c34a7ff22-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-3571096d7c7a6fa3cc8560013607566c34a7ff22-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-3571096d7c7a6fa3cc8560013607566c34a7ff22-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for afe7b16d2f0b0257adfdc456f01970617d02e722:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-67e9c7cd7baeaaeb0d490190aee0df76936a328a-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-67e9c7cd7baeaaeb0d490190aee0df76936a328a-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-67e9c7cd7baeaaeb0d490190aee0df76936a328a-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-67e9c7cd7baeaaeb0d490190aee0df76936a328a-x86-android.apk)

**Comment by m-kuhn** [comment]
Converting to draft, we only want to merge this after the next release to have enough time for testing before a release

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2b2cf8d01a2602812160cdb2e5d4856b5c463ece:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-e5eba36ee14becf8ca57f85ca8eff391b283ad6c-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-e5eba36ee14becf8ca57f85ca8eff391b283ad6c-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-e5eba36ee14becf8ca57f85ca8eff391b283ad6c-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-e5eba36ee14becf8ca57f85ca8eff391b283ad6c-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a117b5f12150b9ec05c2547e78679dbcc99c4775:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-cc7db6ff40b6a011a7d9e1725322c17da46142d7-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-cc7db6ff40b6a011a7d9e1725322c17da46142d7-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-cc7db6ff40b6a011a7d9e1725322c17da46142d7-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-cc7db6ff40b6a011a7d9e1725322c17da46142d7-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 840b078f19e83ea545ca0505dd8befb658ae02fc:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-868ae6d38cb5278e41e6bfe17e78f3ffc35227c7-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-868ae6d38cb5278e41e6bfe17e78f3ffc35227c7-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-868ae6d38cb5278e41e6bfe17e78f3ffc35227c7-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-868ae6d38cb5278e41e6bfe17e78f3ffc35227c7-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 93b0a870c4e6b571bda7c3af97ca8c9c9217056f:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-9783fed528d4a3a2f83b5d7e2c742c12a77424ac-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-9783fed528d4a3a2f83b5d7e2c742c12a77424ac-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-9783fed528d4a3a2f83b5d7e2c742c12a77424ac-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2963-9783fed528d4a3a2f83b5d7e2c742c12a77424ac-x86-android.apk)

**Comment by nirvn** [comment]
Tested the arm64 APK, working.

**Comment by m-kuhn** [comment]
Superseded by #3051

**Pull request closed without merging**
