### PR TITLE
Use qmlimportscanner for all static builds

### PR DESCRIPTION
**Pull request by m-kuhn**
- The condition to use qmlimportscanner is "static qt" (not "ios")
- Use upstream Qt logic to bundle qml modules for static builds (not a local copy of it)

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f5b70349bdec508b6ebee1281d1fab6b33573f4d:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3033-7a0548f813f3f622069574689a273b9d3d775078-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3033-7a0548f813f3f622069574689a273b9d3d775078-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3033-7a0548f813f3f622069574689a273b9d3d775078-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3033-7a0548f813f3f622069574689a273b9d3d775078-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 46a1f202422ce6dfb81d430e7a2ca03045cd80f7:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3033-f19d447e9cb1c83710a47c957c3437272737b4da-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3033-f19d447e9cb1c83710a47c957c3437272737b4da-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3033-f19d447e9cb1c83710a47c957c3437272737b4da-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3033-f19d447e9cb1c83710a47c957c3437272737b4da-x86-android.apk)

**Review by nirvn — APPROVED** [review]

**Comment by 3nids** [comment]
it runs on the ipad

**Review by 3nids — APPROVED** [review]

**Comment by m-kuhn** [comment]
let's merge when 2.2.0 is released

**Comment by nirvn** [comment]
(2.2 branched off just now, this can safely be merged)

**Pull request merged**
