### PR TITLE
build as RelWithDebInfo on iOS, take 2

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3b71440faa3efcc9de8ca5d3bb488624bd1fad44:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-73dbe8d556582ddc828ffcfa3354904f9875e609-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-73dbe8d556582ddc828ffcfa3354904f9875e609-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-73dbe8d556582ddc828ffcfa3354904f9875e609-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-73dbe8d556582ddc828ffcfa3354904f9875e609-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 989de0fdbbde7a4bcf419af9d30e66f2580706bd:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-78cf372c0bae5554e597f38fddd5afe34a73e8d0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-78cf372c0bae5554e597f38fddd5afe34a73e8d0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-78cf372c0bae5554e597f38fddd5afe34a73e8d0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-78cf372c0bae5554e597f38fddd5afe34a73e8d0-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d9ed7b2a52ae90ee149726c09ff307a2aa0a44db:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-33967ff1178fd81fcad5a7e88de065e90b6b8cd0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-33967ff1178fd81fcad5a7e88de065e90b6b8cd0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-33967ff1178fd81fcad5a7e88de065e90b6b8cd0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2161-33967ff1178fd81fcad5a7e88de065e90b6b8cd0-x86.apk)

**Comment by m-kuhn** [comment]
@3nids do we still need this?

**Pull request closed without merging**
