### PR TITLE
Supergreen legend

### PR DESCRIPTION
**Pull request by suricactus**
image

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0fdc57a2eef215965f41ea1e79f79030d923022d:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1437-172a925ab03eb67eae211f4a803178000eaf6e75-arm64_v8a.apk)

Other architectures: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1437-172a925ab03eb67eae211f4a803178000eaf6e75-armv7.apk), [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1437-172a925ab03eb67eae211f4a803178000eaf6e75-x86_64.apk), [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1437-172a925ab03eb67eae211f4a803178000eaf6e75-x86.apk)

**Comment by signedav** [comment]
I definitely like it with the background.
I'm not sure about if it needs to be this covering green or if it could be something more soft. 
Another thing is that it feels a little flickering when selecting an item because of quickly going to gray and then to green. This seemed more smooth before.

**Review by signedav — APPROVED** [review]

**Comment by suricactus** [comment]
Do you have the flickering fixed?

**Comment by signedav** [comment]
@suricactus It still can be improved. Maybe having a slight fade effect on it. And the green still seems to be a little hard to me. But this is only cosmetic. 
Anyway it's nice like it is already. So I'm +1 for merge this already now.

**Pull request merged**
