### PR TITLE
Demo projects

### PR DESCRIPTION
**Pull request by marioba**
Add demo projects to QField. 
The demo projects directory is added to the favorite directories.

WIP, @mbernasocchi will update the projects with the definitive ones.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-810264bb143c5a6bba6f425f0eeeb037b9b26a3c-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-810264bb143c5a6bba6f425f0eeeb037b9b26a3c-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-d04f51ddb5b88ff06d1ddc2861181e7191d4cd70-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-d04f51ddb5b88ff06d1ddc2861181e7191d4cd70-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-e42971e7d5977b7ddf91ba0b13faa9704f65d4eb-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-e42971e7d5977b7ddf91ba0b13faa9704f65d4eb-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-f83d41c891305fcc6ab92705b8894ba80bdfc859-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-f83d41c891305fcc6ab92705b8894ba80bdfc859-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-b31684c29a34a36a6871ab2d7966450145eba6aa-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-b31684c29a34a36a6871ab2d7966450145eba6aa-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-20c0293b7587dc70bd15cc00d14f3409dddc11f1-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-20c0293b7587dc70bd15cc00d14f3409dddc11f1-x86.apk)

**Comment by m-kuhn** [comment]
Can the demo_projects folder be moved into a subfolder `ressources/demo_projects`?

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-207e8168e4dd7671cab4d2a3c084a8b8c66ef3dc-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-207e8168e4dd7671cab4d2a3c084a8b8c66ef3dc-x86.apk)

**Comment by m-kuhn** [comment]
@mbernasocchi move to subfolder and merge?

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-bbf8dc2df65020b06fe7c06c51bdb3ae8d651f89-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-bbf8dc2df65020b06fe7c06c51bdb3ae8d651f89-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-44440487a3edd3f835c7b9384d97cc5657013834-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-534-44440487a3edd3f835c7b9384d97cc5657013834-x86.apk)

**Pull request merged**
