### PR TITLE
upgrade SDK on iOS

### PR DESCRIPTION
**Pull request by 3nids**
this brings Qt 5.15 + QGIS closer to master with auth methods

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for aa7737694a9088698c271937d83ac305c4cdd2a4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-cb9afdb070747a7fcb85e9ba1bdbc942e034dfb5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-cb9afdb070747a7fcb85e9ba1bdbc942e034dfb5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-cb9afdb070747a7fcb85e9ba1bdbc942e034dfb5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-cb9afdb070747a7fcb85e9ba1bdbc942e034dfb5-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ef37e8cf1a54cf1597ace0c6305a3dd7ac15162a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-e534db21bc9985ca65571ff305125ac29d123a73-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-e534db21bc9985ca65571ff305125ac29d123a73-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-e534db21bc9985ca65571ff305125ac29d123a73-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-e534db21bc9985ca65571ff305125ac29d123a73-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e2373ebad89f96041468c9672fc0e5aa45ca1d7d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-39dd2a1b4a4a043fb6aedfb693477f3a63d1b7bc-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-39dd2a1b4a4a043fb6aedfb693477f3a63d1b7bc-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-39dd2a1b4a4a043fb6aedfb693477f3a63d1b7bc-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-39dd2a1b4a4a043fb6aedfb693477f3a63d1b7bc-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 487c3b17de3bca6e08786c8d970d2eaadbba1395:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-5f03c1309cda30e5030afcfe6e2d8a7b6370e458-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-5f03c1309cda30e5030afcfe6e2d8a7b6370e458-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-5f03c1309cda30e5030afcfe6e2d8a7b6370e458-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-5f03c1309cda30e5030afcfe6e2d8a7b6370e458-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ee6db352cd139ca470386e5b70b1a102909d9fa9:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-168f3e8e9788c357ef43febe34d8ac9257c0dd0b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-168f3e8e9788c357ef43febe34d8ac9257c0dd0b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-168f3e8e9788c357ef43febe34d8ac9257c0dd0b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-168f3e8e9788c357ef43febe34d8ac9257c0dd0b-x86.apk)

**Comment by nirvn** [comment]
@3nids , are iOS builds expected to fail in other PRs at this moment?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d593bbbba8c39bdb5f0cdd7b1bfa43dc6e218b7a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-ecb012f8397c519d03c215263e8679de3403bedd-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-ecb012f8397c519d03c215263e8679de3403bedd-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-ecb012f8397c519d03c215263e8679de3403bedd-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2154-ecb012f8397c519d03c215263e8679de3403bedd-x86.apk)

**Pull request merged**
