### PR TITLE
Workflow improvements

### PR DESCRIPTION
**Pull request by suricactus**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Ta-daaa, freshly created APKs are available:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1402-aac5aaa99c57b67b7b1bbb91648b3b7599713f67-arm64_v8a.apk)

Other architectures: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1402-aac5aaa99c57b67b7b1bbb91648b3b7599713f67-armv7.apk), [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1402-aac5aaa99c57b67b7b1bbb91648b3b7599713f67-x86_64.apk), [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1402-aac5aaa99c57b67b7b1bbb91648b3b7599713f67-x86.apk)

**Comment by qfield-fairy** [comment]
Ta-daaa, freshly created APKs are available:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1402-71a812059e8a6a7701883dd9220477478deab8cc-arm64_v8a.apk)

Other architectures: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1402-71a812059e8a6a7701883dd9220477478deab8cc-armv7.apk), [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1402-71a812059e8a6a7701883dd9220477478deab8cc-x86_64.apk), [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1402-71a812059e8a6a7701883dd9220477478deab8cc-x86.apk)

**Review by signedav — APPROVED** [review]

**Comment by 3nids** [comment]
@suricactus  Pull requests are failing since this: https://github.com/opengisch/QField/pull/1409/checks?check_run_id=1381858499#step:4:20

**Comment by suricactus** [comment]
The real cause is not the workflow themselves, but that the PR has no access to the `TX_TOKEN`.
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

I will make the translation jobs optional in such case.

https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Pull request merged**
