### PR TITLE
Copy proj.db and set PROJ_PATH

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-fff6be247d633a1a312d463d0e75c4096b908f0a-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-fff6be247d633a1a312d463d0e75c4096b908f0a-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-fff6be247d633a1a312d463d0e75c4096b908f0a-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-fff6be247d633a1a312d463d0e75c4096b908f0a-x86_64.apk)

**Comment by m-kuhn** [comment]
doesn't work yet ...

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-c4eef2d005b2f55bd4a716078104552de770ea32-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-c4eef2d005b2f55bd4a716078104552de770ea32-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-c4eef2d005b2f55bd4a716078104552de770ea32-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-c4eef2d005b2f55bd4a716078104552de770ea32-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-9d0bba35f165e82e75e3f43d1b2cdc9d251a55ad-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-9d0bba35f165e82e75e3f43d1b2cdc9d251a55ad-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-9d0bba35f165e82e75e3f43d1b2cdc9d251a55ad-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-9d0bba35f165e82e75e3f43d1b2cdc9d251a55ad-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-e614738ec4c5fcd0f0066a46fb5c80f5ef3175b6-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-e614738ec4c5fcd0f0066a46fb5c80f5ef3175b6-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-e614738ec4c5fcd0f0066a46fb5c80f5ef3175b6-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1191-e614738ec4c5fcd0f0066a46fb5c80f5ef3175b6-x86_64.apk)

**Pull request merged**
