### PR TITLE
many-to-many relation editor widget 

### PR DESCRIPTION
**Pull request by signedav**
NM relation integration built on #502

## Implementations Relation Editor Widget basics
- Display relations as widgets
- Pass to the widget the parent feature and the relation id
- Delete child feature
- Delete childs when parent is deleted
- Link parent feature to child - use the parents pk on adding as fk and hide this attribute
- "Buffer" parent when adding child and delete buffered feature on cancel
- Avoid from adding childs when parent pk is empty

## Implementations Relation Editor Widget n:m
- Pass to the widget the associated relation id
- According to the cardinality, on selcting entries one is directed to the related feature and not the association table
- According to the cardinality, the deletion appears for the user as unlinking, and she gets the info about the associated feature there
- According to the cardinality, the display message of the associated feature

## Solved by Configuration
- The display message of the association table (inluding values of the display message of the associated faeture) - solved by expression: The display message can contain expressions like `share || ' % ' || attribute( get_feature( 'people', 'fid', "people"), 'name' )` to have the info about the other parent referenced.
- On entry click it should not open the associated feature but the one from the associated table - solved by not setting cardinality

## Issues (can possibly be ignored)
- [x] Klicking Parent (Dave), creating Child (Lala Land with parent Dave), clicking same Parent (Dave) -> Lala Land not there. Clicking to other parent and then back to Dave: Lala Land is there
- [x] Random crash in multiple nested forms (possibly avoid nested forms)
- [x] Weird crash situation

## Possible additional stuff (can be done on another PR as well)
- [x] rembember values in embedded forms (on PR #502)
- [x] after adding a feature on a relationreference widget, the feature is not "selected" in the widget - see pr #586 
- [ ] recognizing widget type by data source

## Would be nice
- [ ] indicator that the list continues in the list view
- [ ] Unittests
- [x] Documentation

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-117c3370d03039ff69d366203ef1e717b603fb6a-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-117c3370d03039ff69d366203ef1e717b603fb6a-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-2989a191603a870f66114089bdd221ba2ea6683d-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-2989a191603a870f66114089bdd221ba2ea6683d-x86.apk)

**Comment by signedav** [comment]
At the moment crash when cardinality is not set to the associated layer. But I'm not sure if the display message should be built like this anyway.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-2aa08408cfb1b2945a6c8b0bb68f0b259cb956b4-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-2aa08408cfb1b2945a6c8b0bb68f0b259cb956b4-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-c3811d22190b5377e238d503bc1280afce7b97ba-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-c3811d22190b5377e238d503bc1280afce7b97ba-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-c33e113abf9bd34324257b198c5c97b90b23a958-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-c33e113abf9bd34324257b198c5c97b90b23a958-x86.apk)

**Comment by signedav** [comment]
@m-kuhn do you mind if I merge this branch into the the original PR or do you want to have a final 1m relation implementation first?

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-c0a5c7f18410550caaf9ec943681a1fd121e3a06-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-c0a5c7f18410550caaf9ec943681a1fd121e3a06-x86.apk)

**Comment by m-kuhn** [comment]
I'd rather prefer to keep them separate for now

**Comment by signedav** [comment]
Ok.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-ba2c9906198364bd24b6e406b777f7c3de6cf3e9-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-ba2c9906198364bd24b6e406b777f7c3de6cf3e9-x86.apk)

**Comment by signedav** [comment]
Test projects:
1. many-to-many relation from `land` to `people` with association table `share`: 
[middleearth_cardinality.zip](https://github.com/opengisch/QField/files/3133845/middleearth_cardinality.zip)
Tough there is an attribute `share` in `share` it's only needed as the association table and you should come directly to the `people` entry on the relation editor widget of a `land` feature.
Styling is like that:
middle-earth-cardinality

2. many-to-many relations from `land` to `people` with association table `share`, that contains used attribute `share` to tell what `share` the `people` owns of the `land` (or wants to own). There is no direct cardinality configurated - means you always come to the association table.
[middleearth_share.zip](https://github.com/opengisch/QField/files/3133846/middleearth_share.zip)
Styling like that:
middle-earth-share

**Comment by giedrioks26** [comment]
@signedav middleearth_share.zip not working on pc (debian 10), openig but not load map ant fumction not active. Can not show wath is insite relations, how it make.

**Comment by signedav** [comment]
That's weird @giedrioks26 - do it work on QField?

Here are the relation configurations:
image

**Comment by giedrioks26** [comment]
Yes, it work on QField. I'm currently testing. There are inaccuracies. I will report later. I'm working outside now.

**Comment by jhonalex06** [comment]
This works good in QField, but when i save in cache the relation and create a new point, the relation saved in cache does not appear. look this .gif:

issue

Then, i try to create a new relation and the display name of the relation does not appear. the mistake is when i select save in cache.

**Comment by jhonalex06** [comment]
This works good in QField, but when i save in cache the relation and create a new point, the relation saved in cache does not appear. look this .gif:

issue

Then, i try to create a new relation and the display name of the relation does not appear. the mistake is when i select save in cache.

**Comment by signedav** [comment]
Thanks @jhonalex06 I can reproduce that. 

Save in cache was actually not intended to be there on a relation editor widget, because there is not a value cached in the feature (because the value is stored in the child of the feature: the foreign key). If we would use this cache functionality in the relation editor widget as well, this would need to be like: cache the child ids who have an FK of the parent feature and update all of these childs, if I create a new parent feature. This would be nice. But I hope it's okay for you if it's in a future step?

**Comment by signedav** [comment]
Hi @giedrioks26
You mentioned inaccuracies. Any news on that?
Thanks!

**Comment by giedrioks26** [comment]
Hi, @signedav ! I'm sorry for the delay. Working outside took time, even traveling to Finland.

My observations:
1. When you enter an object, QField displays a message in the log window:
Screenshot_20190501-103830


2. Entering data into subform QField crashes:
Action sequence step by step:

  1. I add a "poeple" object, fill in the fields and press the plus to "poepleshares":
Screenshot_20190501-104742



  2. I fill "poeple_id", "land_id" and "share", I save, but the post does not appear:
Screenshot_20190514-144519

Screenshot_20190514-144533



  3. I repeatedly press the plus to "poepleshares" and appear in a different form ("land_id" and "share" only), which is already filled in:
Screenshot_20190514-144549

Screenshot_20190514-153510



  4. repeatedly press the plus to "poepleshares", fill in and add the "land_id" to the list. I push a plus on a white background:
Screenshot_20190514-114521


  5. I fill the house, try to add "landshares" record or save and then QField crashes:

Screenshot_20190514-114653

**Comment by signedav** [comment]
Thanks @giedrioks26 I'll analyze.

**Comment by signedav** [comment]
Here my response @giedrioks26 

To 1. I cannot reproduce that, can you give me more information? On every object? On people layer or land layer?

To 2. It's weird that you have a form where you can select the people-id, since this should be already set and be invisible. See my GIF how it should look like:
simple_add

To 2.4 and 2.5 I can reproduce the crash. Will take care.
crash

**Comment by signedav** [comment]
I've seen that I didn't pushed a fix for the forms :see_no_evil: Could you test the first part of number 2 again, please @giedrioks26

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-e475920fe503199d62e6b5f748de86e80c2df42f-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-e475920fe503199d62e6b5f748de86e80c2df42f-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-1282bc2fcf7cbe351a9364ec3baca5b52f0fdde4-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-1282bc2fcf7cbe351a9364ec3baca5b52f0fdde4-x86.apk)

**Comment by signedav** [comment]
@giedrioks26 The crash should be fixed with the rebase with original branch.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-c07979a2ce007c53b70605f20be5d58dd85b417a-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-c07979a2ce007c53b70605f20be5d58dd85b417a-x86.apk)

**Comment by giedrioks26** [comment]
test result.

These are solved:

> * I add a "poeple" object, fill in the fields and press the plus to "poepleshares":
>   [Screenshot_20190501-104742](https://user-images.githubusercontent.com/6436791/57697148-41d39e80-765b-11e9-85f4-2fe63c953844.png)
> * I fill "poeple_id", "land_id" and "share", I save, but the post does not appear:
>   [Screenshot_20190514-144519](https://user-images.githubusercontent.com/6436791/57697302-9119cf00-765b-11e9-9c3c-8a9fd40a1678.png)
>   [Screenshot_20190514-144533](https://user-images.githubusercontent.com/6436791/57697414-cfaf8980-765b-11e9-9a91-5d4159a2b1f8.png)
> * I repeatedly press the plus to "poepleshares" and appear in a different form ("land_id" and "share" only), which is already filled in:
>   [Screenshot_20190514-144549](https://user-images.githubusercontent.com/6436791/57697503-100f0780-765c-11e9-8928-f9bbd47b7829.png)
>   [Screenshot_20190514-153510](https://user-images.githubusercontent.com/6436791/57698323-156d5180-765e-11e9-8b8c-7726342ffbed.png)
> *





crashes persist:

> * repeatedly press the plus to "poepleshares", fill in and add the "land_id" to the list. I push a plus on a white background:
>   [Screenshot_20190514-114521](https://user-images.githubusercontent.com/6436791/57698521-78f77f00-765e-11e9-88ca-0b3caa6ac879.png)
> * I fill the house, try to add "landshares" record or save and then QField crashes:
>   [Screenshot_20190514-114653](https://user-images.githubusercontent.com/6436791/57698589-a3e1d300-765e-11e9-984a-ea6868cb408a.png)

**Comment by giedrioks26** [comment]
and this is not repeated:

> 1. When you enter an object, QField displays a message in the log window:
>    [Screenshot_20190501-103830](https://user-images.githubusercontent.com/6436791/57696941-bc4fee80-765a-11e9-9342-ff9df614ca83.png)

**Comment by signedav** [comment]
Thanks @giedrioks26

**Comment by giedrioks26** [comment]
> crashes persist:
> 
> > * repeatedly press the plus to "poepleshares", fill in and add the "land_id" to the list. I push a plus on a white background:
> >   [Screenshot_20190514-114521](https://user-images.githubusercontent.com/6436791/57698521-78f77f00-765e-11e9-88ca-0b3caa6ac879.png)
> > * I fill the house, try to add "landshares" record or save and then QField crashes:
> >   [Screenshot_20190514-114653](https://user-images.githubusercontent.com/6436791/57698589-a3e1d300-765e-11e9-984a-ea6868cb408a.png)

Note: crashes only when form is not filled. When I enter data, no crashes.

**Comment by signedav** [comment]
@giedrioks26 I cannot reproduce the crash. Can you give me again more info?

I do:
```
- Add people
- + in peopleshares
- + on land_id
- + on landshares
- + on people_id
- writing "dave" to name + save
- selecting "dave" in people_id + save
- writing "lalaland" on name + save
- selecting "lalaland" in land_id + save
```
Entry is in the peopleshares...

**Comment by giedrioks26** [comment]
> @giedrioks26 I cannot reproduce the crash. Can you give me again more info?

I don't understand why, but now no crashe. Maybe the fresh installation is affected

**Comment by signedav** [comment]
Okay. I'll try again with a fresh installation. Thanks.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-ad54ca39099741772e0fe5b4bfc42b7bdd14279a-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-ad54ca39099741772e0fe5b4bfc42b7bdd14279a-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-ad54ca39099741772e0fe5b4bfc42b7bdd14279a-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-ad54ca39099741772e0fe5b4bfc42b7bdd14279a-x86-5.apk))

**Comment by signedav** [comment]
Hi @giedrioks26 Since I still not succeeded with the reproduction of the crash I assume, that it has been solved by the rebaseing of the original branch.

Anyway, I set the relation editor widget in embedded forms to read only. Means you cannot go that deep down. Is this fine for you? Or do you have use cases where you need to create childrens into a newly created parent etc?

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-a2eba4bd58eb545579b3c4e76cc5d6d8d532d96b-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-a2eba4bd58eb545579b3c4e76cc5d6d8d532d96b-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-a2eba4bd58eb545579b3c4e76cc5d6d8d532d96b-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-a2eba4bd58eb545579b3c4e76cc5d6d8d532d96b-x86-5.apk))

**Comment by giedrioks26** [comment]
> Means you cannot go that deep down. Is this fine for you? Or do you have use cases where you need to create childrens into a newly created parent etc?

@signedav It's enough for me. There is no need to go deeper. However, crashes remain. Sometimes it works well. Maybe here depends on the fact that it is a test apk?

**Comment by signedav** [comment]
Shouldn't be because of test APK. But I really cannot reproduce. Do you have another step by step description or is it still like mentioned above? Could you provide logcat-traces?

**Comment by giedrioks26** [comment]
> Do you have another step by step description or is it still like mentioned above?

It happens differently.
Just enter a new name and crash:

GIF-190530_073944

There is no list left after entering a new name, empty form, objects disappear. But this is not always the case:

GIF-190530_073234

**Comment by giedrioks26** [comment]
> Could you provide logcat-traces?

[2019-05-30-07-49-08.txt](https://github.com/opengisch/QField/files/3235468/2019-05-30-07-49-08.txt)

**Comment by signedav** [comment]
Hi @giedrioks26 
Please test the APK provided soon by the @qfield-fairy 
We found something, that effected a crash at my tests. I believe it's the same thing, like in your cases.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-82c16142519ddac732eb44b048a7ae92fe138ec6-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-82c16142519ddac732eb44b048a7ae92fe138ec6-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-82c16142519ddac732eb44b048a7ae92fe138ec6-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-82c16142519ddac732eb44b048a7ae92fe138ec6-x86-5.apk))

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-a977a09d9acac7c1f59d9d73324f712f024a1105-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-a977a09d9acac7c1f59d9d73324f712f024a1105-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-a977a09d9acac7c1f59d9d73324f712f024a1105-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-568-a977a09d9acac7c1f59d9d73324f712f024a1105-x86-5.apk))

**Comment by giedrioks26** [comment]
> Please test the APK provided soon by the @qfield-fairy

I tried. Works well. But sometimes you enter the droplist after entering and all objects disappear from the map. The log shows the following information:
Screenshot_20190621-195453


After reopening qfield, corrects and works well. I can't understand the sequence that happens.

**Comment by signedav** [comment]
This happens on one of the project I uploaded above @giedrioks26 ?

**Comment by giedrioks26** [comment]
> This happens on one of the project I uploaded above @giedrioks26 ?

Yes

**Comment by signedav** [comment]
@giedrioks26 I will care for this issue beside the beta version is out.

**Pull request merged**
