### PR TITLE
Swipe up and down to show the feature form in fullscreen

### PR DESCRIPTION
**Pull request by suricactus**
Peek 2020-12-07 04-26

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
I love it.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c951449f8a19d94b97deda1b4c43ca9c6be63b76:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-63b8de6430c88b0ca59da34fa1a56e95d9a96766-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-63b8de6430c88b0ca59da34fa1a56e95d9a96766-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-63b8de6430c88b0ca59da34fa1a56e95d9a96766-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-63b8de6430c88b0ca59da34fa1a56e95d9a96766-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 325b6d7c656a793bd33876f37887aaa0982a883f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-db23b884e7ae0fb2cf8bc6aa4e63221a2b66a9d8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-db23b884e7ae0fb2cf8bc6aa4e63221a2b66a9d8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-db23b884e7ae0fb2cf8bc6aa4e63221a2b66a9d8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-db23b884e7ae0fb2cf8bc6aa4e63221a2b66a9d8-x86.apk)

**Comment by m-kuhn** [comment]
Very nice !
What happens in landscape mode?

**Comment by suricactus** [comment]
Nothing. We only allow swipe in vertical mode.

**Comment by nirvn** [comment]
Could we implement left/right swipe when in landscape mode?

**Comment by suricactus** [comment]
We can, but let's do it in a separate PR?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c22c48d7d752c1dee756b488d9c31bd46d62f146:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-ba0ef01f0bd48b34280ab9cfadcf9335010eeb93-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-ba0ef01f0bd48b34280ab9cfadcf9335010eeb93-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-ba0ef01f0bd48b34280ab9cfadcf9335010eeb93-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1456-ba0ef01f0bd48b34280ab9cfadcf9335010eeb93-x86.apk)

**Pull request merged**
