### PR TITLE
When sending/exporting datasets, insure all sidecars are taken into account

### PR DESCRIPTION
**Pull request by nirvn**
Java failures expected, local docker builds not setup yet.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 697eac2683fd8384813c582286368435c83c8045: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3393-2f65a03c6878006263fafd2014b8f07282c57a1d-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3393-2f65a03c6878006263fafd2014b8f07282c57a1d-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3393-2f65a03c6878006263fafd2014b8f07282c57a1d-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3393-2f65a03c6878006263fafd2014b8f07282c57a1d-x86-android.apk)
</details>

**Comment by nirvn** [comment]
@m-kuhn , this is ready for review.

**Comment by m-kuhn** [comment]
Are the svg patches meant to be bundled?

**Comment by nirvn** [comment]
@m-kuhn , oups, bad rebase. Cleaned up.

**Pull request merged**
