### PR TITLE
Demo Projects with UUIDs etc

### PR DESCRIPTION
**Pull request by signedav**
Use uuids instead of fids and fix display texts to support them in the relation editor.
Then there are no saving errors, what is not that nice to be there in demonstration projects.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 09aef45cca6655da7f824f973b986e1e0a756f68:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-68cbf6da47f1a723af8b15ebcd630212571d5cf3-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-68cbf6da47f1a723af8b15ebcd630212571d5cf3-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-68cbf6da47f1a723af8b15ebcd630212571d5cf3-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-68cbf6da47f1a723af8b15ebcd630212571d5cf3-x86.apk)

**Comment by signedav** [comment]
@lucienicolier Can you install the apk and have a quick look at the demo projects and if everything works nice approve? Thanks.

**Comment by signedav** [comment]
Okay, I just see that there are still troubles beside that the setup has been not that nice. 

Well  it's good to have proper projects now.
But there are still problems. Maybe with the storage.

**Comment by lucienicolier** [comment]
@signedav should I still testing or not?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0b56bb0e237c34c8cf4068a6c356fb35c3557f74:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-17917dde6d67d7a2a9a464e3217ce7eb62c822b2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-17917dde6d67d7a2a9a464e3217ce7eb62c822b2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-17917dde6d67d7a2a9a464e3217ce7eb62c822b2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-17917dde6d67d7a2a9a464e3217ce7eb62c822b2-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0b56bb0e237c34c8cf4068a6c356fb35c3557f74:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-3fb91f242d07c8da2e7757e86acb03c46fe3314e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-3fb91f242d07c8da2e7757e86acb03c46fe3314e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-3fb91f242d07c8da2e7757e86acb03c46fe3314e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1659-3fb91f242d07c8da2e7757e86acb03c46fe3314e-x86.apk)

**Review by lucienicolier — APPROVED** [review]

**Pull request merged**
