### PR TITLE
Sparkles

### PR DESCRIPTION
**Pull request by domi4484**
Falling unicorns

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1297-0b58398a51adeda1f023ffebd7159126ce6b2e49-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1297-0b58398a51adeda1f023ffebd7159126ce6b2e49-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1297-0b58398a51adeda1f023ffebd7159126ce6b2e49-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1297-0b58398a51adeda1f023ffebd7159126ce6b2e49-x86_64.apk)

**Review by m-kuhn — APPROVED** [review]
:unicorn: :gun:

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1297-e9d56671072ccdee6179dbde419ad6b36fd45e01-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1297-e9d56671072ccdee6179dbde419ad6b36fd45e01-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1297-e9d56671072ccdee6179dbde419ad6b36fd45e01-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1297-e9d56671072ccdee6179dbde419ad6b36fd45e01-x86_64.apk)

**Comment by lbartoletti** [comment]
Nice Easter egg! :unicorn: :sparkling_heart:

**Pull request merged**
