### PR TITLE
Add arm64 builds

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-eb21d131aaa9b72b4a4cb5a20f422c71408d451c-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-eb21d131aaa9b72b4a4cb5a20f422c71408d451c-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-eb21d131aaa9b72b4a4cb5a20f422c71408d451c-x86-X.apk)
 - (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-eb21d131aaa9b72b4a4cb5a20f422c71408d451c-armv7-5.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-eb21d131aaa9b72b4a4cb5a20f422c71408d451c-x86-5.apk))

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-12943de3a79fc304ac622e3cf9b4293fbd9ac288-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-12943de3a79fc304ac622e3cf9b4293fbd9ac288-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-12943de3a79fc304ac622e3cf9b4293fbd9ac288-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-12943de3a79fc304ac622e3cf9b4293fbd9ac288-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-12943de3a79fc304ac622e3cf9b4293fbd9ac288-x86-5.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-00376f3f222a637e5b7e62aa43669a7ec031ae24-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-00376f3f222a637e5b7e62aa43669a7ec031ae24-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-00376f3f222a637e5b7e62aa43669a7ec031ae24-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-00376f3f222a637e5b7e62aa43669a7ec031ae24-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-00376f3f222a637e5b7e62aa43669a7ec031ae24-x86-5.apk)

**Comment by m-kuhn** [comment]
Please double check https (e.g. wms on https)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-df2a2a99da8a71624d287860a22f01d640c77154-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-df2a2a99da8a71624d287860a22f01d640c77154-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-df2a2a99da8a71624d287860a22f01d640c77154-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-df2a2a99da8a71624d287860a22f01d640c77154-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-df2a2a99da8a71624d287860a22f01d640c77154-x86-5.apk)

**Comment by signedav** [comment]
@3nids yes

**Comment by signedav** [comment]
I receive a "Parse Error" when I try to open this APK:
https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-df2a2a99da8a71624d287860a22f01d640c77154-armv7-X.apk

"There was a problime while parsing the package"

**Comment by 3nids** [comment]
rebuilding to see

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-b18346f729bb2d08dfe2fc1e8e40136a2699ef2e-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-b18346f729bb2d08dfe2fc1e8e40136a2699ef2e-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-b18346f729bb2d08dfe2fc1e8e40136a2699ef2e-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-b18346f729bb2d08dfe2fc1e8e40136a2699ef2e-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-b18346f729bb2d08dfe2fc1e8e40136a2699ef2e-x86-5.apk)

**Comment by signedav** [comment]
Same...

**Comment by signedav** [comment]
(PS. sorry closed it accidentally)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-07935ca87a31e298e9d51ad8c123d75cb8ea2264-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-07935ca87a31e298e9d51ad8c123d75cb8ea2264-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-07935ca87a31e298e9d51ad8c123d75cb8ea2264-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-07935ca87a31e298e9d51ad8c123d75cb8ea2264-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-07935ca87a31e298e9d51ad8c123d75cb8ea2264-x86-5.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-85452ea73e10118de6716a55b20bb09176fec33f-armv7-X.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-85452ea73e10118de6716a55b20bb09176fec33f-arm64_v8a-X.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-85452ea73e10118de6716a55b20bb09176fec33f-x86-X.apk)
 - [armv7 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-85452ea73e10118de6716a55b20bb09176fec33f-armv7-5.apk)
 - [x86 (legacy build for Android 5)](https://download.opengis.ch/qfield/ci-builds/qfield-dev-625-85452ea73e10118de6716a55b20bb09176fec33f-x86-5.apk)

**Comment by signedav** [comment]
Aight. That works. Thanks @m-kuhn and @3nids

**Pull request merged**
