### PR TITLE
Simplify simple demo project

### LINKED ISSUE #1032: Make simple demo project simple again
- remove constraints
- remove Mapthemes
- remove Relations and referencing tables (maybe keep one relation hive >- area)
- simple symbology without clustering, just categorize them according the species

### PR DESCRIPTION
**Pull request by signedav**
removed map themes in simple project
removed cluster symbols in simple project
removed constraints in simple project
made less aggressive symbols and labels

resolves #1032

### CODE REVIEW

**Comment by nirvn** [comment]
Screenshot?

**Comment by signedav** [comment]
Screenshot_20200522-152209_QField

**Comment by signedav** [comment]
Screenshot_20200522-152813_QField
(No constraints)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1033-05fe8857faf3e9ea31fc664653236321a140cf8d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1033-05fe8857faf3e9ea31fc664653236321a140cf8d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1033-05fe8857faf3e9ea31fc664653236321a140cf8d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1033-05fe8857faf3e9ea31fc664653236321a140cf8d-x86_64.apk)

**Comment by mbernasocchi** [comment]
@signedav the labelling and symbols are sooo much better

**Comment by signedav** [comment]
> @signedav the labelling and symbols are sooo much better

Should I take them for the advanced project as well? 
Means labeling like here and in the advanced project same sized symbols but still clustered etc?

**Pull request merged**
