### PR TITLE
[DON'T MERGE] Scan drive to find file if no other solution works

### PR DESCRIPTION
**Pull request by marioba**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-471-72f016613eb5558fc3ad2a0f56dcb245d811443f-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-471-72f016613eb5558fc3ad2a0f56dcb245d811443f-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-471-1bb3e7227df2bd80aa26446d17d0de49cac0d5af-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-471-1bb3e7227df2bd80aa26446d17d0de49cac0d5af-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-471-8642c33be6efe07274a921000668105a0301f3f0-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-471-8642c33be6efe07274a921000668105a0301f3f0-x86.apk)

**Comment by janneke-qgis** [comment]
This works! Do you still need another log?

**Comment by marioba** [comment]
Hi @janneke-qgis , 
yes, please, send me the log with the last apk.

Thank you.

**Comment by m-kuhn** [comment]
screenshot_20190206-114609

**Comment by marioba** [comment]
@m-kuhn can you post the log please?

**Comment by m-kuhn** [comment]
@marioba do we keep this branch or delete it?

**Comment by marioba** [comment]
@m-kuhn Let's keep it until we have a definitive solution for the sd-card permissions. Some unmerged parts of this branch may be useful.

**Pull request closed without merging**
