### PR TITLE
Update SDK to sync with QGIS 3.18.1 final

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 87a30690cad77db7a98ed64ae4479741b090304c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1792-59f5037a83d39371973a5a9bcee4cc4bc2656bc9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1792-59f5037a83d39371973a5a9bcee4cc4bc2656bc9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1792-59f5037a83d39371973a5a9bcee4cc4bc2656bc9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1792-59f5037a83d39371973a5a9bcee4cc4bc2656bc9-x86.apk)

**Review by suricactus — APPROVED** [review]

**Review by suricactus — DISMISSED** [review]
nvm, the osgeo4a_version is not in the date format?

**Comment by nirvn** [comment]
@signedav , it'll be, just wanted to make sure APKs were working before hitting the OSGeo4A release button.

**Comment by suricactus** [comment]
Ok, @signedav :)

**Comment by nirvn** [comment]
@suricactus , god, how many more time will I do this mistake? :)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6b2daafc60d265f539d2665845395d304079159d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1792-07577bf94e3e56c0b066fe51ef88ad7e6ac4fec5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1792-07577bf94e3e56c0b066fe51ef88ad7e6ac4fec5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1792-07577bf94e3e56c0b066fe51ef88ad7e6ac4fec5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1792-07577bf94e3e56c0b066fe51ef88ad7e6ac4fec5-x86.apk)

**Review by suricactus — APPROVED** [review]

**Pull request merged**
