### PR TITLE
Fix serious brokenness with vertex editor mishandling ZM geometries

### LINKED ISSUE #3128: OGR error: Coordinates with non-finite values are not allowed on QGIS after on edited geometries (+ display error on QField)
Hello, 

On QField, when after adding a polygon geometry, if the geometry is modified, when saving, a part of it isn't displayed (video after). 

The geometry still exist (we can see the shape when selecting it), it is just partially visible. To make it appear totally, the whole geometry has to be changed (every vertex). 

But the worse part is on QGIS. When this geometry is synchronized, it's not possible to work with it. Every modification or copy-paste brings this error : Coordinates with non-finite values are not allowed on QGIS

error_OGR

When we check on the vertex editor, there is no coordinate error. 
vertex_editor

### Expected behavior
This error isn't recent, I saw it in many previous versions. 

https://user-images.githubusercontent.com/72577399/181425126-800c65d3-38da-4da5-92a5-33ee69dc9021.mp4

Desktop
OS: [Windows 10]
QGIS Version [3.26.0]
QFieldSync Version [4.1.1]

Mobile

Device: [Samsung Galaxy S9]
OS: [Android 11]
QField version: [master-dev (c77752)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Thank you

### PR DESCRIPTION
**Pull request by nirvn**
This PR fixes #3128 -- while QGIS should improve its handling of nan values, QField should _not_ break geometries to begin with :)

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nice, thanks!
Any chance to get a test for this (test_vertexmodel is there already)
Unrelated: Can you remove the QDebug include too, I think that's a leftover?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8c1a04fd22662b0630dee89b3aca6951c260cd63: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3130-32bd7fe52c977c4d096031ef2b9c24ea79a38396-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3130-32bd7fe52c977c4d096031ef2b9c24ea79a38396-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3130-32bd7fe52c977c4d096031ef2b9c24ea79a38396-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3130-32bd7fe52c977c4d096031ef2b9c24ea79a38396-x86-android.apk)
</details>

**Comment by nirvn** [comment]
@m-kuhn , qdebug include removed.

**Comment by nirvn** [comment]
@m-kuhn , test added, which revealed missing fixes needed in the vertex model.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
