### PR TITLE
Tiny multimedia camera

### PR DESCRIPTION
**Pull request by signedav**
Integrated very tiny version of the multimedia camera only with the basic functionality.

Couldn't test it yet with the device and needs some appearance improvements.

(Additional fix of MessageLog with later QGIS version)

### CODE REVIEW

**Comment by m-kuhn** [comment]
Uploaded test apk to https://opengis.ch/download/qfield/ci-builds/qfield-dev-221-61e3025aab9d91b9d896ebbeb33550f216509147.apk

**Comment by signedav** [comment]
It's still crashing. But I don't think for the same reasons...

**Comment by m-kuhn** [comment]
Did you add [`android.permission.CAMERA`](https://developer.android.com/reference/android/hardware/Camera.html) to AndroidManifest.xml?

**Comment by signedav** [comment]
No. I can do that. But I don't think it's the problem. Starting of Camera and making a photo works. But then later it crashes. Maybe something with destroying the Loader Component or similar.

**Comment by m-kuhn** [comment]
Does `adb logcat` print any information regarding the crash?

**Comment by signedav** [comment]
> Does adb logcat print any information regarding the crash?
If I use it correctly, then no. 

Anyway I can reproduce a crash in the debug mode on the computer, when I wan't to open the camera again after closing. But this issue does not appear on the mobile...

**Comment by mrtwister3142** [comment]
I don't want to interfere here, but the APK of the second post works for me (although it was a bit difficult to take and confirm a photo since there weren't any buttons visible)!

**Comment by m-kuhn** [comment]
> I don't want to interfere here, but the APK of the second  post works for me (although it was a bit difficult to take and confirm a  photo since there weren't any buttons visible)! BTW, while installing I was asked to grant additional permissions for camera and microphone.

Thanks a lot, that's very interesting. Which device and android version?

**Comment by mrtwister3142** [comment]
It's a Samsungs Galaxy A3 2016 with Android 7.0.

**Comment by giedrioks26** [comment]
With test apk. When you want to take a picture, it shows the mirror image and the side. Shows a good non-mirror image when captured. When I take pictures in a portrait position, there is no button to take pictures. When I take pictures of the landscape, buttons appear, but do not fit on the screen. It works. No crashes. 
Device: Blackview BV6000s, android 7.0


1.
screenshot_20180303-080848
2. mirror image, landscape, landscape, buttons not fit on the screen
screenshot_20180303-080903
3. when captured, non-mirror image
screenshot_20180303-080917
4. It works. No crashes.
screenshot_20180303-123011

**Comment by signedav** [comment]
@giedrioks26 Thanks. I can confirm that. I will care about it.

**Comment by m-kuhn** [comment]
@signedav can we leave the old implementation alive next to the new one, with a setting (which we might even autodetect)?

**Comment by signedav** [comment]
@m-kuhn Yes, this would be nice. But not for that version.
This has to be improved.
At least the bug with the mirrored output and the usability with the white buttons (they are white and depending of the device format the background on the sides of the video output is white as well).
I close this pull request and will reopen or make a new one with the fixed version.

**Comment by m-kuhn** [comment]
Thanks, @signedav can you delete the branch on the main repo?

**Pull request closed without merging**
