### PR TITLE
If a layer is empty and pressing feature list display should notify the layer is empty

### PR DESCRIPTION
**Pull request by suricactus**
Until now clicking the button does not show anything and feels broken.

Peek 2022-01-16 05-54

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1600 Make sure the field visibility is enforced when opening the form of the feature created just before](https://app.clickup.com/t/2192114/QF-1600)

**Comment by duke-nyuki** [comment]
Task linked: [QF-1601 When the layer is empty and the user requested to see the feature list display a toast that the layer is empty](https://app.clickup.com/t/2192114/QF-1601)

**Review by nirvn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 01435600aff311d20987ba26be73436de69027b3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2410-632c48a42342c2ac794ae3ca18343835d8f13e83-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2410-632c48a42342c2ac794ae3ca18343835d8f13e83-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2410-632c48a42342c2ac794ae3ca18343835d8f13e83-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2410-632c48a42342c2ac794ae3ca18343835d8f13e83-x86.apk)

**Comment by nirvn** [comment]
gradle server error fixed, restarting.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 01435600aff311d20987ba26be73436de69027b3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2410-aed82899af444586cb31a2ccbd41a638c595dee2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2410-aed82899af444586cb31a2ccbd41a638c595dee2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2410-aed82899af444586cb31a2ccbd41a638c595dee2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2410-aed82899af444586cb31a2ccbd41a638c595dee2-x86.apk)

**Pull request merged**
