### PR TITLE
Remove open image option

### PR DESCRIPTION
**Pull request by signedav**
Sine #780 is not yet working properly

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-849-f033ea9db30581fb70b8f2ae1ccd00245a667d09-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-849-f033ea9db30581fb70b8f2ae1ccd00245a667d09-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-849-f033ea9db30581fb70b8f2ae1ccd00245a667d09-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-849-f033ea9db30581fb70b8f2ae1ccd00245a667d09-x86_64.apk)

**Comment by 3nids** [comment]
so should this be backported to 1.4 ?

**Comment by mbernasocchi** [comment]
> so should this be backported to 1.4 ?

yes

**Comment by mbernasocchi** [comment]
APK tested, looks good to me. @signedav for me you can merge and backport

**Pull request merged**
