### PR TITLE
Allow hidding legend nodes

### PR DESCRIPTION
**Pull request by jhonalex06**
configuration is to be done InvisibleLayersAndGroups Qgis Plug-in

### CODE REVIEW

**Comment by mbernasocchi** [comment]
hi @jhonalex06 could you update this to current master?

**Comment by 3nids** [comment]
Hi @jhonalex06 
Any update on this?

**Comment by gacarrillor** [comment]
This PR has not been updated to master because with @m-kuhn we plan to support Hidden nodes in a different way. 

This PR works with the "Invisible Layer and Nodes" [plugin](https://github.com/gacarrillor/InvisibleLayersAndGroups). Using such plugin we configure the project, including visibility of layer and group nodes, in a way that this PR make QField understand them and hide them accordingly.

The proposed solution is to port the plugin to QGIS Core, as described in this [QEP](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/155).

In that sense, I'd ask @m-kuhn whether we should discard this PR or not.

**Comment by m-kuhn** [comment]
@gacarrillor 
I would very much like to see this functionality land in QField.
How high is the QGIS core functionality currently on your priority list?

**Comment by gacarrillor** [comment]
Do you mean that we can merge this PR for now, and when the QEP has been implemented in QGIS core we sort of make QField switch to that way? If so, I'm fine with that. 

For the QEP implementation I'd like to have a mentor :)

**Comment by m-kuhn** [comment]
Yes, I'm fine with that too.
I think it should be a minimal code overhead to keep both checks in place and provide a smooth upgrade path.

**Comment by m-kuhn** [comment]
Superseeded by #725

**Pull request closed without merging**
