### PR TITLE
Measurement tool UI/UX fixes

### PR DESCRIPTION
**Pull request by nirvn**
Before (left) vs. PR (right):
image

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-672-5ae24263523c5ef1c39d745cebaf428beb94961e-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-672-5ae24263523c5ef1c39d745cebaf428beb94961e-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-672-5ae24263523c5ef1c39d745cebaf428beb94961e-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-672-5ae24263523c5ef1c39d745cebaf428beb94961e-x86_64.apk)

**Comment by VxTedxV** [comment]
In your example, we can't see whether the cross is transparent with white borders or black with white borders. I recommend transparent in order to be more precise (to be able to see the layer under the cross where we are pointing at).

**Comment by nirvn** [comment]
It can't be transparent with white border as the cross would then disappear on white background.

**Comment by VxTedxV** [comment]
You are right. Trying black with 75% transparent ? (will appear light grey on white background)

**Pull request merged**
