### PR TITLE
Fix export redirect

### PR DESCRIPTION
**Pull request by suricactus**
- Fixes following redirects when downloading files. 
- Other minor improvements in the downloading process.
- Fixed layer feedback:

image

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bf5875ae942910beae57125a67603fae41c684fb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-b9a7823931ff260300cfbf811905d9002bc79561-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-b9a7823931ff260300cfbf811905d9002bc79561-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-b9a7823931ff260300cfbf811905d9002bc79561-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-b9a7823931ff260300cfbf811905d9002bc79561-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6a8b2125571834bf2bcd0725d1623948ce304020:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-a634264d2cafa6cac617aba155f6ae33ab100edf-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-a634264d2cafa6cac617aba155f6ae33ab100edf-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-a634264d2cafa6cac617aba155f6ae33ab100edf-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-a634264d2cafa6cac617aba155f6ae33ab100edf-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for da24c37ea7b5683cf7f94e5e68f9d35ba9af9479:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-ae0998289db2e7bac215917538dd001e33adf1a7-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-ae0998289db2e7bac215917538dd001e33adf1a7-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-ae0998289db2e7bac215917538dd001e33adf1a7-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-ae0998289db2e7bac215917538dd001e33adf1a7-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 23a1d5d2c1f175ee9c3a655fc33f45bf5429bb99:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-eeff42a7d4345aa6e91ebc85fd54e8f69db7ea3f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-eeff42a7d4345aa6e91ebc85fd54e8f69db7ea3f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-eeff42a7d4345aa6e91ebc85fd54e8f69db7ea3f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-eeff42a7d4345aa6e91ebc85fd54e8f69db7ea3f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2f1fecb8fef5949636a60dd785b1e711bc8a3166:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-67d4dfed91fa2998b5e7e74733f1dd77c6d946ac-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-67d4dfed91fa2998b5e7e74733f1dd77c6d946ac-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-67d4dfed91fa2998b5e7e74733f1dd77c6d946ac-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-67d4dfed91fa2998b5e7e74733f1dd77c6d946ac-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 146161c0efc3738a404a9f7dcad1708cd36ee16d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-bc2e7de65822877d214a8f2919e90afea4e922fa-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-bc2e7de65822877d214a8f2919e90afea4e922fa-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-bc2e7de65822877d214a8f2919e90afea4e922fa-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-bc2e7de65822877d214a8f2919e90afea4e922fa-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b2efe5af0af498fe017eec69738a2b57429496c3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-5a120ba11ee5517bc9dd5d99e35387fb66218098-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-5a120ba11ee5517bc9dd5d99e35387fb66218098-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-5a120ba11ee5517bc9dd5d99e35387fb66218098-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1793-5a120ba11ee5517bc9dd5d99e35387fb66218098-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
