### PR TITLE
Further improvements to the settings dialog

### PR DESCRIPTION
**Pull request by nirvn**
This is a follow up to #670 to address issue with text wrap. Long story short, the SwitchDelegate doesn't handle text wrapping well; the way around that is to use labels and associate those with switch-only items.

Screenshot from 2019-10-23 08-58-43

@m-kuhn , this PR also silence the warning you noted last week.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-bdc38cf22f26ce18b2df94b22687fbcc014cd07f-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-bdc38cf22f26ce18b2df94b22687fbcc014cd07f-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-bdc38cf22f26ce18b2df94b22687fbcc014cd07f-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-bdc38cf22f26ce18b2df94b22687fbcc014cd07f-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-3ac108d2d5443d39a47085afdb1c86cdc000938d-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-3ac108d2d5443d39a47085afdb1c86cdc000938d-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-3ac108d2d5443d39a47085afdb1c86cdc000938d-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-3ac108d2d5443d39a47085afdb1c86cdc000938d-x86_64.apk)

**Comment by nirvn** [comment]
@m-kuhn , OK, this is ready for review. I've added the description string you had requested in the earlier PR for the fixed scale navigation toggle too.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-fab0fb59aece73e40e5dcc5247aa18347a95d994-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-fab0fb59aece73e40e5dcc5247aa18347a95d994-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-fab0fb59aece73e40e5dcc5247aa18347a95d994-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-690-fab0fb59aece73e40e5dcc5247aa18347a95d994-x86_64.apk)

**Comment by Emic37** [comment]
@nirvn Really really good job ! Thanks ! It's a big improvement. Just one thing : the toggles are a bit too big on S10e :

Screenshot_20191023-103035_QField

**Comment by nirvn** [comment]
@Emic37 , the large size is on purpose; the larger surface area makes it easier to hit, and it seems we have the space to afford it.

Glad this has fixed your text reflow issues. Looking pretty nice on your phone :)

**Comment by Emic37** [comment]
@nirvn Ok... I never had some difficulties to enable or disable a parameters with "normal" size toggles. But why not. I have just the bad impression to have a phone for elderly person with big buttons ! 😜   But for sure, I should be able to get used to it.

However, I found a strange bug : 
When I open Qfield, I select an entity.ies to opening the attributes table(or list of entities). A push on the android back button close the forms. Normal.

Now, I open the parameters (I can change or not a parameter). The back button doesn't work. If I close the parameters using the "ok" button on the top left corner and I select again an entity.ies to display the attributes (or list of entities), the back button doesn't work anymore here too. 

Now, if before to close the parameters I open the variables tab, the back button works again and I can use it to close the parameters, or attributes tables (or lists of entities).

I can reproduce this behavior again and again. Can you reproduce it too ?

**Comment by nirvn** [comment]
@Emic37 , yeah, something's wrong with the management of focused controls in QField ATM, I pretty confident it's not settings dialog related, it's app-wide.

**Comment by Emic37** [comment]
@nirvn Ok, you're probably right. Simply, I discovered this bug with this new beta-apk and I never encountered this issue before. And when we use as me the attributes tables in fullscreen (because the form is too long... 🙄), the only way to close an entity is to close the app. It's really problematic.
Maybe you work allready on this problem or began allready to investigate ? Or should I open a new issue ?

**Comment by nirvn** [comment]
@Emic37 , you should definitively file a new issue.

**Comment by Emic37** [comment]
Thanks !

**Pull request merged**
