### PR TITLE
Further improve the metrics popup, re-asks to get a clear(er) answer

### PR DESCRIPTION
**Pull request by nirvn**
@m-kuhn , here's how it looks now:
image

I've taken the liberty to change the "we've asked already" settings key so users are re-asked with this much clearer UI.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 00f4ba2af8a2ec84e70ea388cf168a29550aa23d:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-4f92ff2f68d30d56b0f2830932e3fcedf2478aa2-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-4f92ff2f68d30d56b0f2830932e3fcedf2478aa2-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-4f92ff2f68d30d56b0f2830932e3fcedf2478aa2-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-4f92ff2f68d30d56b0f2830932e3fcedf2478aa2-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 14f72a3e797365215cce6154577b276e7aa8bfcd:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-46614f4c6af7a7af594fcaa877c556342d2918ff-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-46614f4c6af7a7af594fcaa877c556342d2918ff-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-46614f4c6af7a7af594fcaa877c556342d2918ff-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-46614f4c6af7a7af594fcaa877c556342d2918ff-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7266d3c13d59e47b2fc70756790c20612761b138:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-1fa57ddd820632500ee08c97098149161e663010-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-1fa57ddd820632500ee08c97098149161e663010-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-1fa57ddd820632500ee08c97098149161e663010-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-1fa57ddd820632500ee08c97098149161e663010-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0456ad948f4026c83767e7123101a88d36942c11:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-647bb0fb8d683d4224cf499916e50c2e2b844220-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-647bb0fb8d683d4224cf499916e50c2e2b844220-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-647bb0fb8d683d4224cf499916e50c2e2b844220-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-647bb0fb8d683d4224cf499916e50c2e2b844220-x86-android.apk)

**Comment by m-kuhn** [comment]
Looks very good, thanks.
Do we have a "learn more" link to the docs already?

**Comment by nirvn** [comment]
Do we have a doc page on this?

**Comment by m-kuhn** [comment]
@marioba ?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e3d6e4332aded61cfc40ce1e779cdc5640ebfd59:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-a9af2994197f563b3c0e3397c4b8dddbf853fa08-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-a9af2994197f563b3c0e3397c4b8dddbf853fa08-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-a9af2994197f563b3c0e3397c4b8dddbf853fa08-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2724-a9af2994197f563b3c0e3397c4b8dddbf853fa08-x86-android.apk)

**Comment by marioba** [comment]
> Do we have a doc page on this?

not yet

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
