### PR TITLE
Pop up dialogs harmonization and improvements

### PR DESCRIPTION
**Pull request by nirvn**
Dialogs now all share the same green header with the same black bold font (this includes having let go of the blue header for feature addition dialog, which offered nothing in terms of UI/UX).

image
_Feature addition_

image
_Identify features list_

image
_Feature view_

image
_Feature addition_

image
_Layer login dialog_

As seen above, in the feature addition/view dialog, the delete feature button now has a nice dark red background, to avoid confusion between the close button and the delete button; the red ties in nicely with the same color used to cancel the digitizing of a new feature (introduced in PR #630).

### CODE REVIEW

**Comment by nirvn** [comment]
This addresses issue #634 filed by @mbernasocchi .

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-2c778f6f2690b9d9a42bf839ddb86341f9cd3602-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-2c778f6f2690b9d9a42bf839ddb86341f9cd3602-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-2c778f6f2690b9d9a42bf839ddb86341f9cd3602-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-2c778f6f2690b9d9a42bf839ddb86341f9cd3602-x86-5.apk))

**Comment by nirvn** [comment]
After some more internal deliberation, I've switched the header font color to white, it matches the color used by Qt's FileDialog picker header, and IMHO nicely like with the use of white icons in the dashboard top green bar.

I'm not going to update the screenshots above.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-e5c867baa2d5e7599332202a7d1dce7f16615eb1-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-e5c867baa2d5e7599332202a7d1dce7f16615eb1-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-e5c867baa2d5e7599332202a7d1dce7f16615eb1-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-e5c867baa2d5e7599332202a7d1dce7f16615eb1-x86-5.apk))

**Comment by mbernasocchi** [comment]
> After some more internal deliberation, I've switched the header font color to white, it matches the color used by Qt's FileDialog picker header, and IMHO nicely like with the use of white icons in the dashboard top green bar. It also helps preserve focus on content of the pop ups / dialogs by being a bit more subdued than black.
> 
> I'm not going to update the screenshots above.

white is for sure nicer. 
great work

**Comment by mbernasocchi** [comment]
from a UI point of view, it is a go for a merge for me. @signedav can you do the code review please?

**Comment by m-kuhn** [comment]
Maybe we should switch to using [Pages](https://doc.qt.io/qt-5/qml-qtquick-controls2-page.html)?

**Comment by nirvn** [comment]
@m-kuhn , can you elaborate? I had changed the login object from a generic Item to a Page , worked well enough (no real difference visually but nothing broken).

**Comment by m-kuhn** [comment]
There is an explicit space for headers in the page layout and a title property, which could make the boilerplate code for this standard things smaller and unify.

page layout

Another thing is, that it inherits from [Pane](https://doc.qt.io/qt-5/qml-qtquick-controls2-pane.html)

> Pane provides a background color that matches with the application style and theme. Pane does not provide a layout of its own, but requires you to position its contents, for instance by creating a RowLayout or a ColumnLayout.

In the long run I think using more standard items like these will make our life easier

**Comment by nirvn** [comment]
@m-kuhn , updated the login dialog to use a page with the toolbar as its header.

**Comment by m-kuhn** [comment]
@nirvn what happens with the Page.title property?

**Comment by nirvn** [comment]
@m-kuhn , it's not used. We can make use of it and link the label text to the page title.

**Comment by m-kuhn** [comment]
That won't let us get rid of the label itself?

**Comment by nirvn** [comment]
Not as far as I understand it. Per the example given in Qt's doc (https://doc.qt.io/qt-5/qml-qtquick-controls2-page.html#title-prop), title is a string that can be used alongside views, not an element that'll show in the page itself.

**Comment by m-kuhn** [comment]
Ok, let's ignore it then.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-2d3e90b8441c3fd823fb14c79914f067e4acf8a1-armv7-X.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-2d3e90b8441c3fd823fb14c79914f067e4acf8a1-x86-X.apk) (Android 5: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-2d3e90b8441c3fd823fb14c79914f067e4acf8a1-armv7-5.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-640-2d3e90b8441c3fd823fb14c79914f067e4acf8a1-x86-5.apk))

**Comment by m-kuhn** [comment]
@nirvn what's your opinion about a unified header (https://github.com/opengisch/QField/compare/antennaHeight?expand=1#diff-4b82d28c8c688f21de824ddfbdd319c5)

Usage like this https://github.com/opengisch/QField/compare/antennaHeight?expand=1#diff-80686e7c3bc1e07278207b03b164906eR17-R26

It misses some more properties to dynamically change the icons and bg color of the icons, but well...

**Comment by nirvn** [comment]
Nice, nice. While it might not work for "dynamic" headers, it'd be quite useful in many cases (bad layers, layer login, settings page, etc).

For the bad layers example, we'd need to be able to hide the accept button.

**Comment by nirvn** [comment]
That unified header would be a net loss of code lines across the source tree, that's always nice.

**Comment by m-kuhn** [comment]
I'm quite confident that with some additional properties we could make it quite generic (`showAcceptButton`, `acceptButtonIcon`, `acceptButtonColor`, ...)

**Comment by nirvn** [comment]
@3nids , @signedav , could we get this approved and merged today? I'm about to go offline for a couple of days and I'd love to see these PRs merged.

**Pull request merged**
