### PR TITLE
Disabled icon semi-transparent

### PR DESCRIPTION
**Pull request by m-kuhn**
https://github.com/opengisch/QField/pull/2033#issuecomment-876942499

### CODE REVIEW

**Review by nirvn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3409b20c234bb164d41b6485af7dc290c1ac2880:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-a843129c4e117378eecaec67ae8135f8266fbd58-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-a843129c4e117378eecaec67ae8135f8266fbd58-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-a843129c4e117378eecaec67ae8135f8266fbd58-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-a843129c4e117378eecaec67ae8135f8266fbd58-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f1a98ef535ad00c03cc6b76dc8f2d07ce1ddee46:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-282e573490fdccd29f4cf43eaca805654b1143df-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-282e573490fdccd29f4cf43eaca805654b1143df-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-282e573490fdccd29f4cf43eaca805654b1143df-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-282e573490fdccd29f4cf43eaca805654b1143df-x86.apk)

**Comment by m-kuhn** [comment]
image

**Comment by nirvn** [comment]
Lovely -- getting rid of those dark gray squares is _such_ a good move.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bac737107bb71d5201c7d2626664bd9f62ad1162:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-00765da67c72f8d887729c157320115e29f1e93d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-00765da67c72f8d887729c157320115e29f1e93d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-00765da67c72f8d887729c157320115e29f1e93d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-00765da67c72f8d887729c157320115e29f1e93d-x86.apk)

**Comment by m-kuhn** [comment]
@signedav with a selection count added now

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 963fb0e1d16e2582a0f62825ae31320a88891a80:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-a2d699b2f2ceaa8f9cd532141d0b8fc58fc9f87f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-a2d699b2f2ceaa8f9cd532141d0b8fc58fc9f87f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-a2d699b2f2ceaa8f9cd532141d0b8fc58fc9f87f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2039-a2d699b2f2ceaa8f9cd532141d0b8fc58fc9f87f-x86.apk)

**Comment by signedav** [comment]
Supernice :-)

But why we don't have it on "add feature" and embedded forms? Because it will follow up later or is it not intended?

**Comment by m-kuhn** [comment]
> But why we don't have it on "add feature" and embedded forms? Because it will follow up later or is it not intended?

I think because there's duplicated code ;-P

**Comment by signedav** [comment]
Okay. So it's planned to have the same appearance everywhere.
Not sure about the efford to resolve all the duplicate code. I remember some complexity there with the bindings.  Then we might make the design change just everywhere before we find time to clean up.

**Comment by m-kuhn** [comment]
Yes, I think we should let go of the background everywhere.
I just wasn't aware of those spots, keep reporting them !

**Pull request merged**
