### PR TITLE
Update target sdk to version 26

### LINKED ISSUE #304: Update targetSdkVersion to 26 or newer
Hello Google Play Developer,

This is a reminder that **starting November 1, 2018**, updates to apps and games on Google Play **will be required to target Android Oreo (API level 26) or higher**. After this date, the Play Console will prevent you from submitting new APKs with a targetSdkVersion less than 26.

Configuring your app to target a recent API level ensures that users benefit from significant security and performance improvements, while still allowing your app to run on older Android versions (down to the minSdkVersion). 

https://developer.android.com/distribute/best-practices/develop/target-sdk

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #304

Request permissions at runtime if they are not granted but required.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-387-6412342674c1862a2dccb8c9e55d32f15ddf50b3-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-387-6412342674c1862a2dccb8c9e55d32f15ddf50b3-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-387-140d134b8b2616e24935fb4f784bf61541338455-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-387-140d134b8b2616e24935fb4f784bf61541338455-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-387-a21a5e9475fbe9102f481389a48bbd3496a66d10-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-387-a21a5e9475fbe9102f481389a48bbd3496a66d10-x86.apk)

**Comment by 3nids** [comment]
Coooool

**Pull request merged**
