### PR TITLE
QField has for too long auto-detected HTML irrespective of the settings, let's continue

### LINKED ISSUE #3135: URL not displaying correctly in last version (Display as html code and not as clickable link)
Hello

I recently update my QField app from play store, and in the last version, seems there is a different behaviour interpreting url/hyperlinks text.

In my project, I have two QEdit field in my forms, wich are not editable, where i put two different url (a GMaps Link and a Waze link). I just write for example : _http://www._ ,with no html formatting in this field.
In the previous version, the fields where clickable, perfect behaviour. 
But in the new version, QField displays the html code (as you can see in attachments) and not the clickable link .

Is it normal ?

Could you fix it in the next update ?

Thank a lot to all devs for all your work !!! 

Desktop
OS: [Windows 10]
QGIS Version [3.22.9]
QFieldSync Version [4.1.1]

Mobile
Device: [Samsung Galaxy A10]
OS: [Android 9]
QField version: [2.2.1 Capybara (137bc3 v2.2.1)]
Same on all devices i tested (Android 9 -10)

Additional information

Problem started happening recently, didn't happen in an older version of QField: [Yes]
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
Problem happens with all files and projects, not only some files or projects: [Yes]
Screenshot_20220729-114711

### PR DESCRIPTION
**Pull request by nirvn**
Fixes #3135

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 207a312c8e925e028b6da43ae674ee8e88b02242: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3137-2beb1a408d4e0833a78100a4a6ade0cd6c18cacc-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3137-2beb1a408d4e0833a78100a4a6ade0cd6c18cacc-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3137-2beb1a408d4e0833a78100a4a6ade0cd6c18cacc-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3137-2beb1a408d4e0833a78100a4a6ade0cd6c18cacc-x86-android.apk)
</details>

**Review by suricactus — APPROVED** [review]
Poor guys trying to show some HTML code as text field.

**Comment by Kinad** [comment]
> 🎉 Ta-daaa, freshly created APKs are available for [207a312](https://github.com/opengisch/QField/commit/207a312c8e925e028b6da43ae674ee8e88b02242): [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3137-2beb1a408d4e0833a78100a4a6ade0cd6c18cacc-arm64-android.apk)
> Other architectures
> 
>     * [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3137-2beb1a408d4e0833a78100a4a6ade0cd6c18cacc-arm-android.apk)
> 
>     * [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3137-2beb1a408d4e0833a78100a4a6ade0cd6c18cacc-x64-android.apk)
> 
>     * [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3137-2beb1a408d4e0833a78100a4a6ade0cd6c18cacc-x86-android.apk)

Works like a charm ! Thanks

**Comment by nirvn** [comment]
@Kinad , thanks for testing and confirming all is good now :)

**Comment by Kinad** [comment]
> 

Could you explain me the right way to do to have clickable link in QField ? Do i have to format the text field as multiline =True and html=True, and explicitely have a value like `<a href=mylink>mylink</a>` ? 

Thanks a lot for your answer

**Pull request merged**
