### PR TITLE
SD-Card warning and read only entry

### LINKED ISSUE #518: Opening secondary storage from file selector only opens the opengis.qfield folder
[Short description of problem here]

### Reproduction Steps:

1. Open QField
2. Go to Open Project
3. Select Secondary storage

### Expected behavior:

Get access to the entire SD card to look for projects.

### Observed behavior:

Only access to the "ch.opengis.qfield/files" folder and not the entire SD card.

However if I use the phone file browser to find the project file and I select the project file, QField opens it without any problems. If the project is opened this way, it will not later appear in the recent projects the next time

### Screenshots and GIFs

image

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 1.0.0 Release Candidate 5

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] since file browser changes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

### PR DESCRIPTION
**Pull request by marioba**
Screenshot_20190315-135359

Closes #518

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-522-8b10d7073b3e29d7dcb10ca81dc54f547b1c0193-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-522-8b10d7073b3e29d7dcb10ca81dc54f547b1c0193-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-522-dab1916ed1afaa9ec6c33f07d222abf08ed1f075-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-522-dab1916ed1afaa9ec6c33f07d222abf08ed1f075-x86.apk)

**Comment by VxTedxV** [comment]
"This directory **including your QGis projects & datas** will be deleted..." might be a better warning.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-522-f7011734bec564371dc876f0119b4edb3f70560f-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-522-f7011734bec564371dc876f0119b4edb3f70560f-x86.apk)

**Comment by mbernasocchi** [comment]
Works perfect thanks
Also If I try to open a project from the read-only storage, as expected, I can't create features.
tempFileForShare_20190318-194608

**Pull request merged**
