### PR TITLE
Dont write to global cmake variables

### PR DESCRIPTION
**Pull request by 3nids**
* CMAKE_AUTOUIC (not used by the project anyway, no .ui files)
* CMAKE_AUTOMOC 
* CMAKE_AUTORCC 
* CMAKE_CXX_STANDARD 
* CMAKE_CXX_STANDARD_REQUIRED

This should remove the need in the future of this kind of commit : https://github.com/opengisch/tessellate/commit/4375d9752104175c68e755055f22cf6596f6e249

Maybe it should be the same for `INCLUDE_DIRECTORIES` to `target_include_directories`
And `ADD_DEFINITION` to `target_compile_definitions `

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Ta-daaa, freshly created APKs are available:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1414-c7c48369a1d115ec461e0fea1673e8491660a9a2-arm64_v8a.apk)

Other architectures: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1414-c7c48369a1d115ec461e0fea1673e8491660a9a2-armv7.apk), [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1414-c7c48369a1d115ec461e0fea1673e8491660a9a2-x86_64.apk), [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1414-c7c48369a1d115ec461e0fea1673e8491660a9a2-x86.apk)

**Comment by m-kuhn** [comment]
Looks very good !

We normally do uppercase for cmake functions, I'd like to be coherent, that's the only thing

**Comment by 3nids** [comment]
> We normally do uppercase for cmake functions, I'd like to be coherent, that's the only thing

after discussing with @OlivierLDff, cmake new convention is to have cmake function in lowercase, mainly for better readability.
I agree it has much better readability.
once we have other work merged, I would propose to switch them all.

**Review by m-kuhn — APPROVED** [review]
Works for me.
I'd have done it in one single PR and not step by step, but that's a detail. Proceed as you like

**Comment by qfield-fairy** [comment]
Ta-daaa, freshly created APKs are available:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1414-4071babcc72b77305f218d5b7c9253ee290a1005-arm64_v8a.apk)

Other architectures: [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1414-4071babcc72b77305f218d5b7c9253ee290a1005-armv7.apk), [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1414-4071babcc72b77305f218d5b7c9253ee290a1005-x86_64.apk), [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1414-4071babcc72b77305f218d5b7c9253ee290a1005-x86.apk)

**Comment by nirvn** [comment]
A ta-daaa without :tada: is really broken, glad you took care of that too @3nids :wink:

**Pull request merged**
