### PR TITLE
Try to adjust paths

### PR DESCRIPTION
**Pull request by nirvn**
:crossed_fingers:

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 10fd2cbcf690c40969cecdf91e86392d96437d13:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-f2407711acea87208d995b0ae10a8d4bba701421-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-f2407711acea87208d995b0ae10a8d4bba701421-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-f2407711acea87208d995b0ae10a8d4bba701421-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-f2407711acea87208d995b0ae10a8d4bba701421-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1bcac6df4e3b58757b957e4fa11fb94b154018d1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-824d2ab9275442f42cd9f35c0a03aa24b763ea9c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-824d2ab9275442f42cd9f35c0a03aa24b763ea9c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-824d2ab9275442f42cd9f35c0a03aa24b763ea9c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-824d2ab9275442f42cd9f35c0a03aa24b763ea9c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ea51b13640b503592ae09769310e37cb2ecde178:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-ed4bbd0bd44593eb9c74d6abce1bb53343d984db-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-ed4bbd0bd44593eb9c74d6abce1bb53343d984db-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-ed4bbd0bd44593eb9c74d6abce1bb53343d984db-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-ed4bbd0bd44593eb9c74d6abce1bb53343d984db-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b1dabe84b33b278288cf946c7b9b97ed0323c749:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-c059b828c5e5475419238f9ec55e9aee19f96ab8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-c059b828c5e5475419238f9ec55e9aee19f96ab8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-c059b828c5e5475419238f9ec55e9aee19f96ab8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-c059b828c5e5475419238f9ec55e9aee19f96ab8-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d3faedd6637e1ca6bf36ab49e11c32685587c7e3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-bbe5fce22b22833c70a57dbadb8b9cd0ddc6b694-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-bbe5fce22b22833c70a57dbadb8b9cd0ddc6b694-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-bbe5fce22b22833c70a57dbadb8b9cd0ddc6b694-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-bbe5fce22b22833c70a57dbadb8b9cd0ddc6b694-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fa4c7fc132764db503942c16670ba6de1035d480:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-18dd5dedc94ec50345943ceab5093e492f48f1a0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-18dd5dedc94ec50345943ceab5093e492f48f1a0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-18dd5dedc94ec50345943ceab5093e492f48f1a0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-18dd5dedc94ec50345943ceab5093e492f48f1a0-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d3e2b929f32a9ed03ad854ad97687a7473f9c406:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-b03167537d9220bb8a201dbeca1a9d3e9d572ecf-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-b03167537d9220bb8a201dbeca1a9d3e9d572ecf-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-b03167537d9220bb8a201dbeca1a9d3e9d572ecf-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1496-b03167537d9220bb8a201dbeca1a9d3e9d572ecf-x86.apk)

**Comment by nirvn** [comment]
This fixes projection issues (reported as #1491) as well as broken SVG markers (unreported), regressions from the (much needed) java revamp.

**Review by m-kuhn — APPROVED** [review]
Good catch!!!

**Pull request merged**
