### PR TITLE
Add PROJ 8.0.0 to vcpkg overlay

### PR DESCRIPTION
**Pull request by nirvn**
Let's see.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2a5ef30f609435c2d686ce0bcdc938ff3c15d583:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-65e05860c3d8bf54fee6a30ed5325d3b3ed94b4c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-65e05860c3d8bf54fee6a30ed5325d3b3ed94b4c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-65e05860c3d8bf54fee6a30ed5325d3b3ed94b4c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-65e05860c3d8bf54fee6a30ed5325d3b3ed94b4c-x86.apk)

**Comment by nirvn** [comment]
APKs working great.

**Comment by nirvn** [comment]
Windows errors out building gdal. 

The console output says:
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U -f makefile.vc devinstall install INSTALLDIR=C:/src/packages/gdal_x64-windows/debug JPEG_LIB=C:\\builddir\\vcpkg_installed\\x64-windows\\debug\\lib\\jpeg.lib ZSTD_LIBS=C:\\builddir\\vcpkg_installed\\x64-windows\\debug\\lib\\zstdd.lib TIFF_LIB=C:\\builddir\\vcpkg_installed\\x64-windows\\debug\\lib\\tiffd.lib GEOTIFF_LIB=C:\\builddir\\vcpkg_installed\\x64-windows\\debug\\lib\\geotiff_d_i.lib FREEXL_LIBS=C:\\builddir\\vcpkg_installed\\x64-windows\\debug\\lib\\freexl.lib JPEG_EXTERNAL_LIB=1 JPEGDIR=C:\\builddir\\vcpkg_installed\\x64-windows\\include ZSTD_CFLAGS=-IC:\\builddir\\vcpkg_installed\\x64-windows\\include TIFF_INC=-IC:\\builddir\\vcpkg_installed\\x64-windows\\include TIFF_OPTS=-DBIGTIFF_SUPPORT GEOTIFF_INC=-IC:\\builddir\\vcpkg_installed\\x64-windows\\include FREEXL_CFLAGS=-IC:\\builddir\\vcpkg_installed\\x64-windows\\include DATADIR=C:/src/packages/gdal_x64-windows/share/gdal HTMLDIR=C:/src/packages/gdal_x64-windows/share/gdal/html GEOS_DIR=C:/builddir/vcpkg_installed/x64-windows/include "GEOS_CFLAGS=-IC:/builddir/vcpkg_installed/x64-windows/include -DHAVE_GEOS" PROJ_INCLUDE=-IC:/builddir/vcpkg_installed/x64-windows/include EXPAT_DIR=C:/builddir/vcpkg_installed/x64-windows/include EXPAT_INCLUDE=-IC:/builddir/vcpkg_installed/x64-windows/include CURL_INC=-IC:/builddir/vcpkg_installed/x64-windows/include "SQLITE_INC=-IC:/builddir/vcpkg_installed/x64-windows/include -DHAVE_SPATIALITE" PG_INC_DIR=C:/builddir/vcpkg_installed/x64-windows/include OPENJPEG_ENABLED=YES OPENJPEG_CFLAGS=-IC:/builddir/vcpkg_installed/x64-windows/include OPENJPEG_VERSION=20100 WEBP_ENABLED=YES WEBP_CFLAGS=-IC:/builddir/vcpkg_installed/x64-windows/include LIBXML2_INC=-IC:/builddir/vcpkg_installed/x64-windows/include PNG_EXTERNAL_LIB=1 PNGDIR=C:/builddir/vcpkg_installed/x64-windows/include ZLIB_INC=-IC:/builddir/vcpkg_installed/x64-windows/include ZLIB_EXTERNAL_LIB=1 ACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1 MSVC_VER=1900 WIN64=YES WITH_PDB=1 DLLBUILD=1 GDAL_HOME=C:/src/packages/gdal_x64-windows/debug CXX_CRT_FLAGS=/MDd PROJ_LIBRARY=C:/builddir/vcpkg_installed/x64-windows/debug/lib/proj_d.lib PNG_LIB=C:/builddir/vcpkg_installed/x64-windows/debug/lib/libpng16d.lib "GEOS_LIB=C:/builddir/vcpkg_installed/x64-windows/debug/lib/geos_cd.lib C:/builddir/vcpkg_installed/x64-windows/debug/lib/geosd.lib" EXPAT_LIB=C:/builddir/vcpkg_installed/x64-windows/debug/lib/libexpatd.lib "CURL_LIB=C:/builddir/vcpkg_installed/x64-windows/debug/lib/libcurl-d.lib wsock32.lib wldap32.lib winmm.lib" "SQLITE_LIB=C:/builddir/vcpkg_installed/x64-windows/debug/lib/sqlite3.lib C:/builddir/vcpkg_installed/x64-windows/debug/lib/spatialite.lib" OPENJPEG_LIB=C:/builddir/vcpkg_installed/x64-windows/debug/lib/openjp2.lib WEBP_LIBS=C:/builddir/vcpkg_installed/x64-windows/debug/lib/webpd.lib "LIBXML2_LIB=C:/builddir/vcpkg_installed/x64-windows/debug/lib/libxml2.lib C:/builddir/vcpkg_installed/x64-windows/debug/lib/iconv.lib C:/builddir/vcpkg_installed/x64-windows/debug/lib/charset.lib C:/builddir/vcpkg_installed/x64-windows/debug/lib/lzmad.lib" ZLIB_LIB=C:/builddir/vcpkg_installed/x64-windows/debug/lib/zlibd.lib "PG_LIB=C:/builddir/vcpkg_installed/x64-windows/debug/lib/libpq.lib C:/builddir/vcpkg_installed/x64-windows/debug/lib/libpgcommon.lib C:/builddir/vcpkg_installed/x64-windows/debug/lib/libpgport.lib Secur32.lib Shell32.lib Advapi32.lib Crypt32.lib Gdi32.lib C:/builddir/vcpkg_installed/x64-windows/debug/lib/libcrypto.lib C:/builddir/vcpkg_installed/x64-windows/debug/lib/libssl.lib" DEBUG=1 BUILD_TOOLS=0
    Working Directory: C:/src/buildtrees/gdal/x64-windows-dbg
    See logs for more information:
      C:\src\buildtrees\gdal\build-x64-windows-dbg-out.log
      C:\src\buildtrees\gdal\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:221 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_nmake.cmake:89 (vcpkg_build_nmake)
  D:/a/QField/QField/vcpkg/overlay/gdal/portfile.cmake:127 (vcpkg_install_nmake)
  scripts/ports.cmake:141 (include)
```

The build err.log says:
```
Microsoft (R) Program Maintenance Utility Version 14.29.30137.0
Copyright (C) Microsoft Corporation.  All rights reserved.

The syntax of the command is incorrect.
The system cannot find the file specified.
NMAKE : fatal error U1077: 'copy' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.EXE"' : return code '0x2'
Stop.
```

The last lines of the build output log says:
```
	cd ..\apps
	nmake /nologo /f makefile.vc install
	copy *.exe "C:/src/packages/gdal_x64-windows/debug\bin"
*.exe 
        0 file(s) copied.
```

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 73f08f450607f643743079f6dc8684df098c6612:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-0b56ec393d7d83e8fdbc3554be2c37a110376aaa-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-0b56ec393d7d83e8fdbc3554be2c37a110376aaa-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-0b56ec393d7d83e8fdbc3554be2c37a110376aaa-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-0b56ec393d7d83e8fdbc3554be2c37a110376aaa-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e784826d42fd057a68ca90950ce77223d38d8930:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-fc6399788d8543203a3215c183c795994ccf7b0c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-fc6399788d8543203a3215c183c795994ccf7b0c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-fc6399788d8543203a3215c183c795994ccf7b0c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-fc6399788d8543203a3215c183c795994ccf7b0c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2ee9d73262a9b43bb7a9e2477d8328b8572414b3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-aaba69e9e12f6dd8775f49448505e0e56ef14ff9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-aaba69e9e12f6dd8775f49448505e0e56ef14ff9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-aaba69e9e12f6dd8775f49448505e0e56ef14ff9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-aaba69e9e12f6dd8775f49448505e0e56ef14ff9-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 18384735ae84372cdc6371758287a2d588168aa4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-766c6b16bfa74384520e2916557cbddcd3a43734-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-766c6b16bfa74384520e2916557cbddcd3a43734-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-766c6b16bfa74384520e2916557cbddcd3a43734-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-766c6b16bfa74384520e2916557cbddcd3a43734-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fcf6e1b1a92630608012d0a2a8405234736aacb6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-05cc78aea7f4e437f971c72f8f2a2dd4ba8f0169-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-05cc78aea7f4e437f971c72f8f2a2dd4ba8f0169-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-05cc78aea7f4e437f971c72f8f2a2dd4ba8f0169-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2309-05cc78aea7f4e437f971c72f8f2a2dd4ba8f0169-x86.apk)

**Comment by nirvn** [comment]
Tested on my end, all good. QField back on PROJ 8.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
