### PR TITLE
Make demo project titles translatable

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
I heard there's someone in shouth-east asia who knows how to deal with that :stuck_out_tongue_winking_eye:

**Comment by nirvn** [comment]
We could tr() the project title when present (and not filename as title). It'd catch the demo titles we have translations for since those are strings in the source file, and likely wouldn't interfere with most project titles otherwise.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1051-75a040a6b8f8ecf92871bbcd4cf5c61d8f0c5fac-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1051-75a040a6b8f8ecf92871bbcd4cf5c61d8f0c5fac-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1051-75a040a6b8f8ecf92871bbcd4cf5c61d8f0c5fac-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1051-75a040a6b8f8ecf92871bbcd4cf5c61d8f0c5fac-x86_64.apk)

**Comment by m-kuhn** [comment]
Now you made me think.

Maybe we should either completely translate the projects (including attribute names etc) or not at all. Otherwise it's quite misleading.

**Comment by nirvn** [comment]
I agree it's an all or nothing otherwise it's confusing.

**Comment by m-kuhn** [comment]
that's it then. gotta focus on some sdk build things first.

**Pull request closed without merging**
