### PR TITLE
Load libssl differently

### PR DESCRIPTION
**Pull request by m-kuhn**
Maybe fixes Android 5?

https://stackoverflow.com/questions/25147714/qt-openssl-android

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-f9e0a4d8680cbe44af43922c6d1dd319ba424ea2-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-f9e0a4d8680cbe44af43922c6d1dd319ba424ea2-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-e30da991975ff87103a1ef16dc6b190a56d26441-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-e30da991975ff87103a1ef16dc6b190a56d26441-x86.apk)

**Comment by m-kuhn** [comment]
@saemiw @signedav 
do you have an Android 5 device to test this closeby?

**Comment by saemiw** [comment]
yes but I cant install the apk. I get an error "Parsing-Fehler - Fehler beim Parsen des Pakets".

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-523f09251a8322afaae1a48391dd656c13c006f8-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-523f09251a8322afaae1a48391dd656c13c006f8-x86.apk)

**Comment by saemiw** [comment]
still get the parsing-error

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-bfcdfbfeb768f4152c298890d0f028321eaa1720-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-bfcdfbfeb768f4152c298890d0f028321eaa1720-x86.apk)

**Comment by m-kuhn** [comment]
@saemiw I hope the latest change makes it loadable again. Sorry that I have no possibility to test myself right now.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-f422d16e634295d72c6ab1f1b76179f7837ed014-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-f422d16e634295d72c6ab1f1b76179f7837ed014-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-3521549a000fb0e20eb27bae4c5905170e45172d-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-504-3521549a000fb0e20eb27bae4c5905170e45172d-x86.apk)

**Comment by m-kuhn** [comment]
@saemiw or @signedav we are quite confident that the latest build fixes the issues. If you can test, we'll probably hit the release RC4 button and get closer to 1.0 ;)

**Comment by signedav** [comment]
Still crashing on startup. Sorry.

**Comment by m-kuhn** [comment]
Thanks @signedav which one did you try?

**Comment by signedav** [comment]
The second one I guess - I doublecheck.

**Comment by signedav** [comment]
Both are not working. 

@saemiw I think the parsing error occurs if there is already an apk in the Download folder - because of renaming etc. it cannot install on Android. But I haven't made more research on that. Just happened before on my tablet and after cleaning Download folder everything was fine again.

**Comment by mbernasocchi** [comment]
@m-kuhn https://appetize.io/app/aar180awabg0jn0zjajet5zreg?debug=true&device=nexus7&scale=50&orientation=landscape&osVersion=5.1

**Comment by mbernasocchi** [comment]
```
I/Qt      ( 3429): qt started

W/linker  ( 3429): libqandroidbearer.so: unused DT entry: type 0x1d arg 0x16df

W/linker  ( 3429): Unsupported flags DT_FLAGS_1=0x80

W/linker  ( 3429): libqandroidbearer.so: unused DT entry: type 0x6ffffffe arg 0x2844

W/linker  ( 3429): libqandroidbearer.so: unused DT entry: type 0x6fffffff arg 0x1

W/linker  ( 3429): libqtposition_android.so: unused DT entry: type 0x1d arg 0x1444

W/linker  ( 3429): Unsupported flags DT_FLAGS_1=0x80

W/linker  ( 3429): libqtposition_android.so: unused DT entry: type 0x6ffffffe arg 0x2404

W/linker  ( 3429): libqtposition_android.so: unused DT entry: type 0x6fffffff arg 0x1

I/QtPositioning( 3429): Positioning start

W/linker  ( 3429): libqtsensors_android.so: unused DT entry: type 0x1d arg 0x109d

W/linker  ( 3429): Unsupported flags DT_FLAGS_1=0x80

W/linker  ( 3429): libqtsensors_android.so: unused DT entry: type 0x6ffffffe arg 0x2004

W/linker  ( 3429): libqtsensors_android.so: unused DT entry: type 0x6fffffff arg 0x1

I/Qt      ( 3429): Sensors start

W/linker  ( 3429): libqtmedia_android.so: unused DT entry: type 0x1d arg 0x5650

W/linker  ( 3429): Unsupported flags DT_FLAGS_1=0x80

W/linker  ( 3429): libqtmedia_android.so: unused DT entry: type 0x6ffffffe arg 0x9224

W/linker  ( 3429): libqtmedia_android.so: unused DT entry: type 0x6fffffff arg 0x1

W/linker  ( 3429): libgeos.so: unused DT entry: type 0x6ffffffe arg 0x85810

W/linker  ( 3429): libgeos.so: unused DT entry: type 0x6fffffff arg 0x3

W/linker  ( 3429): libgeos_c.so: unused DT entry: type 0x6ffffffe arg 0xac24

W/linker  ( 3429): libgeos_c.so: unused DT entry: type 0x6fffffff arg 0x1

W/linker  ( 3429): libgslcblas.so: unused DT entry: type 0x6ffffffe arg 0x18b0

W/linker  ( 3429): libgslcblas.so: unused DT entry: type 0x6fffffff arg 0x2

W/linker  ( 3429): libsqlite3.so: unused DT entry: type 0x6ffffffe arg 0x39cc

W/linker  ( 3429): libsqlite3.so: unused DT entry: type 0x6fffffff arg 0x3

W/linker  ( 3429): libcharset.so: unused DT entry: type 0x6ffffffe arg 0x56c

W/linker  ( 3429): libcharset.so: unused DT entry: type 0x6fffffff arg 0x1

W/linker  ( 3429): libiconv.so: unused DT entry: type 0x6ffffffe arg 0x7b0

W/linker  ( 3429): libiconv.so: unused DT entry: type 0x6fffffff arg 0x1

W/linker  ( 3429): libfreexl.so: unused DT entry: type 0x1d arg 0x224

W/linker  ( 3429): libfreexl.so: unused DT entry: type 0x6ffffffe arg 0x81c

W/linker  ( 3429): libfreexl.so: unused DT entry: type 0x6fffffff arg 0x2

W/linker  ( 3429): libtiff.so: unused DT entry: type 0x6ffffffe arg 0x32e0

W/linker  ( 3429): libtiff.so: unused DT entry: type 0x6fffffff arg 0x2

W/linker  ( 3429): libgdal.so: unused DT entry: type 0x6ffffffe arg 0x1f3554

W/linker  ( 3429): libgdal.so: unused DT entry: type 0x6fffffff arg 0x5

W/linker  ( 3429): libproj.so: unused DT entry: type 0x6ffffffe arg 0x8020

W/linker  ( 3429): libproj.so: unused DT entry: type 0x6fffffff arg 0x2

W/linker  ( 3429): libspatialindex.so: unused DT entry: type 0x6ffffffe arg 0x47894

W/linker  ( 3429): libspatialindex.so: unused DT entry: type 0x6fffffff arg 0x3

W/linker  ( 3429): libpq.so: unused DT entry: type 0x1d arg 0x1205

W/linker  ( 3429): libpq.so: unused DT entry: type 0x6ffffffe arg 0x35fc

W/linker  ( 3429): libpq.so: unused DT entry: type 0x6fffffff arg 0x1

E/art     ( 3429): dlopen("/data/app/ch.opengis.qfield-1/lib/x86/libpq.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "X509_get_signature_nid" referenced by "libpq.so"...

E/AndroidRuntime( 3429): FATAL EXCEPTION: qtMainLoopThread

E/AndroidRuntime( 3429): Process: ch.opengis.qfield, PID: 3429

E/AndroidRuntime( 3429): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "X509_get_signature_nid" referenced by "libpq.so"...

E/AndroidRuntime( 3429): 	at java.lang.Runtime.load(Runtime.java:331)

E/AndroidRuntime( 3429): 	at java.lang.System.load(System.java:981)

E/AndroidRuntime( 3429): 	at org.qtproject.qt5.android.QtNative$3.run(QtNative.java:223)

E/AndroidRuntime( 3429): 	at org.qtproject.qt5.android.QtThread$2.run(QtThread.java:87)

E/AndroidRuntime( 3429): 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)

E/AndroidRuntime( 3429): 	at java.lang.Thread.run(Thread.java:818)

I/Process ( 3429): Sending signal. PID: 3429 SIG: 9
```

**Comment by saemiw** [comment]
> 
> 
> Still crashing on startup. Sorry.
> 
> Edit: Installation went fine...

same behaviour as noted by @signedav also on my tablet (with latest apk).

**Comment by m-kuhn** [comment]
Releases for android 5 will be shipped without ssl support for the moment, but not each of them.

**Pull request closed without merging**
