### PR TITLE
Sentry support for ios

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6deff6c2cc818d24c6d44dcac1e4ef52e833ba47: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3174-df8c1658040fb9049cd65c0eb9ed2cf64a5f6019-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3174-df8c1658040fb9049cd65c0eb9ed2cf64a5f6019-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3174-df8c1658040fb9049cd65c0eb9ed2cf64a5f6019-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3174-df8c1658040fb9049cd65c0eb9ed2cf64a5f6019-x86-android.apk)
</details>

**Comment by m-kuhn** [comment]
Tested on ios and macos

**Comment by m-kuhn** [comment]
Todo: upload debug symbols

**Comment by nirvn** [comment]
@m-kuhn , report from the field: APK works, local linux build successful.

**Comment by m-kuhn** [comment]
:heavy_check_mark:  "Nighly" build deployment from a branch
:heavy_check_mark:  Sentry push
:heavy_check_mark:  Sentry symbol upload
:negative_squared_cross_mark: Automatically enable external testers group
- [ ] Push nightlies from master (not from this branch)
- [ ] Check that sentry issues are symbolicated

**Review by nirvn — APPROVED** [review]

**Pull request merged**
