### PR TITLE
Local data picker follow ups

### PR DESCRIPTION
**Pull request by nirvn**
Commits' description self explanatory :)

Showing the cloud project name instead of the folder name (i.e. the cloud project UUID) is a nice improvement:
image

File size information added to dataset items:
image

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4ae78b006764ea908e6daa87bda8dde880955606:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-e402b1d5c7d7a8be8268463a46696bc83adec0e0-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-e402b1d5c7d7a8be8268463a46696bc83adec0e0-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-e402b1d5c7d7a8be8268463a46696bc83adec0e0-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-e402b1d5c7d7a8be8268463a46696bc83adec0e0-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8b6792a0aa6d12a72cc4965454a8bb76b480ebf3:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-7d02722f09d6154136274c800c4a3439a1ee725f-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-7d02722f09d6154136274c800c4a3439a1ee725f-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-7d02722f09d6154136274c800c4a3439a1ee725f-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-7d02722f09d6154136274c800c4a3439a1ee725f-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c9debaab8ad7205cbee6b07a2b8995c8915ad026:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-a3cf6e7c316fa52e7c3b71e60076b096978d5720-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-a3cf6e7c316fa52e7c3b71e60076b096978d5720-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-a3cf6e7c316fa52e7c3b71e60076b096978d5720-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-a3cf6e7c316fa52e7c3b71e60076b096978d5720-x86-android.apk)

**Comment by suricactus** [comment]
Not sure if moving the file extension in the details is a good move.

First, the users of QField are already have some techincal knowledge, so file extensions should not be super scary for them. Having the filename extension is something that has always been next to the filename. It brings confidence you know exactly what you are looking at and I can also imagine someone naming `data.tif` and `data.gpkg` in their project. They have to move their eyes down to read the details.

Another not super argument, but also the default Android file browsers, which have much less expectations on technical knowledge of their users, already show the file extension next to the filename.

**Comment by suricactus** [comment]
Other than my concerns about the file extension, great improvements!

Showing the project name instead of UUID is a great move, having the file size too. Have you tried to make the details below each file a little bit lighter. Being black is a bit harder to ignore them when jumping to the next file.

**Comment by nirvn** [comment]
@suricactus , your comments were addressed:
image

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c0da00c7dec9b32ca6143b1f2f812f4b22009c1b:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-0e8029ad04bd2ed5a0c60eabd4fd7cfc2b5959af-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-0e8029ad04bd2ed5a0c60eabd4fd7cfc2b5959af-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-0e8029ad04bd2ed5a0c60eabd4fd7cfc2b5959af-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2924-0e8029ad04bd2ed5a0c60eabd4fd7cfc2b5959af-x86-android.apk)

**Review by suricactus — APPROVED** [review]
Lovely! <3

**Pull request merged**
