### PR TITLE
[digitizing] remove pen icon

### PR DESCRIPTION
**Pull request by 3nids**
I'd like to propose these changes for digitizing to make it more coherent with desktop but also within the app: merge it with the "+" icon.

The button has the same effect as the add vertex button and I find current mode a bit confusing.

[screencast](https://www.youtube.com/watch?v=CeVu2Y64cww "screencast")

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-316-aed1e968481e76ed52efd9f5efca9423e6a46f4d-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-316-aed1e968481e76ed52efd9f5efca9423e6a46f4d-x86.apk)

**Comment by signedav** [comment]
+1 

I like the idea. The "pen" symbol is actually more for an "edit" than an "add" button.

**Comment by 3nids** [comment]
yes, but it was adding a vertex, so I found it confusing.
I'll wait for @m-kuhn opinion too, thanks for the input

**Comment by signedav** [comment]
An additional idea:

Do we need the X to cancel the digitization? 
Or would minus, minus, minus, minus make it as well?

image

If it's a big lack of comfort I would keep the X - but I think we could live without X as well. Or make a long press on the minus to delete all corners...

**Comment by 3nids** [comment]
not sure about this one, the long press is nice, but it's kind of a hidden feature.
We could display a message "long press to cancel" if there is some vertices removed at a high speed. That could do the job.

**Comment by signedav** [comment]
Don't you think it's intuitive like backspacing text?
But message would be okay for me as well...

**Comment by 3nids** [comment]
I'm maybe not a heavy user enough to know....

**Comment by signedav** [comment]
Me neither :-)

**Comment by m-kuhn** [comment]
Looks great to me!

Long press on + -> was proposed for going into "autocapture" mode (new vertex every x seconds/meters), so I'd rather not change to this. But maybe changing the x to a trashbin?

**Comment by signedav** [comment]
Or remove it completely. If you digitize a feature and then you want to cancel it, it's a small part of the effort to press minus, minus, minus, minus... But it's not that relevant for me.

**Comment by 3nids** [comment]
@m-kuhn it was long press on - and not +, so it could work, no?

**Comment by m-kuhn** [comment]
> @m-kuhn it was long press on - and not +, so it could work, no?

good point, yes :)

**Pull request merged**
