### PR TITLE
Add a couple more gdal-supported vector/raster formats

### LINKED ISSUE #2341: Add support for Flatgeobuff format
Format is getting more and more attention and I believe is quickly becoming mainstream. Performance is very good and file size is small enough. When opened in Qgis it also doesn’t modifiy its date and time like with gpkg which is good if you have real-time synchronisation active (Qnap, Dropbox, box etc.).

### PR DESCRIPTION
**Pull request by nirvn**
Formats are: GML, MapInfo MIF, FlatGeobuf (fixes #2341), spatialite [.db, .sqlite], and virtual vector/raster files (.vrt).

### CODE REVIEW

**Review by suricactus — APPROVED** [review]
I don't remember exactly, but I think we already tried to make these lists in `qgismobileapp.h` multiline and that failed. l58 and l59 are way too long but I guess I have to live with it :(

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for db3c0fddda194b0549f9c08d8411c84f10adaf26:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-ca46324d15d3eaea30af76cf16eb1bcbdd03784b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-ca46324d15d3eaea30af76cf16eb1bcbdd03784b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-ca46324d15d3eaea30af76cf16eb1bcbdd03784b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-ca46324d15d3eaea30af76cf16eb1bcbdd03784b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e3338b9831028ded6af262ba8e72013f96c2c5f6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-b44395182885df69b4722d7d05b5fc4fa3d991c5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-b44395182885df69b4722d7d05b5fc4fa3d991c5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-b44395182885df69b4722d7d05b5fc4fa3d991c5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-b44395182885df69b4722d7d05b5fc4fa3d991c5-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bb7c7018712c855d752b139d73939470bac79f72:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-c8fd4b94ac766ff83019d3b37092220db519af29-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-c8fd4b94ac766ff83019d3b37092220db519af29-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-c8fd4b94ac766ff83019d3b37092220db519af29-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-c8fd4b94ac766ff83019d3b37092220db519af29-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d4b1d24e042231ba889f1c07b509e20ffb81dfb4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-ff6aa0ce37ef729ebee81e274d4611debed5c6ec-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-ff6aa0ce37ef729ebee81e274d4611debed5c6ec-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-ff6aa0ce37ef729ebee81e274d4611debed5c6ec-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2350-ff6aa0ce37ef729ebee81e274d4611debed5c6ec-x86.apk)

**Pull request merged**
