### PR TITLE
Update to newer SDK with SSL support

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-389-9c8e0219d5d79299ceac79c5f7fffe1cc17b622e-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-389-9c8e0219d5d79299ceac79c5f7fffe1cc17b622e-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-389-f3576191340cd1ed3a9c5a0b8a1e11e2f3ff61a4-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-389-f3576191340cd1ed3a9c5a0b8a1e11e2f3ff61a4-x86.apk)

**Comment by m-kuhn** [comment]
Thanks for testing @soester 
I've merged this as it's an improvement in itself already, even if saving new features to postgres is still an issue.
Are you sure that this is related to the ssl connection? On first sight and without much tests on our side yet: a permission issue would seem much more likely than ssl being responsible.

**Comment by soester** [comment]
@m-kuhn This is defenitly a big improvement!

> Are you sure that this is related to the ssl connection? On first sight and without much tests on our side yet: a permission issue would seem much more likely than ssl being responsible.

Not realy sure that it is. SELECT seams to work fine, so also the connection is fine.
Let me know if you have any idea why INSERT isnt working.

Thanks for the fix!

**Comment by m-kuhn** [comment]
> Thanks for the fix!

Thanks forwarded to @PeterPetrik he did all the nasty work to get openssl to compile

>  Let me know if you have any idea why INSERT isnt working.

* Permissions on the table <- Try with the same project from QGIS
* Maybe some invalid data (widget configuration ... ) <- Have a look at the server logs

**Comment by soester** [comment]
Project works fine in QGIS.
Now getting a bit off topic:

UPDATE also works fine.

But on INSERT i get:
screenshot_2018-11-16-15-49-31

Server Log:
```
[pg-96-8]
2018-11-16T14:56:48.367071
[postgresql-9.6]
[5-1] user=my_user,db=my_db,app=[unknown],client=my_ip LOG: connection authorized: user=my_user database=my_db SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)
```

**Pull request merged**
