### PR TITLE
Temporary fix to avoid a dead QField on iOS

### PR DESCRIPTION
**Pull request by nirvn**
If this works, IMHO it'd be good to push a QField 2.4.5 version on iOS to fix the crasher (reported here https://github.com/opengisch/QField/issues/3545)

The downside is that it'll disable vertical grid shift on iOS until we have a proper fix. IMHO, a "price" worth paying.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e9137e47820c30fd727218ca512fe2b43a4c503e: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3547-b8ec41c22757cf986f7726b2b184d1faed0021d9-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3547-b8ec41c22757cf986f7726b2b184d1faed0021d9-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3547-b8ec41c22757cf986f7726b2b184d1faed0021d9-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3547-b8ec41c22757cf986f7726b2b184d1faed0021d9-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3547-b8ec41c22757cf986f7726b2b184d1faed0021d9-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3547-b8ec41c22757cf986f7726b2b184d1faed0021d9-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3547-b8ec41c22757cf986f7726b2b184d1faed0021d9-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3547-b8ec41c22757cf986f7726b2b184d1faed0021d9-x86-android.apk)
</details>

**Comment by m-kuhn** [comment]
If someone can confirm I'm happy to merge

**Review by 3nids — APPROVED** [review]
works on iOS 16.1

**Comment by 3nids** [comment]
are the changes in the workflow meant to be???

**Comment by qfield-fairy** [comment]
The backport to `release-2_4` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 3cdd1f24a... Fix iOS deployment
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/core/qgismobileapp.cpp
[backport-3547-to-release-2_4 49c2ea030] Temporary fix to avoid a dead QField on iOS
 Author: Mathieu Pellerin <nirvn.asia@gmail.com>
 Date: Mon Oct 31 16:30:28 2022 +0700
 1 file changed, 2 insertions(+)
Auto-merging .github/workflows/ios.yml
CONFLICT (content): Merge conflict in .github/workflows/ios.yml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release-2_4 release-2_4
# Navigate to the new working tree
cd .worktrees/backport-release-2_4
# Create a new branch
git switch --create backport-3547-to-release-2_4
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 74bd9b18cff0ccd7d210f390307028dbbf204a95,3cdd1f24ab84c1ddb71251deb840b9f386bbe1c4
# Push it to GitHub
git push --set-upstream origin backport-3547-to-release-2_4
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release-2_4
```
Then, create a pull request where the `base` branch is `release-2_4` and the `compare`/`head` branch is `backport-3547-to-release-2_4`.

**Comment by mbernasocchi** [comment]
backported in #3553

**Pull request merged**
