### PR TITLE
Fix rubber band drawing precision issues

### LINKED ISSUE #1626: Polygon preview error while editing small polygons
While digitizing or editing small polygons on Qfield, the preview is not displayed correctly. Exact digitizing and snapping is almost impossible. After finishing the object, geometry is displayed correctly. Problem disappears when editing bigger polygons (several m2).

### Reproduction Steps:

1. Create any polygon layer on qgis
2. transfer to qfield with Sync
3. Start editing
4. create small polygon-feature (< 2 m2)

### Expected behavior:

correct preview of polygon geometry during editing

### Observed behavior:

polygon preview doesn't match the points and is flickering / jumping

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]
* QGis 3.4.8, Qfield 1.7.8
 
Screenshot_20210127-194004_QField

### PR DESCRIPTION
**Pull request by nirvn**
This PR fixes rubber band drawing issues / precision when digitizing on small areas with CRSes having a large number of pre-decimals digits. It fixes #1626 (and likely a few more).

Before:

https://user-images.githubusercontent.com/1728657/106092400-ced8c700-6160-11eb-8e75-067ab713a2e2.mp4

PR:

https://user-images.githubusercontent.com/1728657/106092554-18291680-6161-11eb-9911-25e4a3e080fe.mp4

Since QField can be as precise as 1mm via NMEA devices, we might as well make sure our rubber bands can too :wink:

### CODE REVIEW

**Comment by nirvn** [comment]
Second part of this PR in: fixing feature highlight drawing precision issue.

Before:

https://user-images.githubusercontent.com/1728657/106107847-056f0b80-617a-11eb-871f-9ca06b4e2d21.mp4

PR:

https://user-images.githubusercontent.com/1728657/106107857-0869fc00-617a-11eb-8d31-850bcae9f9d3.mp4

This fixes a long-standing issue report in #119 by @donkey12345.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 84fb0c98bdaa0322d7ef80aa29265b8595641fa0:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-a735c9fb8ba3f9914c9cc2cca4996c260c589850-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-a735c9fb8ba3f9914c9cc2cca4996c260c589850-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-a735c9fb8ba3f9914c9cc2cca4996c260c589850-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-a735c9fb8ba3f9914c9cc2cca4996c260c589850-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7b360284b05c7d8df63fd1dd20ed9fcba0cfe9d8:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-9743046e53a64f9d452e9055af593c4364094412-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-9743046e53a64f9d452e9055af593c4364094412-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-9743046e53a64f9d452e9055af593c4364094412-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-9743046e53a64f9d452e9055af593c4364094412-x86.apk)

**Review by suricactus — APPROVED** [review]

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 680149e4f2e38d17bc09fe03266c0f7f2eb5b6f4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-b6dff7ad2a28ba7bdc87bee89cf90f8c2d9e110d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-b6dff7ad2a28ba7bdc87bee89cf90f8c2d9e110d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-b6dff7ad2a28ba7bdc87bee89cf90f8c2d9e110d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1629-b6dff7ad2a28ba7bdc87bee89cf90f8c2d9e110d-x86.apk)

**Pull request merged**
