### PR TITLE
Homogenize badges

### PR DESCRIPTION
**Pull request by m-kuhn**
Capitalization and wording

### CODE REVIEW

**Comment by suricactus** [comment]
TBH I like the in Title Case more.

**Comment by m-kuhn** [comment]
Me too, but can releases and read the docs be adjusted?

**Comment by suricactus** [comment]
[Read the Docs](https://docs.qfield.org/)
[Discussions](https://github.com/opengisch/QField/discussions)
[Sponsor](https://github.com/sponsors/opengisch)
[Contribute](#contribute)
[Release](https://github.com/opengisch/QField/releases)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1b46c000a34b5c5b3499ab8da260aa6a6fb8ada6:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-aaa253539192098a90530b798439a4d6ebb7f838-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-aaa253539192098a90530b798439a4d6ebb7f838-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-aaa253539192098a90530b798439a4d6ebb7f838-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-aaa253539192098a90530b798439a4d6ebb7f838-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-aaa253539192098a90530b798439a4d6ebb7f838-x86-android.apk)

**Comment by m-kuhn** [comment]
Lgtm but I canno add a review 😅

**Comment by suricactus** [comment]
tbh I would prefer without fancy colors, just gray background?

[Read the Docs](https://docs.qfield.org/)
[Discussions](https://github.com/opengisch/QField/discussions)
[Sponsor](https://github.com/sponsors/opengisch)
[Contribute](#contribute)
[Release](https://github.com/opengisch/QField/releases)

**Comment by m-kuhn** [comment]
I like!

**Comment by suricactus** [comment]
image

**Review by suricactus — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 77252be845812c22a122270c3abe11928d2f9531:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-d5f7e80350f16274be097badf4d7c1ee3c33200a-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-d5f7e80350f16274be097badf4d7c1ee3c33200a-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-d5f7e80350f16274be097badf4d7c1ee3c33200a-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-d5f7e80350f16274be097badf4d7c1ee3c33200a-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2876-d5f7e80350f16274be097badf4d7c1ee3c33200a-x86-android.apk)

**Pull request merged**
