### PR TITLE
Fix missing translations

### PR DESCRIPTION
**Pull request by nirvn**
Hopefully fixes issue #1754.

@m-kuhn , as you hinted, it seems QObject::tr() doesn't work out in providing translatable strings here. The hopeful part is me hoping QCoreApplication::translate() will work better :smile:

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 68178cb2975d833bb66b41d0a35f01fa7c23ca06:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-2326cc2774a1e62f5e72710b2bd1940db9fad4a2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-2326cc2774a1e62f5e72710b2bd1940db9fad4a2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-2326cc2774a1e62f5e72710b2bd1940db9fad4a2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-2326cc2774a1e62f5e72710b2bd1940db9fad4a2-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 52f8f98b60ee7079d7e36e77146b4752464cb46e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-95888833247ce060ee573cb2fc524249fc46bfce-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-95888833247ce060ee573cb2fc524249fc46bfce-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-95888833247ce060ee573cb2fc524249fc46bfce-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-95888833247ce060ee573cb2fc524249fc46bfce-x86.apk)

**Comment by m-kuhn** [comment]
I don't think this will work either.
Translating only works after we have initialized the QTranslator with a locale (in main.cpp), while this code is executed earlier on library load.
Better move the code directly into the data() method (local static variable).

**Comment by nirvn** [comment]
@m-kuhn , makes sense. Thanks for the TIL moment :+1:

**Comment by nirvn** [comment]
@m-kuhn , comment addressed.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 62b82a27ae2c912d28d777400663c83b51a3f892:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-5798a1b50225971628f76ef22caae8620c86ade5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-5798a1b50225971628f76ef22caae8620c86ade5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-5798a1b50225971628f76ef22caae8620c86ade5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1755-5798a1b50225971628f76ef22caae8620c86ade5-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
