### PR TITLE
Align apk naming

### PR DESCRIPTION
**Pull request by m-kuhn**
Currently apks are named like `qfield-v3.1.7-arm64-android.apk`, whereas other platforms do `qfield-v3.1.7-windows-x64.exe`

This changes the scheme and it's now `qfield-v3.1.7-android-arm64.apk` which also makes the android artifacts appear next to each other on the release page

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b4ca4f0c12ba8d09fa40293a798a8910f28dbaee: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4945-beab0737418fb4fe3a0e5d03bb0bc2471e7de572-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4945-beab0737418fb4fe3a0e5d03bb0bc2471e7de572-android-arm-neon.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4945-beab0737418fb4fe3a0e5d03bb0bc2471e7de572-android-x64.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4945-beab0737418fb4fe3a0e5d03bb0bc2471e7de572-android-x86.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4945-beab0737418fb4fe3a0e5d03bb0bc2471e7de572-android-arm64.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4945-beab0737418fb4fe3a0e5d03bb0bc2471e7de572-android-arm-neon.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4945-beab0737418fb4fe3a0e5d03bb0bc2471e7de572-android-x64.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4945-beab0737418fb4fe3a0e5d03bb0bc2471e7de572-android-x86.apk)
</details>

**Review by nirvn — APPROVED** [review]
@m-kuhn , approved.

**Comment by nirvn** [comment]
@m-kuhn , this'll require a change in required checks on master.

**Comment by nirvn** [comment]
Oh, while we're at it, even though we are likely going to end up removing the pointless .ipa from release pages, could be good to align the filename too:

image

**Pull request merged**
