### PR TITLE
Give focus to identify form to close it

### LINKED ISSUE #138: QField closes by closing the Identify window
When I try to close the identify results window, it does not close or close QField

Action from which this happens:
1. Press the screen to identify the object. Identity window pops up. Press the "back" button. The identification window closes. Everything is fine here.

2. Touch screen to identify the object. Identity window pops up. Press the grid and mark the layer or go to the next layer. I close the layers window. Press the "back" button to hide the identification window. QField closes.

**QField version:** 0.10

### PR DESCRIPTION
**Pull request by 3nids**
fix #138

### CODE REVIEW

**Comment by m-kuhn** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-241-35c66e0221825cae3738b926cda7cebf7583bc60-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-241-35c66e0221825cae3738b926cda7cebf7583bc60-x86.apk)

**Comment by saemiw** [comment]
Cool. #138 was just recently reported from our field workers that it is quite annoying. So what is this armv7? Is that an official release we can test or is it still very unstable?

**Comment by m-kuhn** [comment]
armv7 is the one you can use to test, it's not an official release and will never land on google play but it should be equally stable and if we get positive feedback we'll be more confident and merge (and release) it faster.

**Comment by saemiw** [comment]
I downloaded armv7 and tested with a project that is running smoothly on 0.9.10. With armv7 Qfield is crashing as soon as I move the map (sometimes only when I move the map a second time). The only difference I can notice is the message that is shown by the alarm-bell symbol (top right corner) when I start the application: 

With 0.9.10 (latest release) it says: 
> CRS
> Could not open CRS database /data/data/ch.opengis.qfield/files/profiles/default/qgis.db
> Error(14): unable to open database file

With armv7 it says:
> CRS
> Could not open CRS database //profiles/default/qgis.db
> Error(14): unable to open database file

**Comment by signedav** [comment]
I don't think that the crash has something to do with this PR. 
Possibly it's the same problem like here #235

**Comment by m-kuhn** [comment]
Apart from those (obviously critical) issues, are you able to properly close the sidebar with the back button?

**Comment by m-kuhn** [comment]
(Just triggering a new build that should no longer have the CRS issue)

**Comment by m-kuhn** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-241-2411889b69a70d90948d11136e05c351af25f2ca-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-241-2411889b69a70d90948d11136e05c351af25f2ca-x86.apk)

**Comment by saemiw** [comment]
> Apart from those (obviously critical) issues, are you able to properly close the sidebar with the back button?
@m-kuhn : I was hardly able to test that because it crashed so quickly. I was once able to click on the map and then properly close the sidebar. But this also worked sometimes in 0.10.9. (official release), depending on where your last click was on the screen. I'll test the new armv7 this afternoon

**Comment by saemiw** [comment]
downloaded the armv7 from your latest post @m-kuhn and I have bad news ;D:

- qfield is still crashing as soon as I move the map
- I still get the CRS-error explained in my second last post
- I was not really able to test the behaviour of the sidebar. But it seemed that it was not closing when I pressed the back button...

Are you interested in getting my test project. I wouldn't like to post it here publicly but I can send it to you if you want.

**Comment by giedrioks26** [comment]
The problem persists.
When press the "back" button to hide the identification window. QField closes.

**Comment by m-kuhn** [comment]
> The problem persists.

Too bad.
@giedrioks26 no crash at your place?

@saemiw can you try to go to the app settings > storage > delete cache and data? If this doesn't help, we'll prepare another apk for you with some more debug info, to see what's going on with this CRS.

**Comment by giedrioks26** [comment]
@m-kuhn no crash, just close

**Comment by m-kuhn** [comment]
Does it ask you "press back again to close project and app"?

**Comment by giedrioks26** [comment]
> Does it ask you "press back again to close project and app"?

Yes, I see this message. It protects against clouse.
Then I'm doing work around: 1. Touch the indentify window on the entry; 2. Touch back from the entry; 3. press back again. This will turn off the identify window.

1.
screenshot_20180317-115448
2.
screenshot_20180317-120142
3.
screenshot_20180317-115507

**Comment by signedav** [comment]
I have the same behavior like @giedrioks26 but I don't really understand why. It seems right to me to set the focus as long as visible. But it seems not to do it.

Another idea would be to make it dynamic. Means in case we wan't to make something on the layer on purpose for example and still have the window open.
Just something like this:
```
    MouseArea {
      anchors.fill: parent
      onClicked: focus = true
    }
```
So if it does not close (because out of focus) a tip on it is enough to set the focus.
I made some simple tests, but I'm not sure if this solution entails some other risks.

What is your opinion?

**Comment by m-kuhn** [comment]
I think what we need is to get the focus to behave properly. Saying, if something steals the focus away from the sidebar, it needs to give it back after. Possibly we need to somehow use `FocusScope` but still after reading all the material found on it I'm having a hard time understanding how exactly it's supposed to work.

One first step would be to find out *what* exactly has the focus at the time the sidebar no longer reacts.

**Comment by signedav** [comment]
Okay. I agree. I will do some investigations on it as well.

**Comment by signedav** [comment]
>  it needs to give it back after.
Well the question is, when "after" is. On this example, here I made a yellow border, when the featurelist "has" the focus:
focus
When clicking on a layer the focus is given to the listview. So when is "after" and the focus need to be given back to the the featurelist?
IMHO it's when:
- clicking again on a feature on the map
- clicking inside the featurelist-sidebar
But I don't know every usecase. What do you think @m-kuhn ?

**Comment by m-kuhn** [comment]
In this case the back click should first close the other sidebar and when that one is closed the focus should be handed over to the second sidebar.

**Comment by m-kuhn** [comment]
Or it should never ever even take the focus (if it doesn't even react to back clicks)

**Comment by signedav** [comment]
The "first" sidebar is the one on the left, right? 
Yes, it's never closed by back-key. But other thinks are. Like for example the menue-tree.

**Comment by m-kuhn** [comment]
I'm not sure we really want this behavior on the layer tree, do you like it?
On the other hand, I wouldn't mind if every back click first closes every sidebar (in whatever order) and finally the app when no more sidebars are open. Read: I don't care that much which sidebar closes first, but they should both, one after the other.
How does that sound?

**Comment by signedav** [comment]
It sounds pretty good. 

Means on close of one of the two sidebars the focus should go to the other one if expanded. So first closes the one that is opened secondly (or used). Than the other one. Than the app. Fine.

But there is still one use case we should care about as well: I open the layer list, and I open the feature list. I want to close the layer list. I think that the UX would be that if I do something on the layer list (even just clicking on it) kind of "activates" it and so the focus is there.

So there are two thinks:
1. give the focus to the other sidebar on close
2. get the focus when something is done

**Comment by m-kuhn** [comment]
Perfect, sounds good to me.
Maybe it's just a matter of enclosing the layer list in a `FocusScope` and making sure that it loses focus when hidden?

**Comment by m-kuhn** [comment]
Superseded by https://github.com/opengisch/QField/pull/266

**Pull request closed without merging**
