### PR TITLE
Add static windows build

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9409b8864cd4f2f4f8d15af9584728c08e0ce4ab:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-93a13fc5fcb6c19def06bc2d2d3738ed8e2f3cf6-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-93a13fc5fcb6c19def06bc2d2d3738ed8e2f3cf6-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-93a13fc5fcb6c19def06bc2d2d3738ed8e2f3cf6-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-93a13fc5fcb6c19def06bc2d2d3738ed8e2f3cf6-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8c9c247879eacf8de77f46713189947a3d48ff58:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-b3e8085c22d9450d778c9a7fb8b54ce3c4bdc3d1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-b3e8085c22d9450d778c9a7fb8b54ce3c4bdc3d1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-b3e8085c22d9450d778c9a7fb8b54ce3c4bdc3d1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-b3e8085c22d9450d778c9a7fb8b54ce3c4bdc3d1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 531cd6f5898c4102a287b256bcaf1318d0ca1bde:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-94b1a5d5eb395aa9caf52985a3cbe39278ae3374-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-94b1a5d5eb395aa9caf52985a3cbe39278ae3374-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-94b1a5d5eb395aa9caf52985a3cbe39278ae3374-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-94b1a5d5eb395aa9caf52985a3cbe39278ae3374-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for df23e054a17535c6e8f18f16c85d635b984a0308:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-f5c8051a3c5b044209639948629310624b1a0510-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-f5c8051a3c5b044209639948629310624b1a0510-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-f5c8051a3c5b044209639948629310624b1a0510-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-f5c8051a3c5b044209639948629310624b1a0510-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 254c061b074d59c2b68ac0440cf2a21d470af891:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-3e7f3c07ec17f971843294b2c57620575c6fe1a1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-3e7f3c07ec17f971843294b2c57620575c6fe1a1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-3e7f3c07ec17f971843294b2c57620575c6fe1a1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-3e7f3c07ec17f971843294b2c57620575c6fe1a1-x86.apk)

**Comment by m-kuhn** [comment]
> Hmm, tmate to the rescue?

In my experience this only works one out of 10 times on windows

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 141d4fa20b96a864c654b4dc3dc7428428777d07:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-8470918d0f0d4cf11746691b3a194613b68e8468-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-8470918d0f0d4cf11746691b3a194613b68e8468-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-8470918d0f0d4cf11746691b3a194613b68e8468-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-8470918d0f0d4cf11746691b3a194613b68e8468-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f86696e1e8bc73ca3f08c2cd0bb20c9ef885cb61:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-3f906635a792cbb4e750990971d9669a3519b6f1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-3f906635a792cbb4e750990971d9669a3519b6f1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-3f906635a792cbb4e750990971d9669a3519b6f1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-3f906635a792cbb4e750990971d9669a3519b6f1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2b495e29ba8d54e6dd32741c7f2442c8b3853635:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-11bc94b63122399d50e63ca8e11de4dfafded366-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-11bc94b63122399d50e63ca8e11de4dfafded366-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-11bc94b63122399d50e63ca8e11de4dfafded366-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-11bc94b63122399d50e63ca8e11de4dfafded366-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 184d663dd14629949cd86a21f14f247d0d0bfa5f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-a4ca051a15c3fc67dbc79e2219ab1c6376c3511c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-a4ca051a15c3fc67dbc79e2219ab1c6376c3511c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-a4ca051a15c3fc67dbc79e2219ab1c6376c3511c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-a4ca051a15c3fc67dbc79e2219ab1c6376c3511c-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a14b083b40c3cbf27081daad01424821f6b7a33b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-c699d1a56e9d0a9dc69ca189fad162a4bc4983a4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-c699d1a56e9d0a9dc69ca189fad162a4bc4983a4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-c699d1a56e9d0a9dc69ca189fad162a4bc4983a4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2304-c699d1a56e9d0a9dc69ca189fad162a4bc4983a4-x86.apk)

**Pull request closed without merging**
