### PR TITLE
Bump windows dependencies

### PR DESCRIPTION
**Pull request by m-kuhn**
... because who would not want geos 3.9.1

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a7514040f0cc10cdcaca8f88a8cfbc4e4243a859:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-61901aa927d8dc10861e9c615730e532527643eb-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-61901aa927d8dc10861e9c615730e532527643eb-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-61901aa927d8dc10861e9c615730e532527643eb-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-61901aa927d8dc10861e9c615730e532527643eb-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 631b33669b355e12fb7a394b1b21678d7cc14513:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-62c8329ec18f6fffa16fff8b61fd45569175dc9b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-62c8329ec18f6fffa16fff8b61fd45569175dc9b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-62c8329ec18f6fffa16fff8b61fd45569175dc9b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-62c8329ec18f6fffa16fff8b61fd45569175dc9b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 59499d3b0de34fffc77ec514a6a60025e1530b9c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-79dae7335ed11779c3d868d0de75ad1f7d3ccd6f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-79dae7335ed11779c3d868d0de75ad1f7d3ccd6f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-79dae7335ed11779c3d868d0de75ad1f7d3ccd6f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-79dae7335ed11779c3d868d0de75ad1f7d3ccd6f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 883818f8c7c299470e007faa029d1a36c041b577:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-215c2eb1f8787ad7b8f485eb44ca8ea56bcd9f30-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-215c2eb1f8787ad7b8f485eb44ca8ea56bcd9f30-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-215c2eb1f8787ad7b8f485eb44ca8ea56bcd9f30-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-215c2eb1f8787ad7b8f485eb44ca8ea56bcd9f30-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ed328c0cd250783d14b8807a909c133101476381:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-79f7ee343b15615ab3f74967d3d46b166c00c2f0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-79f7ee343b15615ab3f74967d3d46b166c00c2f0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-79f7ee343b15615ab3f74967d3d46b166c00c2f0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-79f7ee343b15615ab3f74967d3d46b166c00c2f0-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0ebea8118495632393b8f0918fc55834cceeea1c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-3276ba63941fee2aa9bc3d587b047d9c69863fa1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-3276ba63941fee2aa9bc3d587b047d9c69863fa1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-3276ba63941fee2aa9bc3d587b047d9c69863fa1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-3276ba63941fee2aa9bc3d587b047d9c69863fa1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ba22a83e6d19ac29211522f2642dc33bd303b856:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-4fb7f51a23b1a2689d1c9f00ce5d097797e0511c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-4fb7f51a23b1a2689d1c9f00ce5d097797e0511c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-4fb7f51a23b1a2689d1c9f00ce5d097797e0511c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-4fb7f51a23b1a2689d1c9f00ce5d097797e0511c-x86.apk)

**Review by nirvn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a7514040f0cc10cdcaca8f88a8cfbc4e4243a859:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-ad8cf56177789f32aa677bab663255b2e60674ad-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-ad8cf56177789f32aa677bab663255b2e60674ad-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-ad8cf56177789f32aa677bab663255b2e60674ad-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2049-ad8cf56177789f32aa677bab663255b2e60674ad-x86.apk)

**Pull request merged**
