### PR TITLE
workshop swarms

### PR DESCRIPTION
**Pull request by lucienicolier**
Here is the workshop about swarms.

The story is about bees leaving apiary because something is wrong.
In apiary, you have a new issue group (hive fault), if you check this box you got a list to determinate what's wrong. 

You also have two new point layers, swarms and music source.

Swarms is to situate bees and from witch apiary it is from (relation between queen id), you also can check a box to say it is easy to catch.

Maya will figure out  that swarms are going close to music source, here a school music and a concert auditorium.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-897-2084ccb5ebf1a9fed355e446f7f70321710efc18-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-897-2084ccb5ebf1a9fed355e446f7f70321710efc18-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-897-2084ccb5ebf1a9fed355e446f7f70321710efc18-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-897-2084ccb5ebf1a9fed355e446f7f70321710efc18-x86_64.apk)

**Comment by signedav** [comment]
Does this need to be in the demo project?

**Comment by lucienicolier** [comment]
Where should it be?

**Comment by signedav** [comment]
I think best would be to have a new repository qfield_workshop (or similar) to have all the data and notes there.

**Comment by lucienicolier** [comment]
what kind of widget do you mean?

**Comment by signedav** [comment]
For the relation reference? This kind of widget:

**Pull request closed without merging**
