### PR TITLE
Fairytales

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-f93abfd82fc4e4ef9662db5d64e61803d5f101e5-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-f93abfd82fc4e4ef9662db5d64e61803d5f101e5-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-f93abfd82fc4e4ef9662db5d64e61803d5f101e5-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-f93abfd82fc4e4ef9662db5d64e61803d5f101e5-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-686e7ad6133461002881329e3c34689cc8c83964-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-686e7ad6133461002881329e3c34689cc8c83964-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-686e7ad6133461002881329e3c34689cc8c83964-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-686e7ad6133461002881329e3c34689cc8c83964-x86_64.apk)

**Review by suricactus — APPROVED** [review]
Super fairy!

**Comment by m-kuhn** [comment]
There is still the "publish to google play" code to port to here before we can retire travis

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-5738c2d23ae64a3b82511711520fbf9befbb88f9-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-5738c2d23ae64a3b82511711520fbf9befbb88f9-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-5738c2d23ae64a3b82511711520fbf9befbb88f9-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-5738c2d23ae64a3b82511711520fbf9befbb88f9-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-351c34597c5aa6d9d2bf6e16bf717bcd411cfe20-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-351c34597c5aa6d9d2bf6e16bf717bcd411cfe20-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-351c34597c5aa6d9d2bf6e16bf717bcd411cfe20-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-351c34597c5aa6d9d2bf6e16bf717bcd411cfe20-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-9c909c39363fd9e3b35386bb55db2aead1786877-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-9c909c39363fd9e3b35386bb55db2aead1786877-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-9c909c39363fd9e3b35386bb55db2aead1786877-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-9c909c39363fd9e3b35386bb55db2aead1786877-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-6467f809f720b3914c1dcf4a8efef4d8086ccf33-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-6467f809f720b3914c1dcf4a8efef4d8086ccf33-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-6467f809f720b3914c1dcf4a8efef4d8086ccf33-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-6467f809f720b3914c1dcf4a8efef4d8086ccf33-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-7cd328e0b2d994e2bc0c94eec04fbd7c55ec33de-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-7cd328e0b2d994e2bc0c94eec04fbd7c55ec33de-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-7cd328e0b2d994e2bc0c94eec04fbd7c55ec33de-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-7cd328e0b2d994e2bc0c94eec04fbd7c55ec33de-x86_64.apk)

**Comment by qfield-fairy** [comment]
Ta-daaa, freshly created APKs are available:
  - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-c259fd8ce6d850b0097b73328ec633016dd76555-arm64_v8a.apk)
Other architectures:
  - [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-c259fd8ce6d850b0097b73328ec633016dd76555-armv7.apk)
  - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-c259fd8ce6d850b0097b73328ec633016dd76555-x86_64.apk)
  - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-c259fd8ce6d850b0097b73328ec633016dd76555-x86.apk)

**Comment by qfield-fairy** [comment]
Ta-daaa, freshly created APKs are available:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-35a115796711c7922b8ba83a2c7d0a6d1124d03e-arm64_v8a.apk)

Other architectures:

  - [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-35a115796711c7922b8ba83a2c7d0a6d1124d03e-armv7.apk)
  - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-35a115796711c7922b8ba83a2c7d0a6d1124d03e-x86_64.apk)
  - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-35a115796711c7922b8ba83a2c7d0a6d1124d03e-x86.apk)

**Comment by qfield-fairy** [comment]
Ta-daaa, freshly created APKs are available:
  - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-de9791f1b71eb6a32cee7f4c4e1147228c1ebf91-arm64_v8a.apk)

Other architectures:

  - [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-de9791f1b71eb6a32cee7f4c4e1147228c1ebf91-armv7.apk)
  - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-de9791f1b71eb6a32cee7f4c4e1147228c1ebf91-x86_64.apk)
  - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1300-de9791f1b71eb6a32cee7f4c4e1147228c1ebf91-x86.apk)

**Pull request merged**
