### PR TITLE
Fix a QField crash when opening a second project in a single session

### PR DESCRIPTION
**Pull request by nirvn**
Finally managed to narrow down a crasher that had been haunting me. Not sure why it doesn't systematically happen (which made it harder to debug). In any case, nailed!

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1233-9b6a8378e44eba1608302ef2fb19484bc7898a3c-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1233-9b6a8378e44eba1608302ef2fb19484bc7898a3c-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1233-9b6a8378e44eba1608302ef2fb19484bc7898a3c-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1233-9b6a8378e44eba1608302ef2fb19484bc7898a3c-x86_64.apk)

**Comment by signedav** [comment]
Without having updated the QGIS and compiling with 5.12 I could reproduce the crash on desktop.

It works now with my projects.

It still crashes with the projects, the users sent us. Here: https://github.com/opengisch/QField/pull/1233/files#diff-2099c399b23e92aa99547c8d698c0409R371

**Comment by nirvn** [comment]
Alright, this is crude but it works well. Whenever a row is removed, we rebuild the flat layer tree. That fixes all project crashes over here. @signedav 's projects were still crashing as row removed signals are now covering children items. 

In the future, if QField allows for layer removal within a project session, it'd be worth handling rows removal differently (to gain some speed), but for now IMHO this is an acceptable solution.

**Comment by nirvn** [comment]
Actually I'm not sure there's a better approach. I was initially thinking we could loop through children and delete those, but that wouldn't be enough since the model items would have entirely different index rows after deletion.

Rebuilding the flat tree is the way to go. :)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1233-e81395119bc0cfd2dd37600097fe0c99f9d31461-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1233-e81395119bc0cfd2dd37600097fe0c99f9d31461-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1233-e81395119bc0cfd2dd37600097fe0c99f9d31461-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1233-e81395119bc0cfd2dd37600097fe0c99f9d31461-x86_64.apk)

**Comment by signedav** [comment]
Tests on desktop has been successful.
The userprojects still crash on device - but this could be the other crash issue.

**Review by signedav — APPROVED** [review]
Haven't analyzed the code deeply, but tested on desktop and device.

**Comment by m-kuhn** [comment]
@nirvn I guess bp bot fails -- can I ask you to create a backport?

**Pull request merged**
