### PR TITLE
test

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by suricactus** [comment]
I think `github.actor` can do the trick too.

**Comment by m-kuhn** [comment]
@suricactus when checking for `if secrets.TX_TOKEN` we had `Unrecognized named-value: 'secrets'.`. Will the same happen when it's run on a commit (and not a PR)?

**Comment by suricactus** [comment]
It was wrong, `secrets.*` would not work in the `if` expression. The secrets should be assigned to environment variables and used as `if: env.TX_TOKEN`.

**Comment by m-kuhn** [comment]
Does this actually work? Internet research didn't give a conclusive answer.

**Comment by m-kuhn** [comment]
@suricactus works now, should we merge as is?

**Comment by suricactus** [comment]
If the env is per job, I think it works fine.

Anyway I prefer your approack, it does not rely on some kind of gh magic and workarounds.

**Review by suricactus — APPROVED** [review]

**Pull request merged**
