### PR TITLE
Trim down AndroidManfest.xml

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e8640e087b3c9fdd7ba0ca38086aa1dece3980ce:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1485-c33517784a88c3b5a80e9c044b6bd8f9e9fa094f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1485-c33517784a88c3b5a80e9c044b6bd8f9e9fa094f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1485-c33517784a88c3b5a80e9c044b6bd8f9e9fa094f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1485-c33517784a88c3b5a80e9c044b6bd8f9e9fa094f-x86.apk)

**Comment by nirvn** [comment]
When I go to the home screen, and then try to get back to QField, the app restarts instead of resuming.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bce3e310e52e03614dc0963c7796e81a2a4f43bb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1485-a20707b1a1cc4baf237dade025179e0114b713ab-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1485-a20707b1a1cc4baf237dade025179e0114b713ab-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1485-a20707b1a1cc4baf237dade025179e0114b713ab-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1485-a20707b1a1cc4baf237dade025179e0114b713ab-x86.apk)

**Comment by nirvn** [comment]
No luck, still seeing app restart on returning to it after clicking on the home button.

**Pull request closed without merging**
