### PR TITLE
Add a configurable antenna height option

### PR DESCRIPTION
**Pull request by m-kuhn**
This can be used to compensate measured Z values for an antenna height.
It can also be abused to compensate for anything else like geoid differences.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-a6ab29b6522bed8d93cebbad37a7725547a8cc64-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-a6ab29b6522bed8d93cebbad37a7725547a8cc64-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-a6ab29b6522bed8d93cebbad37a7725547a8cc64-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-a6ab29b6522bed8d93cebbad37a7725547a8cc64-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cb2e3f0acd9a21bec674923fc60c3579c8c0425b-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cb2e3f0acd9a21bec674923fc60c3579c8c0425b-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cb2e3f0acd9a21bec674923fc60c3579c8c0425b-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cb2e3f0acd9a21bec674923fc60c3579c8c0425b-x86_64.apk)

**Comment by m-kuhn** [comment]
Todo:

- Checkbox size
- Line edit not visible / editable

Screenshot_20191016-115502_QField

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-5b3b0e741ebdeddc68061bc3caaaef1de00a8b43-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-5b3b0e741ebdeddc68061bc3caaaef1de00a8b43-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-5b3b0e741ebdeddc68061bc3caaaef1de00a8b43-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-5b3b0e741ebdeddc68061bc3caaaef1de00a8b43-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-852c7cda4bf461d27b988ac9d7c6bc0931b0cc19-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-852c7cda4bf461d27b988ac9d7c6bc0931b0cc19-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-852c7cda4bf461d27b988ac9d7c6bc0931b0cc19-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-852c7cda4bf461d27b988ac9d7c6bc0931b0cc19-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-0c78e9f714a2fe09613e14415a8680a24dc4d08b-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-0c78e9f714a2fe09613e14415a8680a24dc4d08b-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-0c78e9f714a2fe09613e14415a8680a24dc4d08b-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-0c78e9f714a2fe09613e14415a8680a24dc4d08b-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-218698209d765e5fd095ea6194755d8051a0e774-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-218698209d765e5fd095ea6194755d8051a0e774-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-218698209d765e5fd095ea6194755d8051a0e774-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-218698209d765e5fd095ea6194755d8051a0e774-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-ad9597a223ea702e4398abd2075fc5f4692cba50-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-ad9597a223ea702e4398abd2075fc5f4692cba50-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-ad9597a223ea702e4398abd2075fc5f4692cba50-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-ad9597a223ea702e4398abd2075fc5f4692cba50-x86_64.apk)

**Comment by Emic37** [comment]
Hi @m-kuhn, did you make changes about the compilation of  the test apks this last days ?
I cannot install anymore all of the new test-apks armv7 which were released since 4 days.

**Comment by m-kuhn** [comment]
Yes, we did some changes.
How does it fail? Does it work if you uninstall the app first?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-7d376cdc4ba7243debbab0fc65348cf1093a9e2f-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-7d376cdc4ba7243debbab0fc65348cf1093a9e2f-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-7d376cdc4ba7243debbab0fc65348cf1093a9e2f-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-7d376cdc4ba7243debbab0fc65348cf1093a9e2f-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cc54f26904a67c6c7c245e3c06de6ac13b3a6292-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cc54f26904a67c6c7c245e3c06de6ac13b3a6292-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cc54f26904a67c6c7c245e3c06de6ac13b3a6292-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cc54f26904a67c6c7c245e3c06de6ac13b3a6292-x86_64.apk)

**Comment by Emic37** [comment]
@m-kuhn, all happens as if there is no issue. The installation Wizard opens, works a few seconds and when the progress bar is completed, it displays "app is not installed".

**Comment by m-kuhn** [comment]
Does it work if you uninstall the app first?

**Comment by Emic37** [comment]
Oh sorry. I forgot to precise it : no it doesn't work when I uninstall the previous version before.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-4734bf02c24dab37c9b53a2f77f7d8145cbfcf30-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-4734bf02c24dab37c9b53a2f77f7d8145cbfcf30-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-4734bf02c24dab37c9b53a2f77f7d8145cbfcf30-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-4734bf02c24dab37c9b53a2f77f7d8145cbfcf30-x86_64.apk)

**Comment by Emic37** [comment]
Hi @m-kuhn, I was able to try this new feature using an other more modern phone (arm64v8). Good ! But why not add this option to the parameters ? 

There is allready in the parameters an option to show the digitize information. It would make sense that the option to show position information is also in the parameters. And of course, this option to set the heigh of the antenna. 

Also, these options are "set and don't touch" options, no ? It shouldn't be a problem for users to do not have a "shortcut" via the localisation menu.

And, in the parameters, there is more place than in this little position menu...

**Comment by mbernasocchi** [comment]
> Oh sorry. I forgot to precise it : no it doesn't work when I uninstall the previous version before
could you try uninstalling QField installed from the playstore?

**Comment by EulenspiegelTill** [comment]
@m-kuhn We'll see that we can test the function this week. The goal would be to play through an "usecase" and verify the heights. keep you posted..

**Comment by m-kuhn** [comment]
@EulenspiegelTill we still see "strange" behavior that digitizing is completely impossible. Before investing a lot, do some basic sanity testing in the office first.

**Comment by soester** [comment]
@EulenspiegelTill @m-kuhn 
I think the feature is not ready to test yet..
Screenshot_20191023-131101_QField
Positioning is not really working and i get the above errors.

Nevertheless we are looking forward to this great feature!

**Comment by soester** [comment]
> Hi @m-kuhn, I was able to try this new feature using an other more modern phone (arm64v8). Good ! But why not add this option to the parameters ?
> 
> There is allready in the parameters an option to show the digitize information. It would make sense that the option to show position information is also in the parameters. And of course, this option to set the heigh of the antenna.
> 
> Also, these options are "set and don't touch" options, no ? It shouldn't be a problem for users to do not have a "shortcut" via the localisation menu.
> 
> And, in the parameters, there is more place than in this little position menu...

would it be possible to use the antenna height as a variable to store the value with this?
eg. 
'@z_mockprovider
'@z_corrected (which woud be also stored in geometry of feature and equivalent of default value for z($geometry)
'@antenna_height

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-9412bd49ea8987b6dcb2cbd75fffa6301c68ee8d-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-9412bd49ea8987b6dcb2cbd75fffa6301c68ee8d-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-9412bd49ea8987b6dcb2cbd75fffa6301c68ee8d-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-9412bd49ea8987b6dcb2cbd75fffa6301c68ee8d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-4cd9e858a70232ee57e6fd826f4ef54b0be6a360-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-4cd9e858a70232ee57e6fd826f4ef54b0be6a360-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-4cd9e858a70232ee57e6fd826f4ef54b0be6a360-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-4cd9e858a70232ee57e6fd826f4ef54b0be6a360-x86_64.apk)

**Comment by signedav** [comment]
What is the status here?

**Comment by soester** [comment]
I tried to test after https://github.com/opengisch/QField/pull/677/commits/4217c3abcbd7e613bb0ed57565f853b41309464e yesterday.
Unfortunately Qfield crashed when trying to set antenna height (not really predictable).
After the crash i was not able to restart qfield. I had to remove the app and reinstall from downloaded apk.

**Comment by signedav** [comment]
Okay, thanks @soester

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-450204003802c8dc4f29ef40565d6972cae22d49-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-450204003802c8dc4f29ef40565d6972cae22d49-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-450204003802c8dc4f29ef40565d6972cae22d49-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-450204003802c8dc4f29ef40565d6972cae22d49-x86_64.apk)

**Comment by soester** [comment]
@m-kuhn tested after https://github.com/opengisch/QField/pull/677/commits/818dd6b0896c74fd16a0f3e528bca727b92b4191 with fake gps mock provider (locatizator).
altitude form mock provider (3 m), displayed value and geometry recorded in feature do not match:
Screenshot_2019-11-13-09-06-38

some how there seems to be a geoid-correction?

**Comment by m-kuhn** [comment]
@soester I see what you mean. Let's test something...

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-21dd951a1f02e37058fd796791c6e1b8645bd0fd-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-21dd951a1f02e37058fd796791c6e1b8645bd0fd-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-21dd951a1f02e37058fd796791c6e1b8645bd0fd-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-21dd951a1f02e37058fd796791c6e1b8645bd0fd-x86_64.apk)

**Comment by m-kuhn** [comment]
Stay tuned... It's not this one yet...

**Comment by m-kuhn** [comment]
@3nids does this require a CMakeLists update as well?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-a61263a2237443a196d64df7986e07335b82d561-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-a61263a2237443a196d64df7986e07335b82d561-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-a61263a2237443a196d64df7986e07335b82d561-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-a61263a2237443a196d64df7986e07335b82d561-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-b1b8394b9b9c0e0e30792a9029fd210a09d1231b-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-b1b8394b9b9c0e0e30792a9029fd210a09d1231b-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-b1b8394b9b9c0e0e30792a9029fd210a09d1231b-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-b1b8394b9b9c0e0e30792a9029fd210a09d1231b-x86_64.apk)

**Comment by soester** [comment]
with the new ui there are no more checkboxes:
Screenshot_20191120-073716_QField Beta 677

**Comment by nirvn** [comment]
@m-kuhn , as mentioned over google hangout, I've worked on this branch to improve the positioning settings popup. GIF says it all:
Peek 2019-12-22 12-08

Improvements include:
- Fix auto wrapping of text
- Add scroll area for small screens
- Adjust the text input width

I've also upgraded QField's settings dialog to make use of the QfSwitch introduced in this PR, a net -186 lines of code, nice.

**Comment by nirvn** [comment]
@soester , tried the updated PR packages whenever those popup in the forthcoming hour, I believe your UI issue has been fully addressed.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-7f3ac462921d88e7939c2724175f8a119d4cf16e-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-7f3ac462921d88e7939c2724175f8a119d4cf16e-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-7f3ac462921d88e7939c2724175f8a119d4cf16e-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-7f3ac462921d88e7939c2724175f8a119d4cf16e-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cdc7b08859381674a89192fa97c9b896bbbf3ed3-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cdc7b08859381674a89192fa97c9b896bbbf3ed3-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cdc7b08859381674a89192fa97c9b896bbbf3ed3-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-cdc7b08859381674a89192fa97c9b896bbbf3ed3-x86_64.apk)

**Comment by nirvn** [comment]
@m-kuhn , assuming that what was holding this PR from being merged were the UI issues, I'd like to get this merged ASAP to make use of the PageHeader in other parts of the code.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-f86e7e6a5b4fcc9f3fc84fb7c55bbc9959dba92b-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-f86e7e6a5b4fcc9f3fc84fb7c55bbc9959dba92b-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-f86e7e6a5b4fcc9f3fc84fb7c55bbc9959dba92b-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-f86e7e6a5b4fcc9f3fc84fb7c55bbc9959dba92b-x86_64.apk)

**Comment by nirvn** [comment]
Looking good on my phone:
image
_Note the new 2-column arrangement for the position information overlay at the bottom, looking much better on narrow-width screens._

**Comment by nirvn** [comment]
There:
Screenshot from 2019-12-22 15-38-09

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-662b69aac986a78c82e222184939ffca56e1086d-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-662b69aac986a78c82e222184939ffca56e1086d-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-662b69aac986a78c82e222184939ffca56e1086d-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-662b69aac986a78c82e222184939ffca56e1086d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-980012529b603cf781acda0d209ac81bdbcd0bce-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-980012529b603cf781acda0d209ac81bdbcd0bce-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-980012529b603cf781acda0d209ac81bdbcd0bce-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-980012529b603cf781acda0d209ac81bdbcd0bce-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-89a701bdddc4bda45a30621661b1f424133d5909-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-89a701bdddc4bda45a30621661b1f424133d5909-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-89a701bdddc4bda45a30621661b1f424133d5909-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-89a701bdddc4bda45a30621661b1f424133d5909-x86_64.apk)

**Comment by soester** [comment]
Thanks @nirvn, i think all ui issues are solved!  Also the "Skip altitude correction" switch implemented by @m-kuhn works :). The displayed altitude is the same as the one i get with z($geometry) as default value.

But i am not sure if the note below the antenna height field is still correct with the current behaviour.
Now:
"Z values which are recorded from a positioning receiver will be corrected by this value. If a value of 1.6 is entered, this will result in a correction of -1.6 m for each recorded value. The value shown in the position information view **will be** corrected by this value."

Proposal:
"Z values which are recorded from a positioning receiver will be corrected by this value. If a value of 1.6 is entered, this will result in a correction of -1.6 m for each recorded value. The value shown in the position information view **is allready** corrected by this value. The Antennaheight is shown in brackets."

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-f5cc5a5ecf4ffe16a6b4b8c3b40683fa08880539-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-f5cc5a5ecf4ffe16a6b4b8c3b40683fa08880539-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-f5cc5a5ecf4ffe16a6b4b8c3b40683fa08880539-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-f5cc5a5ecf4ffe16a6b4b8c3b40683fa08880539-x86_64.apk)

**Comment by nirvn** [comment]
@soester , glad to hear the latest commits fixed your UI issues. @m-kuhn has updated the wording you raised in your last commit. 

This is ready to merge; I've just rebased the PR to fix the conflicts, will merge as soon as travis gives us the green light.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-48c72f02d8371ae4ad822006c0cbe6746789def2-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-48c72f02d8371ae4ad822006c0cbe6746789def2-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-48c72f02d8371ae4ad822006c0cbe6746789def2-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-677-48c72f02d8371ae4ad822006c0cbe6746789def2-x86_64.apk)

**Pull request merged**
