### PR TITLE
Improve formatted code readability for multiline objects/function calls

### PR DESCRIPTION
**Pull request by suricactus**
Fixes weird situations like:
before:
```
  NetworkReply *deltasCloudReply = mCloudConnection->post(
  QStringLiteral( "/api/v1/deltas/%1/" ).arg( projectId ),
  QVariantMap(),
  QStringList() );
```
after

```
  NetworkReply *deltasCloudReply = mCloudConnection->post(
    QStringLiteral( "/api/v1/deltas/%1/" ).arg( projectId ),
    QVariantMap(),
    QStringList() );
```

==================

before
```
  QJsonObject delta(
  {
    { "localPk", oldFeature.attribute( localPkAttrName ).toString() },
  } );
```
after
```
  QJsonObject delta(
    {
      { "localPk", oldFeature.attribute( localPkAttrName ).toString() },
    } );
```

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1474 Improve formatted code readability for multiline objects/function calls](https://app.clickup.com/t/2192114/QF-1474)

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
I deleted "Chinese (Hong Kong)", there were no translators available for this language and 0 translations lost.
Let's see how it goes and check if we can update the `lang_map` for a supported code if it was this.

**Comment by suricactus** [comment]
Can we merge this even if it fails now? Otherwise all the new PRs will have a parasite "formatter" commit. I am not allowed to force merge.

**Review by m-kuhn — APPROVED** [review]
Very true

**Pull request merged**
