### PR TITLE
Update to Qt 5.12.1

### PR DESCRIPTION
**Pull request by m-kuhn**
And a shiny new build chain without crystax

 - [x] libssl.so still has a versioned filename, trying [this](https://stackoverflow.com/questions/24204366/how-to-build-openssl-as-unversioned-shared-lib-for-android) now
 - [x] libpq.so crashes on Android <8

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-590e6b725593589b53effefa507840991d6f0157-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-590e6b725593589b53effefa507840991d6f0157-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-0075084cf52587497d67371813c57a1e347f54d0-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-0075084cf52587497d67371813c57a1e347f54d0-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-3fa2c6254f77091464ff1675bd9034b4323076b9-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-3fa2c6254f77091464ff1675bd9034b4323076b9-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-3fa2c6254f77091464ff1675bd9034b4323076b9-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-3fa2c6254f77091464ff1675bd9034b4323076b9-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-445e7599c3b9bbe82627feffdb7eae7bdeba0c74-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-445e7599c3b9bbe82627feffdb7eae7bdeba0c74-x86.apk)

**Comment by m-kuhn** [comment]
And it runs :tada:

**Comment by m-kuhn** [comment]
@signedav @marioba @mbernasocchi @3nids @giedrioks @saemiw and whoever else is interested, can you give this version a short testride and put a :+1: or :-1: on the qfield fairy comment above.

**Comment by 3nids** [comment]
I got a crash at some point, but could not reproduce.
I've played with legend, digitizing, locator, feature form. It went all good (except the crash at first run).

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f4eaa9880b0050c6b265a777734762e5eb831095-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f4eaa9880b0050c6b265a777734762e5eb831095-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f4eaa9880b0050c6b265a777734762e5eb831095-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f4eaa9880b0050c6b265a777734762e5eb831095-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f4eaa9880b0050c6b265a777734762e5eb831095-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f4eaa9880b0050c6b265a777734762e5eb831095-x86.apk)

**Comment by m-kuhn** [comment]
Still not working with Android 7

libpq links to an unavailable symbol `nl_langinfo`

```
02-20 14:41:36.712 26755 26770 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "nl_langinfo" referenced by "/data/app/ch.opengis.qfield-1/lib/arm/libpq.so"...
```

**Comment by marioba** [comment]
Works on Android 9 ;-)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f4eaa9880b0050c6b265a777734762e5eb831095-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f4eaa9880b0050c6b265a777734762e5eb831095-x86.apk)

**Comment by mbernasocchi** [comment]
works on Android 8

**Comment by m-kuhn** [comment]
Needs testing on Android 7, ping @signedav

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f2f26ed22e7946eeb80e6d6165fb6bc5091ebd08-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f2f26ed22e7946eeb80e6d6165fb6bc5091ebd08-x86.apk)

**Comment by saemiw** [comment]
I confirm as well that the lastes qfield-fairy armv7 works on Android 8

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f2f26ed22e7946eeb80e6d6165fb6bc5091ebd08-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-478-f2f26ed22e7946eeb80e6d6165fb6bc5091ebd08-x86.apk)

**Comment by m-kuhn** [comment]
The latest package now finally also works with Android 7

Can others confirm it still works on Android 8 (and if somehow possible Android 5 would be great to know)

**Comment by saemiw** [comment]
Seems to work fine on Android 8

**Comment by mbernasocchi** [comment]
Works for me

**Comment by m-kuhn** [comment]
Does not work on Android 5 :(

**Pull request merged**
