### PR TITLE
Button size

### LINKED ISSUE #922: Button icons not HiDPI agnostic
In current master, icons are super small on HiDPI devices (since the buttons have been updated to QuickControls.2).

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #922

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-924-d53994c31302c250127d574e9163f33df753c3a9-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-924-d53994c31302c250127d574e9163f33df753c3a9-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-924-d53994c31302c250127d574e9163f33df753c3a9-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-924-d53994c31302c250127d574e9163f33df753c3a9-x86_64.apk)

**Comment by nirvn** [comment]
This is weird, I'd have expected things to go the other way around, i.e. less dp workarounds, not more. Oh well, I guess until the code is quick 2.0 only, there's no escape.

**Comment by m-kuhn** [comment]
> Oh well, I guess until the code is quick 2.0 only, there's no escape.

Yep, once we get rid of *all* QuickControls 1 we can remove so much crappy code

**Comment by signedav** [comment]
WhatsApp Image 2020-04-01 at 12 19 56

**Comment by nirvn** [comment]
@m-kuhn , I'm wondering whether this is all far more trouble than its worth it.

I've been compiling QField today, and pretty much all the buttons are missized and have unwanted margins. Eg:
Screenshot from 2020-04-06 16-38-22
_Bad margins in header buttons_

Screenshot from 2020-04-06 16-38-30
_Mismatch of button size between menu button and the (x) close button_

Maybe the easiest here is to revert the initial change, and have a got at it when QField as a whole will be moved to be Quick 2.0 only?

**Comment by m-kuhn** [comment]
You are right.
Let's close, revert and have a call for a plan of action for Quick.2 migration

**Pull request closed without merging**
