### PR TITLE
Fix find_package proj regression on non-vcpkg linux builds

### PR DESCRIPTION
**Pull request by nirvn**
@m-kuhn , this fixes a regression from this commit (https://github.com/opengisch/QField/commit/045de0344f15ffe3583fb4ad88172043a20acd38).

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 804be39c5eeda07aec3d5a32bd1cabcf8b4cf5c1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2305-18477e1f776604051a5ed9e90a2fa1c40644e2ae-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2305-18477e1f776604051a5ed9e90a2fa1c40644e2ae-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2305-18477e1f776604051a5ed9e90a2fa1c40644e2ae-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2305-18477e1f776604051a5ed9e90a2fa1c40644e2ae-x86.apk)

**Comment by m-kuhn** [comment]
Hmmm... https://proj.org/development/cmake.html
Can we not use the standard way?

**Comment by m-kuhn** [comment]
https://github.com/OSGeo/PROJ/blob/master/cmake/CMakeLists.txt

**Comment by nirvn** [comment]
@m-kuhn , on my machine, I get:

```
CMake Warning at CMakeLists.txt:124 (find_package):
  By not providing "FindPROJ.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PROJ", but
  CMake did not find one.

  Could not find a package configuration file provided by "PROJ" with any of
  the following names:

    PROJConfig.cmake
    proj-config.cmake

  Add the installation prefix of "PROJ" to CMAKE_PREFIX_PATH or set
  "PROJ_DIR" to a directory containing one of the above files.  If "PROJ"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by m-kuhn** [comment]
On my Fedora 34 system, it's found (through `/lib64/cmake/proj/proj-config.cmake`) and creates the target `PROJ::proj` in `${PROJ_LIBRARIES}`. However, that links to an inexistant file `/usr/lib64/libtiff.so`... Too bad.

**Comment by nirvn** [comment]
@m-kuhn , not present on my system, anywhere.

**Review by m-kuhn — APPROVED** [review]
Let's merge until the whole messiness about the proj-config.cmake has been fixed

**Pull request merged**
