### PR TITLE
Hey, don't shut my screen, I'm looking!

### PR DESCRIPTION
**Pull request by nirvn**
Because it's never fun to have Android shut my screen when I'm looking at my canvas.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-e326d293ed0f3a009ff493b6684bdde809267010-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-e326d293ed0f3a009ff493b6684bdde809267010-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-e326d293ed0f3a009ff493b6684bdde809267010-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-e326d293ed0f3a009ff493b6684bdde809267010-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-bda187047b6f60498da4fff44a9d964b05cc63b7-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-bda187047b6f60498da4fff44a9d964b05cc63b7-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-bda187047b6f60498da4fff44a9d964b05cc63b7-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-bda187047b6f60498da4fff44a9d964b05cc63b7-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-5762012ec5771c662f6744bb6a8d349839c86aad-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-5762012ec5771c662f6744bb6a8d349839c86aad-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-5762012ec5771c662f6744bb6a8d349839c86aad-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-5762012ec5771c662f6744bb6a8d349839c86aad-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-4e4dec931fff199e0e6bd8028da8e6c5a05f570b-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-4e4dec931fff199e0e6bd8028da8e6c5a05f570b-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-4e4dec931fff199e0e6bd8028da8e6c5a05f570b-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-4e4dec931fff199e0e6bd8028da8e6c5a05f570b-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-49ec913b5e4e3478021006a030f59c2dec0e21ff-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-49ec913b5e4e3478021006a030f59c2dec0e21ff-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-49ec913b5e4e3478021006a030f59c2dec0e21ff-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-49ec913b5e4e3478021006a030f59c2dec0e21ff-x86_64.apk)

**Comment by m-kuhn** [comment]
Good move!
I wonder if we should toggle this when GPS canvas following (and especially tracking) is enabled only.
Code-wise, this should have a default empty implementation in PlatformUtilities so we get away without any platform-specific #ifdefs in the code (and any platform can implement as appropriate).

**Comment by nirvn** [comment]
@m-kuhn , if the PR author has a vote here, I'd call for QField to also prevent screen lock. While the GPS canvas follow pushed this PR, I remember using QField just two weeks ago in the context of anthropological field interviews where a number of people were looking at the canvas. It was a real pain to see the screen dim (or worse lock) while discussing, and always having to poke at the phone to prevent that.

**Comment by nirvn** [comment]
@m-kuhn , OK, I've addressed your comments by:
- adding a virtual default implementation
- modified the function to not only disable but also re-enable screen locking (again, I'd suggest to always prevent screen locking, but this toggle might be useful in the future)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-5ff557940154f638bed2d0d030520873f18628ed-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-5ff557940154f638bed2d0d030520873f18628ed-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-5ff557940154f638bed2d0d030520873f18628ed-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-5ff557940154f638bed2d0d030520873f18628ed-x86_64.apk)

**Comment by VxTedxV** [comment]
> @m-kuhn , if the PR author has a vote here, I'd call for QField to also prevent screen lock. While the GPS canvas follow pushed this PR, I remember using QField just two weeks ago in the context of anthropological field interviews where a number of people were looking at the canvas. It was a real pain to see the screen dim (or worse lock) while discussing, and always having to poke at the phone to prevent that.

User should still be allowed to lock manually their screen (to prevent from wrong pocket manipulations while in the field)

**Comment by nirvn** [comment]
@VxTedxV , yes, that's permitted. This PR is about disabling the auto time out lock, not prohibiting manual lock.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-7a1c5fc2f0817b3e0530e2e96018f94500446abe-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-7a1c5fc2f0817b3e0530e2e96018f94500446abe-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-7a1c5fc2f0817b3e0530e2e96018f94500446abe-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-808-7a1c5fc2f0817b3e0530e2e96018f94500446abe-x86_64.apk)

**Pull request merged**
