### PR TITLE
Fix tiny slider handle on hidpi screens

### PR DESCRIPTION
**Pull request by nirvn**
PR title says it all.

### CODE REVIEW

**Comment by mbernasocchi** [comment]
@nirvn on my S9 checkboxes are also rather tiny

**Comment by nirvn** [comment]
@mbernasocchi , tiny checkboxes or tiny check symbol within a properly sized checkbox?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-835-318cb5665bcf61e0777c91a2dfa19f30af86db4b-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-835-318cb5665bcf61e0777c91a2dfa19f30af86db4b-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-835-318cb5665bcf61e0777c91a2dfa19f30af86db4b-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-835-318cb5665bcf61e0777c91a2dfa19f30af86db4b-x86_64.apk)

**Comment by mbernasocchi** [comment]
@nirvn tiny checks in propper boxes

**Comment by mbernasocchi** [comment]
Screenshot_20200215-223543_QField Dev

**Pull request merged**
