### PR TITLE
Relationeditormodel Unittests

### PR DESCRIPTION
**Pull request by signedav**
Not yet working.

I opened this issue since I we can only run one test at the moment. 
I cannot overwrite the main here:
```
QTEST_MAIN( TestReferencingFeatureListModel )
```

I do not really know the testing environment how it's solved in QGIS, but there we have kind of sub-projects for each test and `QGSTEST`.

Possibly you know how this can be done easily @3nids @m-kuhn - otherwise I'll check it out myself. Thanks.

### CODE REVIEW

**Comment by 3nids** [comment]
it's a bit vague in my mind.
I remember we had two approaches for the test structures.
Either using subdirs, similarly to what is doing Qt. It had the advantage of being able to report for tests individually. But a big drawback I can't recall.
Or having the tests in chain as we currently do. The main drawback is that tests are run one after the other, if the first one fails, the rest is not tested.

**Comment by signedav** [comment]
I'm stucked here a little bit. Apparently the firing of signal `collectedValues` does not effect anything here https://github.com/opengisch/QField/blob/master/src/core/referencingfeaturelistmodel.h#L222 - the slot `updateModel` is not reached (connected here https://github.com/opengisch/QField/blob/master/src/core/referencingfeaturelistmodel.cpp#L161) But the signal should be fired. Since I got the log output:
```
QDEBUG : TestReferencingFeatureListModel::testGetReferencingFeatures() Testdebug: Gatherer: fire collected values signal
QDEBUG : TestReferencingFeatureListModel::testGetReferencingFeatures() Testdebug: Gatherer: signal fired
```
on this:
```
      qDebug() << "Testdebug: Gatherer: fire collected values signal";
      emit collectedValues();
      qDebug() << "Testdebug: Gatherer: signal fired";
```

@m-kuhn do you have an idea what's the issue here?

**Comment by signedav** [comment]
Apparently ` QTest::qSleep( 10000 );` kind of blocks the procedure... I don't know why.
With the implementation of waiting for an emitted signal like...
```
QVERIFY(QSignalSpy(mModel, &ReferencingFeatureListModel::modelUpdated).wait(1000));
```
...it works fine...

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-606-5e1b5c51695d837001e507ebd70fbb0fb0892863-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-606-5e1b5c51695d837001e507ebd70fbb0fb0892863-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-606-5e1b5c51695d837001e507ebd70fbb0fb0892863-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-606-5e1b5c51695d837001e507ebd70fbb0fb0892863-x86_64.apk)

**Comment by nirvn** [comment]
@m-kuhn , can you check your google hangout now? :) apologies for the spam to all.

**Comment by signedav** [comment]
Works great! Thanks :tada:

**Pull request merged**
