### PR TITLE
Update QGIS to 3.22.2

### PR DESCRIPTION
**Pull request by nirvn**
A couple of important bug fixes in there.

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d5c661a0678698ae101ea6140d2382f90c0373a5:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2365-00ca88704c30f4aab8e84c72398456919f23669c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2365-00ca88704c30f4aab8e84c72398456919f23669c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2365-00ca88704c30f4aab8e84c72398456919f23669c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2365-00ca88704c30f4aab8e84c72398456919f23669c-x86.apk)

**Comment by nirvn** [comment]
Tested, working.

**Comment by nirvn** [comment]
5h20min into building desktop CI...

**Comment by m-kuhn** [comment]
I think github ships often minor VC updates which triggers a complete rebuild (including Qt)

**Comment by nirvn** [comment]
Ahhh good to know

**Pull request merged**
