### PR TITLE
Fix back button on welcome screen when no project is opened

### PR DESCRIPTION
**Pull request by suricactus**
| before | after |
|-|-|
| Peek 2023-08-20 13-29 | Peek 2023-08-20 13-27 |

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-3059 Fix back button on welcome screen when no project is opened](https://app.clickup.com/t/2192114/QF-3059)

**Review by nirvn — APPROVED** [review]
Nice one,

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c1ba28f4d25f4b725f19b8b65316c76e02fc08cb: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4524-2b35a556249ee8168a10e5ca7459cab92c797d3e-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4524-2b35a556249ee8168a10e5ca7459cab92c797d3e-arm-neon-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4524-2b35a556249ee8168a10e5ca7459cab92c797d3e-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4524-2b35a556249ee8168a10e5ca7459cab92c797d3e-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4524-2b35a556249ee8168a10e5ca7459cab92c797d3e-arm64-android.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4524-2b35a556249ee8168a10e5ca7459cab92c797d3e-arm-neon-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4524-2b35a556249ee8168a10e5ca7459cab92c797d3e-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4524-2b35a556249ee8168a10e5ca7459cab92c797d3e-x86-android.apk)
</details>

**Comment by suricactus** [comment]
@nirvn merge whenever you feel like pressing the green button.

**Comment by nirvn** [comment]
@suricactus , now! :)

**Pull request merged**
