### PR TITLE
Update SDK to test openssl threads compilation flags

### PR DESCRIPTION
**Pull request by nirvn**
Gimme APKs.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e0fd5beb04b4f5991627917b842ef3979f067000:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-93a0ca02e77b2c6df5de443cad21bade364e3760-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-93a0ca02e77b2c6df5de443cad21bade364e3760-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-93a0ca02e77b2c6df5de443cad21bade364e3760-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-93a0ca02e77b2c6df5de443cad21bade364e3760-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cacbe8b566f2cc22de969e5a7bdf4fb4eaadfe87:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-135d6e3d5522d8736323af59aaee77313f7abdd0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-135d6e3d5522d8736323af59aaee77313f7abdd0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-135d6e3d5522d8736323af59aaee77313f7abdd0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-135d6e3d5522d8736323af59aaee77313f7abdd0-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cacbe8b566f2cc22de969e5a7bdf4fb4eaadfe87:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-062921f4195ba4ee05282cf49cf415126cdeec7c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-062921f4195ba4ee05282cf49cf415126cdeec7c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-062921f4195ba4ee05282cf49cf415126cdeec7c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1703-062921f4195ba4ee05282cf49cf415126cdeec7c-x86.apk)

**Comment by signedav** [comment]
fyi 


1.8.3

```
dave@dave-ThinkPad-T590:~$ adb logcat -c
dave@dave-ThinkPad-T590:~$ adb logcat QField:D *:S
--------- beginning of system
--------- beginning of main
02-22 10:44:36.369 27393 27412 W QField  : Unsupported ICC input color space 47524159
02-22 10:44:36.369 27393 27412 W QField  : fromIccProfile: failed general sanity check
02-22 10:44:36.369 27393 27412 W QField  : QPngHandler: Failed to parse ICC profile
02-22 10:44:36.424 27393 27412 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 10:44:36.516 27393 27412 W QField  : Unsupported ICC input color space 47524159
02-22 10:44:36.516 27393 27412 W QField  : fromIccProfile: failed general sanity check
02-22 10:44:36.516 27393 27412 W QField  : QPngHandler: Failed to parse ICC profile
02-22 10:44:36.583 27393 27412 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 10:44:36.583 27393 27412 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 10:44:37.073 27393 27412 W QField  : qrc:/qml/qgismobileapp.qml:192: TypeError: Cannot read property 'frozen' of null in file qrc:/qml/qgismobileapp.qml line 192
02-22 10:44:37.073 27393 27412 W QField  : qrc:/qml/qgismobileapp.qml:1108:9: Unable to assign [undefined] to GnssPositionInformation in file qrc:/qml/qgismobileapp.qml line 1108
02-22 10:44:37.073 27393 27412 W QField  : qrc:/qml/qgismobileapp.qml:2013:5: Unable to assign [undefined] to GnssPositionInformation in file qrc:/qml/qgismobileapp.qml line 2013
02-22 10:44:37.256 27393 27412 W QField  : Case insensitive sorting unsupported in the posix collation implementation
--------- beginning of crash


dave@dave-ThinkPad-T590:~$ adb logcat -c
dave@dave-ThinkPad-T590:~$ adb logcat ActivityManager:I QField:D *:S
--------- beginning of main
--------- beginning of system
02-22 10:47:10.676  3674  3674 E ActivityManager: TouchDown intent received, starting ActiveLaunch
02-22 10:47:10.704  3674  3674 I ActivityManager: Start proc 29627:ch.opengis.qfield/u0a87 for activity ch.opengis.qfield/.QFieldActivity
02-22 10:47:10.731  3674 10639 I ActivityManager: DSS on for ch.opengis.qfield and scale is 1.0
02-22 10:47:10.753  3674 10639 I ActivityManager: START u0 {act=android.intent.action.MAIN typ=null flg=0x10200000 cmp=ComponentInfo{ch.opengis.qfield/ch.opengis.qfield.QFieldActivity}} from uid 10063
02-22 10:47:11.318  3674  3703 I ActivityManager: Displayed ch.opengis.qfield/.QFieldActivity: +536ms (total +46s525ms)
02-22 10:47:12.057 29627 29644 W QField  : Unsupported ICC input color space 47524159
02-22 10:47:12.057 29627 29644 W QField  : fromIccProfile: failed general sanity check
02-22 10:47:12.057 29627 29644 W QField  : QPngHandler: Failed to parse ICC profile
02-22 10:47:12.109 29627 29644 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 10:47:12.200 29627 29644 W QField  : Unsupported ICC input color space 47524159
02-22 10:47:12.200 29627 29644 W QField  : fromIccProfile: failed general sanity check
02-22 10:47:12.200 29627 29644 W QField  : QPngHandler: Failed to parse ICC profile
02-22 10:47:12.267 29627 29644 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 10:47:12.267 29627 29644 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 10:47:12.660  3674  4414 I ActivityManager: START u0 {act=ch.opengis.qfield.QFieldAppRaterActivity typ=null flg=0x0 cmp=ComponentInfo{ch.opengis.qfield/ch.opengis.qfield.QFieldAppRaterActivity}} from uid 10087
02-22 10:47:12.714 29627 29644 W QField  : qrc:/qml/qgismobileapp.qml:192: TypeError: Cannot read property 'frozen' of null in file qrc:/qml/qgismobileapp.qml line 192
02-22 10:47:12.714 29627 29644 W QField  : qrc:/qml/qgismobileapp.qml:1108:9: Unable to assign [undefined] to GnssPositionInformation in file qrc:/qml/qgismobileapp.qml line 1108
02-22 10:47:12.714 29627 29644 W QField  : qrc:/qml/qgismobileapp.qml:2013:5: Unable to assign [undefined] to GnssPositionInformation in file qrc:/qml/qgismobileapp.qml line 2013
02-22 10:47:12.882 29627 29644 W QField  : Case insensitive sorting unsupported in the posix collation implementation
--------- beginning of crash
02-22 10:47:13.986  3674 29671 W ActivityManager: crash : ch.opengis.qfield,0
02-22 10:47:13.988  3674 29671 W ActivityManager:   Force finishing activity ch.opengis.qfield/.QFieldActivity
02-22 10:47:14.003  3674  3695 I ActivityManager: Showing crash dialog for package ch.opengis.qfield u0
02-22 10:47:14.106  3674  4413 I ActivityManager: Process ch.opengis.qfield (pid 29627) has died: vis  +99TOP (159,1779)
02-22 10:47:14.136  3674  3703 W ActivityManager: setHasOverlayUi called on unknown pid: 29627
02-22 10:47:14.155  3674  4416 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.sec.android.app.launcher:10063?v=0 pkg=com.google.android.googlequicksearchbox } U=0: not found

```

VERSION 1703 (https://github.com/opengisch/QField/pull/1703#issuecomment-783256211)

```
dave@dave-ThinkPad-T590:~$ adb logcat -c
dave@dave-ThinkPad-T590:~$ adb logcat QField:D *:S
--------- beginning of main
--------- beginning of system
02-22 11:19:17.388 22714 22730 W QField  : Unsupported ICC input color space 47524159
02-22 11:19:17.388 22714 22730 W QField  : fromIccProfile: failed general sanity check
02-22 11:19:17.388 22714 22730 W QField  : QPngHandler: Failed to parse ICC profile
02-22 11:19:17.436 22714 22730 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 11:19:17.527 22714 22730 W QField  : Unsupported ICC input color space 47524159
02-22 11:19:17.527 22714 22730 W QField  : fromIccProfile: failed general sanity check
02-22 11:19:17.527 22714 22730 W QField  : QPngHandler: Failed to parse ICC profile
02-22 11:19:17.593 22714 22730 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 11:19:17.593 22714 22730 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 11:19:18.030 22714 22730 W QField  : qrc:/qml/qgismobileapp.qml:1109:9: Unable to assign [undefined] to GnssPositionInformation in file qrc:/qml/qgismobileapp.qml line 1109
02-22 11:19:18.030 22714 22730 W QField  : qrc:/qml/qgismobileapp.qml:2122:5: Unable to assign [undefined] to GnssPositionInformation in file qrc:/qml/qgismobileapp.qml line 2122
02-22 11:19:18.185 22714 22730 W QField  : Case insensitive sorting unsupported in the posix collation implementation
--------- beginning of crash

dave@dave-ThinkPad-T590:~$ adb logcat -c
dave@dave-ThinkPad-T590:~$ adb logcat ActivityManager:I QField:D *:S
--------- beginning of main
--------- beginning of system
02-22 11:20:06.782  3674  3674 E ActivityManager: TouchDown intent received, starting ActiveLaunch
02-22 11:20:06.812  3674  3674 I ActivityManager: Start proc 22812:ch.opengis.qfield_beta/u0a87 for activity ch.opengis.qfield_beta/.QFieldActivity
02-22 11:20:06.853  3674 11202 I ActivityManager: START u0 {act=android.intent.action.MAIN typ=null flg=0x10200000 cmp=ComponentInfo{ch.opengis.qfield_beta/ch.opengis.qfield_beta.QFieldActivity}} from uid 10063
02-22 11:20:06.860  3674 10025 I ActivityManager: DSS on for ch.opengis.qfield_beta and scale is 1.0
02-22 11:20:07.341  3674  3703 I ActivityManager: Displayed ch.opengis.qfield_beta/.QFieldActivity: +476ms
02-22 11:20:08.113 22812 22827 W QField  : Unsupported ICC input color space 47524159
02-22 11:20:08.113 22812 22827 W QField  : fromIccProfile: failed general sanity check
02-22 11:20:08.113 22812 22827 W QField  : QPngHandler: Failed to parse ICC profile
02-22 11:20:08.160 22812 22827 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 11:20:08.251 22812 22827 W QField  : Unsupported ICC input color space 47524159
02-22 11:20:08.251 22812 22827 W QField  : fromIccProfile: failed general sanity check
02-22 11:20:08.251 22812 22827 W QField  : QPngHandler: Failed to parse ICC profile
02-22 11:20:08.313 22812 22827 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 11:20:08.313 22812 22827 W QField  : Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
02-22 11:20:08.745  3674 11202 I ActivityManager: START u0 {act=ch.opengis.qfield_beta.QFieldAppRaterActivity typ=null flg=0x0 cmp=ComponentInfo{ch.opengis.qfield_beta/ch.opengis.qfield_beta.QFieldAppRaterActivity}} from uid 10087
02-22 11:20:08.788 22812 22827 W QField  : qrc:/qml/qgismobileapp.qml:1109:9: Unable to assign [undefined] to GnssPositionInformation in file qrc:/qml/qgismobileapp.qml line 1109
02-22 11:20:08.788 22812 22827 W QField  : qrc:/qml/qgismobileapp.qml:2122:5: Unable to assign [undefined] to GnssPositionInformation in file qrc:/qml/qgismobileapp.qml line 2122
02-22 11:20:08.952 22812 22827 W QField  : Case insensitive sorting unsupported in the posix collation implementation
--------- beginning of crash
02-22 11:20:10.063  3674 22855 W ActivityManager: crash : ch.opengis.qfield_beta,0
02-22 11:20:10.065  3674 22855 W ActivityManager:   Force finishing activity ch.opengis.qfield_beta/.QFieldActivity
02-22 11:20:10.076  3674  3693 I ActivityManager: Showing crash dialog for package ch.opengis.qfield_beta u0
02-22 11:20:10.160  3674  5192 I ActivityManager: Process ch.opengis.qfield_beta (pid 22812) has died: vis  +99TOP (175,1934)
02-22 11:20:10.172  3674  3703 W ActivityManager: setHasOverlayUi called on unknown pid: 22812
02-22 11:20:10.183  3674  8305 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.sec.android.app.launcher:10063?v=0 pkg=com.google.android.googlequicksearchbox } U=0: not found

```

**Pull request closed without merging**
