### PR TITLE
Kill a bunch of warnings, helps debugging

### PR DESCRIPTION
**Pull request by nirvn**
Clears the console a bit, makes it easier to see *new* warnings from code being added.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-a199169dc1ce31b9508ad18d0e5958f14a765f4d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-a199169dc1ce31b9508ad18d0e5958f14a765f4d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-a199169dc1ce31b9508ad18d0e5958f14a765f4d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-a199169dc1ce31b9508ad18d0e5958f14a765f4d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-98fdaf1ee22019f7c78c7134cb3c0c4fa995acb7-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-98fdaf1ee22019f7c78c7134cb3c0c4fa995acb7-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-98fdaf1ee22019f7c78c7134cb3c0c4fa995acb7-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-98fdaf1ee22019f7c78c7134cb3c0c4fa995acb7-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-7673ef0fd89ad6d429a2769141c7e3dbd0855818-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-7673ef0fd89ad6d429a2769141c7e3dbd0855818-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-7673ef0fd89ad6d429a2769141c7e3dbd0855818-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-7673ef0fd89ad6d429a2769141c7e3dbd0855818-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-fb310803e7384c6873d2b74a5606287a549633e3-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-fb310803e7384c6873d2b74a5606287a549633e3-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-fb310803e7384c6873d2b74a5606287a549633e3-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-806-fb310803e7384c6873d2b74a5606287a549633e3-x86_64.apk)

**Comment by m-kuhn** [comment]
Probably good. Hard to say ;P

**Pull request merged**
