### PR TITLE
Fix search bar x clear action on virtual keyboards, increase hit area

### LINKED ISSUE #1512: "X" button in search input doesn't clear text
The "X" button in the search lime edit just closes the search box, but doesn't clear any existing text.

### Reproduction Steps:

1. Open search
2. Enter text
3. Click clear

### Expected behavior:

Text is cleared

### Observed behavior:

Search is closed, but text is remembered

### Screenshots and GIFs

Screenshots and GIFs which follow reproduction steps to demonstrate the problem

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 1.8.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

### PR DESCRIPTION
**Pull request by nirvn**
This fixes an issue with virtual keyboards and the search bar not clearing text when hitting the X clear button.

While testing on my smartphone, my large fingers didn't play well with the relatively small "hit" area, so I've tried to improve that on behalf of all large finger users.

Fixes #1512

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d2dad6eb5f1ce85cf3e16f34283a8d7879d95076:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-2dcfa0b6a07274182de16110992a4158fae74682-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-2dcfa0b6a07274182de16110992a4158fae74682-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-2dcfa0b6a07274182de16110992a4158fae74682-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-2dcfa0b6a07274182de16110992a4158fae74682-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for dee2a975a49c373dd399c7a1739e27c9fb294f5c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-164f9798c235c3e5d8ae11b9a4bb10e57bad923d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-164f9798c235c3e5d8ae11b9a4bb10e57bad923d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-164f9798c235c3e5d8ae11b9a4bb10e57bad923d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-164f9798c235c3e5d8ae11b9a4bb10e57bad923d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1959053e01259ecc6596949601dd1861a359ea28:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-09fe532b3d2bebb7a30b09a44147b93cdd3d3aa4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-09fe532b3d2bebb7a30b09a44147b93cdd3d3aa4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-09fe532b3d2bebb7a30b09a44147b93cdd3d3aa4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-09fe532b3d2bebb7a30b09a44147b93cdd3d3aa4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4cbaea358d184b85df028ca1fa94c5341a60a174:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-1277649d9ada4957854e1300a42f3a344bb91124-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-1277649d9ada4957854e1300a42f3a344bb91124-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-1277649d9ada4957854e1300a42f3a344bb91124-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-1277649d9ada4957854e1300a42f3a344bb91124-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 16124bf326bfa85d3a4cf804645551bb3b4fd6b2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-965f8d92ee4adea24d3b84f0a4572e18665dd002-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-965f8d92ee4adea24d3b84f0a4572e18665dd002-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-965f8d92ee4adea24d3b84f0a4572e18665dd002-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-965f8d92ee4adea24d3b84f0a4572e18665dd002-x86.apk)

**Comment by nirvn** [comment]
@nyalldawson , alright, this should fix the X issue you reported. Virtual keyboards are a PITA.

**Comment by nyalldawson** [comment]
This is a step forward, but there's still an oddity - the target area for showing the search field seems to differ from that for hiding the search field. So if I double tap on the search icon, the bar doesn't disappear. Instead you have to move the finger slightly right to get it to hide, then back left again to reshow it...

**Comment by nirvn** [comment]
@nyalldawson , right, the search button doesn't toggle, it only shows the panel. I've had it this way thinking there are likely a number of people out there thinking they need to hit that button to trigger the search. 

That said, now that we have a beautiful spinner in there, maybe the button could be a toggle.

@m-kuhn , @signedav , thoughts?

**Comment by signedav** [comment]
I prefer that it closes by hitting the search button again.
I think that I would rather press "Done"/"Enter" on the keyboard when I think I need to do something to trigger the search.
And if a user clicks it accidentially (because he wants to trigger the search) his text and search result would not be lost when he reopens. So I think he can live with it.

**Comment by nirvn** [comment]
OK, sounds good to me.

**Comment by nirvn** [comment]
Done, it has a nice feel to it too. Thanks @nyalldawson for these useful comments.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 64a55d03154f65a4c50205d8dd601c3972d02e3b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-bcc9c2d45472c55953b17ac83005a28c25f9a76d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-bcc9c2d45472c55953b17ac83005a28c25f9a76d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-bcc9c2d45472c55953b17ac83005a28c25f9a76d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1524-bcc9c2d45472c55953b17ac83005a28c25f9a76d-x86.apk)

**Review by m-kuhn — APPROVED** [review]
Feels good now, thanks

**Pull request merged**
