### PR TITLE
use modified icons for the different apps (main, dev/beta and PR)

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-aa924575e0e12b93eb31a4fc82097980266ceff0-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-aa924575e0e12b93eb31a4fc82097980266ceff0-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-aa924575e0e12b93eb31a4fc82097980266ceff0-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-aa924575e0e12b93eb31a4fc82097980266ceff0-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-06e075764b4870c47e022efc19dea7f2d2090611-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-06e075764b4870c47e022efc19dea7f2d2090611-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-06e075764b4870c47e022efc19dea7f2d2090611-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-06e075764b4870c47e022efc19dea7f2d2090611-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-f4aa133e02f1983a599f6619bce7707262b1564e-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-f4aa133e02f1983a599f6619bce7707262b1564e-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-f4aa133e02f1983a599f6619bce7707262b1564e-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-f4aa133e02f1983a599f6619bce7707262b1564e-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-31c7c95d61bbada0cb1dd1a83f96fd248da34c2d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-31c7c95d61bbada0cb1dd1a83f96fd248da34c2d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-31c7c95d61bbada0cb1dd1a83f96fd248da34c2d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-31c7c95d61bbada0cb1dd1a83f96fd248da34c2d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-0879515c7b3d1ceb1604a94d2456150267d88cae-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-0879515c7b3d1ceb1604a94d2456150267d88cae-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-0879515c7b3d1ceb1604a94d2456150267d88cae-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-0879515c7b3d1ceb1604a94d2456150267d88cae-x86_64.apk)

**Comment by 3nids** [comment]
image

image

**Comment by mbernasocchi** [comment]
@3nids the beta is good, I guess to test the dev one we have to merge right?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-de39ef0c4a4646e07910fce3c06f2b3daf346945-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-de39ef0c4a4646e07910fce3c06f2b3daf346945-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-de39ef0c4a4646e07910fce3c06f2b3daf346945-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-845-de39ef0c4a4646e07910fce3c06f2b3daf346945-x86_64.apk)

**Comment by nirvn** [comment]
:heart:

**Pull request merged**
