### PR TITLE
Implement a follow compass orientation mode

### PR DESCRIPTION
**Pull request by nirvn**
With this PR, clicking twice on the bottom-right positioning button will have QField's map canvas follow _both_ the location as well as compass orientation.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0768097de4840c5d447bea9bf66a54d3165f965f: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3955-71e2cc54470008c11f4773beac6b56604af984bd-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3955-71e2cc54470008c11f4773beac6b56604af984bd-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3955-71e2cc54470008c11f4773beac6b56604af984bd-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3955-71e2cc54470008c11f4773beac6b56604af984bd-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3955-71e2cc54470008c11f4773beac6b56604af984bd-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3955-71e2cc54470008c11f4773beac6b56604af984bd-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3955-71e2cc54470008c11f4773beac6b56604af984bd-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-3955-71e2cc54470008c11f4773beac6b56604af984bd-x86-android.apk)
</details>

**Review by suricactus — APPROVED** [review]
Code looks good, didn't test myself.

Is it on purpose that `function followOrientation()` uses 2 spaces indent and function onRotationChanged()` 4, while in the same (mega) file?

**Comment by nirvn** [comment]
@suricactus , re spacing, yeah, we'll eventually need to run a script against all QML files, two big inconsistencies ATM include:
- 4 space vs 2 space
- if ( spaces ) vs if(spaceless)
- if (...) { vs. if (...)<newline>{

**Comment by suricactus** [comment]
Unfortunately the official QML linter and formatter was crap the last time I tried it (the one shipped with 5.15).

**Pull request merged**
