### PR TITLE
feat: update softwareVersion android_5_v1.0.3 in publiccode.yml

### PR DESCRIPTION
**Pull request by qfield-fairy**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a8f6db3970943cd60128c13981c27296930d8cc8:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-2cd809249f0a96a954eceec2afa9ecbf106e9318-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-2cd809249f0a96a954eceec2afa9ecbf106e9318-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-2cd809249f0a96a954eceec2afa9ecbf106e9318-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-2cd809249f0a96a954eceec2afa9ecbf106e9318-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0a1e2fc70308d51875b038520175300624e64581:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-95dc954bd7d5fea27246b08a1c166ef53539ede2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-95dc954bd7d5fea27246b08a1c166ef53539ede2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-95dc954bd7d5fea27246b08a1c166ef53539ede2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-95dc954bd7d5fea27246b08a1c166ef53539ede2-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c7057c88c40c8459d5fb26cc2f2b44b8f087c4e6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-caff1d232009b6321f2735d58111308b753c0653-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-caff1d232009b6321f2735d58111308b753c0653-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-caff1d232009b6321f2735d58111308b753c0653-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1989-caff1d232009b6321f2735d58111308b753c0653-x86.apk)

**Comment by m-kuhn** [comment]
I think we need to disable this. Too many false prs opened...

CC @astagi

**Pull request closed without merging**
