### PR TITLE
Support opening of 7z and rar archives as standalone datasets

### PR DESCRIPTION
**Pull request by nirvn**
Unlocked by adding [lib]archive driver support in gdal. Since libarchive is already in vcpkg's repository this makes it super easy to unlock and upstream.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 191abc028c8710d1f4f553ae828e5a5f2a578e2f: [**arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5780-a7d14515964d7faff701bfe4f9f5fef6f5a8240d-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5780-a7d14515964d7faff701bfe4f9f5fef6f5a8240d-android-arm-neon.apk)
- [x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5780-a7d14515964d7faff701bfe4f9f5fef6f5a8240d-android-x64.apk)
- [x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5780-a7d14515964d7faff701bfe4f9f5fef6f5a8240d-android-x86.apk)
- [**all access arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5780-a7d14515964d7faff701bfe4f9f5fef6f5a8240d-android-arm64.apk)
- [all access arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5780-a7d14515964d7faff701bfe4f9f5fef6f5a8240d-android-arm-neon.apk)
- [all access x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5780-a7d14515964d7faff701bfe4f9f5fef6f5a8240d-android-x64.apk)
- [all access x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5780-a7d14515964d7faff701bfe4f9f5fef6f5a8240d-android-x86.apk)
</details>

**Review by m-kuhn — APPROVED** [review]
It shouldn't be hard to unlock libarchive too (I guess a nes wlag to disable tools), but that's a good start 👍
If you upstream like this, better add a `supports: !ios` flag to libarchive too.

**Comment by nirvn** [comment]
@m-kuhn , yeah I was thinking about modifying libarchive too.

**Comment by m-kuhn** [comment]
good job!

**Comment by nirvn** [comment]
@m-kuhn , upstreaming done in the two following PRs:
- https://github.com/microsoft/vcpkg/pull/41896
- https://github.com/microsoft/vcpkg/pull/41897

**Pull request merged**
