### PR TITLE
allow to copy text from clipboard in search bar

### PR DESCRIPTION
**Pull request by 3nids**
but what is the use case?
waiting for feedback

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-470-429334ef3412b17e0634e39a81aded87aad3f9ec-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-470-429334ef3412b17e0634e39a81aded87aad3f9ec-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-470-87ce2467e7093e87d3f157a5cc42b54caf2ec5e6-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-470-87ce2467e7093e87d3f157a5cc42b54caf2ec5e6-x86.apk)

**Comment by m-kuhn** [comment]
> but what is the use case?

what was the developpement triggered by?

> waiting for feedback

from who?

**Comment by 3nids** [comment]
I got no reply, I will turn this down for now as I don't really see a benefit from copying from the search bar.

**Comment by 3nids** [comment]
@m-kuhn Client says it's interesting to be able to copy/paste in both direction. I don't have a strong opinion here, but I guess it doesn't hurt if it's there?

**Comment by m-kuhn** [comment]
I don't see any risks involved, so I'd rather merge.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-470-84eaedd233a6241101941a5a521eb5524dbd7104-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-470-84eaedd233a6241101941a5a521eb5524dbd7104-x86.apk)

**Pull request merged**
