### PR TITLE
Geotag indicator for external resource (i.e. picture) widget

### PR DESCRIPTION
**Pull request by nirvn**
This PR adds a visual indicator floating over external resource pictures to indicate the presence of geotags:
Screenshot from 2020-02-08 16-03-44

This is achieved by making use of QGIS' QgsExifTools class (thanks to Nyall for that one). It requires for https://github.com/qgis/QGIS/pull/34367 to be merged and the QField SDK to be updated. It also means QField would add QGIS' analysis library, which on the short term might be a bit of an overkill but on the longer term is likely going to benefit QField in other areas.

### CODE REVIEW

**Comment by nirvn** [comment]
(ping @m-kuhn as this will require your participation :) )

**Comment by nirvn** [comment]
An alternative to incorporating qgis' analysis lib is to copy/paste QgsExifTools class into QField, but that would come with maintenance burden et cie.

**Comment by m-kuhn** [comment]
https://github.com/opengisch/OSGeo4A/releases/tag/20200209

**Comment by nirvn** [comment]
@m-kuhn , you're the best. Can I already update this PR to point to that SDK?

**Comment by m-kuhn** [comment]
It's currently building, try in ~2 hours

**Comment by nirvn** [comment]
@m-kuhn , OK -- in the meantime, any idea why the build is failing to locate the clang++: error: no such file or directory: '/home/osgeo4a/armeabi-v7a/lib/libqgis_analysis.so' ? Did you not only sync QGIS source to master but also toggled on the making of analysis?

**Comment by m-kuhn** [comment]
@nirvn analysis was never built for and shipped in osgeo4a.
The error pops up because it's required by this PR ( your changes ;) ). I'll trigger a new build that includes analysis.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-807-11ef4cf83daa0dfd30987f793f3d18e22112c786-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-807-11ef4cf83daa0dfd30987f793f3d18e22112c786-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-807-11ef4cf83daa0dfd30987f793f3d18e22112c786-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-807-11ef4cf83daa0dfd30987f793f3d18e22112c786-x86_64.apk)

**Comment by nirvn** [comment]
@3nids , @m-kuhn , for the record, I tried an alternative approach to registring ExifTools, using qmlRegisterUncreatableType(...), and it didn't work (gave me an error along the lines of hasTag is not a function of [ Object object ] or something.

**Comment by 3nids** [comment]
> I tried an alternative approach to registring ExifTools, using qmlRegisterUncreatableType

It's `qmlRegisterSingletonType`, look at `utilsSingletonProvider` in the header

**Comment by nirvn** [comment]
@3nids , ah, TIL. @m-kuhn , do you have an implementation preference here?

**Comment by nirvn** [comment]
@3nids , by 'pin' you mean this:
Screenshot from 2020-02-10 17-19-56
?

**Comment by 3nids** [comment]
> Screenshot from 2020-02-10 17-19-56

yes

**Comment by 3nids** [comment]
what do you think of grey when it's not geotagged, and some color when it's present?

**Comment by nirvn** [comment]
I'd prefer nothing when no geotag, and a white (or QField green) icon when geotagging is detected.

**Comment by m-kuhn** [comment]
> @3nids , ah, TIL. @m-kuhn , do you have an implementation preference here?

I don't see any technical differences (except for ownership and amount of code required), no preference on my end (yet). Others?

> I'd prefer nothing when no geotag, and a white (or QField green) icon when geotagging is detected.

... or a stroked-through version (I think with the "unstable" background color of pictures a different icon is better suited than a different color of the same icon).
+1 for white as color.

**Comment by 3nids** [comment]
let's move the discussion of the singletons to: https://github.com/opengisch/QField/pull/813

regarding the icon, what do you think of the stroked version @nirvn ?

**Comment by nirvn** [comment]
As suggested by both @3nids and @m-kuhn , I've added a pair of geotag images (present vs missing), and updated the code so that images with no geo tag found have a no geotag badge.

Image with geotag:
Screenshot from 2020-02-12 12-55-35

Image without geotag:
Screenshot from 2020-02-12 12-55-51

A subtle drop shadow was also added to insure visibility of icon over light background.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-807-6c2212da206e0b25d47bfa262ca1674567a45513-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-807-6c2212da206e0b25d47bfa262ca1674567a45513-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-807-6c2212da206e0b25d47bfa262ca1674567a45513-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-807-6c2212da206e0b25d47bfa262ca1674567a45513-x86_64.apk)

**Comment by 3nids** [comment]
awesome!
side question, would it be possible that in the scenario you show above (only one picture in the frame) that the picture gets bigger?

**Comment by nirvn** [comment]
@3nids , sure, we could tweak the width of the image and add a maximum height constraint (I'm thinking portrait images for e.g.).

**Comment by 3nids** [comment]
interesting, the test is actually failing here but Travis was green

**Comment by nirvn** [comment]
Hmm, true; odd, I'm not sure what's happening here. Actually, the skd.conf likely refers to the osgeo4a SDK. Maybe travis' testing build isn't building qgis_analysis?

**Comment by nirvn** [comment]
No, ignore that, the log says otherwise:

-- Found QGIS: 3.11.0
```
-- Found QGIS core: /usr/lib/libqgis_core.so
-- Found QGIS gui: /usr/lib/libqgis_gui.so
-- Found QGIS analysis: /usr/lib/libqgis_analysis.so
```

**Comment by 3nids** [comment]
The test is using the Docker image
last build: https://travis-ci.org/qgis/QGIS/jobs/649357243
which contains the exiftools

**Comment by m-kuhn** [comment]
If I can help with something, let me know

**Pull request merged**
