### PR TITLE
PROJ 8.0.1, libspatialite 5.0.1, yay

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7eab884dc0ba6ed1c1f219214798a3d844f08777:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-a24792f45ee2e8f15e68933fcacf13b44c916c29-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-a24792f45ee2e8f15e68933fcacf13b44c916c29-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-a24792f45ee2e8f15e68933fcacf13b44c916c29-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-a24792f45ee2e8f15e68933fcacf13b44c916c29-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 93769b11e61739141210f03a46c52fe09b07fa51:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-466060c6108d91ccfcd6937e78bb82f46795b378-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-466060c6108d91ccfcd6937e78bb82f46795b378-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-466060c6108d91ccfcd6937e78bb82f46795b378-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-466060c6108d91ccfcd6937e78bb82f46795b378-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 836f97e5a3ab2be009a2db9c1f96135eb5c530cc:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-564f79ded72aaffdf0f4f19cef6eda48a016e61d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-564f79ded72aaffdf0f4f19cef6eda48a016e61d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-564f79ded72aaffdf0f4f19cef6eda48a016e61d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-564f79ded72aaffdf0f4f19cef6eda48a016e61d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a02dba368c56ee4909ced1f15595ba15483ef816:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-2d6131bfbbb7f1fb79c8854ce3a3c6cfeececa01-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-2d6131bfbbb7f1fb79c8854ce3a3c6cfeececa01-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-2d6131bfbbb7f1fb79c8854ce3a3c6cfeececa01-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-2d6131bfbbb7f1fb79c8854ce3a3c6cfeececa01-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7ff73ef387026da0cf42e258f45cd32efa5ecc74:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-1b5d5fa2b74f61249988993eacac16f5a52bc650-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-1b5d5fa2b74f61249988993eacac16f5a52bc650-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-1b5d5fa2b74f61249988993eacac16f5a52bc650-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-1b5d5fa2b74f61249988993eacac16f5a52bc650-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cf1ee6056bff7c54cb7ca55596fc5ffd3338a9ee:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-32b48a6f96ef1a41f55cb344f5cc80f5485b1c91-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-32b48a6f96ef1a41f55cb344f5cc80f5485b1c91-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-32b48a6f96ef1a41f55cb344f5cc80f5485b1c91-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-32b48a6f96ef1a41f55cb344f5cc80f5485b1c91-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cb70eda806d8e73b3a3f4460fd365b2770c71393:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-add3fb4cfa9f0480fb499e285510573c878fdd28-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-add3fb4cfa9f0480fb499e285510573c878fdd28-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-add3fb4cfa9f0480fb499e285510573c878fdd28-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-add3fb4cfa9f0480fb499e285510573c878fdd28-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fdd6c4df8a4fe506602831bcb4dba52dd8f74167:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-79b594b1dd3d42774711932e9a5d64d3e25c48ae-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-79b594b1dd3d42774711932e9a5d64d3e25c48ae-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-79b594b1dd3d42774711932e9a5d64d3e25c48ae-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-79b594b1dd3d42774711932e9a5d64d3e25c48ae-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 147492341ff651ce16bda3c37ea326c95fa1ffba:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-22fd34d910d6f0052528961309fc7d286f9e0df9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-22fd34d910d6f0052528961309fc7d286f9e0df9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-22fd34d910d6f0052528961309fc7d286f9e0df9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-22fd34d910d6f0052528961309fc7d286f9e0df9-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6b00b3132f08d1e311c61b96a71444c0b6e33ac3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-9f2f2573a7938e0fc84d85e5a45618d01df497da-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-9f2f2573a7938e0fc84d85e5a45618d01df497da-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-9f2f2573a7938e0fc84d85e5a45618d01df497da-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-9f2f2573a7938e0fc84d85e5a45618d01df497da-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5267f9491d10ea1969e117251bc849ba43405b0c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-4100eb033cd9597316c49a18f99a13f1ef30261b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-4100eb033cd9597316c49a18f99a13f1ef30261b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-4100eb033cd9597316c49a18f99a13f1ef30261b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-4100eb033cd9597316c49a18f99a13f1ef30261b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5ab0281f6e7a109d59c839187af57e9887f01fa1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-f98dfb56121c7e70b7734af35e10c51fca493af9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-f98dfb56121c7e70b7734af35e10c51fca493af9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-f98dfb56121c7e70b7734af35e10c51fca493af9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-f98dfb56121c7e70b7734af35e10c51fca493af9-x86.apk)

**Comment by nirvn** [comment]
@m-kuhn , vcpkg build fails:

```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

That doesn't seem to be implicitly linked to the changes I made here, any idea what's wrong? If possible, I'd merge this PR as is and deal with the issue in a separate PR so we can get oauth2 QField builds out for testing.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 023a8560a279de945518bcca7ea28dbc7d14eb9f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-d49161b00b47da9cd158538afcaaa8fbf96b6931-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-d49161b00b47da9cd158538afcaaa8fbf96b6931-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-d49161b00b47da9cd158538afcaaa8fbf96b6931-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-d49161b00b47da9cd158538afcaaa8fbf96b6931-x86.apk)

**Comment by m-kuhn** [comment]
Does that speak to you?

```
Performing C++ SOURCE FILE Test COMPILER_HAS_DEPRECATED_ATTR failed with the following output:
Change Dir: C:/src/buildtrees/qgis/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe cmTC_e18fd.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  src.cxx

C:\src\buildtrees\qgis\x64-windows-dbg\CMakeFiles\CMakeTmp\src.cxx(1,16): error C2065: '__deprecated__': undeclared identifier [C:\src\buildtrees\qgis\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_e18fd.vcxproj]

C:\src\buildtrees\qgis\x64-windows-dbg\CMakeFiles\CMakeTmp\src.cxx(1,31): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\src\buildtrees\qgis\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_e18fd.vcxproj]

C:\src\buildtrees\qgis\x64-windows-dbg\CMakeFiles\CMakeTmp\src.cxx(1,37): error C2448: '__attribute__': function-style initializer appears to be a function definition [C:\src\buildtrees\qgis\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_e18fd.vcxproj]



Source file was:
__attribute__((__deprecated__)) int somefunc() { return 0; }
    int main() { return somefunc();}
Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/src/buildtrees/qgis/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe cmTC_48a64.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  CheckIncludeFile.c

C:\src\buildtrees\qgis\x64-windows-dbg\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\src\buildtrees\qgis\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_48a64.vcxproj]


```

**Comment by nirvn** [comment]
Nope :( this might be completely unrelated but I'll offer this bit anyways: the only time I saw a pthread error, it had to do with pdal.

**Comment by m-kuhn** [comment]
Might be sthng else

```
>  C:\builddir\vcpkg_installed\x64-windows\include\spatialindex\MovingRegion.h(155,49): error C2504: 'binary_function': base class undefined (compiling source file C:\src\buildtrees\qgis\src\99f8270f7a-60adedfa0c.clean\src\core\vector\qgsvectorlayerdiagramprovider.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
>          C:\builddir\vcpkg_installed\x64-windows\include\spatialindex\MovingRegion.h(155,49): error C2143: syntax error: missing ',' before '<' (compiling source file C:\src\buildtrees\qgis\src\99f8270f7a-60adedfa0c.clean\src\core\vector\qgsvectorlayerdiagramprovider.cpp) [C:\src\buildtrees\qgis\x64-windows-dbg\src\core\qgis_core.vcxproj]
> 
>     7 Warning(s)
>     48 Error(s)
> 
```

**Comment by m-kuhn** [comment]
I may have copied too little. It's the last lines from install out log, something related to std.

**Comment by nirvn** [comment]
@m-kuhn , QGIS 3.20 did apply loads of update using c++17, that could have caused problems with vcpkg?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9bf67f15e630c76b0d621ffd9ff38c2534d69ea6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-3674f899d060f8a02ab9216fc4cd4433dcad54a2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-3674f899d060f8a02ab9216fc4cd4433dcad54a2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-3674f899d060f8a02ab9216fc4cd4433dcad54a2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-3674f899d060f8a02ab9216fc4cd4433dcad54a2-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 48cce63ab78a300bbdbf0ab532dc2ad334859862:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-4290c9ab14721c2e1d5d10c9405543ba6e4190dc-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-4290c9ab14721c2e1d5d10c9405543ba6e4190dc-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-4290c9ab14721c2e1d5d10c9405543ba6e4190dc-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-4290c9ab14721c2e1d5d10c9405543ba6e4190dc-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7778e8f92b7ead55e0e97691ca9a517b4c68a6b5:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-14a4a3ca99da31aa65b38678c6ceadc99286190f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-14a4a3ca99da31aa65b38678c6ceadc99286190f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-14a4a3ca99da31aa65b38678c6ceadc99286190f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1905-14a4a3ca99da31aa65b38678c6ceadc99286190f-x86.apk)

**Comment by nirvn** [comment]
Success, libspatialindex needed updating.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
