### PR TITLE
Fixed the projects list download feedback

### PR DESCRIPTION
**Pull request by suricactus**
Turns out delegate within a delegate does not work properly. This PR temporarily disables the "public" tab until I find a better sollution.
image

### CODE REVIEW

**Comment by suricactus** [comment]
For those doing a review https://github.com/opengisch/QField/pull/1781/files?diff=split&w=1

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 18e1740adf9536e1bd810c622b9ace76e700c3d0:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-f8a59115187a15b69f33fc64f4eeeb5d19b7da70-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-f8a59115187a15b69f33fc64f4eeeb5d19b7da70-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-f8a59115187a15b69f33fc64f4eeeb5d19b7da70-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-f8a59115187a15b69f33fc64f4eeeb5d19b7da70-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0000050ced399a116001058c3d4f3bda9ddad220:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-03221e5fa400925de210c834e0c2239a39baf8bb-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-03221e5fa400925de210c834e0c2239a39baf8bb-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-03221e5fa400925de210c834e0c2239a39baf8bb-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-03221e5fa400925de210c834e0c2239a39baf8bb-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1c0e81eafeee11b36b59bb5864fba9b44e9ee857:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-caa11ef54e022f79357ca56d3f8ecafca38f9632-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-caa11ef54e022f79357ca56d3f8ecafca38f9632-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-caa11ef54e022f79357ca56d3f8ecafca38f9632-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1781-caa11ef54e022f79357ca56d3f8ecafca38f9632-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
