### PR TITLE
Use vcpkg overlay instead of custom repository

### PR DESCRIPTION
**Pull request by m-kuhn**
Makes management a lot easier because qgis updates can go with one pull request (instead of two interdependent ones)

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 99274dd6b2154f0d43bbfdadf63e52e22b399cd5:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-85234df1e49761f3ceb6dfe2e96b46f23ef627e5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-85234df1e49761f3ceb6dfe2e96b46f23ef627e5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-85234df1e49761f3ceb6dfe2e96b46f23ef627e5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-85234df1e49761f3ceb6dfe2e96b46f23ef627e5-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 83f585df16e2f20653daf9f66168a56733e41adb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-a6763fbdea85993872ceb21fe4c30dbad8f08192-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-a6763fbdea85993872ceb21fe4c30dbad8f08192-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-a6763fbdea85993872ceb21fe4c30dbad8f08192-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-a6763fbdea85993872ceb21fe4c30dbad8f08192-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c12c36f290be1c83c4250e31e775079f67555f83:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-dc23c010faab3ca52adf0da701929fb0c1501865-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-dc23c010faab3ca52adf0da701929fb0c1501865-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-dc23c010faab3ca52adf0da701929fb0c1501865-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-dc23c010faab3ca52adf0da701929fb0c1501865-x86.apk)

**Comment by nirvn** [comment]
@m-kuhn , you need to update libspatialindex to 1.9.3 to fix QGIS compilation (see https://github.com/opengisch/vcpkg/commit/25a5af376e742868aad421dcc5f474c423b6cb2f)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9afb49b08cfab0c54d351de2eacc209e7dce1fda:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-d1a2ee1c440e4cc7b5021a306b7fb22242cfc94b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-d1a2ee1c440e4cc7b5021a306b7fb22242cfc94b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-d1a2ee1c440e4cc7b5021a306b7fb22242cfc94b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-d1a2ee1c440e4cc7b5021a306b7fb22242cfc94b-x86.apk)

**Comment by m-kuhn** [comment]
@nirvn https://github.com/microsoft/vcpkg/pull/17506

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4dee4d7c3b72214e7642f3dfdb235ab38ba2fd46:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-fa2bfbb944d53273536ab781bc769fbfb4a249e0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-fa2bfbb944d53273536ab781bc769fbfb4a249e0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-fa2bfbb944d53273536ab781bc769fbfb4a249e0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-fa2bfbb944d53273536ab781bc769fbfb4a249e0-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a0b39d600ab6a391c490047f30aa4093f97922ab:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-56288c5897f507e64f2c44072a43a34661a7d0f0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-56288c5897f507e64f2c44072a43a34661a7d0f0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-56288c5897f507e64f2c44072a43a34661a7d0f0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1915-56288c5897f507e64f2c44072a43a34661a7d0f0-x86.apk)

**Review by nirvn — APPROVED** [review]
Very cool stuff.

**Pull request merged**
