### PR TITLE
Fix freehand digitizing within geometry editor tools

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 8b7bb4c3b81dea0e1a0c7d07393cf4dfd95d5602: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4551-435de8c407f7b3702336fe8d26fc55a703249e4e-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4551-435de8c407f7b3702336fe8d26fc55a703249e4e-arm-neon-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4551-435de8c407f7b3702336fe8d26fc55a703249e4e-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4551-435de8c407f7b3702336fe8d26fc55a703249e4e-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4551-435de8c407f7b3702336fe8d26fc55a703249e4e-arm64-android.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4551-435de8c407f7b3702336fe8d26fc55a703249e4e-arm-neon-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4551-435de8c407f7b3702336fe8d26fc55a703249e4e-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4551-435de8c407f7b3702336fe8d26fc55a703249e4e-x86-android.apk)
</details>

**Review by suricactus — APPROVED** [review]
I see a missing curly brace `{`.

**Review by suricactus — CHANGES_REQUESTED** [review]
I see a missing curly bracket `{` after the modified `if`.

**Comment by nirvn** [comment]
@suricactus , done.

**Review by suricactus — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
