### PR TITLE
More legend backports

### PR DESCRIPTION
**Pull request by nirvn**
More legend widget backports to 1.6 prior to 1.6.1 release.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1140-237d9c32466fe42c9f4ed120fa4fe2b72e013a16-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1140-237d9c32466fe42c9f4ed120fa4fe2b72e013a16-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1140-237d9c32466fe42c9f4ed120fa4fe2b72e013a16-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1140-237d9c32466fe42c9f4ed120fa4fe2b72e013a16-x86_64.apk)

**Comment by Emic37** [comment]
Hi @nirvn,
There is no arrow to minimize the groups anymore. Is it normal?  
Then, in the 1.6.0, the scroll is faster and it was better. Now, the scroll is slower anymore.

**Comment by nirvn** [comment]
@Emic37 , yes, groups can't be collapsed anymore as we've migrated away from a tree widget. So, :ballot_box_with_check: normal :wink: 

I'm perplexed at the scrolling speed. Are you in a position to record your screen and provide us with MP4s of 'fast scroll' vs. 'slow scroll'? We added some logic but I'd be surprised it had such a big impact.

**Comment by Emic37** [comment]
Ok. That's pity : the navigation is more difficult when we have really many layers. 

For scrolling, I don't think a video may highlight the difference but on use, there is it. 
I had reported many month ago that scrolling seemed laggy. It was like there is a little inertia.

With 1.6.0, it was better. I don't know if you will see what I want to say but the scroll followed better the finger. It's simply smoother.

Also I noted his difference all over the app.

**Pull request merged**
