### PR TITLE
Fix that it tries to open a folder on image click without file

### PR DESCRIPTION
**Pull request by signedav**
Check if a file exists on image press because otherwise it tries to open a folder.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-889-97d6e76e3024138ec4d96312340b13c14996787d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-889-97d6e76e3024138ec4d96312340b13c14996787d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-889-97d6e76e3024138ec4d96312340b13c14996787d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-889-97d6e76e3024138ec4d96312340b13c14996787d-x86_64.apk)

**Comment by m-kuhn** [comment]
Can we modify this to `FileUtils.isFile(fileName)` in this case? I think that's more verbose than the proposed check.

**Comment by signedav** [comment]
I decided otherwise. The function `fileExists` returns only true if 1 the file exists and 2 it's a file. I think otherwise it's misleading anyway.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-889-269912940cd9413b0c01cc6effca4a76380eaebd-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-889-269912940cd9413b0c01cc6effca4a76380eaebd-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-889-269912940cd9413b0c01cc6effca4a76380eaebd-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-889-269912940cd9413b0c01cc6effca4a76380eaebd-x86_64.apk)

**Pull request merged**
