### PR TITLE
Better demo titles

### PR DESCRIPTION
**Pull request by nirvn**
Since we're making use of titles in the welcome screen now, let's have some better title strings. Full disclosure: those aren't great, but consistent :)

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-763-3fa37942643e1c3f096549773c4da8c15eb9ad73-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-763-3fa37942643e1c3f096549773c4da8c15eb9ad73-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-763-3fa37942643e1c3f096549773c4da8c15eb9ad73-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-763-3fa37942643e1c3f096549773c4da8c15eb9ad73-x86_64.apk)

**Comment by signedav** [comment]
Good idea.

The "online" in the bumblebee project would be misleading since it does not store the data online, like the online survey does. It just contains an osm map.
The most important thing about this project is, that it's simple. Means small forms without any constraints.

So I would prefer "simple bees demo" but I understand that it's not consistent anymore. But what do you think about.
- Simple bees demo (or easy)
- Complex bees demo (or advanced)
- Online survey demo

The fact that one project contains "online" implicates that the others are not online, so the "offline" is not needed anymore...

**Comment by signedav** [comment]
And maybe change the filename as well.

**Comment by nirvn** [comment]
@signedav , I'll finish this PR once the welcome revolution PR is merged.

**Pull request closed without merging**
