### PR TITLE
Improve vertex editor UI/UX

### PR DESCRIPTION
**Pull request by nirvn**
This PR applies a set of UI/UX improvements to the vertex editor tool. First, the GIF:
Peek 2020-04-09 11-48

Changes include:
- Getting rid of the yellow color (this goes back to my first set of commits to QField where we agreed to try and reduce the color palette used by QField); IMHO, a much, *much* clearer look
- The previous and next vertex buttons now sit next to each other; in my vertex edits, I've often found myself navigating left and right, and having those two buttons closer saves time; it's also a better grouping for a busy toolbar
- The way the tool deals with operation cancellation has been harmonized with the two other editing tools. 
- When a vertex was selected but not yet moved, the model wasn't dirtied, allowing user to switch to another tool and have their tools collide; that's fixed by cancelling any tool operation when clicking on the switch button

Vertex editor tool, before vs. PR:
image

Geometry editor tools before vs. PR:
image

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-99954d237591a3ad6c018bb56b51b04d72d010d3-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-99954d237591a3ad6c018bb56b51b04d72d010d3-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-99954d237591a3ad6c018bb56b51b04d72d010d3-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-99954d237591a3ad6c018bb56b51b04d72d010d3-x86_64.apk)

**Comment by nirvn** [comment]
The second commit improves the icons for QField's geometry editor tools:
Screenshot from 2020-04-09 12-25-28

Improvements include:
- the icon for the vertex editor tool features a square symbol for the vertex, which is what we use onthe canvas (and it also harmonizes looks with the related topological editing icon)
- the icon for the split tool has a line added to it, to avoid people wrongly thinking that icon is about cutting the geometry onto the clipboard
- icons are white, since we use white icons on green button background (for e.g., the check "ok" button, the search button, etc.)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-08e40de0847576df936b07a32c87d8743d23ecdf-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-08e40de0847576df936b07a32c87d8743d23ecdf-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-08e40de0847576df936b07a32c87d8743d23ecdf-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-08e40de0847576df936b07a32c87d8743d23ecdf-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-0e56f459ab0d2acc70f4bfdd24dd73bfd882a668-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-0e56f459ab0d2acc70f4bfdd24dd73bfd882a668-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-0e56f459ab0d2acc70f4bfdd24dd73bfd882a668-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-941-0e56f459ab0d2acc70f4bfdd24dd73bfd882a668-x86_64.apk)

**Comment by VxTedxV** [comment]
Looking better !
Btw I don't understand what the third green button is designed for ...

**Pull request merged**
