### PR TITLE
Dashboard fixes

### PR DESCRIPTION
**Pull request by signedav**
- Remove title of map-themes
- Legend in same groupbox like the map-theme combo
image

I need to check how it looks like on device. And needs good testing to check if the focus handling is still correct...

PS. And yes, I will set up my local apk build environment, so I don't need to open a PR for every test :slightly_smiling_face:

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-2f8b9bb0ce551e4df0e6254362733ec3e5853316-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-2f8b9bb0ce551e4df0e6254362733ec3e5853316-x86.apk)

**Comment by signedav** [comment]
Hmm... Looks fine but margin issue is still existing...

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-7d82f706622a03cc930a8acef0241f13d472b3e2-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-7d82f706622a03cc930a8acef0241f13d472b3e2-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-85df9f9b8e8abdd33548a7e27a6a5db67b4e6564-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-85df9f9b8e8abdd33548a7e27a6a5db67b4e6564-x86.apk)

**Comment by signedav** [comment]
Looks like this now:
Screenshot_20190318-114458_QField
screenshot_20190318-114315_qfield

Please check it on your devices and test if it's still working like before @mbernasocchi

**Comment by mbernasocchi** [comment]
@signedav testing. have a look at #525 i played a bit with the margin there. you can also close it

**Comment by mbernasocchi** [comment]
@signedave looks great

**Comment by signedav** [comment]
Woopsy - Haven't seen your work there @mbernasocchi - funny that it seems you tried first to set a margin for the whole legend as well and then on the second try you did the `Styles.TreeViewStyle` - exactly like me...
The approach is the same, but it seems you haven't used the `indentation` Why? Haven't you seen it or is there a reason not to use it?

**Comment by mbernasocchi** [comment]
@signedav can you reduce the space vetween the arrow and the text? half would probably be enough

**Comment by mbernasocchi** [comment]
@signedave git log will tell you what time it was ;)

**Comment by signedav** [comment]
> @signedav can you reduce the space vetween the arrow and the text? half would probably be enough

That's the empty space where a symbol could be. If we crop it on empty symbol, then the legend could be ugly when some have symbols and other don't...

**Comment by signedav** [comment]
> @signedave git log will tell you what time it was ;)

Hehe. Sounds familiar...

**Comment by mbernasocchi** [comment]
what symbol do you mean? you mean single symbol simbology?

**Comment by signedav** [comment]
Yes

**Comment by mbernasocchi** [comment]
Screenshot_20190318-122529_QField
Screenshot_20190318-122441_QField

**Comment by signedav** [comment]
Phu... No idea if it could have been solved more elegant. The issue is, that the space for the expand/unexpand icon is displayed anyway on tree view. So I had to make a little hack. Looks like this: 
image
Please test @mbernasocchi

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-097173e560b72594c4f7803da4be27273f4d3b47-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-097173e560b72594c4f7803da4be27273f4d3b47-x86.apk)

**Comment by mbernasocchi** [comment]
# Perfect and beautiful at start
WhatsApp Image 2019-03-18 at 18 26 46 (4)
WhatsApp Image 2019-03-18 at 18 26 46 (3)

# Some cache like Issues when opening another project
WhatsApp Image 2019-03-18 at 18 26 46 (2)
WhatsApp Image 2019-03-18 at 18 26 46 (1)

# Perfect again after killing QField
WhatsApp Image 2019-03-18 at 18 26 46

**Comment by mbernasocchi** [comment]
@signedav wonderful job, just need to figure out the cache-like proble an then we can merge.
Thanks a lot

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-f7c7c50bdbcb1097fba243b9d744477a253bbcec-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-f7c7c50bdbcb1097fba243b9d744477a253bbcec-x86.apk)

**Comment by signedav** [comment]
Still problems - but I guess I know what...

**Comment by signedav** [comment]
This could most probably be solved cleaner by fixing the ImageProvider. Obviously there are "old" images, what would not mind if there wouldn't be "old" layers somewhere. I couldn't find it... so I did :tada: another slightly dirty hack, that in case it's a branch, there is an overlaying rectangle under the expand-icon. So if there is an old symbol - we do not see it...

Btw. the issue with the "old" symbol has been existent before this PR already...

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-fd21bb16a21d526b17834335cd65328b2cb305a7-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-fd21bb16a21d526b17834335cd65328b2cb305a7-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-031e93edd8875f4ac8c3f4f3284e63fbae069fdd-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-527-031e93edd8875f4ac8c3f4f3284e63fbae069fdd-x86.apk)

**Pull request merged**
