### PR TITLE
Sunday improvements to file picker / welcome screen

### PR DESCRIPTION
**Pull request by nirvn**
This PR improves the Android file picker by using a pair of icons to differentiate project files (.qgs, .qgz) vs. individual datasets. Following the support for individual dataset loading, it had become a bit harder to visually spot the project files in a directory with mixed content.

Before (left) vs. PR:
image

It has the bonus effect of harmonizing the Android file picker with QField's welcome screen by using the map project icon. Speaking of that, the recent projects list also makes use of the new dataset icon:
image

Finally, the desktop file picker has a received a bit of love. By default, all supported file types are shown (matching Android file picker behavior), and because nobody likes to be driven insane by machines, it now remembers the last opened directory. Should help push forward the thin plate of glass project too :)

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 79c71b5caf11f2ae556b90aad8b6162f62b71107:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-b513e94f170523a2a12716e6e2f08dc35b82f99f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-b513e94f170523a2a12716e6e2f08dc35b82f99f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-b513e94f170523a2a12716e6e2f08dc35b82f99f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-b513e94f170523a2a12716e6e2f08dc35b82f99f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c2cddcd34812fad2c1fc62081c179d5d32737d5c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-81d90ffa2daa5f16930101fd4a1a6aa1028db4c9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-81d90ffa2daa5f16930101fd4a1a6aa1028db4c9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-81d90ffa2daa5f16930101fd4a1a6aa1028db4c9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-81d90ffa2daa5f16930101fd4a1a6aa1028db4c9-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 971604154a50d111099773f683b4f378b3a45edf:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-3e9670f24d13ef700da27335fdb7c8ea8ca6f632-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-3e9670f24d13ef700da27335fdb7c8ea8ca6f632-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-3e9670f24d13ef700da27335fdb7c8ea8ca6f632-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1701-3e9670f24d13ef700da27335fdb7c8ea8ca6f632-x86.apk)

**Review by m-kuhn — APPROVED** [review]
:+1:

**Pull request merged**
