### PR TITLE
Fix when attempting to get absolute path of disconnected external storage

### PR DESCRIPTION
**Pull request by nirvn**
Fix ~~a~~two crashers reported on sentry (:heart:)

### CODE REVIEW

**Review by suricactus — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9d9724100b5fb8225a039b718dae0349d6f2f8e1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-1b84d4f452a31deb6ccdb420414c68890e408f18-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-1b84d4f452a31deb6ccdb420414c68890e408f18-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-1b84d4f452a31deb6ccdb420414c68890e408f18-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-1b84d4f452a31deb6ccdb420414c68890e408f18-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0ca989195877a71244ff21d49ad1205489a1bcd4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-f755d7d5afc6a64aeec791f33130b1ff511d9530-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-f755d7d5afc6a64aeec791f33130b1ff511d9530-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-f755d7d5afc6a64aeec791f33130b1ff511d9530-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-f755d7d5afc6a64aeec791f33130b1ff511d9530-x86.apk)

**Comment by m-kuhn** [comment]
Thank you for keeping old hardware usable :heart:

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1b65cce8fd313f5d44709594f46f715cb1858ad1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-d833653d7246f3ae6ea53e8bf4ab986d63c1b631-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-d833653d7246f3ae6ea53e8bf4ab986d63c1b631-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-d833653d7246f3ae6ea53e8bf4ab986d63c1b631-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-d833653d7246f3ae6ea53e8bf4ab986d63c1b631-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 315b010ba8a49226f910b24c4f30f3f8feed43e4:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-761216da225c17626e08c10fc6cc795ada2c734e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-761216da225c17626e08c10fc6cc795ada2c734e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-761216da225c17626e08c10fc6cc795ada2c734e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-761216da225c17626e08c10fc6cc795ada2c734e-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3d0988928755e7dbefab49c4c43f7597f0edefc3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-f788bd997f8722c375f7d122902d0eccf4947124-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-f788bd997f8722c375f7d122902d0eccf4947124-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-f788bd997f8722c375f7d122902d0eccf4947124-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-f788bd997f8722c375f7d122902d0eccf4947124-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 279d8a3050e7bd4b14ac9055ee6425b63eb9e1fb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-52ccc497197c8695afc5884386b10a0b10fdddf4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-52ccc497197c8695afc5884386b10a0b10fdddf4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-52ccc497197c8695afc5884386b10a0b10fdddf4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-52ccc497197c8695afc5884386b10a0b10fdddf4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6155b352e3adb41c1908942d4ef0f322ca061b26:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-d026fe4c83fbd0ae8dec0f83d22c0ed7a469b2c4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-d026fe4c83fbd0ae8dec0f83d22c0ed7a469b2c4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-d026fe4c83fbd0ae8dec0f83d22c0ed7a469b2c4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2425-d026fe4c83fbd0ae8dec0f83d22c0ed7a469b2c4-x86.apk)

**Pull request merged**
