### PR TITLE
feature form take full screen when in portrait mode

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-423-f4882e9ab6534d11f740f6f5ff4a906f2bd6b7c0-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-423-f4882e9ab6534d11f740f6f5ff4a906f2bd6b7c0-x86.apk)

**Comment by m-kuhn** [comment]
This definitely makes sense on phones.
Does it also make sense on all tablets? Or should it be triggered by a screen width instead of orientation?

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-423-04e4583504b97e4d07743aed0bce4f23ec1180ab-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-423-04e4583504b97e4d07743aed0bce4f23ec1180ab-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-423-1340f3c7b8149fd813e750a0224926e7aeb558a3-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-423-1340f3c7b8149fd813e750a0224926e7aeb558a3-x86.apk)

**Pull request merged**
