### PR TITLE
Fix search only triggered when hitting space

### PR DESCRIPTION
**Pull request by nirvn**
@3nids , can you confirm search is fixed for you when the APKs pop up? Thanks

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-ee1b39a924b09b54658801c6b1d6528a3abe0b51-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-ee1b39a924b09b54658801c6b1d6528a3abe0b51-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-ee1b39a924b09b54658801c6b1d6528a3abe0b51-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-ee1b39a924b09b54658801c6b1d6528a3abe0b51-x86_64.apk)

**Comment by 3nids** [comment]
sorry, still the same (need to hit space)

**Comment by nirvn** [comment]
Hm -- @3nids , can you check against QField 1.6.0 to see if was a problem then?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-f3521c8ef3f1610c6be9d033483c83d1b4e9ed99-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-f3521c8ef3f1610c6be9d033483c83d1b4e9ed99-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-f3521c8ef3f1610c6be9d033483c83d1b4e9ed99-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-f3521c8ef3f1610c6be9d033483c83d1b4e9ed99-x86_64.apk)

**Comment by 3nids** [comment]
same issue for me 1.6.0

**Comment by nirvn** [comment]
Ah good to know it was a problem before I started tweaking the search bar.

Maybe it's a QtQuick 2 upgrade issue. Was it a problem in 1.5.3?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-d2a2678ede480638a2f506acb05cd2cf6f87f026-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-d2a2678ede480638a2f506acb05cd2cf6f87f026-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-d2a2678ede480638a2f506acb05cd2cf6f87f026-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-d2a2678ede480638a2f506acb05cd2cf6f87f026-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-972764c1c6e2d922464afe671cfe2fa54f687b7d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-972764c1c6e2d922464afe671cfe2fa54f687b7d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-972764c1c6e2d922464afe671cfe2fa54f687b7d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-972764c1c6e2d922464afe671cfe2fa54f687b7d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-72f066a1b65f067f369250ada62d1428b611dea2-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-72f066a1b65f067f369250ada62d1428b611dea2-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-72f066a1b65f067f369250ada62d1428b611dea2-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-72f066a1b65f067f369250ada62d1428b611dea2-x86_64.apk)

**Comment by 3nids** [comment]
sorry still the same here
(the box is now correctly sized though)

issue is here also on 1.5.2…

**Comment by nirvn** [comment]
Ahh good to know, it's something that's been there forever then.

The problem lies with the way qt handles virtual keyboards. If you disable predictive text on your Android, you'll see it works just fine.

Why the hint flags aren't fixing this is mystery to me.

In any case the 1.7 UI/UX revamp of the search bar while help here as ppl will instinctively hit the search button (not visible pre 1.7), which applies content of typed word on virtual keyboards.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-d8ef6db751ed2e2ff001de65179ed1bfb0708fd2-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-d8ef6db751ed2e2ff001de65179ed1bfb0708fd2-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-d8ef6db751ed2e2ff001de65179ed1bfb0708fd2-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1207-d8ef6db751ed2e2ff001de65179ed1bfb0708fd2-x86_64.apk)

**Comment by nirvn** [comment]
@3nids , good news, the latest revision of this commit fixes the spacing issue.

Amazing nobody has stumbled on this before now :) 

I'll forwardport this onto master.

**Comment by 3nids** [comment]
I confirm this is fixed with last APK 🎉

**Comment by mbernasocchi** [comment]
fixed for me too

**Pull request merged**
