### PR TITLE
Revamp the about dialog

### PR DESCRIPTION
**Pull request by m-kuhn**
Makes the about dialog usable in protrait mode

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-679-67b826bfb3af98b70d83f62cf150140776e9d0e7-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-679-67b826bfb3af98b70d83f62cf150140776e9d0e7-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-679-67b826bfb3af98b70d83f62cf150140776e9d0e7-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-679-67b826bfb3af98b70d83f62cf150140776e9d0e7-x86_64.apk)

**Comment by nirvn** [comment]
I'd stack the developed by and support development parts on top of one another. Right now, it looks odd as they aren't horizontally aligned properly. That or finding  a way for each parts to be middle centered within two 50% of the screen  areas.

**Comment by m-kuhn** [comment]
> I'd stack the developed by and support development parts on top of one another.

Done

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-679-7e0bc43e5f8023ded5d4021e3c36e0fbdde735c3-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-679-7e0bc43e5f8023ded5d4021e3c36e0fbdde735c3-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-679-7e0bc43e5f8023ded5d4021e3c36e0fbdde735c3-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-679-7e0bc43e5f8023ded5d4021e3c36e0fbdde735c3-x86_64.apk)

**Pull request merged**
