### PR TITLE
If we can't do native, don't do native ;)

### PR DESCRIPTION
**Pull request by nirvn**
@m-kuhn , part 1 or hopefully 1 part ;)

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bbea69fbacdc09319bb32869af981b0ecabead2e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2199-ca118e66afb8c63323843388e65b244f2c680d97-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2199-ca118e66afb8c63323843388e65b244f2c680d97-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2199-ca118e66afb8c63323843388e65b244f2c680d97-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2199-ca118e66afb8c63323843388e65b244f2c680d97-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a4498f19b902a3e86734322f2725a4bd617964e8:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2199-ea8778192f7bf8ac82f4af090cda004b1b27f31f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2199-ea8778192f7bf8ac82f4af090cda004b1b27f31f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2199-ea8778192f7bf8ac82f4af090cda004b1b27f31f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2199-ea8778192f7bf8ac82f4af090cda004b1b27f31f-x86.apk)

**Comment by nirvn** [comment]
@lucienicolier , can you try this build (https://github.com/opengisch/QField/suites/3962371302/artifacts/99559104) -- I think camera should work.

**Comment by lucienicolier** [comment]
image

Yes!

**Comment by nirvn** [comment]
Belle photo!

**Pull request merged**
