### PR TITLE
Fix package data path for srs.db

### LINKED ISSUE #286: Could not open CRS database. Error (14): Unable to open database file.
Upon opening a QField project packaged via the QField Sync plugin, an alert icon appears in the upper right corner of the screen. Tapping on the alert shows the following message:

CRS
Could not open CRS database//profiles/default/qgis.db
Error(14): unable to open database file

Upon exiting this and returning to the map canvas the notification disappears and data can be collected (seemingly) without any issues and imported into QGIS, via the QField Sync plugin.

This appears to be similar to the following closed issues (which I have also experienced).

https://github.com/opengisch/QField/issues/192
https://github.com/opengisch/QField/issues/84

I'm cautious about sending staff out to collect data when the issue doesn't seem entirely resolved.

### Reproduction Steps:
Set up project and confirm 'Save paths' is set to 'Relative'

image

Confirm project CRS is set to British National Grid (EPSG 27700).

image

Confirm CRS of each layer in the project (Test Point, Test Line, Test Polygon) is set to British National Grid (EPSG 27700).

image

image

image

Package the project using QField Sync (copy all option used) and drop in the following location on device:

image

Open project in QField using the 'Open Project' dialogue:

image

Full file path copied from the QField dialogue is as follows:

/data/data/ch.opengis.qfield/files/storage/Android/data/ch.opengis.qfield/files/Test Field Package

Project opens successfully, but with error notification in upper right hand corner:

image

Error notification as follows:

image

Exiting this results in disappearance of the error icon. Activating the GPS correctly places the cursor on the map canvas. This is an an improvement on the issue highlighted in #192 by saemiw on 20th Feb whereby activation of the GPS caused the cursor to centre on a location away from the basemap in white space.

Point, line and polygon data can be collected:

image

Collected data can be imported to QGIS successfully using the QField Sync plugin and plots in the correct location.

### Expected behavior:

Project opens with no CRS warning

### Observed behavior:

Project opens with three line error warning as described above (as opposed to the multiple lines reported in #192). Upon exiting this, GPS cursor location and data collection appear to function correctly. Data can be imported into QGIS successfully.

**QField version:** 0.10.12 (although this behaviour has been observed as reported in #192 since 0.10.2)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No] - occurred as reported in #192 from v 0.10.2 onwards.

* Problem can be reliably reproduced, doesn't happen randomly: [Yes] - can be reproduced with multiple projects on different devices (Samsung Galaxy Tab Active 2, Android 7.1.1; OnePlus 5, Android 8.1.0, Samsung Galaxy Tab A, Android 7.0)

* Problem happens with all files and projects, not only some files or projects: [Yes]

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #286

### CODE REVIEW

**Comment by m-kuhn** [comment]
giedrioks26 do you have a chance to test this one?

**Comment by m-kuhn** [comment]
@giedrioks26  do you have a chance to test this one?

**Comment by giedrioks26** [comment]
Great! Works perfectly! Thank you!

**Comment by VxTedxV** [comment]
After a fresh install of QField 0.11.4 from .apk, when I opened my usual project, I still have the CRS alert.
After quitting and reopening QField, the alert disappeared -> Don't know how but it works !

**Comment by nicpitsch** [comment]
The issue is gone, great. Thanks a lot!

**Comment by mixedbredie** [comment]
Works for me running 0.11.5 - thanks for the prompt fix.

**Pull request merged**
