### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-33c27d37700acce628a622a3d6c1810fd76eb0f8-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-33c27d37700acce628a622a3d6c1810fd76eb0f8-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-33c27d37700acce628a622a3d6c1810fd76eb0f8-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-33c27d37700acce628a622a3d6c1810fd76eb0f8-x86_64.apk)

**Comment by nirvn** [comment]
🤞🤞

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-26ffd337bb808cd1fa8a5790dfe7ce88f56b253b-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-26ffd337bb808cd1fa8a5790dfe7ce88f56b253b-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-26ffd337bb808cd1fa8a5790dfe7ce88f56b253b-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-26ffd337bb808cd1fa8a5790dfe7ce88f56b253b-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-2f97e55d91542c35c980189120558ce460477d3a-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-2f97e55d91542c35c980189120558ce460477d3a-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-2f97e55d91542c35c980189120558ce460477d3a-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-2f97e55d91542c35c980189120558ce460477d3a-x86_64.apk)

**Comment by m-kuhn** [comment]
:tada:

**Comment by m-kuhn** [comment]
https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-9f5b5d8f702b75a5627cf5971d61fdf9d1a301e2-armv7.apk

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-9f5b5d8f702b75a5627cf5971d61fdf9d1a301e2-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-9f5b5d8f702b75a5627cf5971d61fdf9d1a301e2-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-9f5b5d8f702b75a5627cf5971d61fdf9d1a301e2-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-9f5b5d8f702b75a5627cf5971d61fdf9d1a301e2-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-7b364f02e4a3dab8e56f825845d1555fe46e4bb1-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-7b364f02e4a3dab8e56f825845d1555fe46e4bb1-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-7b364f02e4a3dab8e56f825845d1555fe46e4bb1-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-7b364f02e4a3dab8e56f825845d1555fe46e4bb1-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-6e28a2adec47c4060fce9931e93a65a8ef0004c4-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-6e28a2adec47c4060fce9931e93a65a8ef0004c4-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-6e28a2adec47c4060fce9931e93a65a8ef0004c4-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1217-6e28a2adec47c4060fce9931e93a65a8ef0004c4-x86_64.apk)

**Pull request closed without merging**
