### PR TITLE
Remove duplicating ui/LayerTreeItemProperties.qml

### PR DESCRIPTION
**Pull request by suricactus**
As we discussed here https://github.com/opengisch/QField/pull/1059#discussion_r442048521 , I remove the `./qml/ui/LayerTreeItemProperties.qml` and merge it with `./qml/LayerTreeItemProperties.qml`.

NOTE there are strings in translations that have their context marked as `LayerTreeItemProperties.ui`, I guess they should not be touched, as they are managed on transifex.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1071-89839739fea08c26862c956ae1c3872a81a7d2c3-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1071-89839739fea08c26862c956ae1c3872a81a7d2c3-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1071-89839739fea08c26862c956ae1c3872a81a7d2c3-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1071-89839739fea08c26862c956ae1c3872a81a7d2c3-x86_64.apk)

**Comment by m-kuhn** [comment]
> NOTE there are strings in translations that have their context marked as LayerTreeItemProperties.ui, I guess they should not be touched, as they are managed on transifex.

Which strings exactly? E.g. the "zoom to layer" one is broken on transifex (and I don't know why), so no worries, better replace it?

**Comment by suricactus** [comment]
For example here, available in all languages https://github.com/opengisch/QField/blob/master/i18n/qfield_af.ts#L298-L304 . AFAIK leave it as it is should not affect anything.

**Comment by m-kuhn** [comment]
It's in the .ts but it does not show up on transifex (compare https://github.com/opengisch/QField/issues/987)
I don't know why, the only difference I see from the rest of the string is the `.ui` in the context, so it would probably be good to change it.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1071-8414ea987e9458cef1491bc4bcb5ab3313df3a10-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1071-8414ea987e9458cef1491bc4bcb5ab3313df3a10-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1071-8414ea987e9458cef1491bc4bcb5ab3313df3a10-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1071-8414ea987e9458cef1491bc4bcb5ab3313df3a10-x86_64.apk)

**Comment by nirvn** [comment]
@suricactus , nice cleanup.

**Comment by m-kuhn** [comment]
"Show on map canvas" finally shows up on transifex :tada:

**Pull request merged**
