### PR TITLE
Allow text wrapping for value relation widget

### PR DESCRIPTION
**Pull request by nirvn**
@lindacamathias :

image

### CODE REVIEW

**Review by suricactus — APPROVED** [review]
Isn't in the same for the relation editor too?

**Comment by nirvn** [comment]
@suricactus , I didn't want to touch that part since you're neck deep into changing things there in your PR :)

**Comment by suricactus** [comment]
Thanks a lot. Just wanted to get a written confirmation I would not get into the conflicts hell. Feel free to merge.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5c9d7c35ee4c8fea51aeca52324cdcfa5ca97586:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1986-6ef75b5a3e54f5dc684bdacb07ba77fc31067d4c-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1986-6ef75b5a3e54f5dc684bdacb07ba77fc31067d4c-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1986-6ef75b5a3e54f5dc684bdacb07ba77fc31067d4c-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1986-6ef75b5a3e54f5dc684bdacb07ba77fc31067d4c-x86.apk)

**Comment by qfield-fairy** [comment]
The backport to `release-2_0` failed:
```
The process '/usr/bin/git' failed with exit code 128
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release-2_0 release-2_0
# Navigate to the new working tree
cd .worktrees/backport-release-2_0
# Create a new branch
git switch --create backport-1986-to-release-2_0
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 5c9d7c35ee4c8fea51aeca52324cdcfa5ca97586
# Push it to GitHub
git push --set-upstream origin backport-1986-to-release-2_0
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release-2_0
```
Then, create a pull request where the `base` branch is `release-2_0` and the `compare`/`head` branch is `backport-1986-to-release-2_0`.

**Pull request merged**
