### PR TITLE
Flag the goto locator filter as a fast one, will fetch in the main thread

### PR DESCRIPTION
**Pull request by nirvn**
@m-kuhn , that should make the goto locator blazingly fast even when QField has access to only one thread.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1197-ba3329fb87c105fda98fb2cc470b035df987c34c-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1197-ba3329fb87c105fda98fb2cc470b035df987c34c-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1197-ba3329fb87c105fda98fb2cc470b035df987c34c-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1197-ba3329fb87c105fda98fb2cc470b035df987c34c-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1197-2db5901120097a8ca7ea1f4dff8cd20344f5b0a4-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1197-2db5901120097a8ca7ea1f4dff8cd20344f5b0a4-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1197-2db5901120097a8ca7ea1f4dff8cd20344f5b0a4-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1197-2db5901120097a8ca7ea1f4dff8cd20344f5b0a4-x86_64.apk)

**Comment by m-kuhn** [comment]
Looks good to me, should work in theory, but @VxTedxV had different test results.
Let's still merge?

**Comment by nirvn** [comment]
@m-kuhn , yeah, good to merge in any case.

**Pull request merged**
