### PR TITLE
Add more translations

### LINKED ISSUE #708: Translation Portuguese (Brazil) (pt_BR)
Hello,

The translation Portuguese (Brazil) (pt_BR) is completed in transifex.
Do I need to do anything to apply?

Thanks a lot.

### PR DESCRIPTION
**Pull request by m-kuhn**
Brazilian portuguese and Turkish

Fix #708

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-711-59f448979ee259fb745d8bc457db4aba68418cd8-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-711-59f448979ee259fb745d8bc457db4aba68418cd8-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-711-59f448979ee259fb745d8bc457db4aba68418cd8-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-711-59f448979ee259fb745d8bc457db4aba68418cd8-x86_64.apk)

**Comment by m-kuhn** [comment]
@ElvisDahnert can you test this?

**Comment by ElvisDahnert** [comment]
@m-kuhn  
It works. However, when the system language is changed, Portuguese (Brazil) is kept **(QT qfield)**, but **qfield_android** is changed.

### Portuguese (Brazil)
photo_2019-11-13_09-27-17 photo_2019-11-13_09-27-23

### English (United States)
photo_2019-11-13_09-27-28 photo_2019-11-13_09-27-32

**Comment by m-kuhn** [comment]
When you change the language during QField runtime or with restarting QField?

**Comment by ElvisDahnert** [comment]
Yes, I restarted QField and continued in **Portuguese (Brazil)** when the language settings are in **English**.
QField returns to **English** when I remove **Portuguese (Brazil)** from the language list.
I did a test keeping a list with **Portuguese (generic)**, **English** and vice versa, QField respected the hierarchy.
Conclusion: If **Portuguese (Brazil)** is listed as a language, no matter what the sequence, QField Beta 711 will work with this language.
Not a problem, just curious.

photo_2019-11-13_23-06-09

**Comment by m-kuhn** [comment]
That's likely related to how [Qt handles translations](https://doc.qt.io/qt-5/qtranslator.html) and if it works for you, let's not touch it ;)

**Comment by ElvisDahnert** [comment]
For me it works.
Thanks.

**Comment by m-kuhn** [comment]
@signedav good to merge?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-711-d6a468a238334b992ccd5476d679beb50432c70d-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-711-d6a468a238334b992ccd5476d679beb50432c70d-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-711-d6a468a238334b992ccd5476d679beb50432c70d-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-711-d6a468a238334b992ccd5476d679beb50432c70d-x86_64.apk)

**Pull request merged**
