### PR TITLE
Remove version numbering from all QML imports

### PR DESCRIPTION
**Pull request by nirvn**
This is legacy stuff from Qt5, and it causes erroneous warnings in QtCreator.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 117d470f57fdfa9c9a1b848c08fb40b3a0b4b970: [**arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5572-1ed5ec99f80907ef68caa9a7d833937edf4d1956-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5572-1ed5ec99f80907ef68caa9a7d833937edf4d1956-android-arm-neon.apk)
- [x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5572-1ed5ec99f80907ef68caa9a7d833937edf4d1956-android-x64.apk)
- [x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5572-1ed5ec99f80907ef68caa9a7d833937edf4d1956-android-x86.apk)
- [**all access arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5572-1ed5ec99f80907ef68caa9a7d833937edf4d1956-android-arm64.apk)
- [all access arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5572-1ed5ec99f80907ef68caa9a7d833937edf4d1956-android-arm-neon.apk)
- [all access x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5572-1ed5ec99f80907ef68caa9a7d833937edf4d1956-android-x64.apk)
- [all access x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5572-1ed5ec99f80907ef68caa9a7d833937edf4d1956-android-x86.apk)
</details>

**Comment by m-kuhn** [comment]
@mohsenD98 can you review this?

**Comment by mohsenD98** [comment]
> @mohsenD98 can you review this?

sure.

**Comment by mohsenD98** [comment]
Grate work @nirvn  :+1: 

--- 

these files left over:
* tst_editorwidgets.qml
* tst_featureForm.qml
* tst_positioning.qml
* tst_qFieldGuide.qml

also in `FeatureForm.qml` [line 323] && `BrowserPanel.qml` [line 88]:
```QML
Qt.createQmlObject('import QtWebView 1.14
```

---

+ Sample projects tested, no issue occurred.  :+1:

**Review by mohsenD98 — APPROVED** [review]

**Pull request merged**
