### PR TITLE
Android 5

### PR DESCRIPTION
**Pull request by m-kuhn**
!!!Don't merge, for review only!!!

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-511-5afb1f44d31c09a3c4562222099ab35cb2210b0c-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-511-5afb1f44d31c09a3c4562222099ab35cb2210b0c-x86.apk)

**Comment by signedav** [comment]
Seems to work fine :-)

**Comment by signedav** [comment]
Screenshot_2019-03-12-11-15-31
File selector looks hacky but  works fine.

**Comment by m-kuhn** [comment]
Thanks @mbernasocchi please rebase and release :)

**Comment by mbernasocchi** [comment]
@signedav will rebase and ask you to retest

**Pull request closed without merging**
