### PR TITLE
Increase font size

### PR DESCRIPTION
**Pull request by m-kuhn**
Based on https://twitter.com/timlinux/status/1193777205706448896
Fix #710

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-916756be7aa205374dd3b21434686ef7a8e84a7c-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-916756be7aa205374dd3b21434686ef7a8e84a7c-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-916756be7aa205374dd3b21434686ef7a8e84a7c-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-916756be7aa205374dd3b21434686ef7a8e84a7c-x86_64.apk)

**Comment by m-kuhn** [comment]
@timlinux what do you think about the increased size?

Hint: I like it a lot ;)

https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-916756be7aa205374dd3b21434686ef7a8e84a7c-arm64_v8a.apk

**Comment by timlinux** [comment]
Hi! Thanks for the tweaks! I tried test it but had no luck installing any of the above apks on my Huawei P Smart :-( I just get an 'app not installed' message.

**Comment by m-kuhn** [comment]
Ah shit, we need to fix the beta builds. If you uninstall QField first you will succeed but that means loosing all settings.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-338bcedde9ba3ba1ee53ba8188828050576f8fa1-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-338bcedde9ba3ba1ee53ba8188828050576f8fa1-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-338bcedde9ba3ba1ee53ba8188828050576f8fa1-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-338bcedde9ba3ba1ee53ba8188828050576f8fa1-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-a2626c296eab25f61e1c2fd8048a25c15429b148-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-a2626c296eab25f61e1c2fd8048a25c15429b148-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-a2626c296eab25f61e1c2fd8048a25c15429b148-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-a2626c296eab25f61e1c2fd8048a25c15429b148-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-467248483f96b4f296277348ca01c7ffea793c83-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-467248483f96b4f296277348ca01c7ffea793c83-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-467248483f96b4f296277348ca01c7ffea793c83-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-467248483f96b4f296277348ca01c7ffea793c83-x86_64.apk)

**Comment by m-kuhn** [comment]
@timlinux does the latest one work better ? https://download.opengis.ch/qfield/ci-builds/qfield-dev-710-467248483f96b4f296277348ca01c7ffea793c83-arm64_v8a.apk

**Comment by timlinux** [comment]
Hi @m-kuhn 

OK cool that works - thanks! The font is much more readable now. It still seems a tiny bit smaller now than the labels, but that is more a question of a sense of balance rather than legibility.

 

opengis qfield_beta

**Comment by m-kuhn** [comment]
Glad we did this patch recently to have one central place where to change all fonts together :smile:

**Comment by m-kuhn** [comment]
@timlinux if you find more places where font updates would be required, please open an issue for that.

**Comment by Emic37** [comment]
> @Emic37 so unrelated question, what's your opinion about the adjusted font size?

@m-kuhn, I'm not really fan of this new font size. The principal disavantage of the increasing the size of the fonts is that to display a same strings now need more place on the screen. 
I found the font used in the past was a good compromise.

But the increasing is small, so it's not crippling. I just notice a strange behavior contrary of @timlinux. The only places where the font size was increased are the

- field content
- them drop list
- menus
- parameters

It ensues that the font of the content of fields is now bigger than the font of the titles of fields, groups, or tabs. 

In the forms, using the same font size is maybe sufficient because these strings are bolded?  


Screenshot_20191111-222006_QField Beta 710

**Comment by nirvn** [comment]
@m-kuhn , good move, font size looks good here.

@Emic37 , I like your project style :)

**Pull request merged**
