### PR TITLE
OSGeo4a 20191203

### PR DESCRIPTION
**Pull request by signedav**
Wait for build of OSGeo4a before merge

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-735-9cd08b045ca6022f1bdad0455d39e098b1dff0d4-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-735-9cd08b045ca6022f1bdad0455d39e098b1dff0d4-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-735-9cd08b045ca6022f1bdad0455d39e098b1dff0d4-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-735-9cd08b045ca6022f1bdad0455d39e098b1dff0d4-x86_64.apk)

**Comment by ElvisDahnert** [comment]
Sorry for testing this request after closing.

> Uploaded test apks for
> 
> * [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-735-9cd08b045ca6022f1bdad0455d39e098b1dff0d4-armv7.apk)
> * [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-735-9cd08b045ca6022f1bdad0455d39e098b1dff0d4-arm64_v8a.apk)
> * [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-735-9cd08b045ca6022f1bdad0455d39e098b1dff0d4-x86.apk)
> * [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-735-9cd08b045ca6022f1bdad0455d39e098b1dff0d4-x86_64.apk)

I noticed two problems with this APK.
1. labels do not work, even in demo projects.
2. when moving the map, the screen goes black. 

Comparing:

### **QField 1.3.1 (10301993)**
your_gif_from_mp4togif_com_1576118037248



### **QField Beta 735**
your_gif_from_mp4togif_com_1576118118030

Thank you very much!

**Comment by m-kuhn** [comment]
Thanks for the feedback.
Could you test the latest 1.3.2 release from yesterday? https://github.com/opengisch/QField/releases

**Comment by ElvisDahnert** [comment]
Of course yes.
Unfortunately, the same problem occurs in version 1.3.2 (10302993).

**Comment by m-kuhn** [comment]
@ElvisDahnert do you have access to a QGIS nightly/master build to verify your project works there?

**Comment by ElvisDahnert** [comment]
@m-kuhn, did I do what you asked me correctly?
In QGIS 3.11.0 is working with labels.

QGIS3 11 0

**Comment by signedav** [comment]
I can reproduce the label issue:

1.3.1 vs 1.3.2

**Pull request closed without merging**
