### PR TITLE
Icons for layer actions

### PR DESCRIPTION
**Pull request by m-kuhn**
image

Also removes the png version of the tracking icon

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 539b2043cfd0dcf09fe519ef6a7b1092d0276ac9:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1477-20e4db6dda47d1d5dd42c2567b558fc3fdd8bbd2-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1477-20e4db6dda47d1d5dd42c2567b558fc3fdd8bbd2-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1477-20e4db6dda47d1d5dd42c2567b558fc3fdd8bbd2-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1477-20e4db6dda47d1d5dd42c2567b558fc3fdd8bbd2-x86.apk)

**Comment by signedav** [comment]
Nice. Just checked the APK.

The icons are black on the mobile. Should they?
What about having the same icon for zoom to layer and zoom to map?

**Comment by suricactus** [comment]
@m-kuhn I see missing `icon.color`, if this property in `QfButton` where `icon.source` resides, should fix the black icons? Probably setting this globally in `QfButton` makes even more sense.

**Comment by m-kuhn** [comment]
I had the change locally sitting in the theme/QfButton which I didn't commit thanks to prior great work by @suricactus . Should be good now.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1c1b5ec160b230e6fe57533dc913d29825cc9afb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1477-1fd2efbbdafd60d96a99fa448d1a176df6242d43-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1477-1fd2efbbdafd60d96a99fa448d1a176df6242d43-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1477-1fd2efbbdafd60d96a99fa448d1a176df6242d43-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1477-1fd2efbbdafd60d96a99fa448d1a176df6242d43-x86.apk)

**Review by signedav — APPROVED** [review]

**Pull request merged**
