### PR TITLE
Fix uploading attachments

### PR DESCRIPTION
**Pull request by suricactus**

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1793 Investigate and fix problems uploading files](https://app.clickup.com/t/2192114/QF-1793)

**Comment by duke-nyuki** [comment]
Task linked: [QF-1776 Hide the loading bar when requests are aborted](https://app.clickup.com/t/2192114/QF-1776)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 275bbb2a908f77f2204c934ba5c088e15a0dc21e:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2557-6019a349391376d06c3d74ffd5e299d3042e5b45-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2557-6019a349391376d06c3d74ffd5e299d3042e5b45-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2557-6019a349391376d06c3d74ffd5e299d3042e5b45-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2557-6019a349391376d06c3d74ffd5e299d3042e5b45-x86-android.apk)

**Review by nirvn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 275bbb2a908f77f2204c934ba5c088e15a0dc21e:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2557-1c0fba673c352ede4259cac75ad4e433309e9403-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2557-1c0fba673c352ede4259cac75ad4e433309e9403-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2557-1c0fba673c352ede4259cac75ad4e433309e9403-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2557-1c0fba673c352ede4259cac75ad4e433309e9403-x86-android.apk)

**Pull request merged**
