### PR TITLE
Canvas follow GPS location implementation

### PR DESCRIPTION
**Pull request by nirvn**
~~(Work in progress, pushing now to get APKs)~~

This PR implements a canvas-follow-GPS-location feature. The UX logic is as follow:
- when the user clicks on the GPS button, the canvas follow location state is turned on
- if the user pans the canvas, the follow location state is turned off, and the GPS button changes its styling from a GPS-blue background to a dark gray background
- if the user re-clicks on the GPS button, the follow state is turned on again

This matches google maps' behavior (which IMHO is a good one), and saves us from adding another UI element, or worse a right-click menu item (the latter being hardly discoverable).

Since we're not re-centering the canvas every time the location changes (that'd be way too costly), the implementation uses a threshold from border value.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-91d694b243e0d2eb5e856777b2ba2a36b7ba2a33-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-91d694b243e0d2eb5e856777b2ba2a36b7ba2a33-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-91d694b243e0d2eb5e856777b2ba2a36b7ba2a33-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-91d694b243e0d2eb5e856777b2ba2a36b7ba2a33-x86_64.apk)

**Comment by nirvn** [comment]
OK, just field tested this. It's even cooler to see it live than I had imagined :wink:

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-5b80b91e2d68753b75c9dd8bd16c29ec9d7ac461-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-5b80b91e2d68753b75c9dd8bd16c29ec9d7ac461-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-5b80b91e2d68753b75c9dd8bd16c29ec9d7ac461-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-5b80b91e2d68753b75c9dd8bd16c29ec9d7ac461-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-5944411f3044d7043dd971af7f5ad198f224b1f6-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-5944411f3044d7043dd971af7f5ad198f224b1f6-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-5944411f3044d7043dd971af7f5ad198f224b1f6-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-805-5944411f3044d7043dd971af7f5ad198f224b1f6-x86_64.apk)

**Comment by nirvn** [comment]
The tweaked threshold logic is really nice on my second field testing (ie driving and walking around).

This PR really needs the screen lock prevention PR to fully appreciate it.

**Comment by m-kuhn** [comment]
Like it a LOT!

**Comment by 3nids** [comment]
Awesome, merge away

**Pull request merged**
