### PR TITLE
Notarize and staple

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 93336ebee049375ebc93961545e8215905dde6c1:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-83a9aa80611ce343502d0438f61f0aa7eec60f4a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-83a9aa80611ce343502d0438f61f0aa7eec60f4a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-83a9aa80611ce343502d0438f61f0aa7eec60f4a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-83a9aa80611ce343502d0438f61f0aa7eec60f4a-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2c969e7f39c8f512e9ad1d2f0fdbb3d96ce2b095:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-fcd72a0edd33db0a7f72e1de75f915b7e38408e8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-fcd72a0edd33db0a7f72e1de75f915b7e38408e8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-fcd72a0edd33db0a7f72e1de75f915b7e38408e8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-fcd72a0edd33db0a7f72e1de75f915b7e38408e8-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 30e65a214ceb04e4c11122b8f3762ea0b83cebe6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-dfd0e6ca2491c55cbd5e6fc59780889e5be65147-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-dfd0e6ca2491c55cbd5e6fc59780889e5be65147-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-dfd0e6ca2491c55cbd5e6fc59780889e5be65147-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-dfd0e6ca2491c55cbd5e6fc59780889e5be65147-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5d268577985b18aa1035b3f902c3b387bf771deb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-8ef125aaa7dead207e4a5894be4d2fc5073b23fd-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-8ef125aaa7dead207e4a5894be4d2fc5073b23fd-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-8ef125aaa7dead207e4a5894be4d2fc5073b23fd-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-8ef125aaa7dead207e4a5894be4d2fc5073b23fd-x86.apk)

**Comment by m-kuhn** [comment]
Test

**Comment by m-kuhn** [comment]
Test

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5d268577985b18aa1035b3f902c3b387bf771deb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-8c42917395335ee667356b4bb20b161f1c34b188-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-8c42917395335ee667356b4bb20b161f1c34b188-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-8c42917395335ee667356b4bb20b161f1c34b188-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-8c42917395335ee667356b4bb20b161f1c34b188-x86.apk)

**Comment by m-kuhn** [comment]
test

**Comment by m-kuhn** [comment]
Test

**Comment by m-kuhn** [comment]
test

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 66b01e86a0193dab5f633d5134368d7488472a46:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-eec8da300d65f89e53bd6d8dd76259f06d596a5b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-eec8da300d65f89e53bd6d8dd76259f06d596a5b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-eec8da300d65f89e53bd6d8dd76259f06d596a5b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-eec8da300d65f89e53bd6d8dd76259f06d596a5b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cc59f1536bf49235292977865e931bbc4bcb9799:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-45b6b57079726025a04d7b8067bf56a800e20732-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-45b6b57079726025a04d7b8067bf56a800e20732-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-45b6b57079726025a04d7b8067bf56a800e20732-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-45b6b57079726025a04d7b8067bf56a800e20732-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9c9517ef28077ca57ee132658f2ddbd27be292de:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-47cfcd757c03ba08d22ee002c4d9d4e62ebbaeb9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-47cfcd757c03ba08d22ee002c4d9d4e62ebbaeb9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-47cfcd757c03ba08d22ee002c4d9d4e62ebbaeb9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-47cfcd757c03ba08d22ee002c4d9d4e62ebbaeb9-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6c3703ebfb9f414b01ad5c1ecf68351dda083fde:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-033dedad6a975ce56e5b6ea29d00af965596c816-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-033dedad6a975ce56e5b6ea29d00af965596c816-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-033dedad6a975ce56e5b6ea29d00af965596c816-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-033dedad6a975ce56e5b6ea29d00af965596c816-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3cb93a27c4635fe79283e996293382058063fc98:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-4a335d7a279a85147e926acb37d4e1ea4045a571-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-4a335d7a279a85147e926acb37d4e1ea4045a571-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-4a335d7a279a85147e926acb37d4e1ea4045a571-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-4a335d7a279a85147e926acb37d4e1ea4045a571-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c82892b22637f9fd3782b29c528f0446eb2cc918:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-19d0775222be98b917ab49235e8eb5ccb18504b4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-19d0775222be98b917ab49235e8eb5ccb18504b4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-19d0775222be98b917ab49235e8eb5ccb18504b4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-19d0775222be98b917ab49235e8eb5ccb18504b4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 61572e0a4907bfb28c561675fc000a9bb3bf4867:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-9906ded56bfc58d72fe4097f46dc105402bba17b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-9906ded56bfc58d72fe4097f46dc105402bba17b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-9906ded56bfc58d72fe4097f46dc105402bba17b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2479-9906ded56bfc58d72fe4097f46dc105402bba17b-x86.apk)

**Pull request closed without merging**
