### PR TITLE
use CI run number instead of failing number of commits

### PR DESCRIPTION
**Pull request by 3nids**
and exit on error if version code is getting too close to max

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cf6e31bd295f0f3a286f6958ff433912f0e4c45c:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2169-c80f8b854e1400c1d0005f35cbb50548927f0ebf-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2169-c80f8b854e1400c1d0005f35cbb50548927f0ebf-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2169-c80f8b854e1400c1d0005f35cbb50548927f0ebf-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2169-c80f8b854e1400c1d0005f35cbb50548927f0ebf-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 7fdca32b83e0a9a33c12437bc5cb3ad2b786b902:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2169-c9b25a030bb391f13ddda47d295c72d67c70d059-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2169-c9b25a030bb391f13ddda47d295c72d67c70d059-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2169-c9b25a030bb391f13ddda47d295c72d67c70d059-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2169-c9b25a030bb391f13ddda47d295c72d67c70d059-x86.apk)

**Comment by m-kuhn** [comment]
do we have a comparison of old numbers vs new numbers?

**Comment by 3nids** [comment]
```
0019341880 is a recent build ID
0019434150 with the new system
2100000000 is max
```
The run number is depedent of the workflow, it's a bit lower on iOS, so I had to create a small offset (not to make things too complicated and keep same build ID across different platflorms)

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
@3nids I assume it's this PR that introduced the upload failures for dev packages (see https://github.com/opengisch/QField/runs/3780517312) do we need a different offset there?

**Comment by 3nids** [comment]
should be fixed here https://github.com/opengisch/QField/commit/fb866dae13dc905668590aa7cc0f90eaa4703dc4#diff-ff2e05c008be9da7c68a90edcf13c637def8b86895df1ae94ba13cc56bfd519eR44

**Pull request merged**
