### PR TITLE
Add support for loading of datasets stored in a localized data path (i.e. 'basemaps')

### PR DESCRIPTION
**Pull request by nirvn**
This PR implements a localized data paths for QField, and adds a static data path (root_external_storage/QField/basemaps/) on the android platform. 

The implementation envisions the possibility of passing on multiple data paths via a string using semicolon as separator.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-65fb9eca229c3cb99d822c988d101477214f3798-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-65fb9eca229c3cb99d822c988d101477214f3798-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-65fb9eca229c3cb99d822c988d101477214f3798-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-65fb9eca229c3cb99d822c988d101477214f3798-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-48397ef72eaec8a3ada5b0063ed3d735050cad28-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-48397ef72eaec8a3ada5b0063ed3d735050cad28-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-48397ef72eaec8a3ada5b0063ed3d735050cad28-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-48397ef72eaec8a3ada5b0063ed3d735050cad28-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-5dad09b34e7a7f7a7930cbcef6d951798681b4c1-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-5dad09b34e7a7f7a7930cbcef6d951798681b4c1-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-5dad09b34e7a7f7a7930cbcef6d951798681b4c1-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-5dad09b34e7a7f7a7930cbcef6d951798681b4c1-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-d18ecf85963962f44b9bd370b79aaca7c4d4ed42-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-d18ecf85963962f44b9bd370b79aaca7c4d4ed42-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-d18ecf85963962f44b9bd370b79aaca7c4d4ed42-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-d18ecf85963962f44b9bd370b79aaca7c4d4ed42-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-be865df07e0189393cf0b30aa0db13e6786aa55c-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-be865df07e0189393cf0b30aa0db13e6786aa55c-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-be865df07e0189393cf0b30aa0db13e6786aa55c-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1231-be865df07e0189393cf0b30aa0db13e6786aa55c-x86_64.apk)

**Review by 3nids — APPROVED** [review]

**Pull request merged**
