### PR TITLE
Update QGIS to 3.25 in preparation to adopt 3.26

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 605a8be281a9652b38928b629f440a0e96587295:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-b50c82a6223eae9924383ab8a630e5f665e2f2ca-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-b50c82a6223eae9924383ab8a630e5f665e2f2ca-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-b50c82a6223eae9924383ab8a630e5f665e2f2ca-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-b50c82a6223eae9924383ab8a630e5f665e2f2ca-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fb304b8ae0edfd89ca5ce3cc7ca51d9b3906b3a8:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-fbe918179b387de3817ee7e88643c3527b2c8bfd-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-fbe918179b387de3817ee7e88643c3527b2c8bfd-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-fbe918179b387de3817ee7e88643c3527b2c8bfd-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-fbe918179b387de3817ee7e88643c3527b2c8bfd-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d5042afa18f5a7952becf9a3660d6a584c09eadd:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-021028b981c7654935f2d9c4f551b4d19e523e1b-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-021028b981c7654935f2d9c4f551b4d19e523e1b-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-021028b981c7654935f2d9c4f551b4d19e523e1b-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-021028b981c7654935f2d9c4f551b4d19e523e1b-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4d5abdbf8f92c3284b3ad11a9b2e691d93a32b3b:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-329578b503677562495ebc11bed16a0ac552e710-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-329578b503677562495ebc11bed16a0ac552e710-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-329578b503677562495ebc11bed16a0ac552e710-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-329578b503677562495ebc11bed16a0ac552e710-x86-android.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for de5abb376b65a20d985d5ef4798fb3ca43ac88d5:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-0a3ea11c09295c8a644ca7bf20e36c70a67c1031-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-0a3ea11c09295c8a644ca7bf20e36c70a67c1031-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-0a3ea11c09295c8a644ca7bf20e36c70a67c1031-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-0a3ea11c09295c8a644ca7bf20e36c70a67c1031-x86-android.apk)

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 99c3a297641589f9e1b01cccee7f7cb5a468e205:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-c499b727ad777449f91e9a4b031d17e6cc329875-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-c499b727ad777449f91e9a4b031d17e6cc329875-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-c499b727ad777449f91e9a4b031d17e6cc329875-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2941-c499b727ad777449f91e9a4b031d17e6cc329875-x86-android.apk)

**Pull request merged**
