### PR TITLE
A couple of position fixes

### PR DESCRIPTION
**Pull request by nirvn**
This PR should fix missing positioning information @variables when adding new features (#1640), as well as respect minimum accuracy requirements when set by the user (#1804).

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cda55649e95e2ed6789fa539715bc8d8a84ae399:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1819-4261b660a50515a147c066761a7d81378e61c7ce-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1819-4261b660a50515a147c066761a7d81378e61c7ce-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1819-4261b660a50515a147c066761a7d81378e61c7ce-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1819-4261b660a50515a147c066761a7d81378e61c7ce-x86.apk)

**Review by suricactus — APPROVED** [review]
Looks good to me.

**Review by m-kuhn — APPROVED** [review]
code looks good

**Comment by nirvn** [comment]
@m-kuhn , pushed another commit, realized last night child features digitized as part of a parent relationship didn't have access to position information either.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0b3388937e8eaa58b54c7ea86840f95b86384fc7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1819-f25e101f54216eb390ccf56e4d4b86b15126d198-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1819-f25e101f54216eb390ccf56e4d4b86b15126d198-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1819-f25e101f54216eb390ccf56e4d4b86b15126d198-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1819-f25e101f54216eb390ccf56e4d4b86b15126d198-x86.apk)

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
