### PR TITLE
Ready, toast, action!

### PR DESCRIPTION
**Pull request by nirvn**
This PR implements a new action button functionality to QField's toast widget which allows to direct users to relevant UI parts or documentation. I've taken the opportunity to further reduce the amount of code in qgismobileapp.qml by moving the toast code into its own QML file.

Here's a screencast of a 'learn more' action:

https://user-images.githubusercontent.com/1728657/231938799-3f5fcfd8-c6ea-4dd9-9430-bd0bad803ab1.mp4

That's *much nicer* than the original implementation that relied on menu items et al. This new toast functionality can be leveraged to improve UX on warnings and errors too (e.g., connecting to external GNSS failed could offer an action to open the QField settings' positioning panel).

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3625688d0a293132682dd1a46650d0c4e8af4bdf: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4169-bfe207eb0843cd786079a1c7136b5be5b4788dbb-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4169-bfe207eb0843cd786079a1c7136b5be5b4788dbb-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4169-bfe207eb0843cd786079a1c7136b5be5b4788dbb-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4169-bfe207eb0843cd786079a1c7136b5be5b4788dbb-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4169-bfe207eb0843cd786079a1c7136b5be5b4788dbb-arm64-android.apk)
- [all access arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4169-bfe207eb0843cd786079a1c7136b5be5b4788dbb-arm-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4169-bfe207eb0843cd786079a1c7136b5be5b4788dbb-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4169-bfe207eb0843cd786079a1c7136b5be5b4788dbb-x86-android.apk)
</details>

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
I woner if we should still gray out the sensors menu if no sensors are available but leave the toast for on click actions. Most of the users will still not be using sensors and should have their attention turned away from it.

**Comment by nirvn** [comment]
@m-kuhn , if I see a disabled item, I won't click on it, I'm not sure that learn more would therefore become discoverable. 

Completely agree with you on most users never needing sensors to begin with, but I'm not sure an enabled menu item state will be distracting in nature. I feel like worse case scenario users will trigger the menu action once out of curiosity and see the toaster. If they are not interested, they will never click on it again. If one day they need it, they'll trigger the action again and learn more :)

**Comment by mbernasocchi** [comment]
Looks good :)

**Comment by nirvn** [comment]
@mbernasocchi , @m-kuhn , BTW, a similar toaster appears for the 'print to PDF' menu action when the opened project has no layouts, which will definitively be useful to a much broader section of the user base too.

**Comment by m-kuhn** [comment]
ok then, let's go :-)

**Pull request merged**
