### PR TITLE
Update Buttons to QtQuick.Controls 2

### PR DESCRIPTION
**Pull request by m-kuhn**
Screenshot from 2020-03-30 15-49-10

### CODE REVIEW

**Comment by m-kuhn** [comment]
Less Quick.1 :tada:

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-917-b14801d1c1fd1ebf6b3884dcd9f846f5fe757bf8-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-917-b14801d1c1fd1ebf6b3884dcd9f846f5fe757bf8-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-917-b14801d1c1fd1ebf6b3884dcd9f846f5fe757bf8-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-917-b14801d1c1fd1ebf6b3884dcd9f846f5fe757bf8-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-917-0e6a8737f87f335dfe4efcabffc57067d3c541ee-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-917-0e6a8737f87f335dfe4efcabffc57067d3c541ee-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-917-0e6a8737f87f335dfe4efcabffc57067d3c541ee-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-917-0e6a8737f87f335dfe4efcabffc57067d3c541ee-x86_64.apk)

**Comment by signedav** [comment]
@m-kuhn Is this tested on the device?

**Comment by signedav** [comment]
Since I think there are hdpi issues. But I didn't checked out since when. I assume because of this.
WhatsApp Image 2020-04-01 at 11 34 26

**Comment by m-kuhn** [comment]
See #922

**Pull request merged**
