### PR TITLE
Switch CRT linkage back to dynamic on arm platform

### PR DESCRIPTION
**Pull request by nirvn**
Let's produce some APKs to see if we can do that without regressing.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6bc05c7d6d68973fec597e8a3d310295867650b1:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-3b9e0dac8f5d2ce5abf2ba0c2d03e0d84ea65172-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-3b9e0dac8f5d2ce5abf2ba0c2d03e0d84ea65172-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-3b9e0dac8f5d2ce5abf2ba0c2d03e0d84ea65172-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-3b9e0dac8f5d2ce5abf2ba0c2d03e0d84ea65172-x86-android.apk)

**Comment by m-kuhn** [comment]
Thanks

`set(ANDROID_STL c++_static)` this line can be removed, [that's done elsewhere](https://github.com/microsoft/vcpkg/blob/master/scripts/toolchains/android.cmake#L31-L35)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d3022fce40c955a3f21412e52f391f0139360e6c:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-ec609a474f248db91f6b51f86458cd2775f259c2-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-ec609a474f248db91f6b51f86458cd2775f259c2-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-ec609a474f248db91f6b51f86458cd2775f259c2-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-ec609a474f248db91f6b51f86458cd2775f259c2-x86-android.apk)

**Comment by nirvn** [comment]
For the record: @marioba tried the APK that changed VCPKG_CRT_LINKAGE's value to dynamic and reported the resulting APK to be crash free.

The second set of APKs is testing out whether we can safely remove the ANDROID_STL line (I can't see why it'd be a problem, but better be safe than sorry), awaiting another round of test on a 32 bit arm device, then merge.

**Review by m-kuhn — APPROVED** [review]
Looks good to me.
Awaiting test results from @marioba

**Comment by marioba** [comment]
> tada Ta-daaa, freshly created APKs are available for [d3022fc](https://github.com/opengisch/QField/commit/d3022fce40c955a3f21412e52f391f0139360e6c):
> 
> * [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-ec609a474f248db91f6b51f86458cd2775f259c2-arm64-android.apk)
> 
> Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-ec609a474f248db91f6b51f86458cd2775f259c2-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-ec609a474f248db91f6b51f86458cd2775f259c2-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3042-ec609a474f248db91f6b51f86458cd2775f259c2-x86-android.apk)

This apk works correctly on my arm 32 device.

**Comment by nirvn** [comment]
@marioba , thanks.

**Pull request merged**
