### PR TITLE
Replace one carousel photo

### PR DESCRIPTION
**Pull request by nirvn**
This dude-in-front-of-logs photo was just too good not to use as one of the three carousel header photos. A what a great look this makes:
image

The sooner the two remaining mountains can go, the better :wink:

### CODE REVIEW

**Comment by 3nids** [comment]
can this be merged?
As a side note, I'd be in favor of moving the website to a dedicated repo. OK?

**Comment by m-kuhn** [comment]
I'll need to get confirmation to use the image first

**Comment by nirvn** [comment]
@3nids , dedicated repo? +100 :)

**Comment by m-kuhn** [comment]
We have received the official ok for this.

**Comment by nirvn** [comment]
One done, two to go :)

**Pull request merged**
