### PR TITLE
Show commit sha in the about dialog

### PR DESCRIPTION
**Pull request by suricactus**
Everything started as a fix for #1206 . Since there I got a bunch of versions on my phone from both repos, it is hard to keep track what is currently installed on the phone. 

Nevertheless, there were multiple names for the same thing across the app, so I also did a bit of cleanup.

Before approval we need the APKs to see if the PR version string is correctly set.

image

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 4af53c7d8a9932a2a8612c81ad886a6203616924:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-d2a0d6f641970876f72b2cd3423b67bc71f8a96a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-d2a0d6f641970876f72b2cd3423b67bc71f8a96a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-d2a0d6f641970876f72b2cd3423b67bc71f8a96a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-d2a0d6f641970876f72b2cd3423b67bc71f8a96a-x86.apk)

**Comment by suricactus** [comment]
It works fine for PRs, unfortunately we need to merge to check whether it works fine on master (nighly channel on Google Play).

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 42ffca69390e65bc2dcfe97fd81c1edf24f091bf:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-84cdbdd7c9b5dbcc40d68a905e297643f258c391-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-84cdbdd7c9b5dbcc40d68a905e297643f258c391-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-84cdbdd7c9b5dbcc40d68a905e297643f258c391-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-84cdbdd7c9b5dbcc40d68a905e297643f258c391-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 14dda3a73582f2677b3cdcb52f1197f9643a4e8b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-ecdf2dd4cdca8dd1a212bc5707c28e73b9138eac-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-ecdf2dd4cdca8dd1a212bc5707c28e73b9138eac-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-ecdf2dd4cdca8dd1a212bc5707c28e73b9138eac-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-ecdf2dd4cdca8dd1a212bc5707c28e73b9138eac-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d6c338cf6ebb7249f78624363002a68dd091f2b2:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-ead5b2afcc9d9823d2ea018c3dd41a545ddb8940-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-ead5b2afcc9d9823d2ea018c3dd41a545ddb8940-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-ead5b2afcc9d9823d2ea018c3dd41a545ddb8940-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-ead5b2afcc9d9823d2ea018c3dd41a545ddb8940-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3060fe5d2faed10945d2c101fdb4f68cbc103108:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-c95653a2a5d2e7215c03ca7f3425c455370586a9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-c95653a2a5d2e7215c03ca7f3425c455370586a9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-c95653a2a5d2e7215c03ca7f3425c455370586a9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1551-c95653a2a5d2e7215c03ca7f3425c455370586a9-x86.apk)

**Review by m-kuhn — APPROVED** [review]
Nice cleanup

**Pull request merged**
