### PR TITLE
Update QField iOS SDK, add extra providers

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 3daff0cf29a2a815f4321454f177ebe946b6d49e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2284-5bfef65637cd40a68cb2fa65bfa3f3099dd01912-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2284-5bfef65637cd40a68cb2fa65bfa3f3099dd01912-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2284-5bfef65637cd40a68cb2fa65bfa3f3099dd01912-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2284-5bfef65637cd40a68cb2fa65bfa3f3099dd01912-x86.apk)

**Comment by nirvn** [comment]
@3nids , I don't have an iOS device but this should give you a package to try with wfs, arc services, delimited text, spatialite & virtual providers working out of the box. I believe it's a first QGIS-derived iOS app to unlock this, woupidou.

**Review by 3nids — APPROVED** [review]

**Comment by 3nids** [comment]
well done!

**Comment by nirvn** [comment]
@3nids , did you give a wfs layer a try?

**Pull request merged**
