### PR TITLE
Add macos installer

### PR DESCRIPTION
**Pull request by m-kuhn**
Adds a nice drag and drop mac installer for qfield

Screenshot 2022-01-30 at 10 47 26

TODO

 - [x] Assets like proj.db

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fa57e47385ef19c087c16d5e96eb503273555f02:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-340b1221d30d6e7619c49f25ac1dd0b3d6918090-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-340b1221d30d6e7619c49f25ac1dd0b3d6918090-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-340b1221d30d6e7619c49f25ac1dd0b3d6918090-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-340b1221d30d6e7619c49f25ac1dd0b3d6918090-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 5f2664d54af3fed4c0394cf89c78fc9cd3fdc4e0:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-b8333a83cde26dd2d40558cd74ddba1c09c7bc51-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-b8333a83cde26dd2d40558cd74ddba1c09c7bc51-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-b8333a83cde26dd2d40558cd74ddba1c09c7bc51-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-b8333a83cde26dd2d40558cd74ddba1c09c7bc51-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ce0996a6f144223f53839edb7a8b1128bfae3c82:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-5d13db115e1c526261d105b351c60c7ba695040f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-5d13db115e1c526261d105b351c60c7ba695040f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-5d13db115e1c526261d105b351c60c7ba695040f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-5d13db115e1c526261d105b351c60c7ba695040f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ce608c1cbe581c038ca5139466b137bae5a472ec:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-475d538d401d300a21da1012bd3dc487eb670cc6-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-475d538d401d300a21da1012bd3dc487eb670cc6-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-475d538d401d300a21da1012bd3dc487eb670cc6-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-475d538d401d300a21da1012bd3dc487eb670cc6-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fc9927c26a83e8325f151e64aeacdb45edd75314:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-949006692b36fc23e63d5524e4ec6704e880f0eb-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-949006692b36fc23e63d5524e4ec6704e880f0eb-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-949006692b36fc23e63d5524e4ec6704e880f0eb-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-949006692b36fc23e63d5524e4ec6704e880f0eb-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 36f8b0a05bbdb5827bdabd6dd5c15f6280b7c46d:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-da25a1be687ba5520cb1daa5d88b6b439bab9bfd-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-da25a1be687ba5520cb1daa5d88b6b439bab9bfd-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-da25a1be687ba5520cb1daa5d88b6b439bab9bfd-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-da25a1be687ba5520cb1daa5d88b6b439bab9bfd-x86.apk)

**Comment by nirvn** [comment]
TODO: Change background or text color? :)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 33c0f84cc0f126ebcb510bc92566c10c0369f039:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-e787f20f48f039b957f553362b940cf5cf94b2dd-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-e787f20f48f039b957f553362b940cf5cf94b2dd-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-e787f20f48f039b957f553362b940cf5cf94b2dd-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-e787f20f48f039b957f553362b940cf5cf94b2dd-x86.apk)

**Comment by m-kuhn** [comment]
> TODO: Change background or text color? :)

Done in latest commit, see

**Comment by m-kuhn** [comment]
@soester @3nids is that how we install applications on mac in 2022?

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ee6f6e2cfdbff59b25caeffc823e45dc9aa03dc3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-8fd9b8cbaf5d3d902783a531e8fafd755624f955-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-8fd9b8cbaf5d3d902783a531e8fafd755624f955-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-8fd9b8cbaf5d3d902783a531e8fafd755624f955-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-8fd9b8cbaf5d3d902783a531e8fafd755624f955-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a595c0e90aac6ee37c7380296719031e2577346f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-b5885ad162864325af3d045926bce04078c4ba7d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-b5885ad162864325af3d045926bce04078c4ba7d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-b5885ad162864325af3d045926bce04078c4ba7d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2442-b5885ad162864325af3d045926bce04078c4ba7d-x86.apk)

**Review by nirvn — APPROVED** [review]
Nice!

**Comment by nirvn** [comment]
@m-kuhn , :red_circle: this has caused a regression on Android, APKs crashing on me.

**Comment by nirvn** [comment]
Relevant bits of the logcat:

```
02-01 10:16:09.451 32522   969 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 969 (qtMainLoopThrea), pid 32522 (.opengis.qfield)
[...]
02-01 10:16:09.629  1015  1015 F DEBUG   : Build fingerprint: 'samsung/a52qnsxx/a52q:11/RP1A.200720.012/A525FXXS4AUL2:user/release-keys'
02-01 10:16:09.629  1015  1015 F DEBUG   : Revision: '8'
02-01 10:16:09.629  1015  1015 F DEBUG   : ABI: 'arm64'
02-01 10:16:09.638  1015  1015 F DEBUG   : Timestamp: 2022-02-01 10:16:09+0700
02-01 10:16:09.638  1015  1015 F DEBUG   : pid: 32522, tid: 969, name: qtMainLoopThrea  >>> ch.opengis.qfield <<<
02-01 10:16:09.638  1015  1015 F DEBUG   : uid: 10369
02-01 10:16:09.638  1015  1015 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
02-01 10:16:09.638  1015  1015 F DEBUG   : Cause: null pointer dereference
02-01 10:16:09.638  1015  1015 F DEBUG   :     x0  0000000000000001  x1  0000007228a97f40  x2  0000007228a97e18  x3  00000000000000e8
02-01 10:16:09.639  1015  1015 F DEBUG   :     x4  0000000000000010  x5  b4000072dbdbc9d8  x6  000000000000002f  x7  0000000000000000
02-01 10:16:09.639  1015  1015 F DEBUG   :     x8  0000000000000000  x9  0000000000000001  x10 0000000000000018  x11 0000007228a97f40
02-01 10:16:09.639  1015  1015 F DEBUG   :     x12 0000000000000000  x13 0000000000000002  x14 b4000072dbd530a0  x15 b4000072dbdbd6b8
02-01 10:16:09.639  1015  1015 F DEBUG   :     x16 00000072265639d8  x17 000000752f791b58  x18 000000722737a000  x19 00000072233b4db0
02-01 10:16:09.639  1015  1015 F DEBUG   :     x20 00000072233b4000  x21 b4000072bbd8ce50  x22 0000000000000001  x23 000000001330d470
02-01 10:16:09.639  1015  1015 F DEBUG   :     x24 0000000013111e50  x25 000000001318f9f8  x26 0000000013111dc0  x27 000000729bced000
02-01 10:16:09.639  1015  1015 F DEBUG   :     x28 0000000000000043  x29 0000007228a98770
02-01 10:16:09.639  1015  1015 F DEBUG   :     lr  00000072232b8d6c  sp  0000007228a97f00  pc  0000000000000000  pst 0000000060001000
02-01 10:16:09.640  1015  1015 F DEBUG   : backtrace:
02-01 10:16:09.640  1015  1015 F DEBUG   :       #00 pc 0000000000000000  <unknown>
02-01 10:16:09.640  1015  1015 F DEBUG   :       #01 pc 0000000000032d68  /data/app/~~ooEEzrsTWzXKuOc9y8KPiw==/ch.opengis.qfield-OrHwOu7QOcQYRU_O-CBi2w==/lib/arm64/libplugins_platforms_qtforandroid_arm64-v8a.so (BuildId: 84834b292d486c514edcf6b4d5cbd5822a20711e)
```

**Comment by nirvn** [comment]
APKs from PR #2441 , APKs from PR #2442 onwards failing. Must be something changed in the CMakeLists.txt that caused this regression.

**Pull request merged**
