### PR TITLE
Add all expression scopes when identifying

### LINKED ISSUE #1970: Geometries not selectionable when using global variables in symbology
Hi there and first: much appreciation for the great project!

Example: The circles in the symbology in a point-Layer predefined in QGIS are shown to big in QField map canvas so I have to choose between making them smaller for QField, but then I can't see them properly anymore in QGIS – or leave them, as they are in QGIS and have too big symbols in QField.

To solve that, I used a rule based symbology with a filter like "variable"  =  'value' AND  @qgis_os_name  = 'android' for QField and the value 'linux' for QGIS on my laptop. The symbology is displayed correctly and differs between the two operating systems. But doing so I can' select the points in the map canvas of QField anymore.

In this special case maybe I can use a workaround changeing the symbols size unit from mm to pixel, but because of printing purposes I would prefer to stay with mm in the whole project. And sometimes I want to use different symbols in QGIS/QField staying in the same project and without duplicate layers with changed symbology.

### Reproduction Steps:

1. Take a point layer, choose rule based symbology and enter something like

"variable"  =  'value' AND  @qgis_os_name  = 'android'

as one rule and

"variable"  =  'value' AND  @qgis_os_name  = 'linux'

as second rule (maybe you have to adjust the values android/linux to your own OS) and change the size/shape/color etc. of the symbols like you want it and you can see the difference between them clearly.

2. Load the project onto your smartphone/tablet etc. and open it with QField, the symbols should be displayed correctly and different between QGIS/QField.

3. Try to select a point of the point layer – it doesn't work.

### Expected behavior:
Geometries still clickable/selectionable, even when using variables like "@qgis_os_name" in symbology.

### Observed behavior:
Geometries not clickable/selectionable anymore when using variables mentioned above.

**QField version:** QField version 1.9.6 (d5dd01 v1.9.6)

## Additional information:
* Problem started happening recently, didn't happen in an older version of QField: I don't know, I'm relatively new to QField
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes
* Problem happens with other variables: Not tested

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #1970

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
Good one.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f8e0dce9d647d2306df99188152a7d1c081b9cd0:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2036-f6534e32079cac41f7a9eaad69123bd816c11521-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2036-f6534e32079cac41f7a9eaad69123bd816c11521-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2036-f6534e32079cac41f7a9eaad69123bd816c11521-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2036-f6534e32079cac41f7a9eaad69123bd816c11521-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 005f214a565ec164ea818e7cc553a503a6a0f0f6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2036-e98fb52a4a07b44f135ba6052a8b04ec57d5f90f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2036-e98fb52a4a07b44f135ba6052a8b04ec57d5f90f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2036-e98fb52a4a07b44f135ba6052a8b04ec57d5f90f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2036-e98fb52a4a07b44f135ba6052a8b04ec57d5f90f-x86.apk)

**Comment by roedvingetrast** [comment]
Great!

**Pull request merged**
