### PR TITLE
Handlers are ethernal struggles, fix double tap zoom regression

### PR DESCRIPTION
**Pull request by nirvn**
Handlers...

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a0892686aaed694211913e3d900ab55ee930bd81:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-4ec750bb4c32617c71c7c2c16ba8ab796f6bfa71-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-4ec750bb4c32617c71c7c2c16ba8ab796f6bfa71-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-4ec750bb4c32617c71c7c2c16ba8ab796f6bfa71-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-4ec750bb4c32617c71c7c2c16ba8ab796f6bfa71-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 9af64d821bbcdd767bd6ed18a121ffc5cf45b8e8:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-5a225772412a4c190a459d44dc4627a4c0ed877e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-5a225772412a4c190a459d44dc4627a4c0ed877e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-5a225772412a4c190a459d44dc4627a4c0ed877e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-5a225772412a4c190a459d44dc4627a4c0ed877e-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fb9659a1036abd0c2b65699cd597b4fbcef0a7da:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-ce536fef169df080f11b8fba256c93701f386639-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-ce536fef169df080f11b8fba256c93701f386639-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-ce536fef169df080f11b8fba256c93701f386639-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1546-ce536fef169df080f11b8fba256c93701f386639-x86.apk)

**Review by suricactus — APPROVED** [review]
Thanks!

**Pull request merged**
