### PR TITLE
Togglebutton for Modes

### PR DESCRIPTION
**Pull request by signedav**
So you not have to go over the menu every time.

Looks like this:
switch_toggle_pr

PS. The Switch is in the horizontal center of the green in fact.

### CODE REVIEW

**Comment by signedav** [comment]
I have a lot of code in here that fitted to an old master. But why all this is removed from it? Like e.g the whole printing part?

**Comment by signedav** [comment]
Note to myself: Possibly check out new master when it's ready and copy paste new code instead of merging this PR...

**Comment by m-kuhn** [comment]
Sorry for this @signedav I've done an emergency rollback to get a release up and running for the workshop here. Code is back with everything now on master now!

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-341-e6207b5fead68e19239e3e49ce2232c67f7f7f96-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-341-e6207b5fead68e19239e3e49ce2232c67f7f7f96-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://opengis.ch/download/qfield/ci-builds/qfield-dev-341-b48c9ad17e9d1ade005eaa0a4d924f57033cd7cb-armv7.apk) and [x86](https://opengis.ch/download/qfield/ci-builds/qfield-dev-341-b48c9ad17e9d1ade005eaa0a4d924f57033cd7cb-x86.apk)

**Comment by signedav** [comment]
This is wrecked. I'll make a new PR.

**Comment by signedav** [comment]
@giedrioks26 Please see #344 thanks.

**Pull request closed without merging**
