### PR TITLE
Fix dpi scaling on windows

### LINKED ISSUE #1308: Dpi scaling issue on windows.
When using a 4K screen and a 1080p screen on windows, the windows bar doesn't scale well on most application.

### Reproduction Steps:

* Download app from CI.
* Open the app on windows with a 4K screen as primary display and 1080p display as second screen.

### Expected behavior:

The windows bar should the same size as any other windows bar.

### Observed behavior:

The windows bar is too big

### Screenshots and GIFs

image

## Additional information:

The problem can easily big fix by adding :
```c++
#if _WIN32_WINNT >= 0x0600
#include <winuser.h>
#endif

// ...

#if _WIN32_WINNT >= 0x0600
::SetProcessDPIAware();
#endif
```

The code snippet should be called **BEFORE** `QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);`

I can do a PR if you want.

### PR DESCRIPTION
**Pull request by m-kuhn**
Fixes #1308

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 74e5b757287481f9a9a23cc7c8ce0be6354b51e8:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2232-5fd90f33315dd87d8034e68e1b87ccbfe752ab5b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2232-5fd90f33315dd87d8034e68e1b87ccbfe752ab5b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2232-5fd90f33315dd87d8034e68e1b87ccbfe752ab5b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2232-5fd90f33315dd87d8034e68e1b87ccbfe752ab5b-x86.apk)

**Comment by m-kuhn** [comment]
By convention code in subfolders of `platforms` are only added in a condition. But we could kill the `#ifdef`s

**Comment by m-kuhn** [comment]
So let's just keep it as is. Thanks for the help !

**Comment by m-kuhn** [comment]
This hasn't seen any activity in a while. I'll close this to keep the PR queue relevant. We can reopen any time if needed.

**Pull request closed without merging**
