### PR TITLE
A couple of header harmonization

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
:back:

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for ddd92cb6191d27477d3741f0f352a55da8463082:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2371-fe84f4c982bfdb59d8e30b700ea73bcca71df4a5-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2371-fe84f4c982bfdb59d8e30b700ea73bcca71df4a5-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2371-fe84f4c982bfdb59d8e30b700ea73bcca71df4a5-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2371-fe84f4c982bfdb59d8e30b700ea73bcca71df4a5-x86.apk)

**Comment by nirvn** [comment]
@m-kuhn , @suricactus , the ( send log ) button has been moved to the message log panel in this PR.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a8093b79cc8f40ce5e77febd33d951e1958f758b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2371-850b634aeddd5b267febd21edcbc284e5c23f704-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2371-850b634aeddd5b267febd21edcbc284e5c23f704-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2371-850b634aeddd5b267febd21edcbc284e5c23f704-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2371-850b634aeddd5b267febd21edcbc284e5c23f704-x86.apk)

**Pull request merged**
