### PR TITLE
WIP Let's add some debug info before the login fails

### PR DESCRIPTION
**Pull request by suricactus**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 062944ca9ca0b0347930b3b4a9b2511d694b0c46:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-68e990e6d1c116d510674c2534ba528cb56fe4e9-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-68e990e6d1c116d510674c2534ba528cb56fe4e9-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-68e990e6d1c116d510674c2534ba528cb56fe4e9-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-68e990e6d1c116d510674c2534ba528cb56fe4e9-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 85dea94e5a07ad9d4fb4868c3c38f3fa7276d20b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-888a81cc730c5a593b0044f9c85ffb0bdb3d2bd7-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-888a81cc730c5a593b0044f9c85ffb0bdb3d2bd7-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-888a81cc730c5a593b0044f9c85ffb0bdb3d2bd7-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-888a81cc730c5a593b0044f9c85ffb0bdb3d2bd7-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 34b4db6ddba4909eb1163db433e211a2ee9906ba:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-7ea6a9fcb232bf186abcfe240223092ee8ebbbd6-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-7ea6a9fcb232bf186abcfe240223092ee8ebbbd6-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-7ea6a9fcb232bf186abcfe240223092ee8ebbbd6-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-7ea6a9fcb232bf186abcfe240223092ee8ebbbd6-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d51f7d1a3ec96b6e5a92b743a956b46159415e40:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-7fbcf4caf596b21af50f641d8ba9a10f97750b6f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-7fbcf4caf596b21af50f641d8ba9a10f97750b6f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-7fbcf4caf596b21af50f641d8ba9a10f97750b6f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-7fbcf4caf596b21af50f641d8ba9a10f97750b6f-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e0c4c5999b4703d8ec770cfae009fb635bdcde58:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-1782f643f0033d792ae56b5cfd9b247323244e05-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-1782f643f0033d792ae56b5cfd9b247323244e05-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-1782f643f0033d792ae56b5cfd9b247323244e05-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-1782f643f0033d792ae56b5cfd9b247323244e05-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 26287210f3841fe5955e0df8190bf39c0963ce66:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-9b597453093d6c45f582e22448f1c57f72428faa-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-9b597453093d6c45f582e22448f1c57f72428faa-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-9b597453093d6c45f582e22448f1c57f72428faa-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-9b597453093d6c45f582e22448f1c57f72428faa-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1300c923a91c010452f4c705194859e461a8f1a7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-bbd9cd76b4826f05b5400aef3ce5be3cc728b6e1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-bbd9cd76b4826f05b5400aef3ce5be3cc728b6e1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-bbd9cd76b4826f05b5400aef3ce5be3cc728b6e1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-bbd9cd76b4826f05b5400aef3ce5be3cc728b6e1-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2b7ed668a7a30bd3d108f49b96f0411ee384b456:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-3cf7eafaabbe8322895242aa93abbe24cea619a1-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-3cf7eafaabbe8322895242aa93abbe24cea619a1-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-3cf7eafaabbe8322895242aa93abbe24cea619a1-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1982-3cf7eafaabbe8322895242aa93abbe24cea619a1-x86.apk)

**Comment by nirvn** [comment]
@suricactus , we can close this one?

**Comment by m-kuhn** [comment]
@suricactus close, delete, forget?

**Pull request closed without merging**
