### PR TITLE
Add day when it sets time back

### PR DESCRIPTION
**Pull request by signedav**
When we selected a day, it stored one day before. This because the time is set to 0:00:00.
Now with adding a day we have the correct date.

Not sure if this is the correct way to solve the issue. What do you think @3nids ?

### CODE REVIEW

**Comment by 3nids** [comment]
hmmm, that seems very strange.
Can you try by removing all the lines under the "weird" comment?
Maybe, I was confused and 12:00:00 is actually the very end of the previous day and it would work.

But this has to be very carefully checked (see comment around[ line 73](https://github.com/opengisch/QField/blob/bce240754925a57fd4030b1e7e6b4bbd888d3565/src/qml/editorwidgets/DateTime.qml#L73-L79)).

**Comment by signedav** [comment]
It would work, when I remove them. One minute.

**Comment by signedav** [comment]
That would work for my tests. But I didn't tested with shp etc. What tests are needed to be sure it does not break something? 

I tested with gpkg and the online pg db...

**Comment by 3nids** [comment]
sadly there are no available test suite for this...
I have a project I can test along.
Let me try later today

**Comment by signedav** [comment]
I think, we need to release. Do you prefer to merge that without your tests or should we not?

**Comment by 3nids** [comment]
I don't have a testing env at the moment (no compiled QGIS).

Here are the possibilities:
- string field as date (no matter source type)
- string field as date AND time (no matter source type)
- date field on GPKG with time
- date field on shape (has no time)

and testing adding, manually editing and editing using calendar.

The main important one is shape and string as date and time.

**Comment by 3nids** [comment]
my general impression is that there should not be issue...but my experience with date time is that I am very ofter wrong.

**Comment by signedav** [comment]
shp:
date: fine
date-time: fine 12.00.00
string: fine

gpkg:
date: fine
date-time: fine 11.00.00 (who knows why)
string: fine

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-551-abd2007afc2ffba74e3e9ca9bb4d05e7a2f27d82-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-551-abd2007afc2ffba74e3e9ca9bb4d05e7a2f27d82-x86.apk)

**Comment by 3nids** [comment]
@signedav @mbernasocchi this is not working as expected. It gets to 11:00:00 because of the UTC shift and the bad conception on QML side (there is no Date only object, it's always date and time)

this requires more work

**Comment by 3nids** [comment]
Hmmm, I guess this was working for me and not for you (a day before) because I'm on the other side of Greenwich.
I think we need to shift the value by the UTC offset.

**Comment by signedav** [comment]
We definitely need to invest more work on it, but in the end it's better to get the correct date with a random time than a wrong date with the 0 time, no?

**Comment by mbernasocchi** [comment]
yes, let's care about date first of all

**Comment by 3nids** [comment]
I cannot reproduce the issue you mentioned with gpkg and date/time.

**Pull request merged**
