### PR TITLE
Fix warning when attempting to delete a feature

### PR DESCRIPTION
**Pull request by suricactus**
1) select a single feature
2) open the feature form
3) attempt to delete

```
Could not convert argument 1 at onDeleteClicked@qrc:/qml…/FeatureListForm.qml:424
```

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for de1c2e56ff03d6fed67df97f02f142f2705efc40:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2115-518e9d6937f7dd58ad6f4c02569e152a3b3f9512-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2115-518e9d6937f7dd58ad6f4c02569e152a3b3f9512-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2115-518e9d6937f7dd58ad6f4c02569e152a3b3f9512-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2115-518e9d6937f7dd58ad6f4c02569e152a3b3f9512-x86.apk)

**Review by nirvn — APPROVED** [review]
Good -- I suspect the QML syntax formatter is going to reshape that if whenever we start using it. But until then, whatever floats your boat sir :wink:

**Comment by suricactus** [comment]
not sure what is the "standard" way to multiline very long lines, would be great if the QML linter worked properly.

**Comment by suricactus** [comment]
not sure what is the "standard" way to multiline very long lines, would be great if the QML linter worked properly.

**Pull request merged**
