### PR TITLE
finer tuning of QML date/time edit

### LINKED ISSUE #9: DateTime field edit type
I have installed QField 0.3.2 on a Samsung Galaxy Note 8.0. I have a project with a shapefile layer. One of the fields, called "Time" is defined as Date (QDAte) and widget is set to display "yyyy-MM-dd  HH:mm:ss", two other fields are called respectively Start_Date and End_Date, are defined as Date (QDate) and widget is set to display "yyyy-MM-dd" only.
However all fields do not automatically update when opened in QField editor, so that theoretically I'd have to insert all times and dates manually. On the other hand in QGIS for desktop everything is working fine.
When I use a spatialite layer the behavior is the same.

It may be useful to say that if a field was edited in QGIS (2.8.1), when opened in QField it displays as 2015-03-25T00:00:00, even if time was correct in QGIS. May be there a problem when copying the project file? Should I export projects and shapefiles differently, instead of just copying and pasting?

### LINKED ISSUE #215: Calendar widget
In QGis (2.18.16), whether calendar option is checked or not in Date/Time widget, it pops up in QField (0.10.4) when clicking on the field.

### Expected behavior:

Calendar pops up if checked in date/time option in QGis ; doesn't pop up if not checked

## Additional information:

Maybe related to answer given in issue #9 (which would be nice to solve too ;) )

Thanks to all the team : you make great work !

### LINKED ISSUE #371: Entry of time only (without date)
I'd like to only save time into a geopackage. As geopackage only knows date/time format I chose a text as the field type in order to only save time (and not also date). Then I define the attribute form the following way: 
zeittext

On QGIS 3.2 I the data entry is presented like this.
zeittextqgis

On QField I am shown an calendar widget upon data entry, which is of course useless for storing time. I would expect something like this as well:
zeittextqgis

**QField version:** [0.11.6]
**QQGIS version:** [3.2]

## Additional information:
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

### PR DESCRIPTION
**Pull request by 3nids**
* do not open calendar when option is not checked in QGIS project
* use inputMethodHints whenever easily possible, also use regex validator

fix #9
fix #215
fix #371

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-f702cb439f086afc00d9455caf76ac8817d8fe6f-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-f702cb439f086afc00d9455caf76ac8817d8fe6f-x86.apk)

**Comment by 3nids** [comment]
@m-kuhn getting a crash on startup here too. Shall I update to newer SDK (same than in search) ?

**Comment by m-kuhn** [comment]
@3nids It's hard to reason about a crash without a stack trace. But the upgrade sounds easy enough to give it a try.

**Comment by 3nids** [comment]
> 12-10 08:46:06.964  1379  3315 D LocationManagerService: getLastLocation: Request[ACCURACY_FINE gps requested=0 fastest=0 num=1]
> 12-10 08:46:06.965 11921 11993 W System.err: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-f5678a5b7d21c07911d216ff05876e349f03a5fa-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-f5678a5b7d21c07911d216ff05876e349f03a5fa-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-9139e87ba6c552e9b1cc569ac7ff6b305ea5da3e-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-9139e87ba6c552e9b1cc569ac7ff6b305ea5da3e-x86.apk)

**Comment by 3nids** [comment]
@m-kuhn this is working with same SDK as in search
Two things here:
* the validator doesn't seem to work (but input mask is). Is this the right way to construct a RegExpValidator (i.e `new RegExpValidator( /my_reg_ex/)`)?
* the input method hints (date or time) doesn't seem to show up calendar/clock from system. Not sure if I should expect it.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-3f8f784b92f7b75902b7a9a93137aeb451a870e3-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-3f8f784b92f7b75902b7a9a93137aeb451a870e3-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-8a4c31a839047126cb7964eae7a44865802c4532-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-8a4c31a839047126cb7964eae7a44865802c4532-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-be9fe369d06a5621a16b636143748657d117e97c-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-be9fe369d06a5621a16b636143748657d117e97c-x86.apk)

**Comment by m-kuhn** [comment]
True, it probably needs more logic than a validator can provide (e.g. backspace should skip delimiters), so better remove them.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-23cf8538359025e526922eb151aaafa748e4588a-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-23cf8538359025e526922eb151aaafa748e4588a-x86.apk)

**Comment by 3nids** [comment]
@saemiw would you like to give this a try?
I have no strong opinion if it is important or not to be able to use backspace. The validator ensures correct data (valid date/time) but does not allow the user to use backspace as it would result in invalid data.

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-23cf8538359025e526922eb151aaafa748e4588a-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-23cf8538359025e526922eb151aaafa748e4588a-x86.apk)

**Comment by 3nids** [comment]
@saemiw here are some new package if you want to give it a try

**Comment by saemiw** [comment]
> 
> 
> @saemiw here are some new package if you want to give it a try

I am looking at it right now, I give you a feedback the latest tomorrow at 10:00

**Comment by saemiw** [comment]
It's not really working yet as I expected. I'll start explaining one problem after the other:

*Problem 1:* QField doesn't show the same as QGIS
What is entered in QGIS like this:
grafik

Is shown on QField like this:
grafik

So Qfield does not seem to take over the formatting settings properly. Here is a example how I set the formatting for the column time2 in QGIS:
grafik

by the way I use QGIS 3.4.2

**Comment by saemiw** [comment]
*Problem 2:* Can't enter data

At the moment I am not capable of entering data unless I have default "now()" defined. See this video:
https://youtu.be/qfuv9sBijI8 

Here is how I set up the different fields in case you're wondering what the hell I did:
grafik

grafik

grafik

grafik

And here the data types: 
grafik

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-920072aaa82ca7fa8676cceb0e7bcae2190fbe8a-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-404-920072aaa82ca7fa8676cceb0e7bcae2190fbe8a-x86.apk)

**Comment by 3nids** [comment]
new version in #421

**Pull request closed without merging**
