### PR TITLE
Attempt at fixing the white line in settings panel

### PR DESCRIPTION
**Pull request by nirvn**
This is an attempt at fixing #1511 -- I've seen it on some devices, while others don't suffer from it (has to be some HiDPI scaling / rounding issue).

@nyalldawson, since you have a device that has this line, can you test this APK and confirm it's gone? I'll duplicate fix for other panes then.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bfbf1841b8bc1a8a36e15baca438448c4e0df837:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-1d272ac457e94fcf80610bf552f2641b34ec9b7b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-1d272ac457e94fcf80610bf552f2641b34ec9b7b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-1d272ac457e94fcf80610bf552f2641b34ec9b7b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-1d272ac457e94fcf80610bf552f2641b34ec9b7b-x86.apk)

**Comment by nyalldawson** [comment]
Still present, sorry

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 03e5a3c459ceadc30b7fbedaf01290906927761f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-35650101353958acf2d3a08a34fdb660847372b8-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-35650101353958acf2d3a08a34fdb660847372b8-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-35650101353958acf2d3a08a34fdb660847372b8-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-35650101353958acf2d3a08a34fdb660847372b8-x86.apk)

**Comment by nirvn** [comment]
@nyalldawson , here's another round of test APKs using a different placement strategy. Let me know if the line disappears :crossed_fingers:

**Comment by nyalldawson** [comment]
No change, sorry

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for d2b30772cc97776017edd057f8ec7d8c2db65d10:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-73bcfdf5ab4f3d1a27ae253e762a589dbf74ac4e-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-73bcfdf5ab4f3d1a27ae253e762a589dbf74ac4e-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-73bcfdf5ab4f3d1a27ae253e762a589dbf74ac4e-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-73bcfdf5ab4f3d1a27ae253e762a589dbf74ac4e-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 02355974bed47fb33a4110b28fe7ec734d7d47eb:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-9ce3546ace38b4d4b16e39ee22b3c24f2360caf6-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-9ce3546ace38b4d4b16e39ee22b3c24f2360caf6-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-9ce3546ace38b4d4b16e39ee22b3c24f2360caf6-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-9ce3546ace38b4d4b16e39ee22b3c24f2360caf6-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cba2af49103ca0faf694ffa8872c175f41c7ee38:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-45cb3b9b340870837c819ac1ba4113befa6d1118-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-45cb3b9b340870837c819ac1ba4113befa6d1118-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-45cb3b9b340870837c819ac1ba4113befa6d1118-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1522-45cb3b9b340870837c819ac1ba4113befa6d1118-x86.apk)

**Comment by nirvn** [comment]
After many tests and discussions with @suricactus  , it seems there's nothing we can do here. Sorry.

**Pull request closed without merging**
