### PR TITLE
update load proj image

### PR DESCRIPTION
**Pull request by mbernasocchi**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-503-2d623dcbfc79cfe62932dc9650ff579e4c7ccf17-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-503-2d623dcbfc79cfe62932dc9650ff579e4c7ccf17-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-503-a958af61418eaffaa798fce4ad0bb1a17349d867-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-503-a958af61418eaffaa798fce4ad0bb1a17349d867-x86.apk)

**Comment by m-kuhn** [comment]
screenshot_20190306-162237_trebuchet

**Comment by m-kuhn** [comment]
Looks good!

**Pull request merged**
