### PR TITLE
Use QGIS native pretty scale calculation for projected CRS

### LINKED ISSUE #2408: Sometimes QField show `NaN m` in scalebar
Better hide the scalebar or show something better than `NaN`.

[qfield_0000_dependencies.zip](https://github.com/opengisch/QField/files/7876250/qfield_0000_dependencies.zip)

image

### PR DESCRIPTION
**Pull request by suricactus**
- if the scaledDistance.value is nan, better show "Unknown" than "nan km"
- if the scaledDistance.value is 0 (submeter values), better show all the decimals
- fix a warning on startup

Fix #2408 #1046

Peek 2022-01-16 14-50

### CODE REVIEW

**Comment by nirvn** [comment]
There was an issue filed against mm or cm display I think.

Nice papercut fix!

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 00a0d528ddaea36dbdc13bf6934738485829143b:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2412-e0df2c50efa3f52be7a15d98071ff3f2e18103de-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2412-e0df2c50efa3f52be7a15d98071ff3f2e18103de-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2412-e0df2c50efa3f52be7a15d98071ff3f2e18103de-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2412-e0df2c50efa3f52be7a15d98071ff3f2e18103de-x86.apk)

**Comment by suricactus** [comment]
Failed to find it initially. It was #1046.

**Comment by suricactus** [comment]
@nirvn shall we merge?

**Review by nirvn — APPROVED** [review]

**Pull request merged**
