### PR TITLE
Respect DPI in multiline fontsize

### LINKED ISSUE #368: Tiny font for Multiline Text Edit Widget Type
The font size for the Widget Type _Text Edit, Multiline_ is tiny and much smaller than the other Widget Types.

### Reproduction Steps:

1. Open the Attributes Form.
2. Set the Widget Type for a String Field to _Text Edit, Multiline_.
3. Add some text to that field and look at it within QField.

### Expected behavior:

Same font size as for the _Text Edit_ Widget Type (without _Multiline_ checked).

### Observed behavior:

Look at the entry description.

### Screenshots and GIFs
screenshot_20180918-055924

**QField version:** 0.11.6

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

Naive suggestion: could this issue be solved within _src/qml/editorwidgets/TextEdit.qml_ by adding a `font.pointSize: 14` to the TextArea property at line 53? (Unfortunately I was not able to set up a build environment with Docker or OSGeo4A to try it myself).

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #368 

@Emic37 and @nicpitsch can you test this branch (download link should be here in 15 minutes)

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-493-b2d1442899b0f7a22796f6510d078fc977b92606-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-493-b2d1442899b0f7a22796f6510d078fc977b92606-x86.apk)

**Comment by Emic37** [comment]
Thank you very much. For me it's work very well.

**Comment by Emic37** [comment]
In consultation mode, it's good. But in editing mode, it's obviously more better than before but not perfect. Spellchecker doesn't work very well and scrolling too. Maybe it's possible to open a new page with only a text editing field and keyboard when we click on a multiline field ? 
That would reproduce the same behavior that in google keep. I think it would be very ergonomic.

**Comment by m-kuhn** [comment]
Such improvements will be very welcome, please get in touch with us by mail if you would like to get an offer for this.

**Pull request merged**
