### PR TITLE
[WIP] Testing a hard exit

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e0bc5f8306ee01f687fd3940ef1a4f7fea6e693b: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5103-a911208f3a397d8160157e208380e5b2c2a3a9ef-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5103-a911208f3a397d8160157e208380e5b2c2a3a9ef-android-arm-neon.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5103-a911208f3a397d8160157e208380e5b2c2a3a9ef-android-x64.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-5103-a911208f3a397d8160157e208380e5b2c2a3a9ef-android-x86.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5103-a911208f3a397d8160157e208380e5b2c2a3a9ef-android-arm64.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5103-a911208f3a397d8160157e208380e5b2c2a3a9ef-android-arm-neon.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5103-a911208f3a397d8160157e208380e5b2c2a3a9ef-android-x64.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-5103-a911208f3a397d8160157e208380e5b2c2a3a9ef-android-x86.apk)
</details>

**Comment by suricactus** [comment]
Screenshot?

**Comment by nirvn** [comment]
@suricactus , not meant to be nice, just testing :)

image002

**Comment by nicolas-sitylb** [comment]
Hello,


Thank you for providing this new APK file @nirvn 

Unfortunately, we do not see the red square when using that APK file.

In addition, QField is dimming the screen brightness to a level which renders the screen almost black.

image

**Comment by nirvn** [comment]
@nicolas-sitylb , have you tried opening a project? The exit button won't appear until you open a project, then re-enter the home screen.

**Comment by nicolas-sitylb** [comment]
@nirvn
Yes I first entered a project, then exited the app normally, then opening it again. I took the provided screenshot only at this last stage.

**Comment by nicolas-sitylb** [comment]
Okay, quitting the app didn't show up the red square.
But, indeed, you were correct : getting **back home** from an opened project makes this square appear !

Clicking on this red square then kind of "places the app in the background", showing the usual Android desktop screen. 
When opening QField again, it behaves like a fresh, very-first, opening (that's cool) and then it re-ask for the user credentials when a project needs to connect to a web service.

**Comment by nirvn** [comment]
@nicolas-sitylb , excellent that's good. Can you test it multiple times (10 times would make us feel good? :) ) to confirm that when quitting via the red square button, you are _always_ being re-asked for credentials? Cheers.

**Comment by nirvn** [comment]
Superseded by https://github.com/opengisch/QField/pull/5571

**Pull request closed without merging**
