### PR TITLE
Remove gdal overlay

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Review by nirvn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a8b03ca4583843277f5517a1a0166e370fcac33a: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3458-8954e6d390a381920d5a5feea6465f17d2615edf-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3458-8954e6d390a381920d5a5feea6465f17d2615edf-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3458-8954e6d390a381920d5a5feea6465f17d2615edf-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3458-8954e6d390a381920d5a5feea6465f17d2615edf-x86-android.apk)
</details>

**Review by nirvn — APPROVED** [review]
APK worked fine here. Nice to see gdal rm from our overlays.

**Comment by m-kuhn** [comment]
Well possible qhull will also be gone in a day or two, let's wait a tiny bit...

**Comment by m-kuhn** [comment]
Upstream [vcpkg] decided to wait for upstream of upstream [qhull] which makes it unpredictable when this will land, I'd say, let's merge.

**Pull request merged**
