### PR TITLE
Clang format lint

### PR DESCRIPTION
**Pull request by m-kuhn**
I like clang-format. I don't like the number of changes it forces us to do (or can we improve the options?)

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-346ada5ea42d47ab72f49ec8cdacfe602005d465-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-346ada5ea42d47ab72f49ec8cdacfe602005d465-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-346ada5ea42d47ab72f49ec8cdacfe602005d465-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-346ada5ea42d47ab72f49ec8cdacfe602005d465-x86_64.apk)

**Comment by 3nids** [comment]
it's weird I thought that I had the same indent under the class when I tested it.
Isn't there some default style format you rely on?

In any case, I don't care so much about the changes, it's only once. It would be nice to be in sync with QGIS source code of course.

**Comment by m-kuhn** [comment]
>  Isn't there some default style format you rely on?

It's to 99% a style you added ;)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-5fbaf3675e808f8f565b4e4d58e95b8026b54f40-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-5fbaf3675e808f8f565b4e4d58e95b8026b54f40-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-5fbaf3675e808f8f565b4e4d58e95b8026b54f40-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-5fbaf3675e808f8f565b4e4d58e95b8026b54f40-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-55d0e09d8d3b743d5a69661d83a9df0d9efe2b3b-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-55d0e09d8d3b743d5a69661d83a9df0d9efe2b3b-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-55d0e09d8d3b743d5a69661d83a9df0d9efe2b3b-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-55d0e09d8d3b743d5a69661d83a9df0d9efe2b3b-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-ca9fbfb9220fb9a7908f0cd9d1af3e34257bb988-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-ca9fbfb9220fb9a7908f0cd9d1af3e34257bb988-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-ca9fbfb9220fb9a7908f0cd9d1af3e34257bb988-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-ca9fbfb9220fb9a7908f0cd9d1af3e34257bb988-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8612021f31b123e27e3c39e49fc991f8620d540a-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8612021f31b123e27e3c39e49fc991f8620d540a-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8612021f31b123e27e3c39e49fc991f8620d540a-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8612021f31b123e27e3c39e49fc991f8620d540a-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-38ba134fe06b37e6bfc5873f651147891f240f22-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-38ba134fe06b37e6bfc5873f651147891f240f22-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-38ba134fe06b37e6bfc5873f651147891f240f22-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-38ba134fe06b37e6bfc5873f651147891f240f22-x86_64.apk)

**Comment by m-kuhn** [comment]
I really start to like this. If we just could add some additional indentation to class declaration bodies, that'd reduce the code diff a lot.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-2a10158cfdcecdc508055da8511aff94998f6fb0-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-2a10158cfdcecdc508055da8511aff94998f6fb0-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-2a10158cfdcecdc508055da8511aff94998f6fb0-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-2a10158cfdcecdc508055da8511aff94998f6fb0-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-f1c19e6c315b2a240ad822ffe365e9d9fa400875-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-f1c19e6c315b2a240ad822ffe365e9d9fa400875-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-f1c19e6c315b2a240ad822ffe365e9d9fa400875-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-f1c19e6c315b2a240ad822ffe365e9d9fa400875-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8188042c3a77e053ed6bb154cee0ccbd0504da73-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8188042c3a77e053ed6bb154cee0ccbd0504da73-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8188042c3a77e053ed6bb154cee0ccbd0504da73-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8188042c3a77e053ed6bb154cee0ccbd0504da73-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-ba1fae68f057aada6f2a8580077cf6d4653856bf-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-ba1fae68f057aada6f2a8580077cf6d4653856bf-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-ba1fae68f057aada6f2a8580077cf6d4653856bf-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-ba1fae68f057aada6f2a8580077cf6d4653856bf-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-b3b2bc0978ea6c0512793147472ed9f17c65733f-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-b3b2bc0978ea6c0512793147472ed9f17c65733f-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-b3b2bc0978ea6c0512793147472ed9f17c65733f-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-b3b2bc0978ea6c0512793147472ed9f17c65733f-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-cbb0642b3aac195283d6d7827c39f47c0deda8a7-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-cbb0642b3aac195283d6d7827c39f47c0deda8a7-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-cbb0642b3aac195283d6d7827c39f47c0deda8a7-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-cbb0642b3aac195283d6d7827c39f47c0deda8a7-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-c77ca48aa9e93a18b2b4717b01bad280523ea0d6-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-c77ca48aa9e93a18b2b4717b01bad280523ea0d6-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-c77ca48aa9e93a18b2b4717b01bad280523ea0d6-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-c77ca48aa9e93a18b2b4717b01bad280523ea0d6-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-5734586aad697d44e60eb6844cf833d07f20721b-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-5734586aad697d44e60eb6844cf833d07f20721b-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-5734586aad697d44e60eb6844cf833d07f20721b-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-5734586aad697d44e60eb6844cf833d07f20721b-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a86dd7edb25a0ed3b5b0544f00c42e984acf1b7d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a86dd7edb25a0ed3b5b0544f00c42e984acf1b7d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a86dd7edb25a0ed3b5b0544f00c42e984acf1b7d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a86dd7edb25a0ed3b5b0544f00c42e984acf1b7d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-91426f82b4a7ba21daf3ea22214f41fdf7aa3cfe-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-91426f82b4a7ba21daf3ea22214f41fdf7aa3cfe-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-91426f82b4a7ba21daf3ea22214f41fdf7aa3cfe-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-91426f82b4a7ba21daf3ea22214f41fdf7aa3cfe-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a9364dcbefb1163f4aa46b87b0ea8a1455117559-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a9364dcbefb1163f4aa46b87b0ea8a1455117559-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a9364dcbefb1163f4aa46b87b0ea8a1455117559-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a9364dcbefb1163f4aa46b87b0ea8a1455117559-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8d42984d54c20ff93a05c5738ed797b2c18f6cb3-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8d42984d54c20ff93a05c5738ed797b2c18f6cb3-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8d42984d54c20ff93a05c5738ed797b2c18f6cb3-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-8d42984d54c20ff93a05c5738ed797b2c18f6cb3-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a689f889596309fccb6399c2c6b96d4f91bd9a98-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a689f889596309fccb6399c2c6b96d4f91bd9a98-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a689f889596309fccb6399c2c6b96d4f91bd9a98-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-a689f889596309fccb6399c2c6b96d4f91bd9a98-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-4e4676861423b4ff7e7fd49965876c46d59ac07e-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-4e4676861423b4ff7e7fd49965876c46d59ac07e-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-4e4676861423b4ff7e7fd49965876c46d59ac07e-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-913-4e4676861423b4ff7e7fd49965876c46d59ac07e-x86_64.apk)

**Pull request closed without merging**
