### PR TITLE
Reduce map identify radius

### LINKED ISSUE #858: Improve selection by setting a search radius for identifying features
If multiple features are adjacent, a single touch will identify several of them.
A way to control this behaviour would be extremely useful.

The current behaviour offers no control and makes feature identification imprecise.
If several adjacent polygons are present in the layer, a single touch will identify all of them.
After that, the desired polygon must be selected from the list.
It would be effective to allow the user to decide the precision/tolerance of the touch interface.
QGIS has an option to set the search radius for identifying features and I think a similar option would greatly increase QField usability.
Alternatively, an option to force the identification of a single feature upon touch would be effective.

I often suggest Qfield to my clients as an effective solution to leverage geospatial data in field operations.
The current behaviour is not perceived as a feature but rather as the interface being imprecise (even with a stylus) and the feature identification process more complex than it needs to be.

If such a functionality already exists it is inadequately documented.

### PR DESCRIPTION
**Pull request by m-kuhn**
I often identify much more than desired.
Let's see if this version is more precise.

Fixes #858

### CODE REVIEW

**Comment by nirvn** [comment]
What was the default?

**Comment by m-kuhn** [comment]
8

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-dd16be25e6df1b9aa96be04ec00c36d33a03f760-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-dd16be25e6df1b9aa96be04ec00c36d33a03f760-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-dd16be25e6df1b9aa96be04ec00c36d33a03f760-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-dd16be25e6df1b9aa96be04ec00c36d33a03f760-x86_64.apk)

**Comment by nirvn** [comment]
K; cutting the radius in half seems about right.

**Comment by VxTedxV** [comment]
#858

**Comment by nirvn** [comment]
Note: this has some impact on the demo projects that with ship. I.e., when we click on a re-grouped hexagon, we rarely get as many features as clustered.

**Comment by m-kuhn** [comment]
> Note: this has some impact on the demo projects that with ship. I.e., when we click on a re-grouped hexagon, we rarely get as many features as clustered.

What would you propose to do?
We could adapt the symbology to the smaller identify size. Or implement a handler that takes symbology into account, but that's a non-trivial job.

**Comment by nirvn** [comment]
I think just changing the demo project's point cluster symbology settings should suffice :)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-8dfbed42094ad195a3dd40a140684af315efe425-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-8dfbed42094ad195a3dd40a140684af315efe425-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-8dfbed42094ad195a3dd40a140684af315efe425-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-8dfbed42094ad195a3dd40a140684af315efe425-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-3c4599f7f6934b155e475a568087490e63d229c1-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-3c4599f7f6934b155e475a568087490e63d229c1-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-3c4599f7f6934b155e475a568087490e63d229c1-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-3c4599f7f6934b155e475a568087490e63d229c1-x86_64.apk)

**Comment by nirvn** [comment]
Here's my impression after trying radius 4,3, and 2:

- radius 2, -1, I was easily missing points I wanted to identify when tapping on the screen while walking
- radius 3, +0.5, it was OK most of the time; definitively feels 'precise', maybe slightly too much
- radius 4, +1, I felt that hit my sweet spot; I did get one extra feature wrongly identified every now and then, but nothing as bad as the current UX, and IMHO I think it's better to "over identify" than "under identify" due to being too precise.

**Comment by m-kuhn** [comment]
The ballots are open.
My favorite is 3.

**Comment by signedav** [comment]
I like 3 and 4. 2 is too small for me.

**Comment by VxTedxV** [comment]
4 is not precise enough. :worried:
3 is OK. :confused:
2 is much better. :simple_smile:
Tested on a 5" (126,7mm) screen.

**Comment by nirvn** [comment]
I think 3 is winning (fav + fine + fine + ok), can we settle on that and merge?

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-44b1dfe6479d784d3421fe4e75c79a0b76d54e19-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-44b1dfe6479d784d3421fe4e75c79a0b76d54e19-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-44b1dfe6479d784d3421fe4e75c79a0b76d54e19-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1142-44b1dfe6479d784d3421fe4e75c79a0b76d54e19-x86_64.apk)

**Pull request merged**
