### PR TITLE
Ios Beta

### PR DESCRIPTION
**Pull request by m-kuhn**
It's as stable as macos and win

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c43506a493a1959a88d7acfe1b76f035ca730c12:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-c7cd705989442551bc0779bce7aa3418dc5d502b-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-c7cd705989442551bc0779bce7aa3418dc5d502b-arm-android.apk), [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-c7cd705989442551bc0779bce7aa3418dc5d502b-arm-neon-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-c7cd705989442551bc0779bce7aa3418dc5d502b-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-c7cd705989442551bc0779bce7aa3418dc5d502b-x86-android.apk)

**Review by nirvn — APPROVED** [review]
I agree to this statement considering all the work we're doing around the new QML local data picker :wink:

**Review by 3nids — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c43506a493a1959a88d7acfe1b76f035ca730c12:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-0ed00468b1053a79037e9e4c5116e93ac113ac0d-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-0ed00468b1053a79037e9e4c5116e93ac113ac0d-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-0ed00468b1053a79037e9e4c5116e93ac113ac0d-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-0ed00468b1053a79037e9e4c5116e93ac113ac0d-x86-android.apk)

**Comment by m-kuhn** [comment]
The current work on reprojected layers by @3nids seems to be a precondition to me.
And a feedback from the garden by @marioba would be appreciated too.

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for c43506a493a1959a88d7acfe1b76f035ca730c12: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-27189859d4645d325b02fa159a8397e52b2b6823-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-27189859d4645d325b02fa159a8397e52b2b6823-arm-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-27189859d4645d325b02fa159a8397e52b2b6823-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2854-27189859d4645d325b02fa159a8397e52b2b6823-x86-android.apk)
</details>

**Comment by nirvn** [comment]
@m-kuhn , I'd have waited for QField iOS to properly handle local non-cloud projects, but I get the hype :wink:

**Pull request merged**
