### PR TITLE
Add missing quotes in the iOS workflow yml

### PR DESCRIPTION
**Pull request by nirvn**
@m-kuhn , voila.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Looks good, shouldn't we add that on all lines using either ${env} or ${{ github expressions }}?

**Comment by nirvn** [comment]
@m-kuhn , seems like a good idea, done.

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2d542621bc4c8c2172dae48f34b61c15f799e936:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2441-a88a6a8b81bc8d4d8a250dd67f246ecc2fa55fcc-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2441-a88a6a8b81bc8d4d8a250dd67f246ecc2fa55fcc-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2441-a88a6a8b81bc8d4d8a250dd67f246ecc2fa55fcc-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2441-a88a6a8b81bc8d4d8a250dd67f246ecc2fa55fcc-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for cd5582ee54cb4a744108e954d241da144811df36:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2441-53c5de27e85606eff69159d089664ac4f3595f8a-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2441-53c5de27e85606eff69159d089664ac4f3595f8a-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2441-53c5de27e85606eff69159d089664ac4f3595f8a-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2441-53c5de27e85606eff69159d089664ac4f3595f8a-x86.apk)

**Pull request merged**
