### PR TITLE
Skip antenna height correction when IMU is active

### PR DESCRIPTION
**Pull request by domi4484**
When IMU is active, the GNSS device provides the position at the end of the pole.
The antenna height must not be subtracted again from the Z value.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for dcdbe6c17468ee55806cab306182ba8474391f4e: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4503-5259182417788c4b3828b0e0835941387b8f6ac5-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4503-5259182417788c4b3828b0e0835941387b8f6ac5-arm-neon-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4503-5259182417788c4b3828b0e0835941387b8f6ac5-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4503-5259182417788c4b3828b0e0835941387b8f6ac5-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4503-5259182417788c4b3828b0e0835941387b8f6ac5-arm64-android.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4503-5259182417788c4b3828b0e0835941387b8f6ac5-arm-neon-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4503-5259182417788c4b3828b0e0835941387b8f6ac5-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4503-5259182417788c4b3828b0e0835941387b8f6ac5-x86-android.apk)
</details>

**Comment by nirvn** [comment]
@domi4484 , I was re-thinking about this earlier today, and I don't think we can apply the antenna height at the receiver level, as it'll likely mess up (infinitely small value but still) vertical grid shift calculation here. 

We ultimately need to add the antenna height value _after_ we transformed the QgsPoint( lat, lon, elevation ) to the desired destination CRS. So, I think we're back to handling this in the Positioning class, and insure that the destination point's Z value has the antenna height added after the transformation.

**Comment by domi4484** [comment]
> We ultimately need to add the antenna height value _after_ we transformed the QgsPoint( lat, lon, elevation ) to the desired destination CRS. So, I think we're back to handling this in the Positioning class, and insure that the destination point's Z value has the antenna height added after the transformation.

I see only a small problematic with that approach:
- No IMU active: QField does the antenna correction AFTER crs transformation
- IMU active: Antenna correction is done by receiver BEFORE crs transformation

Well if the difference is in infinitely small range maybe better keep it consistent between modes?

**Comment by nirvn** [comment]
@domi4484 , fair point.

**Review by nirvn — APPROVED** [review]

**Comment by domi4484** [comment]
@nirvn I tried to restart the test but the ios is still failing when downloading qt... Can I merge anyway?

**Comment by nirvn** [comment]
@domi4484 , yeah go ahead

**Comment by domi4484** [comment]
> @domi4484 , yeah go ahead

Apparently I can't skip merge protections...

**Comment by mbernasocchi** [comment]
Merging even if iOS did not build, QT download still fails

**Comment by mbernasocchi** [comment]
> @domi4484 , yeah go ahead

Merging even if iOS did not build, QT download still fails

**Pull request merged**
