### PR TITLE
Add JPEG2000 raster support

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by nirvn** [comment]
Extra excited about this.

**Comment by nirvn** [comment]
🥁🥁🥁

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-5ab29b93dcb353256403965aa680442ce6a88beb-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-5ab29b93dcb353256403965aa680442ce6a88beb-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-5ab29b93dcb353256403965aa680442ce6a88beb-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-5ab29b93dcb353256403965aa680442ce6a88beb-x86_64.apk)

**Comment by nirvn** [comment]
:tada: 

image

The topo map here is over 12gb as geotiff, and only 2.1gb as jp2. I couldn't put this project on my phone due to lack of space before, now I can. Yay!

**Comment by m-kuhn** [comment]
Thanks @nirvn , let me prepare a proper SDK then.
As soon as the compass is ready let's do a 1.4.1 including compass and this.

**Comment by nirvn** [comment]
@m-kuhn , compass fix in #786 .

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-7f38b3f5148dd7a7dfc945061bb928ccdb4728ee-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-7f38b3f5148dd7a7dfc945061bb928ccdb4728ee-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-7f38b3f5148dd7a7dfc945061bb928ccdb4728ee-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-7f38b3f5148dd7a7dfc945061bb928ccdb4728ee-x86_64.apk)

**Comment by nirvn** [comment]
Build crashes before the welcome screen is displayed.

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-6b10ea88c28ac55457b2f3cc80d66d564eb081e9-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-6b10ea88c28ac55457b2f3cc80d66d564eb081e9-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-6b10ea88c28ac55457b2f3cc80d66d564eb081e9-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-6b10ea88c28ac55457b2f3cc80d66d564eb081e9-x86_64.apk)

**Comment by m-kuhn** [comment]
@nirvn can you test the latest version with the official sdk?
Then let's squashandmerge :tada:

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-8793be5f7642c608726b161b13ab6cf3ee33a786-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-8793be5f7642c608726b161b13ab6cf3ee33a786-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-8793be5f7642c608726b161b13ab6cf3ee33a786-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-785-8793be5f7642c608726b161b13ab6cf3ee33a786-x86_64.apk)

**Comment by nirvn** [comment]
@m-kuhn , working like a charm here.

**Pull request merged**
