### PR TITLE
Backporting all the good stuff

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1049-29efb609240d9df6bf76858dfb3821e528452e2d-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1049-29efb609240d9df6bf76858dfb3821e528452e2d-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1049-29efb609240d9df6bf76858dfb3821e528452e2d-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1049-29efb609240d9df6bf76858dfb3821e528452e2d-x86_64.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1049-d97691c6e952388500e98a3b7c561321a9968469-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1049-d97691c6e952388500e98a3b7c561321a9968469-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1049-d97691c6e952388500e98a3b7c561321a9968469-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1049-d97691c6e952388500e98a3b7c561321a9968469-x86_64.apk)

**Comment by m-kuhn** [comment]
@3nids I need a review. I don't think anyone is able to really check all of that. It's pretty much current master.

**Comment by 3nids** [comment]
@m-kuhn sorry, but what's the point of backporting?
I would prefer to remove the branch and re-branch when ready or either forget about 1.6.
But not so strong opinion.

**Pull request merged**
