### PR TITLE
Try putting images in pre-existing directory

### PR DESCRIPTION
**Pull request by nirvn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a251caf1464d472c664487bd77e8e8433a240ef7:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-df3561263dedeb8d7e0a6d881f1e2ca4fbf9e60b-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-df3561263dedeb8d7e0a6d881f1e2ca4fbf9e60b-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-df3561263dedeb8d7e0a6d881f1e2ca4fbf9e60b-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-df3561263dedeb8d7e0a6d881f1e2ca4fbf9e60b-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b05953a8da1341d807d73b495434d5f8448e7ffd:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-084e5e8555255c184e9208676aca52bf48f49010-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-084e5e8555255c184e9208676aca52bf48f49010-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-084e5e8555255c184e9208676aca52bf48f49010-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-084e5e8555255c184e9208676aca52bf48f49010-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 98c41c1f04539303ad9b64e9f45d620798bff69f:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-fa1b64eba02cade34ee86da53130c6ace8fe8d72-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-fa1b64eba02cade34ee86da53130c6ace8fe8d72-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-fa1b64eba02cade34ee86da53130c6ace8fe8d72-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-fa1b64eba02cade34ee86da53130c6ace8fe8d72-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 1d5e7c6bbda4620e7518df30f2f4504bb6196f67:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-879ac83263836981d4dd4361d62d8129e09637b4-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-879ac83263836981d4dd4361d62d8129e09637b4-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-879ac83263836981d4dd4361d62d8129e09637b4-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-879ac83263836981d4dd4361d62d8129e09637b4-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 653de148b65b9cee6d86131333600bd038c529c0:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-ec0ac490480d6c138021b107bc814faf24ab469d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-ec0ac490480d6c138021b107bc814faf24ab469d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-ec0ac490480d6c138021b107bc814faf24ab469d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-ec0ac490480d6c138021b107bc814faf24ab469d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for b51c2270f9c036b70df24e0262363e9745cbc5d6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-4248431fff5a24c321b39a07d34d050afee5e965-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-4248431fff5a24c321b39a07d34d050afee5e965-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-4248431fff5a24c321b39a07d34d050afee5e965-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-4248431fff5a24c321b39a07d34d050afee5e965-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 43e036b6449705fa924d5ab18f02c3d8337427a6:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-acd3c4aa56e726eb1d80612331711fe50b57137d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-acd3c4aa56e726eb1d80612331711fe50b57137d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-acd3c4aa56e726eb1d80612331711fe50b57137d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-acd3c4aa56e726eb1d80612331711fe50b57137d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for bc8a38302fca9fb619bf2c73a00decc9401448e3:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-0c44f1c15565692fe34298466511731f6ca21501-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-0c44f1c15565692fe34298466511731f6ca21501-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-0c44f1c15565692fe34298466511731f6ca21501-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-0c44f1c15565692fe34298466511731f6ca21501-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f7c754103b342901545f8a6d0b0c10f1b8769324:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-7cde5cb59c9b15ab4832cb5124bc3bf5b221908d-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-7cde5cb59c9b15ab4832cb5124bc3bf5b221908d-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-7cde5cb59c9b15ab4832cb5124bc3bf5b221908d-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-7cde5cb59c9b15ab4832cb5124bc3bf5b221908d-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 6e0875c2d95ec51bc05371b15b23d7677a01125a:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-abc8bf31bddb4e74761374830ec122f6c772f97f-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-abc8bf31bddb4e74761374830ec122f6c772f97f-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-abc8bf31bddb4e74761374830ec122f6c772f97f-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1947-abc8bf31bddb4e74761374830ec122f6c772f97f-x86.apk)

**Comment by m-kuhn** [comment]
takeScreenshot segfaults

```
Backtrace:
/lib64/libQt5Gui.so.5(_ZNK14QOpenGLContext6formatEv+0x1b)[0x7f9ff5afb8db]
/lib64/libQt5Quick.so.5(_ZN16QSGBatchRenderer8RendererC2EP23QSGDefaultRenderContext+0x815)[0x7f9ff60b85b5]
/lib64/libQt5Quick.so.5(_ZN23QSGDefaultRenderContext14createRendererEv+0x26)[0x7f9ff61096d6]
/lib64/libQt5Quick.so.5(_ZN19QQuickWindowPrivate14syncSceneGraphEv+0x178)[0x7f9ff6172d38]
/lib64/libQt5Quick.so.5(+0x210d58)[0x7f9ff611bd58]
/lib64/libQt5Quick.so.5(+0x20ab6f)[0x7f9ff6115b6f]
/lib64/libQt5Quick.so.5(+0x20d109)[0x7f9ff6118109]
/lib64/libQt5Core.so.5(+0xc6680)[0x7f9ff4ee3680]
/lib64/libpthread.so.0(+0x9432)[0x7f9ff4e04432]
/lib64/libc.so.6(clone+0x43)[0x7f9ff49e06d3]
```

**Comment by m-kuhn** [comment]
Superseded by #1956

**Pull request closed without merging**
