### PR TITLE
Just to rule out API use

### PR DESCRIPTION
**Pull request by nirvn**
The only way what we're being told to use would _actually_ work is if somehow Android won't let native code _lists_ files within a directory granted permission but would somehow allow direct path name file opening... 

Merely doing this to get the data we need to show it's not sufficient.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 0515d0348dab6f262d5683a02fc84ded977d0f87:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-f9b05e0dd80a6158ff349b8eb474a68f956eafae-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-f9b05e0dd80a6158ff349b8eb474a68f956eafae-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-f9b05e0dd80a6158ff349b8eb474a68f956eafae-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-f9b05e0dd80a6158ff349b8eb474a68f956eafae-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f2326eb9e792b43d3a03f4e29adebc47712af722:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-230f8d08a604c65e3f22c57c0dd3ab1aebd1f887-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-230f8d08a604c65e3f22c57c0dd3ab1aebd1f887-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-230f8d08a604c65e3f22c57c0dd3ab1aebd1f887-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-230f8d08a604c65e3f22c57c0dd3ab1aebd1f887-x86.apk)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for f427e56f1cf0431ed3469e43805510345510908e:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-57399fd9b5233048bb037efab26016c4490da567-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-57399fd9b5233048bb037efab26016c4490da567-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-57399fd9b5233048bb037efab26016c4490da567-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2382-57399fd9b5233048bb037efab26016c4490da567-x86.apk)

**Comment by m-kuhn** [comment]
@nirvn should we close this?

**Comment by nirvn** [comment]
Yes we learned everything there was to learn here. Don't kill the branch yet.

**Pull request closed without merging**
