### PR TITLE
Revert "Refresh QField logo (#1311)"

### PR DESCRIPTION
**Pull request by m-kuhn**
Not there yet

### CODE REVIEW

**Review by nirvn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1334-8eb4acf40dbe842c4a65fef4de18c8d78fa361fe-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1334-8eb4acf40dbe842c4a65fef4de18c8d78fa361fe-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1334-8eb4acf40dbe842c4a65fef4de18c8d78fa361fe-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1334-8eb4acf40dbe842c4a65fef4de18c8d78fa361fe-x86_64.apk)

**Comment by signedav** [comment]
Why that?

**Comment by m-kuhn** [comment]
Postponed to next release (major version change)

**Comment by signedav** [comment]
Fair enough. But shouldn't we keep the old logo as well as the icon in the play store?
The current state is, that you click on the new logo and QField opens with an old logo...

**Comment by m-kuhn** [comment]
I think @mbernasocchi did not want to revert the playstore one. It's more a matter of available time I think.

**Comment by mbernasocchi** [comment]
mmm I actually wanted all logos to get updated ASAP, the major selling point of 2.0 is not the new logo. all communication of 2.0 will be on the cloud integration. The docs pages and playstore are already updated

**Pull request merged**
