### PR TITLE
Load openssl libs earlier

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-486-534295de6692fd3636814430eec58fc167d542c1-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-486-534295de6692fd3636814430eec58fc167d542c1-x86.apk)

**Comment by qfield-fairy** [comment]
Uploaded test apks for [armv7](https://download.opengis.ch/qfield/ci-builds/qfield-dev-486-7a96cbf77de190299b285a1bac9f01d940f4c262-armv7.apk) and [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-486-7a96cbf77de190299b285a1bac9f01d940f4c262-x86.apk)

**Comment by 3nids** [comment]
what's up here?

**Comment by m-kuhn** [comment]
Waiting for feedback from @signedav (Android 5) but I assume it does not help and can be closed.

**Comment by signedav** [comment]
Wanna feedback? I can give you feedback. ;-)


just a moment...

**Comment by signedav** [comment]
Crash on start with Android 5.1.1.

**Pull request closed without merging**
