### PR TITLE
Fix RelationCombobox not autocompleting on secon feature

### PR DESCRIPTION
**Pull request by domi4484**
Reset of the flag `isLastKeyPressedReturn` was missing.
This issue is happening only when using the enter button of the virtual keyboard

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for fb969a1640c78fd41904a812ebb7910221ee728e: [**arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5466-31c8488dea1d8bd42f1a5bd437f7e76c79632c9d-android-arm64.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5466-31c8488dea1d8bd42f1a5bd437f7e76c79632c9d-android-arm-neon.apk)
- [x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5466-31c8488dea1d8bd42f1a5bd437f7e76c79632c9d-android-x64.apk)
- [x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield-dev-5466-31c8488dea1d8bd42f1a5bd437f7e76c79632c9d-android-x86.apk)
- [**all access arm64-android**](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5466-31c8488dea1d8bd42f1a5bd437f7e76c79632c9d-android-arm64.apk)
- [all access arm-neon-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5466-31c8488dea1d8bd42f1a5bd437f7e76c79632c9d-android-arm-neon.apk)
- [all access x64-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5466-31c8488dea1d8bd42f1a5bd437f7e76c79632c9d-android-x64.apk)
- [all access x86-android](https://qfieldapks.sos-ch-dk-2.exoscale-cdn.com/ci-builds/qfield_all_access-dev-5466-31c8488dea1d8bd42f1a5bd437f7e76c79632c9d-android-x86.apk)
</details>

**Comment by nirvn** [comment]
@domi4484 , nice! good find -- let's backport :)

**Review by nirvn — APPROVED** [review]

**Comment by domi4484** [comment]
@nirvn is there an automated backport or do I need to do it manually?

**Comment by nirvn** [comment]
@domi4484 , you just need to add the ( backport branch_name ) tag to the PR. I've added it earlier.

**Comment by qfield-fairy** [comment]
The backport to `release-3_3` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply fb969a164... Print some debug info
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/qml/RelationCombobox.qml
CONFLICT (content): Merge conflict in src/qml/RelationCombobox.qml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release-3_3 release-3_3
# Navigate to the new working tree
cd .worktrees/backport-release-3_3
# Create a new branch
git switch --create backport-5466-to-release-3_3
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick fb969a1640c78fd41904a812ebb7910221ee728e,3a533fe550655ed2e146d36935d8d3390fd498e3,89399f391ccd9d89b297d9054ba69406ef537ade,12bfc5a76ea3eb10b0fbc9d995aff0ecf3faf758
# Push it to GitHub
git push --set-upstream origin backport-5466-to-release-3_3
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release-3_3
```
Then, create a pull request where the `base` branch is `release-3_3` and the `compare`/`head` branch is `backport-5466-to-release-3_3`.

**Pull request merged**
