### PR TITLE
Refresh QField logo

### PR DESCRIPTION
**Pull request by nirvn**
Logo harmonization campaign has begun:
Screenshot from 2020-09-18 09-07-13

### CODE REVIEW

**Comment by signedav** [comment]
Does it need the white border? Looks strange to me, since there is no space between anymore.

**Comment by nirvn** [comment]
@signedav , do you prefer that:
Screenshot from 2020-09-18 12-11-28

?

**Comment by mbernasocchi** [comment]
definitely without border

**Comment by nirvn** [comment]
Alright, PR updated, border no more.

**Review by mbernasocchi — APPROVED** [review]

**Pull request merged**
