### PR TITLE
Implement a more robust hover skipping when tapping the screen 

### PR DESCRIPTION
**Pull request by nirvn**
This PR addresses the last known Qt6 regression (did I just use that same formula a week ago? :wink:) whereas the hoverhandler for the stylus and mouse is wrongly triggered by taps on the screen.

What was happening here is that the Qt5 hack to use a Timer would not work anymore and as soon as the 750ms timer would set the isBeingTouched property to false, the stylus hoverhandler would activate.

The new implementation here is a lot more robust, and doesn't go through a shaky Timer.

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for acbaf997cfc8e1306c32d175db4624e6c8029531: [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4468-d368d0e15e16043c5d12a6c58c2613ed4a305c32-arm64-android.apk)
<details>
<summary>Other architectures</summary>

- [arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4468-d368d0e15e16043c5d12a6c58c2613ed4a305c32-arm-neon-android.apk)
- [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4468-d368d0e15e16043c5d12a6c58c2613ed4a305c32-x64-android.apk)
- [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-4468-d368d0e15e16043c5d12a6c58c2613ed4a305c32-x86-android.apk)
- [**all access arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4468-d368d0e15e16043c5d12a6c58c2613ed4a305c32-arm64-android.apk)
- [all access arm-neon-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4468-d368d0e15e16043c5d12a6c58c2613ed4a305c32-arm-neon-android.apk)
- [all access x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4468-d368d0e15e16043c5d12a6c58c2613ed4a305c32-x64-android.apk)
- [all access x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-4468-d368d0e15e16043c5d12a6c58c2613ed4a305c32-x86-android.apk)
</details>

**Comment by m-kuhn** [comment]
What's this good for?

**Comment by nirvn** [comment]
Trying to fix a regression, neither attempts worked so far

**Review by m-kuhn — APPROVED** [review]
🎉

**Pull request merged**
