### PR TITLE
Support loading of QGIS projects saved inside geopackage files

### PR DESCRIPTION
**Pull request by nirvn**
This allows packaging of a _whole_ project within a single file (provided the vector layers are all within the same geopackage or remote). It's a nice little feature to support for users who are relying on this in their QGIS environments.

Note: this will not handle multiple projects saved within a single geopackage. The code will load the first project found in the geopackage.

### CODE REVIEW

**Comment by nirvn** [comment]
Oh, this will fulfill enhancement #1809 filed by @xBcai .

**Review by m-kuhn — APPROVED** [review]

**Comment by xBcai** [comment]
Thanks! It's convenient to transfer files. Otherwise, it's easy to lose one of the two files.

**Comment by nirvn** [comment]
@xBcai , give it a try and let us know how useful it is for your field work :)

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for e0fcdffc3a4f72aff7e6d4cdfc298e041d845130:
  - [**arm64_v8a**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1966-959f6da16e86bdd161a04496e6b8955900c1bea0-arm64_v8a.apk)

Other architectures: [armv7](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1966-959f6da16e86bdd161a04496e6b8955900c1bea0-armv7.apk), [x86_64](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1966-959f6da16e86bdd161a04496e6b8955900c1bea0-x86_64.apk), [x86](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-1966-959f6da16e86bdd161a04496e6b8955900c1bea0-x86.apk)

**Pull request merged**
