### PR TITLE
fix .gitignore

### PR DESCRIPTION
**Pull request by 3nids**
no idea why but I have these files added when I build for iOS....???

 create mode 100644 platform/android/AndroidManifest.xml
 create mode 100644 platform/android/build.gradle
 create mode 100644 platform/android/generated.xml

easy fix in .gitignore

### CODE REVIEW

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for a68df8d33a2b34fa388a2335f0ff8c7665f61d9d:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2614-3e19a42ae7c4b0e557cea20b0259318af6805f46-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2614-3e19a42ae7c4b0e557cea20b0259318af6805f46-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2614-3e19a42ae7c4b0e557cea20b0259318af6805f46-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2614-3e19a42ae7c4b0e557cea20b0259318af6805f46-x86-android.apk)

**Comment by m-kuhn** [comment]
Looks good. Ideally we fix this condition also : https://github.com/opengisch/QField/blob/476876a38b3ffdaeb03b078e18da9f41f1c10833/cmake/Package.cmake#L67 to `if(ANDROID)`

**Comment by m-kuhn** [comment]
Bump @3nids

**Review by m-kuhn — APPROVED** [review]

**Comment by qfield-fairy** [comment]
🎉 Ta-daaa, freshly created APKs are available for 2e423f02154c27b47145a3443c33a0d7f11ceed8:
  - [**arm64-android**](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2614-917777495d2093d0d43c45451af95e0bcb8e9ab5-arm64-android.apk)

Other architectures: [arm-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2614-917777495d2093d0d43c45451af95e0bcb8e9ab5-arm-android.apk), [x64-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2614-917777495d2093d0d43c45451af95e0bcb8e9ab5-x64-android.apk), [x86-android](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2614-917777495d2093d0d43c45451af95e0bcb8e9ab5-x86-android.apk)

**Pull request merged**
