### PR TITLE
isValid is a property these days

### PR DESCRIPTION
**Pull request by nirvn**
Note to the world: there's a risk someone ends up updating the SDK on the release-1_6 branch, which would trigger this regression there. Let us all be aware! :wink:

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1220-461351963b379f2af44a178e6efbe7df9489aef4-armv7.apk)
 - [**x86**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1220-461351963b379f2af44a178e6efbe7df9489aef4-x86.apk)
 - [**arm64_v8a**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1220-461351963b379f2af44a178e6efbe7df9489aef4-arm64_v8a.apk)
 - [**x86_64**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1220-461351963b379f2af44a178e6efbe7df9489aef4-x86_64.apk)

**Comment by nirvn** [comment]
I don't think so, not as of now. The last sdk update there dates back over 14 days. Your isValid change was pushed 9 days ago.

**Comment by nirvn** [comment]
@m-kuhn , I'll prepare a backport to 1.6, it'll be needed since we're about to update the SDK there.

**Comment by m-kuhn** [comment]
@nirvn I don't think we need a backport. `isValid()` is not used there ?

**Comment by nirvn** [comment]
@m-kuhn , right, but should it not be? I thought that isValid in master was fixing a bug that wasn't backported yet.

**Comment by m-kuhn** [comment]
Mostly a visual cue for invalid layers IIRC. Nice, but not critical. Not sure it's worth the effort.

**Comment by nirvn** [comment]
Let's skip it then

**Comment by m-kuhn** [comment]
1.7 is not that far away ;-)

**Pull request merged**
