### PR TITLE
Demo projects improvements

### PR DESCRIPTION
**Pull request by nirvn**
This PR supersedes #763 . 

Beyond improved titles (and filenames, as suggested by @signedav ), I've applied a couple of fixes, including:
- Use multiply blend on heatmap layers, looks much better
- Fix broken simple bee farming species and disease theme (by updating dataset source to include required fields)
- Fix openstreetmap layer not shown in simple bee farming themes

The first run welcome screen looks much better with these updated titles (IMHO):
Screenshot from 2020-01-07 10-49-48

### CODE REVIEW

**Comment by qfield-fairy** [comment]
Uploaded test apks for
 - [**armv7**](https://download.opengis.ch/qfield/ci-builds/qfield-dev-776-418907547ac35db97c81b8a9e487f9f62431a1c1-armv7.apk)
 - [arm64_v8a](https://download.opengis.ch/qfield/ci-builds/qfield-dev-776-418907547ac35db97c81b8a9e487f9f62431a1c1-arm64_v8a.apk)
 - [x86](https://download.opengis.ch/qfield/ci-builds/qfield-dev-776-418907547ac35db97c81b8a9e487f9f62431a1c1-x86.apk)
 - [x86_64](https://download.opengis.ch/qfield/ci-builds/qfield-dev-776-418907547ac35db97c81b8a9e487f9f62431a1c1-x86_64.apk)

**Comment by nirvn** [comment]
@m-kuhn , when you have a minute, please review this PR. It's the last bit of the welcome screen UX that's needed to finalize it for 1.4.

**Comment by signedav** [comment]
I like the names with the "Bee Farming" in it :bee: :man_farmer: 
Thanks @nirvn

**Comment by nirvn** [comment]
@signedav , yeah, I thought it was a nice suggestive word to have in there too. Good thing you suggested renaming the project files too. Cheers.

**Comment by signedav** [comment]
@nirvn I've noticed that the advanced bee farming and the simple bee farming seems to be the same?
Why is the bumbelbee removed instead of changed? On reviewing I thought it's because you made a copy to set it up differently but I did not went into the project files...

**Comment by nirvn** [comment]
@signedav , I think fundamentally the difference between simple and advanced are, AFAIK, 1/ the simple project uses an OSM basemap whereas the advanced project uses vector layers, and 2/ the advanced project has complex feature forms with relationships etc.

The rest was always the same (except that simple had broken symbology which I've fixed).

**Comment by signedav** [comment]
Actually what I intended by creating the simple project has been mainly to be able to make a quick demonstration collecting values with only a few attributes and without constraints etc.

**Pull request merged**
